### ISSUE TITLE
poedit pops "language of the translation isn't set" every time even when it's actually set

### ISSUE THREAD

**Issue by felixonmars** [vslavik/poedit#100]
This only happens for zh_Hans_CN for me (en_GB tested and didn't trigger the problem, other locales not tested).

If I set the language and save, a line will be added to the .po file:

```
"Language: zh_Hans_CN\n"
```

But when I close poedit and open the file again, the same error still pops out. If I didn't set it again and hit "save", the line will be removed from the file.

**Comment by dingpengyu** [comment]
cc
@vslavik

**Comment by dingpengyu** [comment]
This problem can be reproduced using Poedit-2.3.5890.
An update of the RFC 4646 language standard by poedit will solve this problem.

**Comment by vslavik** [comment]
@dingpengyu Please don't spam old issues. If you think there's a new bug, please file a new issue, and provide detailed description (make sure to read the instructions for creating new issues and the linked documents). Thanks.
