### ISSUE TITLE
Poedit crashes on Update from POT File

### ISSUE THREAD

**Issue by Swissbite** [vslavik/poedit#105]
System: Windows 8 (64Bit)
Version: 1.6.9

I made a language file from template. Saved it. Updated the template and tried to update the language catalog with Catalogue -> Update form POT file

Application closes the language specific GUI and let me choose the template.
But it does not start up again.

**Comment by venkat17** [comment]
Hi,
I have similar problem in my machine (windows 7 64bit). Currently I have installed latest version Poedit 1.8.7. It is suddenly disappear when I try the 'update from POT file..' option. But the windows task manager is showing the process is still running. 

I have tried in my colleague machine, but it works very well I could able to do 'update from POT file..' option. 
Solution: Today morning I have found workaround solution for this. I have used only keyboard with out mouse. It works!!!    There must be some issue with the windows updates.

Regards,
Venkat

**Comment by vslavik** [comment]
> I have tried in my colleague machine, but it works very well I could able to do 'update from POT file..' option. 

Great! So you have two computers, one exhibits the problem, one does not. What are the *differences between then?* Please list them all, even if you think they are irrelevant.

> There must be some issue with the windows updates.

Surely not. *Most* people use mouse and most do *not* have this issue; only you two do (so far). There’s *something* special/exceptional/unusual about your computers — and you’re the only one who can find out *what*.

**Comment by venkat17** [comment]
The difference I have seen so far is admin rights. The laptop which is working has admin rights and I am not working with admin rights.

Also Poedit is crashing if i try to select any option using mouse under 'Catalog' menu. The options in other menu are working fine with mouse.

**Comment by vslavik** [comment]
> The difference I have seen so far is admin rights. The laptop which is working has admin rights and I am not working with admin rights.

Are you claiming that the two machines are otherwise absolutely identical? The *exact* same hardware, all Windows settings exact same, Poedit and Windows versions exact same, opening the exact same PO file in the exact same location (and not e.g. once from local disk, once from a network share)? That’s a bit hard to believe… What are *all* differences, not just the ones you think might be related (I don’t see how admin/nonadmin could be)?

> Also Poedit is crashing if i try to select any option using mouse under 'Catalog' menu. The options in other menu are working fine with mouse.

Did you really go through every single menu item under *Catalog* and every single other menu item, as you seem to be saying?

**Comment by venkat17** [comment]
Yes both machines are same with internal hardware configuration having same model no, RAM, Windows version and installed in same location "C:\Program Files (x86)\Poedit". 

I have verified all other menu items also. Its crashing on selection of below menu options.
File -> Export as HTML
Edit -> Translation is Fuzzy
View -> Group by context
View -> Entries with error First
View -> Untranslated entries first
Catalog -> all

**Comment by vslavik** [comment]
> Yes both machines are same with internal hardware configuration having same model no, RAM, Windows version and installed in same location "C:\Program Files (x86)\Poedit”.

OK, then please describe what you *do* with Poedit, on both computers, exactly, step by step. For example it remains unclear where you have your files (network share or if you really copied everything over the other computer). In fact, can you please attach or send me the PO file (and if possible the source code) as well?

> Its crashing on selection of below menu options.

Please try to be precise in your reporting, false or inaccurate information makes it very hard to diagnose and ultimately fix the issue. Are there any more omissions or inaccuracies (e.g. you keep using the word “crashing” even though you said the process is running, i.e. did *not* crash)?

The *View* menu items you listed do nothing other than rearrange the content of the list; something radically different from *Update from POT*. Can you please describe, *in high level of detail*, what happens, and how it differs from *Update from POT* behavior? I wouldn’t mind a screencast, but I understand that may be too difficult to do. But can I have at least a screenshot of your Preferences→General settings and what is checked in the *View* menu?
