### ISSUE TITLE
Error when opening po files combined by msgcat, Malformed header: '#-#-#-#-#

### ISSUE THREAD

**Issue by c72578** [vslavik/poedit#106]
Poedit version: e.g. 1.6.9
OS: e.g. Linux, Windows

How to reproduce:
- Combine two po files using msgcat
- e.g.
  msgcat file1.po file2.po -o new.po
- open the file with Poedit
- Poedit shows the error because of the header comments
  - Malformed header: '#-#-#-#-#  ...
- example for resulting comments in header:

"#-#-#-#-#  poedit_master.de.po (poedit)  #-#-#-#-#\n"
"Project-Id-Version: poedit\n"
"Report-Msgid-Bugs-To: poedit@googlegroups.com\n"
"POT-Creation-Date: 2014-09-02 10:00+0200\n"
"PO-Revision-Date: 2014-10-12 04:39-0400\n"
"Last-Translator: vslavik vaclav@slavik.io\n"
"Language-Team: German\n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"\n"
"X-Generator: crowdin.com\n"
"#-#-#-#-#  poedit_1.6_de.po (poedit)  #-#-#-#-#\n"
"Project-Id-Version: poedit\n"
"Report-Msgid-Bugs-To: poedit@googlegroups.com\n"
"POT-Creation-Date: 2014-09-13 09:18+0200\n"
"PO-Revision-Date: 2014-10-12 04:40-0400\n"
"Last-Translator: vslavik vaclav@slavik.io\n"
"Language-Team: German\n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"\n"
"X-Generator: crowdin.com\n"

![poedit_error_combined_files_msgcat](https://cloud.githubusercontent.com/assets/371551/4605632/24b33b60-51f0-11e4-82dd-231c4aed6f32.PNG)

**Comment by htmgarcia** [comment]
@c72578 when merging files with `msgcat`, add `--use-first`. This solved the issue for me.
