### ISSUE TITLE
Feature request: Add option to sort items by msgid in *.po files while saving

### ISSUE THREAD

**Issue by true-pasky** [vslavik/poedit#124]
Sorting items (including deleted) by `msgid` will keep nice small diffs.
Translators will not see any differences because of current sorting in Poedit interface.

**Comment by pedro-mendonca** [comment]
I have an original .pot file sorted by original key (msgid) but as soon as I update from source files it gets sorted by source file (#: file.php).
What can I do to keep .pot and .po files sorted like this so that pull request diffs are simpler?

**Comment by vslavik** [comment]
I suppose you have two options: a) not sort the .pot in the first place (it makes precious little sense anyway) or b) submit a patch to Poedit that implements some configurable sorting (I have no reason not to accept *good* patches).

**Comment by pedro-mendonca** [comment]
Thank you for your anwser.
Could you help me on why sorting strings by original code order is a best practice?
I'm trying to understand this so I can coordinate my work as a translator with other developers.

**Comment by vslavik** [comment]
> why sorting strings by original code order is a best practice?

For one thing, it keeps strings that occurring together together.

Again, I am open to making this configurable, but there's too many high(er)-priority tasks that realistically speaking, you'd have to step up to do it if you'd want it to happen. After all, you don't have to use Poedit to create POTs (I don't either: I use a script), it's perfectly capable of editing translations in files it didn't create from sources...

**Comment by pedro-mendonca** [comment]
Thanks. It really makes more sense to understand the context to have the strings listed by source code appearance. I'll stick to the current mode :+1:
