### ISSUE TITLE
"page width" detection for complex Java projects

### ISSUE THREAD

**Issue by skarzhevskyy** [vslavik/poedit#135]
Related to issues  #94.
After editing in poedit I see tones of changes in my po files. Its is hard to diff after translation.
"Preserve formatting of existing files" was on

I Look at the source code and apparently  "page  width"  is detected using  length of  #: reference…
In my case this large project with java classes and standard xgettext  do not wrap long paths in source code. Poedit takes this length as suggestion for page width in project.

example:
#: com/pyx4j/site/client/backoffice/ui/prime/report/ReportControlPanelActionBar.java:86 
msgid "Generating Report"                                                                             
msgstr ""              

consider that full project formatted at 88 columns..         

Suggestion to ignore lenght of strings that do not have spaces e.g. are not actually wrapped.

**Comment by vslavik** [comment]
Could you please provide the full PO file (for testing)? TIA!

**Comment by skarzhevskyy** [comment]
Here are the example files.   sample-poEditWrap-before-edit.po   is
considered 88 characters

Vlad

**Comment by vslavik** [comment]
> Here are the example files.

Thanks, but I hoped for something more substantial that I could use to better test the fix — I don’t think this 3-items file is the one where you got “tons of changes”...
