### ISSUE TITLE
Copy and paste does not replace selection in Linux

### ISSUE THREAD

**Issue by alexhenrie** [vslavik/poedit#139]
In Linux, if you try to select an entire translated string and press Ctrl+V to paste over it, the new string is added but the old string is not eliminated.

The problem seems to be [TransTextctrlHandler::OnText](https://github.com/vslavik/poedit/blob/e1f178de36811b9e26cd7345524eeb7e7337ea85/src/edframe.cpp#L225), which suppresses [wxClipboardTextEvent](http://docs.wxwidgets.org/trunk/classwx_clipboard_text_event.html). The bug disappears if you delete [this line](https://github.com/vslavik/poedit/blob/e1f178de36811b9e26cd7345524eeb7e7337ea85/src/edframe.cpp#L234), but because I don't know why that line is there in the first place, I'm not sure if this is the right solution.

**Comment by vslavik** [comment]
> The problem seems to be TransTextctrlHandler::OnText, which suppresses wxClipboardTextEvent.

For the record, it does nothing even remotely close to that. It does [the exact opposite](http://docs.wxwidgets.org/trunk/classwx_event.html#a98eb20b76106f9a933c2eb3ee119f66c), in fact.

**Comment by alexhenrie** [comment]
Thank you, and sorry for my total misunderstanding of wxEvent::Skip.
