### ISSUE TITLE
No Undo and Redo on Linux

### ISSUE THREAD

**Issue by alexhenrie** [vslavik/poedit#140]
On Windows, Ctrl+Z and Ctrl+Shift+Z allow undoing and redoing an edit (character-by-character is fine). Windows also has Undo and Redo buttons in the Edit menu. Linux does not have anything like this, even though [there is code to hook up the nonexistent Undo and Redo buttons to event handlers](https://github.com/vslavik/poedit/blob/master/src/edframe.cpp#L353).

**Comment by vslavik** [comment]
See 089fa371c62748bd6a1de303d1f991c8fc05291f (a lot can be learned from browsing git history…).

I'm not going to reimplement the basics that the underlying GtkTextView doesn't provide (unlike its Windows and OS X counterparts), but you're welcome to.

**Comment by vslavik** [comment]
→ #141 with @alexhenrie's implementation.
