### ISSUE TITLE
Can input only latin letters when XIM used gtk input module

### ISSUE THREAD

**Issue by 375gnu** [vslavik/poedit#143]
Starting with version 1.6 of poedit I can't enter non-latin letters inside it
when gtk input method is XIM. When I set it into "None" from contex menu in
editable area poedit accepts non-latin letter. Other WX based applications like
Audacity or XCHM work as expected.

**Comment by vslavik** [comment]
I have no idea what the "XIM input method" is, nor how would I use it (it doesn't help that you failed to mention such as details as wx or GTK+ version and was extremely vague about the exact specific version of Poedit you actually did test).

You on the other hand do, and can reproduce it, so please debug it a bit and provide a patch — or at least a more technical, *detailed* and *reproducible* description that I can do something about.

**Comment by 375gnu** [comment]
My current poedit version is 1.7.4, but this issue was in 1.6 branch too. My OS is Debian GNU/Linux "Sid".

WX/GTK versions: libwxbase3.0-0, libwxgtk3.0-0 — 3.0.2-1+b1; libgtk-3-0 — 3.14.5-1.

The X Input Method (XIM) is the original input method framework for the X Window System. You can use as "GTK_IM_MODULE=xim poedit" then try to enter something outside ASCII,

**Comment by vslavik** [comment]
> GTK_IM_MODULE=xim poedit

Sounds like something obscure that no normal person would use, then, doesn't it? Is there any legitimate (i.e. not "I'm used to it", "I don't like it" and such) reason not to use the default IBus method? 

You also neglected to mention that this results in `WARNING **: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input` messages on the console and quick search for that shows that [it isn't Poedit or wx specific](http://www.linuxquestions.org/questions/linux-software-2/error-converting-text-from-im-to-utf-8-a-927013/) and [seems related to locale](http://devel.aegisub.org/ticket/1205) — i.e. the XIM method is broken and doesn't work correctly if the application runs under the "C" locale. That would be consistent with the 1.6 timeline.

Oh well, it's locale time. This *hotfix* (read: improper gross hack) patch fixes it:
```diff
diff --git a/src/edapp.cpp b/src/edapp.cpp
index 0c64527..6f8963d 100644
--- a/src/edapp.cpp
+++ b/src/edapp.cpp
@@ -340,6 +340,8 @@ void PoeditApp::SetupLanguage()
     trans->AddStdCatalog();
     trans->AddCatalog("poedit");
 
+    setlocale(LC_ALL, "");
+
     wxString bestTrans = trans->GetBestTranslation("poedit");
     Language uiLang = Language::TryParse(bestTrans.ToStdWstring());
     UErrorCode err = U_ZERO_ERROR;
```

**Comment by LocutusOfBorg** [comment]
Hi @vslavik do you think this "fix" will go on the next release or should debian apply it?

I'm inclined to wait for the new release (if you want to push this workaround on master) since we are on release-freeze

let me know,

thanks :)

**Comment by vslavik** [comment]
> Hi @vslavik do you think this "fix" will go on the next release or should debian apply it?

No and no. The proper way is to use `wxLocale` for this — I'll push a fix to that affect to the `maint-1.7` branch soon.

**Comment by LocutusOfBorg** [comment]
thanks! so I'll keep following your changes then :)

**Comment by 375gnu** [comment]
> Sounds like something obscure that no normal person would use, then, doesn't it? Is there any legitimate (i.e. not "I'm used to it", "I don't like it" and such) reason not to use the default IBus method? 

It's the simplest method to use XCompose.

> You also neglected to mention that this results in WARNING **: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input messages on the console

I don't run poedit from console, so I never saw that message.

Anyway you hotfix works.
