### ISSUE TITLE
Translation strings for WordPress plugin/theme description and author not created

### ISSUE THREAD

**Issue by afragen** [vslavik/poedit#146]
Apparently the `makepot.php` in WordPress creates strings for the Author and Description fields. These fields aren't created when Poedit parses a plugin or theme.

May we consider this a feature request? Thanks.

**Comment by vslavik** [comment]
> These fields aren't created when Poedit parses a plugin or theme.

That would be because `xgettext` has no knowledge of them and they require custom extraction. It requires a custom hack to add them. I had multiple requests for this already and plan to have it in Pro version in 1.8.

**Comment by afragen** [comment]
Thanks.
