### ISSUE TITLE
Validate formatting placeholders (%s, %d, etc)

### ISSUE THREAD

**Issue by dezlov** [vslavik/poedit#147]
Formatting placeholders (%s, %d, etc) in strings are used to insert dynamic content within static and usually translatable text. Most programming languages (C, C++, PHP, Pascal, Java, etc) support them and many applications actively use them.

Miss-placed, miss-typed or simply missing formatting placeholders in the translated text can cause application issues, from minor confusion to more serious application crashes (due to type incompatibilities for example).

Validating formatting placeholders could save the day. By extracting a list of used placeholders in each string and simply comparing them.

**Comment by dezlov** [comment]
I wrote a small PHP script that validates simple formatting placeholders (e.g. %s, %d, etc), but could be easily expanded to also process more complex placeholders (e.g. %10.4d, %.1f, etc) by adjusting the regex pattern. Below is a snippet to demonstrate. 

Call `PoToolkit::containSamePlaceholders($msgid, $msgstr)` for every PO entry, it returns `true` if placeholders match, otherwise `false`.

```php
class PoToolkit
{
	public static function extractPlaceholders($str)
	{
		// strip escaped placeholder symbol
		$str = str_replace('%%', '', $str);
		$matches = array();
		if (preg_match_all('#%[\w]\b#', $str, $matches) !== false)
			return $matches;
		else
			return array();
	}

	public static function containSamePlaceholders($str1, $str2)
	{
		$phs1 = self::extractPlaceholders($str1);
		$phs2 = self::extractPlaceholders($str2);
		if (count($phs1) != count($phs2))
			return false;
		$index = 0;
		$count = count($phs1);
		while ($index < $count)
		{
			$ph1 = array_shift($phs1);
			$ph2 = array_shift($phs2);
			if ($ph1 != $ph2)
				return false;
			$index++;
		}
		return true;
	}
}
```

**Comment by vslavik** [comment]
`msgfmt` already validates format strings and Poedit's validation functionality uses it. I'm not sure what's the point of obvious code snippet in irrelevant (for Poedit) language either to honest…

**Comment by dezlov** [comment]
I am talking about Poedit's built in Validate functionality. It doesn't seem to be catch mismatched placeholders for me...

**Comment by vslavik** [comment]
Again: `msgfmt` most definitely *does* validate these. Whatever the problem is, it's on your end. Most likely not having strings tagged as `php-format` (read the gettext manual).

**Comment by dezlov** [comment]
Here is a simple example of some PO entries which according to Validate functionality fine:
> *No problems with the translation found. The translation is ready for use.*

```
msgid "Example"
msgstr "Example"

msgid "Result: %d out of %d matched."
msgstr "Result"

msgid "Not supported format (%d)"
msgstr "Not supported format"
```

Am I missing something? Shouldn't validation give out that some placeholders are missing?

**Comment by vslavik** [comment]
> Am I missing something?

Yes — AND I ALREADY TOLD YOU EXACTLY WHAT ABOVE. Please read the goddamn GNU gettext manual already, it exists for a reason.
