### ISSUE TITLE
Bing Translations

### ISSUE THREAD

**Issue by renemaas** [vslavik/poedit#149]
Please also add Bing Translator for internet translation suggestions.
It often gives better results than Google does.

http://www.microsoft.com/web/post/using-the-free-bing-translation-apis

**Comment by vslavik** [comment]
Poedit doesn’t use Google Translate’s suggestions, but rather the [MyMemory engine](https://mymemory.translated.net). As far as I know, it sources Microsoft Translator too. In any case, while Translator may provide better suggestions for some specific languages and texts, I believe MyMemory is better overall, across all languages — generally speaking, Translated.net are *the* guys to go to for CAT expertise.

It’s also worth noting that Microsoft Translator API isn’t free, but uses volume-based monthly subscription and it’s (at its current pricing anyway) financially not feasible to fund its usage without making Poedit *itself* subscription-based, which I’d really rather not.

**Comment by vslavik** [comment]
Times change. Some engines improve, some less so, and  some things that made sense in 2015 no longer do in 2018.

Starting with 2.1 (now [in beta](https://poedit.net/download)), Poedit ditches MM for machine translation and uses a combination of [DeepL](https://deepl.com) (if your language is supported, that's what you want to use — [better](https://www.deepl.com/quality.html) than Google's, even w/ NMT), Google Translate and Microsoft Translator.
