### ISSUE TITLE
Bugs in extractors management

### ISSUE THREAD

**Issue by lapause** [vslavik/poedit#151]
Version used: 1.7.4 (3549) - OS X
- Disabling extractors seems to have no effect on files parsing. A library I use (AWS PHP SDK) has a misformed RST file. Even if I only check PHP and Javascript extractors, my catalogs are still not updated as an error occurs on parsing the RST file.
- If I remove all the extractors I never use (including the RST one), the parsing goes fine and my catalogs are updated correctly. However, after closing and starting again the application, all the extractors are back and enabled :-(

**Comment by vslavik** [comment]
Always worth checking *current* code before filing bugs at GitHub: d3c2a38757a0621cda73d59094db6396d0944f48
