### ISSUE TITLE
Long settings window in russian translation

### ISSUE THREAD

**Issue by Zoxon** [vslavik/poedit#154]
![2015-03-25 15-25-54](https://cloud.githubusercontent.com/assets/3866196/6821673/4f3d07e6-d303-11e4-8040-2f04690a6228.png)

In inglish window has normal width. 
v 1.6.6
Widows 7 x64

**Comment by vslavik** [comment]
> v 1.6.6

The latest version is 1.7.5. Please *always* try the latest version first before reporting any problem; if reporting on GitHub, check the `master` branch first as well. That’s not Poedit-specific advise, BTW: *always* do that.
