### ISSUE TITLE
Previous / Next grayed out in Find Window

### ISSUE THREAD

**Issue by c72578** [vslavik/poedit#155]
Poedit version: 1.8beta1
OS: Linux, Windows

During beta version testing it turned out that the buttons Previous and Next are grayed out as shown in the attached screenshot.

![poedit_find_wrap_around](https://cloud.githubusercontent.com/assets/371551/7026575/dd68083a-dd4a-11e4-8d19-78d991a36bb2.png)

**Comment by vslavik** [comment]
Please *always* include detailed steps on how to reproduce — see [why](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html). Even if you may think it’s obvious, changes are that’s not in fact the case. Such as here, where I can *not* reproduce this myself.

(Also, a more detailed description of the environment than just “Linux” or “Windows” would be nice, neither is exactly specific.)

**Comment by c72578** [comment]
Steps to reproduce:
- Start Poedit 1.8beta1
- Open a po file (e.g. a previously downloaded "App strings" de_DE.po from Crowdin for Poedit)
- Press Ctrl+F
- Enter a "String to find"

Tested operating systems, where the problem occurs:
- Fedora 21 (3.19.3-200.fc21.x86_64, further details can be provided)
- Windows XP SP3, de

Tested operating system, where the problem does not occur:
- Windows 7 64Bit, SP1, de

**Comment by vslavik** [comment]
> where the problem does not occur:

Aha! That tidbit explains a lot, must be related to XP’s text controls lacking native support for placeholders then. I’ll look into it a.s.a.p.

(By the way: 1.8.x will probably be the last version to support XP. It’s causing problems all the time, as here, and almost nobody uses it anymore.)
