### ISSUE TITLE
Replace window, String to find deleted

### ISSUE THREAD

**Issue by c72578** [vslavik/poedit#156]
Poedit version: 1.8beta1
OS tested: Linux, Windows

As soon as text is entered into the field "Replacement string", the previously entered "String to find" is deleted again. The buttons (except Close) are grayed out, similar to the find window.

![poedit_replace](https://cloud.githubusercontent.com/assets/371551/7026673/6f8bd85e-dd4b-11e4-953a-794c45488c4d.png)

**Comment by vslavik** [comment]
Again, please include *detailed*, step-by-step instructions on how to reproduce it. Can’t be reproduced as described here.

**Comment by vslavik** [comment]
Is this Windows XP?!

**Comment by c72578** [comment]
Steps to reproduce:
- Start Poedit 1.8beta1
- Open a po file (e.g. a previously downloaded "App strings" de_DE.po from Crowdin for Poedit)
- Press Ctrl+H
- Enter a "String to find"
- Enter "Replacement string"
- The string entered under "String to find" is deleted

Tested operating systems, where the problem occurs:
- Fedora 21 (3.19.3-200.fc21.x86_64, further details can be provided)
- Windows XP SP3, de

Tested operating system, where the problem does not occur:
- Windows 7 64Bit, SP1, de
