### ISSUE TITLE
Enhancement: Spell checking

### ISSUE THREAD

**Issue by prescott66** [vslavik/poedit#158]
Hi. I need often to check spell checking in translated strings massively, but it ist very annoying do that one by one string.
It would be great, if Poedit can mark strings with wrong typed words as fuzzy. Then will translator check only fuzzy strings and not whole .po file.

**Comment by vslavik** [comment]
Spellchecking is done as you type — correct the highlighted misspellings *before* moving to another item.

It would be extremely annoying to normal workflows if anything that fails spellchecking (e.g. unknown words, markup) etc. hard-fuzzied the entry and you’d have to fight the spellchecker to avoid it. It would also cause mass confusion as many users wouldn’t realize that fuzzy entries won’t appear in the compiled MO (this is not a hypothesis, this is experience).

Won’t do, sorry.

**Comment by prescott66** [comment]
I dont ment that this fuzzy marking should by automated and always enabled. only just a button in top bar for example...and can be usefull for users who are translation checkers, and checks not own translations

**Comment by vslavik** [comment]
Proofreading workflow would be a nice addition to Poedit, but a proofreader *needs to look at each entry* as well. This really makes very little sense to have.
