### ISSUE TITLE
Regression: Esc key closes entire application, not just the Find dialog

### ISSUE THREAD

**Issue by alexhenrie** [vslavik/poedit#160]
Pressing Ctrl+F and then Esc should close the Find dialog, not the entire application.

547b115c69ab2ac7fde285c9b5653cbd8309a930 is the first bad commit
commit 547b115c69ab2ac7fde285c9b5653cbd8309a930
Author: Václav Slavík <vaclav@slavik.io>
Date:   Sat Mar 14 13:35:32 2015 +0100

    Use a floating tool window for Find
    
    Keep the window on top of the parent frame at all times, don't show it
    in taskbar and use the small "inspector" window decorations on OS X. The
    latter is what couldn't be accomplished with wxDialog, so change to
    using wxFrame and make the necessary changes.

**Comment by vslavik** [comment]
And your platform is…?

**Comment by alexhenrie** [comment]
Linux.
