### ISSUE TITLE
Feature: show source code permanently in the side bar

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#167]
Similar to #166, I’d like to use the large space in the side bar to show me contextual information that helps me during translation. (My screen is 1920x1280.)

When translating software, the source texts usually know where they appear in the source code. There is already a menu item to show the source code in a separate window.

I’d like to have a similar feature that permanently shows the source code of the current entry, and when I switch to another entry, the source code changes as well.

Currently, when I want to see the source code, I have to open a window for each entry, and later I have to close it again. That’s definitely possible, but also much work.

**Comment by vslavik** [comment]
The references window *already* behaves like this since 9bdeafd98baf5e533d58e630d95a003189ecc843. Please check the current state of `master` before going on an issues-filing spree ;-)

**Comment by rillig** [comment]
Wow, I just tried it and it really feels great. Thank you very much. I think I’ll keep using the beta version instead of the official releases. :)
