### ISSUE TITLE
Opening a file two times at the same time freezes Poedit

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#168]
To reproduce on Windows 7 with Poedit 1.8beta1:

1. Start Poedit by double-clicking on a PO file
2. Start another Poedit by double-clicking on the same PO file again

The first Poedit opens normally, the second one shows the menu bar and then freezes. When I quit the first Poedit, the second one thaws again, opens the file and continues normally.

**Comment by vslavik** [comment]
This too was already fixed, in f14313bd56514024ab9ccc121dc21204c7372088.
