### ISSUE TITLE
Save to an untouched format

### ISSUE THREAD

**Issue by BassLineHUN** [vslavik/poedit#170]
Dear Developers,

I have to try use poedit for a big translation project (more than 10.000 items) and I have a big problem with saving the .po file:

- poedit do many format change that is unacceptable for me for the use of .po file!
- It change the translated lines also, deleting spaces, line breaks, etc.

Is it possible to develop a function to let the user able to save to the EXACTLY THE SAME format that it was and opened ?

Thank you for the help in advanced!
Regards,

BassLine

**Comment by vslavik** [comment]
> poedit do many format change that is unacceptable for me for the use of .po file!

I fail to see how is this related to the size of the project...

You also didn’t mention *any* relevant information, such as the specifics of this horrible “unacceptable” formatting issue, or which version of Poedit you use. Poedit allows you to configure your desired formatting in the preferences, so this seems to me to be a case of you not checking for the latest version first.

> Is it possible to develop a function to let the user able to save to the EXACTLY THE SAME format that it was and opened ?

It certainly is and if you have any improvements over the *current* behavior (which is generally good enough), I will gladly merge your pull request with improvements. 

(Please only use this tracker to file bugs (see [this guide](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) first). http://poedit.net/support lists more appropriate channels for non-bug questions.)

**Comment by BassLineHUN** [comment]
Dear Vslavik,

Thank you for the help and sorry that I have written my task to a wrong place.
I have describe my problem with detaild by mail.

Regards,

BassLine
