### ISSUE TITLE
configure missing in 1.8

### ISSUE THREAD

**Issue by mcirsta** [vslavik/poedit#175]
Hi, 

 I'm trying to build poedit on Linux but in the 1.8 configure seems to be missing and autoreconf gives a strange error.

 Is there another way to build on Linux ?

**Comment by mcirsta** [comment]
I think I've just found ./bootstrap which is probably what needs to be run first. If this is the case the instructions should probably be updated

**Comment by vslavik** [comment]
The Unix source tarball of course *does* contain `configure`. Git tree doesn't, because it's a generated file — by the standard and commonly used `bootstrap` script. 

> If this is the case the instructions should probably be updated

The instructions are fine and explain both tarball- and git-based building. They just need to be *read*.

**Comment by mcirsta** [comment]
I've downloaded the v1.8-oss.tar.gz which doesn't contain any configure, not sure what's the difference between it and poedit-1.8.tar.gz which does indeed contain a configure ... 
 It's a bit confusing, I downloaded that because it said "source code".

**Comment by vslavik** [comment]
If the filenames & icons are not a dead give-away for you which are GitHub-generated *repository snapshots* and which are actual release tarballs, please just use http://poedit.net/download which does link to the correct file and doesn’t cause any confusion about GitHub UI.

**Comment by mcirsta** [comment]
Yep , that clears things up. I just used github and honestly most of the github projects I've seen only include what you'd call repository snapshots I guess.
 
 Anyway ... my bad, it was late at night, I downloaded what I thought was what I needed and didn't know what to do with it. It did work fine though after I ran bootstrap on it so I guess that's an option too.
