### ISSUE TITLE
CTRL+C works in the "original text" box

### ISSUE THREAD

**Issue by tititiou36** [vslavik/poedit#176]
On windows, It is possible to modify what is written in the "original text" box, when doing a CTRL+C. The text in the clipboard gets copied

This is not taken into account (when you select another text and select the "modified" one, the original string is displayed) but can be disturbing.

**Comment by vslavik** [comment]
Ctrl+C is *copy*, it can’t possibly overwrite the text of the Source text box.

Please describe what is actually happening, how to reproduce it, including your Windows version, Poedit version (the fact that you use “original text” term replaced years ago makes me suspect it is not 1.8) and your Poedit preferences settings related to editing.

**Comment by tititiou36** [comment]
Oops, obviously, I was meaning CTRL+V !

Windows XP SP3, POedit 1.7.6 downloaded 2 weeks  ago from poedit.net
I was not aware of 1.8 (available since a fews days ago ?)

How to reproduce : 
   - have something in the clipboard (CTRL+C something somewhere)
   - click in the "Texte Original :" box (in the French version)
   - CTRL+V

![screenshot](https://cloud.githubusercontent.com/assets/679652/7798755/68070378-02fe-11e5-8473-88b916d7f8a6.jpg)

**Comment by vslavik** [comment]
Oops, it’s real :-(

> I was not aware of 1.8

Any particular reason for not allowing automatic checks for updates?

**Comment by tititiou36** [comment]
In my company, we try to have consistent version of the tools we use. So each user should not upgrade to new versions whenever something new is released. This is because of possible regression, change in file format, different UI...

Unless special cases (severe regretion, great new feature, security issue for some of our tools...), we upgrade our tools once or twice a year.
