### ISSUE TITLE
Poedit build failure

### ISSUE THREAD

**Issue by LocutusOfBorg** [vslavik/poedit#178]
Hi Vaclav, not really a bug, but I submit as issue anyway.

Poedit doesn't build if casablanca is available, but there is no webview wx package.
(link failure).

Maybe having a check when cpprest is used for wx-webview might avoid troubles to other people facing the same build failure.

In the meanwhile I'm going to upload poedit 1.8 in Debian/experimental with the added build-dependency libwxgtk-webview3.0-dev

thanks!

**Comment by vslavik** [comment]
Poedit’s configure script adds the webview sublibrary if casablanca is enabled to the list of wx sublibraries for `WX_CONFIG_CHECK `: https://github.com/vslavik/poedit/blob/master/configure.ac#L100

So yes, it is required and Poedit won’t build without it. Not a bug.

**Comment by LocutusOfBorg** [comment]
mmm thanks, but the question actually was:
"shouldn't in this case the error be thrown by the configure script rather than in the build process?"

**Comment by vslavik** [comment]
> but the question actually was:

Perhaps you should have written that from the start… Checking wx availability is `WX_CONFIG_CHECK`’s responsibility, I don’t think something like this is worth working around in Poedit’s script. If it doesn’t check for actual presence, it should be improved in wx’s `wxwin.m4`, not in Poedit.

**Comment by LocutusOfBorg** [comment]
thanks, indeed this is a wxwin.m4 bug.
thanks!

**Comment by vslavik** [comment]
FYI, 1.8.2 (imminent) will no longer require wxWebView, see 48fcff60. It was replaced with a new .desktop file to handle the `poedit://` URI scheme from browsers.

**Comment by LocutusOfBorg** [comment]
wonderful! In the meanwhile I opened a Debian bug with a patch inside.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786986
Unfortunately a wxwidgets 3.0 is waiting in the binary-NEW queue (we added the doc package), so every fix should wait a little bit :)

thanks again,

G.
