### ISSUE TITLE
Catalogs manager: update all reports does not say what language it is updating

### ISSUE THREAD

**Issue by mfrasca** [vslavik/poedit#182]
when you do a mass update using the update all button, you will get a possibly very long sequence of dialog windows reporting about each po file being updated.
the title of the window could tell you which language the report is relative to.
as of now you either count (I have 20 languages in my project), or you just click all away.

an other option could be to organize the reports in one window and in as many tabs as the languages.

the window could show as soon as possible, and as the new reports are available, poedit could add more tabs. the user could this way check the reports in random order.
the button for clicking away the report window should not appear before all reports have been produced.

**Comment by vslavik** [comment]
The catalogs manager is crap all around. I recommend not using it. It's unlikely to be touched in any major way until Poedit 2 (IOW, there's no point in creating more issues about it) at which point it will be either significantly reworked or removed.
