### ISSUE TITLE
A \n was added when pasting a string, and not removable. 

### ISSUE THREAD

**Issue by kaio** [vslavik/poedit#184]
There's a \n attached to the end of translated string when I copied that from my browser and pasted to the translation input box. I tried to remove such \n but it came back when I focused on another segment and focus back. 

Procedures:
1. Go to an empty segment. 
2. Copy a string from browser. 
3. Paste string on the input box. 
4. Remove the \n from the end of the pasted string. 
5. Focus another segment and focus back this segment. 
6. Check results. 

Expected: no \n at all or won't be there after removed. 
Observed: the \n is not removable.

**Comment by vslavik** [comment]
`\n` highlights newlines. It is correct and expected behavior that it is shown after every newline you entered.

If you don't want to have a trailing newline, don't enter it, or delete it (the *newline* preceding `\n`, not *only* `\n`).

**Comment by vslavik** [comment]
On second thought, reopening because you're not the first person confused by this and not realizing that newlines are editable whitespace characters.

**Comment by kaio** [comment]
Thanks for your quick response. 

I know I can edit the \n, so I removed that immediately. However, the problem is when I switched to another segment and come back, the \n appears again.

**Comment by vslavik** [comment]
As I already wrote above: You need to delete *THE ACTUAL NEWLINE*, not the `\n` marker. You didn't. You *STILL* have a newline in your translation. Poedit merely highlights it. You need to delete it. The newline, not (only) the visual indicator of its presence. If the cursor is *under* the text you wrote, there's evidently a newline involved. If you don't want to have a newline at the end of the text, you must end editing it with a cursor to the right of the text (as in any other text editor), not under it.

**Comment by kaio** [comment]
Thanks for your patience. I got what you mean now. Is that possible to have that marker "not editable" to avoid misunderstandings from users?

**Comment by vslavik** [comment]
Yes, it's "possible". It's also insanely huge amount of work (low level changes to *three* layout engines, of which only one has direct-yet-complicated-and-poorly-documented support for it). Would be worth doing if 10% of Poedit users were confused by this, but not when it's 0.001% or so.

**Comment by kaio** [comment]
No problem.
