### ISSUE TITLE
Poedit uses pt-PT instead of pt_BR

### ISSUE THREAD

**Issue by elchevive** [vslavik/poedit#185]
Hi,

I'm using poedit 1.8.1, Win 7 and pt_BR locale. But poedit loads the pt (pt_PT) translation when setting system default, even if I choose pt_BR its always load the pt_PT version.

Its easy to see the differece, The File menu, in pt_BR is transated as "Arquivo", in pt_PT as "Ficheiro".

Regards

**Comment by vslavik** [comment]
Thanks; I'm aware of this screw-up, it was due to a bug in Crowdin export that I didn't notice, it will be fixed in 1.8.2. (You can also get the correct PO file from https://crowdin.com/project/poedit, compile it into MO and replace Poedit's version until then if it's too annoying.)
