### ISSUE TITLE
Down- and upvoting of online suggestions

### ISSUE THREAD

**Issue by lanurmi** [vslavik/poedit#186]
Could there be a way to report completely bogus or inapplicable translation suggestions to whatever online TM they are coming from?

I don't mean suggestions that are just "wrong" for a particular context, but suggestions that are e.g. in the wrong language, or contain typos. I recall seeing a suggestion given in German when everything else was in Spanish. Also the first suggestion in the screenshot below is not very useful for anyone despite its 99% match.
![poedit-suggestion](https://cloud.githubusercontent.com/assets/5632407/8235209/5ba3846e-15e9-11e5-90fe-b872562bbb40.png)

**Comment by vslavik** [comment]
Poedit uses 3rd party service that has no such capability in its API — there's very little I can do right now.

Mid- to long-term, I plan to proxy Poedit's suggestions through a server under my control to apply some gettext specific fixups (I'm sure you noticed not everything is done perfectly) and it would certainly make sense to do as you suggest (thanks!).

In fact, Poedit should arguably "upvote" suggestions that are used automatically and then only have a button for reporting/downvoting the Really Bad ones as in here. Leaving the issue open for this, but I can't promise any timeframe just yet.

**Comment by vslavik** [comment]
Starting with 2.0.7, the suggestions that I have control over (i.e. user-contributed ones from Poedit) are automatically upvoted when manually used. UI for explicit downvoting of crap is coming in 2.1.
