### ISSUE TITLE
Feature Request: TM DB Import/Export

### ISSUE THREAD

**Issue by kaio** [vslavik/poedit#188]
I found that the TM DB was stored in my [User Home Dir]\AppData\Roaming\Poedit\TranslationMemory, I am requesting a feature to import/export that into a packaged file so that users can do back-ups or sharing among their team members.

Thank you very much.

**Comment by vslavik** [comment]
> I am requesting a feature

You are always welcome to implement it and submit a PR…

The TM consists of *files*, you can backup or copy it perfectly fine.
