### ISSUE TITLE
Crash after pressing Enter under GTK+ 3 when inserting `\n` markup

### ISSUE THREAD

**Issue by meskobalazs** [vslavik/poedit#190]
At the 1.8.1 version (in Fedora 22) when I write to the translation text field, the application sometimes crashes when the enter button is pressed. 

This always happens when the field is empty, or the line ends with a specific character. The characters I have tried are the backslash (`\`), angle brackets (`<`, `>`) and curly brackets (`{`,`}`).

**Comment by vslavik** [comment]
Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and add all the missing information that is necessary to be able to *reproduce* it. In particular, but not limited to:

* Backtrace from `gdb`.
* Step-by-step instructions on how to reproduce, and any necessary files.

If your reproduction instructions boil down to "sometimes it crashes when I type something", all I can do is say that I didn't hit this particular "some{time,thing}" yet. I can't fix what I can't *see*.

It certainly can't be as described here, `\` is the only character of those that may be treated specially, and that's done with care. Something crucial is missing here.

**Comment by meskobalazs** [comment]
What I did: 
 - Opened a `.po` file, selected a translation line
 - Hit an enter in the translation field
 - Crash

A gdb output:

    (poedit:8958): Gtk-WARNING **: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
    You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
    You can apply tags and insert marks without invalidating your iterators,
    but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
    will invalidate all outstanding iterators

    (poedit:8958): Gtk-CRITICAL **: _gtk_text_buffer_get_line_log_attrs: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

    (poedit:8958): Gtk-WARNING **: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
    You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
    You can apply tags and insert marks without invalidating your iterators,
    but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
    will invalidate all outstanding iterators
    [New Thread 0x7fffbeffd700 (LWP 8973)]
    [New Thread 0x7fffbf7fe700 (LWP 8972)]
    [New Thread 0x7fffbffff700 (LWP 8971)]
    [New Thread 0x7fffd6df0700 (LWP 8970)]
    [New Thread 0x7fffd65ef700 (LWP 8969)]
    [New Thread 0x7fffd5dee700 (LWP 8968)]
    [New Thread 0x7fffd77fe700 (LWP 8962)]
    [New Thread 0x7fffd7fff700 (LWP 8960)]
    [New Thread 0x7fffde218700 (LWP 8959)]

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff1ce49e7 in inside_word_func () from /lib64/libgtk-3.so.0

**Comment by vslavik** [comment]
> What I did:

Can you please read the article I linked to? You seem to still not understand that you need to describe things, including your environment and what you *do* in more detail than "I opened a file". In fact, you're contradicting yourself: previously you claimed relation to some specific characters, now you claim you don't need to type anything and it happens with every possible PO file regardless of what it contains — which is simply not the case.

So which one is it?

> The gdb output:

I didn't ask for output (which says only a single thing: that yes, it crashes for you, without any information about *why*, which is what I'm after). I asked for the *backtrace*. If you didn't know what I was talking about, you could have asked Google and would find https://fedoraproject.org/wiki/StackTraces in a minute. Do notice how that page explains why backtraces without debug information are not useful, so make sure you fix that first (clearly, you don't have dbginfo above).

**Comment by vslavik** [comment]
Never mind, just got an independent report that included reproducible test case.
