### ISSUE TITLE
changes the path of files comments #: /path/to/file

### ISSUE THREAD

**Issue by siran** [vslavik/poedit#194]
Although the Preferences option of `preserve formatting of existing files` is checked, on Save poEdit changes

```
#: /pah/to/file:line1
#: /pah/to/file2:line10
#: /pah/to/file3:line15
```

to

```
#: /pah/to/file:line1 /pah/to/file2:line10 /pah/to/file3:line15
```

I think it should preserve the formatting in all sensible ways (encoding and line wrapping are working OK).

**Comment by vslavik** [comment]
You should interpret the option as "Preserve formatting…*within reason,"* i.e. for formatting done by GNU gettext tools.

Yes, it would be nicer not to touch this part, but honestly, it's such a minuscule defect that I don't expect to fix it anytime soon. If it bothers you, submit a PR.

**Comment by siran** [comment]
I noted that the 'bug' comes from msgcat... it shouldn't do that...

**Comment by vslavik** [comment]
> it shouldn't do that…

You're welcome to discuss it with GNU gettext folks at *their* bug tracker. Anything other than a PR here (such as commenting about your believes about what gettext tools "should" do) is completely pointless here.
