### ISSUE TITLE
Build error:  wx/preferences.h file not found

### ISSUE THREAD

**Issue by chris5560** [vslavik/poedit#195]
Thanks for support
Christian
```
$ make V=99
Making all in src
make[1]: Verzeichnis »/home/christiana/csbuild/poedit/src« wird betreten
depbase=`echo edapp.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"poedit\" -DPACKAGE_TARNAME=\"poedit\" -DPACKAGE_VERSION=\"1.8.3\" -DPACKAGE_STRING=\"poedit\ 1.8.3\" -DPACKAGE_BUGREPORT=\"help@poedit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"poedit\" -DVERSION=\"1.8.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_MKDTEMP=1 -DDB_HEADER=\"db_cxx.h\" -DDB_HEADER=\"db_cxx.h\" -I.     -g -O2 -std=gnu++11 -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -I/usr/include/x86_64-linux-gnu   -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/gtkspell-2.0   -I/usr/local/include/lucene++     -Wall -Wextra  "-DPOEDIT_PREFIX=\"/usr/local\"" -MT edapp.o -MD -MP -MF $depbase.Tpo -c -o edapp.o edapp.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from edapp.h:35:0,
                 from edapp.cpp:66:
prefsdlg.h:30:28: fatal error: wx/preferences.h: Datei oder Verzeichnis nicht gefunden
 #include <wx/preferences.h>
                            ^
compilation terminated.
make[1]: *** [edapp.o] Fehler 1
```

**Comment by vslavik** [comment]
> Datei oder Verzeichnis nicht gefunden

Hate to break the news to you, but not everybody speaks German, as you apparently believe. Would it hurt you to use the default locale when submitting messages? Or for that matter provide at least a *bit* of information about your system, how you build it, and so on?

As a quick Google search would tell you (if seeing the `wx/` prefix doesn't hit at that enough), `wx/preferences.h` is a *wxWidgets* header. This library is detected by configure. So either you hacked up `configure.ac` to make it pass or you have a fucked-up installation of wxWidgets and need to fix that.

In any case, this is not a *Poedit* issue at all.

**Comment by chris5560** [comment]
I git clone from here.
looking into src/wx/ there is no preferences.h as the source code of edapp.h is looking for.
so this file needs to be there.
.configure works fine and I'm also compiling other apps using wxWidgets without errors but they provide much more files in src/wx.
So not a german problem simply a missing file in src/wx.
Thanks

**Comment by vslavik** [comment]
> looking into src/wx/ there is no preferences.h as the source code of edapp.h is looking for.
...
> but they provide much more files in src/wx

Sigh. `src/wx` has files *using* wxWidgets, not a copy of this *third party* library. That "so this file needs to be there" is pure nonsense. You seem to be perplexed by the whole concept of *system-provided* dependencies. Perhaps you'd be better of using precompiled packages?

> So not a german problem simply a missing file in src/wx.

Sigh. The problem with German is your arrogance in not even bothering to provide the log in English. Understanding what I wrote as somehow the German locale *causing* your problems is absurd, I don't know how you arrived at that.

Please read what I wrote above again, with more attention. *Check* if the wx directory you pointed configure to (`/usr/include/wx-3.0`) contains the header. It doesn't, so fix that. *Read your distro's manual* about compiling from sources. If you persist in believing this is somehow Poedit's fault, read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html *first*, then answer my questions above and provide evidence that it is Poedit's fault and that the header in *system-installed copy of wx* exists. Please don't post here until you do all of that, because it would be pointless.

**Comment by chris5560** [comment]
Distro LinuxMint 17.02
Package wx3.0-headers 3.0.0-2 nothing else available at Ubuntu
No preferences.h
Do need a newer version ?

**Comment by vslavik** [comment]
> Distro LinuxMint 17.02
> Package wx3.0-headers 3.0.0-2 nothing else available at Ubuntu

You seem to be confused about what distro you have. And of course there *is* more than the headers there. As I already told you, kindly read Ubuntu's documentation on complication from sources. It will clear your confusion about quite a few things (if you pay more attention than here, that is) and will introduce you to the existence of `-dev` packages.

> No preferences.h

See? You have a broken system installation of wx. YOU NEED TO FIX THAT, AS I REPEATEDLY TOLD YOU. 

This is not a Poedit issue. This is you having a screwed up wx installation and refusing to see it. It may be an Ubuntu packing bug or wx's make install bug. What it certainly isn't, though, is a *Poedit* bug.

> Do need a newer version ?

You need to, first and foremost, *LISTEN* and do everything I told you. Not one thing from the list picked at random: EVERYTHING. You asked for "support" — why are you wasting my time like that when you *completely ignore* the responses? What's wrong with you?

I already gave you instructions above. You continue to ignore it all, including the request to please do your homework before posting. Please stop doing that.

**Comment by vslavik** [comment]
Apparently a [long-ago fixed wx issue](https://github.com/wxWidgets/wxWidgets/commit/3ab8839562b094c7287d697121fc18956dff1ca6).
