### ISSUE TITLE
Accelerator key for "O.k." in comments dialog

### ISSUE THREAD

**Issue by KennethNielsen** [vslavik/poedit#204]
Hallo poedit devs and thanks for a wonderful program.

When I tend to translate, I use shortcuts a lot, to keep my hands on the keyboard. However, when I have to enter a comment, I find it a little clumsy that the only way I can get out of the dialog is via ctrl-tab (to the ok-key) and enter. It would be great if there was an accelerator key for the ok button, so that I could just do: alt-o or something similar.

Regards Kenneth

**Comment by vslavik** [comment]
The customary shortcut is *Ctrl+Enter*, I believe. A PR to that effect would be gladly accepted.

**Comment by KennethNielsen** [comment]
@vslavik *Ctrl+Enter* would do the job. I have zero C++ experience, but maybe I will give it a shot if I find the time.
