### ISSUE TITLE
Difficult to find donate information

### ISSUE THREAD

**Issue by KennethNielsen** [vslavik/poedit#205]
Hallo poedit devs

Upon installing poedit on a new machine I was met with a dialog asking me if I wanted to donate. When I pressed yes it took me to the front of the website, but I was unable to find any information there about how to do it (the word donate does not appear anywhere on the front page), except buying the pro version. I'm I looking in the wrong place or is buying pro the only way to donate? In that case, maybe the wording in the dialog should be a little more clear, so that I will know what to look for. If there actually is a option to simply donate an amount, I think it should be easier to find. (Or maybe I just missed it for some reason.)

Regards Kenneth

**Comment by vslavik** [comment]
There are no donations. You are using some prehistorical version of Poedit. Please *always* check if you're using the latest version (and if you're not, update and re-check) before filing issues.

**Comment by KennethNielsen** [comment]
Oh wow, you are correct, 1.5.4 from 2012. I am using the latest packaged version in the Ubuntu (and I guess Debian) repositories. Sorry about the noise.
