### ISSUE TITLE
German translation too long in „may poedit submit your translations“ notification

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#206]
![2015-09-12 21_07_35-quelldatei](https://cloud.githubusercontent.com/assets/3233724/9833326/9516e032-5992-11e5-9209-2317c7ea5275.png)

**Comment by c72578** [comment]
During reproducing the behavior here I found the following.
It is dependent on the width of the Poedit window. So the title of this issue should be changed, as it also happens with other languages.
Tested under:
OS: Windows 7 (SP1, 64bit, de)
Poedit: 1.8.4 (4014)

The following screenshots show Poedit with German language (windows 1161 pixel, OK) and English (window 893 pixel, cropped text)

![poedit_1 8 4_tm_question_1_de_w1161pix](https://cloud.githubusercontent.com/assets/371551/9835553/4487bce0-59f1-11e5-9da6-1a8aae67a05c.png)

![poedit_1 8 4_tm_question_2_en_w893pix](https://cloud.githubusercontent.com/assets/371551/9835554/4bb94b32-59f1-11e5-8e06-7b82b7164d3f.png)

**Comment by vslavik** [comment]
Thanks for reporting! There are multiple issues at play here:

1. The German translation of "Apply to all…" is extremely long even by German standards :( 
2. The layout is wide-centric; it would help, if the checkbox was *beneath* the two buttons.
3. Finally, the layout can't cope with insufficient space, truncating stuff.

@c72578 if you think anything can be done with the string from 1. that certainly wouldn't hurt, but as you said, this affects more languages — apparently, this is one of those strings that are unusually short in English. So I'll need to address 2. + 3. anyway.

**Comment by vslavik** [comment]
Putting the checkbox under the buttons doesn't really work (too ugly), so I think this is the least bad fix:

![modified screenshot](https://cloud.githubusercontent.com/assets/145881/10018909/767fb040-613a-11e5-9650-3081f307d345.png)

The bold text now reflows properly, as it should, and I'll update long translations of this text to take two lines.

**Comment by vslavik** [comment]
For reference, this is the other layout variant, which isn't even significantly more narrow:
![2](https://cloud.githubusercontent.com/assets/145881/10020241/27b7a1f4-6142-11e5-97ef-cd9a93af92c8.png)
