### ISSUE TITLE
Setting “check spelling” automatically tries to correct input

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#207]
When I have the “check spelling” checkbox activated and type “command --sort file” into the large Translation input field, it is automatically changed to “command --Sort file”, which a capital S. This is unexpected, since “check spelling” usually means “just check and mark the errors, but don’t automatically try to correct them”.

OS: Windows 8.1
Poedit: 1.8.4 (4014)

**Comment by c72578** [comment]
Which versions are you using (OS, Poedit etc.)?

**Comment by vslavik** [comment]
> Which versions are you using (OS, Poedit etc.)?

(Yes, please always include this information, it's almost always relevant. In the case of spellchecking, which is done completely natively and thus differently on all three platforms, it is doubly so. The language used as well as the complete text being edited in question may very well be relevant here as well.)

> This is unexpected, since “check spelling” usually means “just check and mark the errors, but don’t automatically try to correct them”.

That's actually not true these days. Both [OS X](http://google.com/search?q=os+x+autocorrect) and [Windows](http://google.com/search?q=windows+spell+checking+autocorrect) autocorrect typos and this is enabled by default.

In any case, Poedit simply uses the platform's native spellchecking, so it behaves the same way as in all other applications (that use native spellchecking, such as MSIE on Windows). Or it *should* — if it behaves differently for you, please reopen with more information about how to reproduce it.
