### ISSUE TITLE
Update packages on linux distributions

### ISSUE THREAD

**Issue by stavarengo** [vslavik/poedit#209]
On Ubuntu, the version available is still 1.5.4.

**Comment by vslavik** [comment]
This may come as a surprise, but I am not the maintainer of all distros under the sun. Mandatory reading material [here](https://www.google.com/search?q=how+do+linux+distributions+work). Also do notice that distro *versions* are a thing and your claim that this is the latest packaged version is patently false for the version of Ubuntu that actually is *latest*.

**Comment by fitojb** [comment]
@stavarengo: For the record, here’s [a table](http://packages.ubuntu.com/search?keywords=poedit) of the Poedit versions available in each (supported) release of Ubuntu.
