### ISSUE TITLE
msgctxt rewriting inconsistently adds empty context

### ISSUE THREAD

**Issue by brycecr** [vslavik/poedit#210]
My template file contains 

```
#: web/apps/entities.js:110
msgctxt "web/apps/entities.js:110"
msgid "Upcoming entities"
msgstr ""

#: web/apps/entiites/views/view.js:276
msgctxt "web/apps/entities/views/view.js:276"
msgid "Unnote"
msgstr ""
```

And the resulting po file saved from poedit (with no translations for these strings) gives
```
#: web/apps/entities.js:110
msgctxt "web/apps/entities.js:110"
msgid "Upcoming entities"
msgstr ""

#: web/apps/entiites/views/view.js:276
msgctxt ""
"web/apps/entiites/views/view.js:276"
msgid "Unnote"
msgstr ""
```

I.e., sometimes the msgctxt is preserved exactly as written, but sometimes the empty string is added to the context. The translation system I am using interprets the empty string as "any context", so this makes a difference. Any idea why the difference and is this a bug / is there a way to control this?

**Comment by vslavik** [comment]
There's no “rewriting” or “adding empty context”, let alone “inconsistently” — Poedit only formats the files in GNU gettext standard way, using GNU gettext standard tools, for *consistency*, without altering the represented content in any way.

There’s no bug here. Well, no, that’s not true: there *is* a bug, and a pretty serious one, *in this “translation system” you’re using*. Please educate the developer of that “translation system” on the syntax of the PO files: http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html#sec-powrap.

While you’re at it, consider gently hinting that setting the context to a *file location* (which is already set properly with `#:`!) is stupid and they might want to read up on the proper use of contexts in the gettext manual.

The only workaround I can suggest is going to Preferences→Advanced and unchecking checkboxes (or keeping the wrap one with much larger value).

**Comment by brycecr** [comment]
Thanks for the response. This does indeed appear to be an abuse of msgctxt.
