### ISSUE TITLE
Spellchecking of empty strings under GTK

### ISSUE THREAD

**Issue by c72578** [vslavik/poedit#212]
Description of problem:
Whenever you press enter in the translation field of Poedit, the following message appears on the command line:
** (poedit:5339): CRITICAL **: enchant_dict_check: assertion 'len' failed

Version-Release number of selected component (if applicable):
- Poedit: master branch, commit 21f9c6fdee21a85af2a889526b9cb26b5b46f173
ldd output see below
- OS: Fedora 22, 4.1.7-200.fc22.i686

How reproducible:
Always on this system

Steps to Reproduce:
- Compile Poedit with spell checking enabled under Linux/GTK
- Start Poedit from command line
- Open a .po file
- Press enter inside the translation field
- Check command line for output

Actual results:
Unexpected critical error message:
** (poedit:5339): CRITICAL **: enchant_dict_check: assertion 'len' failed

Expected results:
No error message on command line

Additional info:
ldd /usr/bin/poedit 
	linux-gate.so.1 (0xb776c000)
	libwx_gtk3u_xrc-3.0.so.0 => /lib/libwx_gtk3u_xrc-3.0.so.0 (0xb75e8000)
	libwx_gtk3u_stc-3.0.so.0 => /lib/libwx_gtk3u_stc-3.0.so.0 (0xb7390000)
	libwx_gtk3u_html-3.0.so.0 => /lib/libwx_gtk3u_html-3.0.so.0 (0xb72b5000)
	libwx_baseu_xml-3.0.so.0 => /lib/libwx_baseu_xml-3.0.so.0 (0xb72a5000)
	libwx_gtk3u_adv-3.0.so.0 => /lib/libwx_gtk3u_adv-3.0.so.0 (0xb70fc000)
	libwx_gtk3u_core-3.0.so.0 => /lib/libwx_gtk3u_core-3.0.so.0 (0xb6b6c000)
	libwx_baseu_net-3.0.so.0 => /lib/libwx_baseu_net-3.0.so.0 (0xb6b1b000)
	libwx_baseu-3.0.so.0 => /lib/libwx_baseu-3.0.so.0 (0xb6875000)
	liblucene++.so.0 => /lib/liblucene++.so.0 (0xb5ff9000)
	libexpat.so.1 => /lib/libexpat.so.1 (0xb5fcf000)
	libboost_regex.so.1.57.0 => /lib/libboost_regex.so.1.57.0 (0xb5ed9000)
	libboost_system.so.1.57.0 => /lib/libboost_system.so.1.57.0 (0xb5ed5000)
	libicui18n.so.54 => /lib/libicui18n.so.54 (0xb5c70000)
	libicuuc.so.54 => /lib/libicuuc.so.54 (0xb5adf000)
	libicudata.so.54 => /lib/libicudata.so.54 (0xb42b2000)
	libgtkspell3-3.so.0 => /lib/libgtkspell3-3.so.0 (0xb42a8000)
	libenchant.so.1 => /lib/libenchant.so.1 (0xb429b000)
	libgmodule-2.0.so.0 => /lib/libgmodule-2.0.so.0 (0xb4296000)
	libgtk-3.so.0 => /lib/libgtk-3.so.0 (0xb3b59000)
	libgdk-3.so.0 => /lib/libgdk-3.so.0 (0xb3a90000)
	libpangocairo-1.0.so.0 => /lib/libpangocairo-1.0.so.0 (0xb3a83000)
	libpango-1.0.so.0 => /lib/libpango-1.0.so.0 (0xb3a37000)
	libatk-1.0.so.0 => /lib/libatk-1.0.so.0 (0xb3a12000)
	libcairo-gobject.so.2 => /lib/libcairo-gobject.so.2 (0xb3a0b000)
	libcairo.so.2 => /lib/libcairo.so.2 (0xb38c8000)
	libgdk_pixbuf-2.0.so.0 => /lib/libgdk_pixbuf-2.0.so.0 (0xb389e000)
	libgio-2.0.so.0 => /lib/libgio-2.0.so.0 (0xb370c000)
	libgobject-2.0.so.0 => /lib/libgobject-2.0.so.0 (0xb36b9000)
	libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0xb3577000)
	libstdc++.so.6 => /lib/libstdc++.so.6 (0xb33fc000)
	libm.so.6 => /lib/libm.so.6 (0xb33ae000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb3390000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xb3373000)
	libc.so.6 => /lib/libc.so.6 (0xb31a7000)
	libmspack.so.0 => /lib/libmspack.so.0 (0xb3192000)
	libX11.so.6 => /lib/libX11.so.6 (0xb3051000)
	libSDL-1.2.so.0 => /lib/libSDL-1.2.so.0 (0xb2fb0000)
	libXxf86vm.so.1 => /lib/libXxf86vm.so.1 (0xb2fa9000)
	libSM.so.6 => /lib/libSM.so.6 (0xb2f9f000)
	libpng16.so.16 => /lib/libpng16.so.16 (0xb2f66000)
	libjpeg.so.62 => /lib/libjpeg.so.62 (0xb2f06000)
	libtiff.so.5 => /lib/libtiff.so.5 (0xb2e91000)
	libz.so.1 => /lib/libz.so.1 (0xb2e79000)
	libdl.so.2 => /lib/libdl.so.2 (0xb2e74000)
	/lib/ld-linux.so.2 (0x800b1000)
	libboost_date_time.so.1.57.0 => /lib/libboost_date_time.so.1.57.0 (0xb2e63000)
	libboost_filesystem.so.1.57.0 => /lib/libboost_filesystem.so.1.57.0 (0xb2e4c000)
	libboost_iostreams.so.1.57.0 => /lib/libboost_iostreams.so.1.57.0 (0xb2e35000)
	libboost_thread.so.1.57.0 => /lib/libboost_thread.so.1.57.0 (0xb2e11000)
	librt.so.1 => /usr/lib/librt.so.1 (0xb2e08000)
	libXi.so.6 => /lib/libXi.so.6 (0xb2df5000)
	libXfixes.so.3 => /lib/libXfixes.so.3 (0xb2def000)
	libatk-bridge-2.0.so.0 => /lib/libatk-bridge-2.0.so.0 (0xb2dc0000)
	libepoxy.so.0 => /lib/libepoxy.so.0 (0xb2d00000)
	libpangoft2-1.0.so.0 => /lib/libpangoft2-1.0.so.0 (0xb2cea000)
	libfontconfig.so.1 => /lib/libfontconfig.so.1 (0xb2ca5000)
	libXinerama.so.1 => /lib/libXinerama.so.1 (0xb2ca1000)
	libXrandr.so.2 => /lib/libXrandr.so.2 (0xb2c95000)
	libXcursor.so.1 => /lib/libXcursor.so.1 (0xb2c89000)
	libXcomposite.so.1 => /lib/libXcomposite.so.1 (0xb2c85000)
	libXdamage.so.1 => /lib/libXdamage.so.1 (0xb2c80000)
	libxkbcommon.so.0 => /lib/libxkbcommon.so.0 (0xb2c3e000)
	libwayland-cursor.so.0 => /lib/libwayland-cursor.so.0 (0xb2c35000)
	libwayland-egl.so.1 => /lib/libwayland-egl.so.1 (0xb2c32000)
	libwayland-client.so.0 => /lib/libwayland-client.so.0 (0xb2c26000)
	libXext.so.6 => /lib/libXext.so.6 (0xb2c12000)
	libgthread-2.0.so.0 => /lib/libgthread-2.0.so.0 (0xb2c0f000)
	libharfbuzz.so.0 => /lib/libharfbuzz.so.0 (0xb2bb1000)
	libfreetype.so.6 => /lib/libfreetype.so.6 (0xb2b06000)
	libpixman-1.so.0 => /lib/libpixman-1.so.0 (0xb2a54000)
	libEGL.so.1 => /lib/libEGL.so.1 (0xb2a2b000)
	libxcb-shm.so.0 => /lib/libxcb-shm.so.0 (0xb2a27000)
	libxcb-render.so.0 => /lib/libxcb-render.so.0 (0xb2a1c000)
	libxcb.so.1 => /lib/libxcb.so.1 (0xb29f7000)
	libXrender.so.1 => /lib/libXrender.so.1 (0xb29eb000)
	libGL.so.1 => /lib/libGL.so.1 (0xb293b000)
	libffi.so.6 => /lib/libffi.so.6 (0xb2931000)
	libselinux.so.1 => /lib/libselinux.so.1 (0xb290c000)
	libresolv.so.2 => /lib/libresolv.so.2 (0xb28f0000)
	libICE.so.6 => /lib/libICE.so.6 (0xb28d4000)
	libuuid.so.1 => /lib/libuuid.so.1 (0xb28cd000)
	libjbig.so.2.1 => /lib/libjbig.so.2.1 (0xb28c0000)
	libbz2.so.1 => /usr/lib/libbz2.so.1 (0xb28ae000)
	libatspi.so.0 => /lib/libatspi.so.0 (0xb2880000)
	libdbus-1.so.3 => /lib/libdbus-1.so.3 (0xb2832000)
	libgraphite2.so.3 => /lib/libgraphite2.so.3 (0xb2812000)
	libX11-xcb.so.1 => /lib/libX11-xcb.so.1 (0xb280f000)
	libxcb-dri2.so.0 => /lib/libxcb-dri2.so.0 (0xb2809000)
	libxcb-xfixes.so.0 => /lib/libxcb-xfixes.so.0 (0xb2800000)
	libxcb-shape.so.0 => /lib/libxcb-shape.so.0 (0xb27fa000)
	libgbm.so.1 => /lib/libgbm.so.1 (0xb27ec000)
	libwayland-server.so.0 => /lib/libwayland-server.so.0 (0xb27dc000)
	libdrm.so.2 => /lib/libdrm.so.2 (0xb27cd000)
	libXau.so.6 => /lib/libXau.so.6 (0xb27c9000)
	libglapi.so.0 => /lib/libglapi.so.0 (0xb277e000)
	libxcb-glx.so.0 => /lib/libxcb-glx.so.0 (0xb2763000)
	libxcb-dri3.so.0 => /lib/libxcb-dri3.so.0 (0xb275f000)
	libxcb-present.so.0 => /lib/libxcb-present.so.0 (0xb275b000)
	libxcb-randr.so.0 => /lib/libxcb-randr.so.0 (0xb274b000)
	libxcb-sync.so.1 => /lib/libxcb-sync.so.1 (0xb2742000)
	libxshmfence.so.1 => /lib/libxshmfence.so.1 (0xb273f000)
	libpcre.so.1 => /lib/libpcre.so.1 (0xb26cd000)

**Comment by vslavik** [comment]
Poedit doesn't perform spellchecking itself, it just hooks up GtkSpell with the text control. A quick Google search confirms that this is indeed an already-fixed GtkSpell bug: http://sourceforge.net/p/gtkspell/mailman/message/33494688/
