### ISSUE TITLE
Preserve formatting doesn't seem to have an effect

### ISSUE THREAD

**Issue by Moini** [vslavik/poedit#213]
Using 1.8.5 on LM 17.2, (trusty base), compiled it using your repo supplying the missing packages and up-to-date wxwidgets from their web site (self-compiled because of a bug in the version from my repo, the one that deletes all obsolete translations).

Now I've got another bug that makes version control impossible (my changes are almost invisible between all the changes introduced by the program) - or maybe I'm just using it the wrong way:

Opened a .po file.
Edited it.
Saved it.

Preserve formatting was checked (from the start), but it doesn't. Instead it throws different cpp source files into the same line (before, they were all on separate lines), and it even makes the lines longer than the given line limit (set to 79, but I get 92) (the option is checked - but from that other bug report, I understand it will be ignored, if preserve formatting is also checked.).

I found that just unchecking the 'preserve formatting' box will use the preset line width, which is - fortunately - all I needed, the diff is no longer messed up. I'd still prefer 'preserve formatting' to work as expected, so I won't have to check line lengths manually for every file, to keep the diff from going wild.

**Comment by vslavik** [comment]
> doesn't seem to have an effect
...
> makes version control impossible 
...
> Instead it throws 

Less inflammatory rambling, more facts please. Such as *specific* description of the *exact* misbehavior (contrary to your apparent believe, preserve the formatting actually does work well, you're hitting some corner case, specifics of which you provide zero information). With files necessary to actually understand what misbehavior you're talking about and reproduce it.

Generally speaking, Poedit preserves *reasonable* formatting, i.e. one that GNU gettext uses. Of course, patches from good OSS citizens to improve it further are always welcome.

**Comment by Moini** [comment]
Thank you for your answer, and for asking for more specifics. 

I don't see what I wrote as 'inflammatory rambling', and if you look closely, you might find that, too. It's just the talk of an imperfect user who has difficulties with a software.

Beside the po files (before + after, I guess?), which other specifics exactly would you need? 
I told you how I compiled, which system I'm on, which options were checked, and how the result was different from what I expected.

Renamed file extensions to txt to be able to upload here, which should work according to github's error message - still doesn't work... :/
So find them here:
http://staging.inkscape.org/en/gallery/item/30/
and 
http://staging.inkscape.org/en/gallery/item/31/

Settings tab:

![bildschirmfoto_2015-09-29_16-04-58](https://cloud.githubusercontent.com/assets/3240233/10166436/45beecd4-66c4-11e5-9bb9-befe8e6b9899.png)

Btw. I had a hard time to find out how to compile poedit for my system. I had tried this at the beginning of this year, when this post: http://ubuntuforums.org/showthread.php?t=2287693 hadn't existed, and couldn't make it work, because of the long chain of dependencies. 
Just an idea: maybe you could add the info about your lucene files ppa to the README? I think it could be helpful to a few people. Guess you'll want another bug report for this, too?

**Comment by vslavik** [comment]
> I don't see what I wrote as 'inflammatory rambling

You make ridiculous accusations (which I quoted) exaggerating your case, that's the very definition of “inflammatory” (for example: minor formatting issue is not “making version control impossible”, but *at worst* introducing one extra reformatting commit). If your interest was purely in resolving the issues you’re having, you would use language more appropriate to the situation and the fact that this is OSS code. E.g. I certainly wouldn’t complain if you had a patch handy...

> which other specifics exactly would you need?

I already answered that… From the files (thanks!), it seems that the width was misdetected somehow, for this particular file, and that’s all. For example, it’s not true that “[.cpp files] were all on separate lines” — there were instances of both, but you only noticed the cases where the width boundary was crossed. From that, I expected the file to use non-standard formatting that would be hard to preserve, but that doesn’t appear to be the case here, fortunately.

> Btw.

Don’t make a convoluted mess of bug trackers, keep one issue per *one issue* — typing “BTW” is a good indicator that you’re not following that. That said, no, there’s no “long chain of dependencies”, just a few — but modern versions of Poedit depend on modern versions of dependencies, so either stick to packaged versions, upgrade to a current distro version or build deps from sources. The PPA you mention is for my private needs and if you use it, feel free, but you’re on your own — it’s not something I’m willing to make semi-official by linking to it from anywhere. I may delete it tomorrow if I don’t need it, but need the Launchpad space (which has quotas) for something else.

**Comment by vslavik** [comment]
The culpit was a long comment line that Poedit counted towards the formatting width, but shouldn’t (`msgcat` doesn’t reformat comments). I’m seeing some other differences in file references formatting that I think are attributable to different `msgcat` versions and that would be too complicated to address (plus it will resolve itself in due time).
