### ISSUE TITLE
Poedit goes blank on Update

### ISSUE THREAD

**Issue by LikeBtn** [vslavik/poedit#214]
Windows 8.1 (64bit)
Poedit 1.8.5

When I click "Update" the translation sections just disappears:
![poedit_screenshot](https://cloud.githubusercontent.com/assets/8167133/10251480/a91c1942-6939-11e5-9c5b-0ce921a6a380.png)

Find .po file in "translations" folder:
https://mega.nz/#!B0NEQbCJ!V1-00on4pUj7tAvDOmVQqPYn2uR__glVNflgrD5prY8

**Comment by vslavik** [comment]
You actually have to configure source code extraction to find strings to extract. If you don't have any translatable strings, Poedit naturally won't find any. See the GNU gettext manual.

If you still believe there's a bug in Poedit, please provide a reproducible test case with an explanation of *why* you think it's misbehaving (please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html too).
