### ISSUE TITLE
Poedit does not open on El Capitan

### ISSUE THREAD

**Issue by michaelbeil** [vslavik/poedit#215]
Any others having this issue?

**Comment by vslavik** [comment]
> Any others having this issue?

No. The latest version of Poedit just fine, without any known issues.

BTW, please don't spam every channel you could find with the same question; pick one and politely give non-zero time for reply. Please also see http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and give me some credit: do you really thing it would go unnoticed if Poedit didn't work on 10.11? *Of course* not, so whatever it is that is happening on your system, it's not normal.

**Comment by michaelbeil** [comment]
You do a great job @vslavik! 

I just noticed an issue when I was needing to use the program and I am still having an issue when I open Poedit. Any suggestions?

I am a fellow dev and apologize if this caused a bad taste in your mouth.

**Comment by michaelbeil** [comment]
I deleted Poedit, and reinstalled and now everything is golden. There must have been an issue with the update.

**Comment by michaelbeil** [comment]
Cheers! :beers:

**Comment by vslavik** [comment]
> Any suggestions?

Yes, the one from above: give me some credit and report the issue as a developer should. With details, reproduction steps, tons of relevant information incl. at least relevant console logs, versions involved etc. Now that you know that "El Capitan" is *not* the relevant factor here (or not the only one), do what developers do: help *diagnose* the cause. Running `/Application/Poedit.app/Contents/MacOS/Poedit` from a command line may reveal some useful error too.

**Comment by mahype** [comment]
Just delete the app and reinstall it. I had the same problem and for me it worked. ;)
