### ISSUE TITLE
show cursor position in statusbar to allow easy length checking

### ISSUE THREAD

**Issue by DidierSpaier** [vslavik/poedit#218]
Hi Václav,

I am using poedit 1.8.5

I would like to be able to display in the status bar the cursor's position (starting from 1) in the being edited line of the translation. That would be helpful e.g. for a translator when instructed to limit lines length.

This is not redundant with the automatic line wrap as the allowed line's length can vary among messages in the same file. For instance the translator could insert a \n when she sees that else the line would be too long.

I have already made a similar request, see
https://groups.google.com/forum/#!searchin/poedit/line$20length/poedit/KD6w7_piLOI/eEhQfyWZhdYJ

Sorry to bother you once again but I still feel a need for that feature.

Best regards,
Didier
didier (at) slint (dot) fr

**Comment by vslavik** [comment]
It’s still as I said before: this isn’t a high priority and while I’m leaving the open because yes, it would be nice to *eventually* have it, there are lots of arguably more important things on my todo list.

So your best bet *still* is to provide a patch. Stop “feeling a need” and *do something about it* instead. That’s generally a much more productive approach ;)

**Comment by DidierSpaier** [comment]
Huge thanks Václav!

I will pull master and upgrade

Best regards,
Didier

**Comment by DidierSpaier** [comment]
Hi Václav!,

I failed to build poedit up to and including eb1bd4e.

I attach the build log.
[poedit_giteb1bd4e.LOG](https://github.com/vslavik/poedit/files/6232530/poedit_giteb1bd4e.LOG)

Best regards,
Didier

**Comment by vslavik** [comment]
@DidierSpaier Please don't use the *bug tracker* as support forum.

**Comment by DidierSpaier** [comment]
... And the issue was in the build of one of the deps, sorry for the noise. You may now delete my previous comment
