### ISSUE TITLE
Poedit update fails in non-admin account

### ISSUE THREAD

**Issue by igorlino** [vslavik/poedit#224]
POEdit fails update since it does not triggers the admin rights dialog.

All window programs installers/updaters typically/usually trigger the windows rights popup dialog, that shows/asks for  admin login account.

Since POEdit is not triggering for the admin rights, the update fails eventually. Its really an inconsistency.

The workaround, is to go the website and download the installer, and execute it under as "Admin", then it installs properly.

**Comment by vslavik** [comment]
> POEdit fails update since it does not triggers the admin rights dialog.

Not true exactly like that. See #201 for what is *actually* going on (and please check at least the open issues first to avoid filling duplicates?).

**Comment by igorlino** [comment]
sorry for the duplicate. The "elevate rights" is the better wording. I simply cannot install the package unless I execute as elevated user, this is the 1st time of the hundreds of applications installers that have used where I have this problem, so its specific to POEdit installer/updater.

**Comment by vslavik** [comment]
> I simply cannot install the package 

This is simply not true. You *can* install it. Of course, as a non-admin user, you must install into a location you actually have permission to copy files to. This is very much *not* specific to “Poedit's installer” (which is the widely used Inno Setup). 

Again, this is described in the other bug, including the rationale.
