### ISSUE TITLE
Is there any way to turn off verify function?

### ISSUE THREAD

**Issue by fyrestone** [vslavik/poedit#226]
My project use string id instead of string itself. for example,  my po file is a [string id] to [translated string] map. so, the translated string may contains the '\n' character.

But, when i use poedit to compile po to mo, it show error: 'msgid' and 'msgstr' entries do not both begin with '\n'.

**Comment by vslavik** [comment]
> Is there any way to turn off verify function?

(Please only use the bug tracker for filling bugs, not asking questions.)

No, there is no way to disable the validation, nor do I intend to add it (for one thing, it comes from gettext, not Poedit). You can disable compilation to MOs in Preferences and compile manually, if this annoys you.

Generally speaking, if you abuse gettext in ways it was never intended to be used (the *whole point* of gettext is that it eliminates the need for those stupid symbolic IDs!), you must expect some rough edges in the tools. Things generally work much better when you follow best practices.
