### ISSUE TITLE
[Suggestion] Drop Down: Widget title as label w/ for attribute

### ISSUE THREAD

**Issue by mikeg-de** [vslavik/poedit#232]
For optimal user experience having the widget title set as an label element with the for attribute matching the drop down id would be great.

Markup example footer widget (inline script removed):
<div id="polylang-5" class="fwidget et_pb_widget widget_polylang">
	<label for="lang_choice_polylang-5" class="title">Language</label> 
	<select name="lang_choice_polylang-5" id="lang_choice_polylang-5">
		<option value="en" selected="selected">English</option>
		<option value="ru">Русский</option>
		<option value="de">Deutsch</option>
	</select>
</div>

Markup example using plugin Widgets in Menu for WordPress (inline script removed):
<div id="polylang-4" class="yawp_wim_widget widget_polylang">
	<label class="yawp_wim_title">Language</label> 
	<select name="lang_choice_polylang-4" id="lang_choice_polylang-4">
		<option value="en" selected="selected">English</option>
		<option value="ru">Русский</option>
		<option value="de">Deutsch</option>
	</select>
</div>

**Comment by vslavik** [comment]
I have literally no idea what the heck you’re talking about. None of what you wrote makes any sense to me, nor do I see any relation to Poedit. Please elaborate (a *lot*).

**Comment by mikeg-de** [comment]
Excuse me, accidentally submitted to wrong project
