### ISSUE TITLE
Source keys with custom / literal strings??

### ISSUE THREAD

**Issue by foo123** [vslavik/poedit#241]
Hi,

i'm using poedit to provide translations for an php app which uses templates, where localisation functions
are eventualy rendered as `Contemplate::plg_("l","text here")`

i can also add literal (original) localisation functions e.g `App::l("text here")` in templates, but for other reasons i would prefer to use the template plugin notation above.

![snap-2016-02-22-at-16 15 58](https://cloud.githubusercontent.com/assets/1263582/13220575/9bd65340-d97f-11e5-9d53-123eae0a1bcc.png)

Second case can be handled by poedit as usual. How about adding source keys for the first case?
It would require to be able to declare literal strings, or partial function patterns. Is it doable or any workaround?

Thank you

**Comment by vslavik** [comment]
(Please use the issue tracker for *issues*, not questions. http://poedit.net/support lists appropriate channels for the latter.)

Upgrade to the latest version, which you clearly don't have (this should be common sense, but: *always* do that before filing an issue!). Then click on the link there that takes you to a GNU gettext manual section describing the syntax for the keywords. That's all there is.

Poedit can't magically make `xgettext` do things it can't do. I suggest you change your code to be more traditional/xgettext-compatible/sane instead.

**Comment by foo123** [comment]
Thanks, wasnt sure if any workaround for that matter was possible at all (maybe would be a good idea to accept keyword patterns). 

In any case i have solved the issue otherwise, while meeting the requirements i have.

**Comment by vslavik** [comment]
> maybe would be a good idea to accept keyword patterns

Nah, it really wouldn't. xgettext (which, again, does the extraction, not Poedit) is capable of handling any normal uses of gettext in PHP code. But in any case, you're complaining at the wrong place.

**Comment by foo123** [comment]
Yes i understand, as a sidenote, it would be quite useful if a tool could extract localisation texts from functions or other code patterns out of the source code itself.

These days working with templates (which sometimes do not have a c-like syntax) is common place. Maybe poedit is not for that, but it would be a nice tool anyway.

Thanks and kep up the good work.

**Comment by vslavik** [comment]
> sidenote

Please don't, that's not how you use bug trackers.

>  it would be a nice tool anyway.

Use Google. Plenty of them.
