### ISSUE TITLE
Error while compiling in linux

### ISSUE THREAD

**Issue by pdelgadohurtado** [vslavik/poedit#243]
Error in compiling in linux manjaro (archlinux based) source from poedit-1.8.7.tar.gz

### Configure log:

`checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking for install location... /usr/local
checking for gawk... (cached) gawk
checking whether ln -s works... yes
checking for ranlib... ranlib
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking cpprest/http_client.h usability... no
checking cpprest/http_client.h presence... no
checking for cpprest/http_client.h... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for wx-config... /usr/local/bin/wx-config
checking for wxWidgets version >= 3.0.1 (--unicode)... yes (version 3.0.2)
checking for wxWidgets static library... no
checking if wxWidgets includes XRC... yes
checking for wxrc... /usr/local/bin/wxrc-3.0
checking for mkdtemp... yes
checking for ICU... yes
checking if wxWidgets toolkit uses GTK+ 3... no
checking if wxWidgets toolkit uses GTK+ 2... yes
checking for GTKSPELL... yes
checking for LUCENE... yes
checking for Berkeley DB >= 4.7 (C++)... header db_cxx.h, library -ldb_cxx
checking for EXPAT... yes
checking cld2/public/compact_lang_det.h usability... no
checking cld2/public/compact_lang_det.h presence... no
checking for cld2/public/compact_lang_det.h... no
checking for a sed that does not truncate output... /usr/bin/sed
checking whether the C++ compiler accepts the -Wall flag... yes
checking whether the C++ compiler accepts the -Wextra flag... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating artwork/Makefile
config.status: creating locales/Makefile
config.status: creating docs/Makefile
config.status: executing depfiles commands

Configured poedit-1.8.7 for x86_64-unknown-linux-gnu

Enabled features:

    * debug build:                    no
    * legacy (pre-1.6) TM migration:  yes
    * language detection:             no
    * crowdin integration:            no
`

### Make log and error (Log in spanish)

`Making` all in src
make[1]: se entra en el directorio '/home/pdelgado/Descargas/poedit-1.8.7/src'
  CXX    attentionbar.o
  CXX    errorbar.o
  CXX    catalog.o
In file included from catalog.cpp:46:0:
str_helpers.h:44:45: error fatal: boost/locale/encoding_utf.hpp: No existe el fichero o el directorio
compilación terminada.
Makefile:599: fallo en las instrucciones para el objetivo 'catalog.o'
make[1]: *** [catalog.o] Error 1
make[1]: se sale del directorio '/home/pdelgado/Descargas/poedit-1.8.7/src'
Makefile:351: fallo en las instrucciones para el objetivo 'all-recursive'
make: *** [all-recursive] Error 1`

**Comment by vslavik** [comment]
> Log in spanish

Please use English when reporting issues.

> str_helpers.h:44:45: error fatal: boost/locale/encoding_utf.hpp: No existe el fichero o el directorio
compilación terminada.

If you don't immediately see from this error that *you are missing Boost headers* and need to install them, you probably shouldn't be compiling from sources… Yes, `configure` should check for their presence (leaving open for that), but come on.
