### ISSUE TITLE
No selection mark in the strings list

### ISSUE THREAD

**Issue by SafaAlfulaij** [vslavik/poedit#246]
There is no selection mark (which indicates that the string/row is selected) in the strings list.
OS: Windows 10
PoEdit version: 1.8.7 (4193 build)
![poeditproblems](https://cloud.githubusercontent.com/assets/3509617/13512081/a9f20762-e1a9-11e5-9d8a-437aacdcb38b.png)

**Comment by vslavik** [comment]
This is absurd, you contradict yourself: your screenshot shows _that the selected row is indicated_ (1st one) — and in exactly same manner as in any other Windows application when it's out of keyboard focus (which is something you did as the user).

**Comment by SafaAlfulaij** [comment]
What I meant is the blue background of the row.
In other applications (Like VLC, HexChat), the selected row background turns to grey, so it still tells the user that this specific row is selected (the user doesn't have to guess from the list which is the selected row).
This is an example where the playlist item in the left panel is selected and has focus (light blue background), and the current track (in the table view) is selected also but doesn't have focus, that's why it appears with a grey background.
![poeditproblems_selection_example](https://cloud.githubusercontent.com/assets/3509617/13548552/01853b88-e304-11e5-8bab-391633c18a1b.png)

**Comment by vslavik** [comment]
Please *look* at your own screenshot of Poedit, which plainly shows the very same thing.
