### ISSUE TITLE
"Source string" label doesn't show anything

### ISSUE THREAD

**Issue by SafaAlfulaij** [vslavik/poedit#247]
There is no text in the "Source string" label when I'm translating a string. May be related to #246?
OS: Windows 10
PoEdit version: 1.8.7 (4193 build)
![poeditproblems](https://cloud.githubusercontent.com/assets/3509617/13512081/a9f20762-e1a9-11e5-9d8a-437aacdcb38b.png)
**Update:**
It happens for a while after starting the app only, the source strings shows up after a short delay.

**Comment by vslavik** [comment]
No, it isn't related to a bug that clearly says it was fixed a long time ago.

Please see http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and try to describe the problem more clearly — and, importantly, *reproducibly*, including providing a) the file in question and b) instructions on what exactly(!) to *do* with it. Basically, give me some credit: do you think Poedit *always* hide this? Of course not, there's something specific to your system or your file and to understand what that might be, you have to describe both in as much detail as possible. My preliminary guess is that there's something weird about the file, but...

**Comment by SafaAlfulaij** [comment]
Here is a test file:
```
#
msgid ""
msgstr ""
"Project-Id-Version: Test\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2010-04-27 17:42+0530\n"
"PO-Revision-Date: 2016-03-05 19:41+0300\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && "
"n%100<=99 ? 4 : 5);\n"
"Last-Translator: Safa AlFulaij <test@gmail.com>\n"
"Language-Team: \n"
"Language: ar\n"
"X-Generator: Poedit 1.8.7\n"

msgid ""
"Currently selected Data storage folder is readonly. The storage folder was temporarily switched to Internal "
"memory. Please choose valid storage directory."
msgstr ""
```
(The source and target strings are the most important, as they are the first entry in the file!)

How to reproduce? Open the file in PoEdit, Enter a long translation (that is almost as long as the source text), close the file (after saving of course) and open it again.
I tried: "aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa. aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa."

**Comment by vslavik** [comment]
Did the https://jumpshare.com/v/DH9d2PIrmQGxf5L1Ll1t build change anything about this?

**Comment by SafaAlfulaij** [comment]
Yes! Thanks a lot!
I didn't notice that!

**Comment by vslavik** [comment]
Funny thing: I actually didn’t do anything to address this. So something must have fixed it accidentally.

Closing for now, but let me know if it re-appears in newer versions.
