### ISSUE TITLE
Wrong text height in strings list

### ISSUE THREAD

**Issue by SafaAlfulaij** [vslavik/poedit#249]
When using a custom font (Noto Arabic Naskh here), the lines starts clipping as the height defined for them is fixed (I think). The app shouldn't do such a thing and be dynamic and get the correct height from the font file.
![poeditproblems_](https://cloud.githubusercontent.com/assets/3509617/13512375/4197e838-e1ab-11e5-8c66-ebc30d7c4753.png)

**Comment by vslavik** [comment]
> custom font (Noto Arabic Naskh

Let me guess: a font that has no Latin characters, correct? Thus forcing Windows in finding some substitute font to display the text and falling back to some with very different metrics for lack of a better choice.

If you insist on using a custom font, pick a sensible one that covers the Unicode range needed. Or use the system font.

In any case, Poedit uses a standard Windows ListView control, which doesn't allow for customizing the height in any other way than setting the font. It's not a Poedit issue, it's a Windows one, and there's nothing that can be done about it.

**Comment by SafaAlfulaij** [comment]
Then it's Windows problem, it's ok.
Even if I used a font that covers a good range (but big in size) the clipping happens. So I'll stick with suitable sizes :)
