### ISSUE TITLE
Fuzzy translation not saved to mo file

### ISSUE THREAD

**Issue by g-johnson** [vslavik/poedit#250]
Not sure if this is a feature or bug, but translations marked as fuzzy are not saved to the mo file.  I would prefer as a user that everything get saved to the mo file or at least have an option to do so.

**Comment by fitojb** [comment]
The .mo file is [binary](https://www.gnu.org/software/gettext/manual/html_node/MO-Files.html), so it does not make sense to attempt to save any data intended for human reading (that is the very point of the .po file!)

**Comment by g-johnson** [comment]
Understood... it is a feature. 

If I may make a suggestion then... If someone is saving a translation that includes fuzzy suggestions, it would be nice to alert them in some manner that the fuzzy suggestions are not saved to the mo file.

Thank you for your prompt reply.

**Comment by vslavik** [comment]
> If I may make a suggestion then.

May *I* make a suggestion? If you don't understand what something ("fuzzy") is, your first action shouldn't be to complain about it and file invalid issues, but look if it isn't actually described somewhere. There's a reason why the gettext manual, which explains basic gettext concepts very well, is linked to in the Help menu.

>  alert them in some manner

Such as, I don't know, explain this clearly in the manual? That doesn't seem to do much good to people who don't *read* manuals...
