### ISSUE TITLE
Adding custom source keywords to plural

### ISSUE THREAD

**Issue by Zaszczyk** [vslavik/poedit#252]
Hi, I use Phalcon framework and his adapter to use gettext and for plural translation the code is:
`
$this->translation->nquery('company.form.account.last_name_length_max', 'company.form.account.last_name_length_max', 32,);`

so I added to source keywords:
> nquery:1,2,3

But Poedit doesn't find this translation after update form sources. However when I change my code to use method ngettext:
`
$this->translation->ngettext('company.form.account.last_name_length_max', 'company.form.account.last_name_length_max', 32,);`
Poedit finds such translation now. However this code make fatal error, because translation adapter hasn't such method.

My plural forms is:

> "Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
> "|| n%100>=20) ? 1 : 2);\n"

So how should I add method nquery() to Poedit?

**Comment by vslavik** [comment]
Please only use the issue tracker for reporting *issues*, not asking questions — http://poedit.net/support describes appropriate channels for the latter.

In the Sources keywords tab, there's a "Learn about gettext keywords" link. Click it. Read the document. Then, once you learned what the syntax is, fix your keyword definition to actually say what you think it does. You have plenty of examples in there (hint: as you observed, your function is equivalent to `ngettext`; therefore, its kw definition needs to be equivalent to a `ngettext` one from the manual).

Also, as an aside, using symbolic string IDs with gettext is unwise. That's not how gettext is meant to be used.
