### ISSUE TITLE
RTL issues

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#255]
Hey there,

I'm using Windows 10 x86 Hebrew locale.
While translating the app, I encountered some RTL issues:
1. The icons in the main app's window are also RTL'd (mirrored), which shouldn't happen. Of course this applies only to RTL languages as hebrew/arabic. Reproducibility is 100%- just change the UI to hebrew/arabic and see the flipped icons.
2. The "Upgrade to Pro" button in RTL languages is not RTL'd (would be in arabic too but the translator chose to not include the english word "Pro"), which means that it would be read as "Pro Upgrade to-" (if I'm translating it back into english).
Now it looks like:
שדרג ל-Pro
While it should look like:
Pro-שדרג ל
Image for both issues #1 + #2:
http://prntscr.com/aiq2pz
3. Paths that are shown within the app (for example: Go to catalog tab > properties > Sources paths tab) shouldn't be RTL, the should remain in their LTR layout.
And why? If there's a hebrew/arabic letter/word within the path, it'll look a bit reversed.
For example, if the base path is my desktop, the path will look like:
http://prntscr.com/aiq6nb
While it should look like:
C:\Users\עליזה\AppData\Roaming\Poedit\Cache\Crowdin\Poedit_poedit_he.po

Thanks.

**Comment by vslavik** [comment]
> some RTL issues

Pro tip: Whenever you find yourself writing that, stop, and split it into _one_ issue for _one_, well, issue. This is three independent, unrelated things, and hard to manage reasonably (e.g. closing the ticket with a commit is impossible).

> 1. The icons in the main app's window are also RTL'd (mirrored), which shouldn't happen.

That's very simplistic view — a lot, if not most, of the time (and that's exactly why it's the default in Windows), mirroring *should* happen. Which icons *specifically* do you object to? I can see one: the update icon with ↻ on it shouldn't be mirrored into anti-clockwise. Sidebar icon definitely should be mirrored, so should, I think, the statistics one (graph direction is derived from text direction, isn't it?), I'm unsure about the checkmark validate icon (depends on how you write checkmarks — how?).

> 2. The "Upgrade to Pro" button in RTL languages is not RTL'd

This is weird indeed, something forgot its own directionality somewhere :(

> 3. Paths that are shown within the app (for example: Go to catalog tab > properties > Sources paths tab) shouldn't be RTL, the should remain in their LTR layout.
> And why? If there's a hebrew/arabic letter/word within the path, it'll look a bit reversed.

I don't understand that explanation at all, and indeed, I'm sceptical here. Surely it should be aligned properly if the folders have Hebrew, not English names, and what if there's a mix? Anyway, more importantly, what does *Explorer* do? 

By the way, you can include screenshots directly in here, and it's better that way.

**Comment by ItielMaN** [comment]
> Whenever you find yourself writing that, stop, and split it into one issue for one, well, issue

Hmm. OK. You want me to make new ones or shall we continue discussing here?

> That's very simplistic view — a lot, if not most, of the time (and that's exactly why it's the default in Windows), mirroring should happen

Well, no! No icons should be reversed. Yeah, except for sidebar icon. That would make sense. But all the others should remain as they are in LTR languages.
See for example icons in explorer in Windows (hebrew locale):
![read](http://i.imgur.com/nkfNtN0.png)
All are as the ones in the english locale.
The checkmark validate icon also shouldn't be mirrored.
Also, the checkmarks in Preferences > Extractors are mirrored. Shouldn't be (like the ones General, TM, Updates and Advanced tabs. They look okay there).

> This is weird indeed, something forgot its own directionality somewhere :(

Hoping for a fix :)

> I don't understand that explanation at all, and indeed, I'm sceptical here. Surely it should be aligned properly if the folders have Hebrew, not English names, and what if there's a mix? Anyway, more importantly, what does Explorer do? 

The example I gave *is* with mixed english+hebrew words (unless I didn't understand your question).
In Explorer it looks fine:
![read](http://i.imgur.com/gwYb5Bu.png)
Adding hebrew words to the path in Explorer still makes it readable (and logical). However, adding a hebrew word to a non-RTL'd path (like in Poedit) will mess it up.

**Comment by vslavik** [comment]
> You want me to make new ones 

Certainly not! Just a note for future reference, is all.

> No icons should be reversed.

This is not true, really. See [this guide](https://www.google.com/design/spec/usability/bidirectionality.html) (not for Windows, but the principles apply generally). Any icons that include motion or text direction or are derived from it *should* be mirrored. Your own screenshot shows that: see how the pin in the sidebar is mirrored compared to LTR version:
![fe-win10](https://cloud.githubusercontent.com/assets/145881/14001395/ebb8199c-f145-11e5-9041-c0fb2a9f19b2.jpg)
(This also shows how Microsoft mirrors even *more* than I think reasonable: see how they mirror the ↻ and the looking glass when IMHO they shouldn't... but goes to underscore my point that it would be expected/acceptable on Windows.)

I think the only reasonable thing I can do is to switch my Windows to Hebrew completely, not just Poedit, to better understand native conventions. That's going to be fun.

> Hoping for a fix :)

Of course. I consider any RTL defects serious. They tend to slip in because even though I do test things under RTL locales, it's hard for me to spot the things that are subtly wrong when I don't speak the language(s) and am not familiar with the conventions, or don't realize that bidi text will screw some place up (using pseudo-languages only gets you so far). 

> Adding hebrew words to the path in Explorer still makes it readable (and logical). However, adding a hebrew word to a non-RTL'd path (like in Poedit) will mess it up.

Yeah, sorry, I didn't notice the broken part  at first — that's why I wasn't making any sense to you now :-( I thought you were referring to alignment. I can see the breakage now, thanks!

**Comment by ItielMaN** [comment]
> This is not true, really. See this guide (not for Windows, but the principles apply generally). Any icons that include motion or text direction or are derived from it should be mirrored. Your own screenshot shows that: see how the pin in the sidebar is mirrored compared to LTR version:

Okay, I may have exaggerated a bit with the "No icons should be reversed", but in Poedit's case the icons that *shouldn't be* mirrored are Open, Save, Verify (or was it Validate? can't remember), Update and maybe Sync (icon too small for me to judge). Oh and also the checkmarks in the Extractors tab in Preferences.
Now that I think about it, the icons in Explorer are really mirrored more than they should.. Didn't notice that before.

> I think the only reasonable thing I can do is to switch my Windows to Hebrew completely, not just Poedit, to better understand native conventions. That's going to be fun.
lol no, don't think it would be necessary..

**Comment by vslavik** [comment]
Can you see these black lines on your machine too, or is it just me? (All multiline texts in preferences..)

![parallels picture](https://cloud.githubusercontent.com/assets/145881/14022985/9572a65e-f1e2-11e5-8a94-6a8c88cf2634.png)

**Comment by ItielMaN** [comment]
Mine are thinner and lighter:
![preferences](https://cloud.githubusercontent.com/assets/18016656/14029626/db08e95c-f20b-11e5-9f36-386d6096b5f0.png)

Lol, these lines should be RTL'd too ><

**Comment by vslavik** [comment]
@ItielMaN @SafaAlfulaij With the exception of incorrectly mirrored images (not just toolbar, there’s more), this build should have most issues fixed: https://jumpshare.com/v/CuhDhrLDAQvYLigNG2sz Could you give it a try? This can be used to test the updater as well: https://jumpshare.com/v/NIn4OA19RSQYMccWgbHP

**Comment by ItielMaN** [comment]
Fixed:
- I can't see the black lines in the preferences window (not sure if that can be called "fixed")
- Upgrade to Pro mirroring
- Checkmarks in the Extractors tab in Preferences

Not fixed:
- The third issue in the first post
- Icons mirroring (what's left besides toolbar?)
- A new one: The Updater is not RTL'd at all

**Comment by vslavik** [comment]
> The third issue in the first post

Please provide details. I *did* address this in the places that were discussed here, so if something is still wrong, I need to know the exact details: where and what, exactly (i.e. the text or PO file with problems)….

> Icons mirroring

Yes, as I said...

**Comment by ItielMaN** [comment]
> Please provide details. I did address this in the places that were discussed here, so if something is still wrong, I need to know the exact details: where and what, exactly (i.e. the text or PO file with problems)….

See highlighted:
![d1](https://cloud.githubusercontent.com/assets/18016656/14441470/94b604f4-003d-11e6-8890-7a264abb41c2.png)
Should look like:
C:\Users\עליזה\Desktop\rambo\functions\lang\rambo.pot
(the difference is the hebrew word placement)

> Yes, as I said...

Yeah I know, was just pointing out the facts :)

**Comment by SafaAlfulaij** [comment]
Hi! Thanks for working on RTL issues!
Regarding the suggestions panel issue, it's solved! :)
![Suggestions panel](http://i.imgur.com/XErFdqI.png)
The preferences dialog also opens in the screen not outside of it.

But now I've found that the "developer comment" text isn't aligned (or LTR direction)! Maybe something is missing there?

**Comment by ItielMaN** [comment]
@SafaAlfulaij is right, the comments sections shouldn't be RTL'd.
Although as far as I can see, this issue appears also in the stable build..

**Comment by vslavik** [comment]
> A new one: The Updater is not RTL'd at all

Oops. I completely forgot it won’t inherit directionality. Replacement file: https://jumpshare.com/v/tBTMtEyBenxxeE6MDYiG

**Comment by ItielMaN** [comment]
Perfect! :)

**Comment by vslavik** [comment]
Unless I forgot something, this should fix the remaining issues: https://jumpshare.com/v/DH9d2PIrmQGxf5L1Ll1t

- Fixed icons
- Fixed recent files
- Detect language of both developer’s and translator’s comments and align them accordingly
- Fixes to rendering artifacts and misplacement of stats window from the other issues

**Comment by ItielMaN** [comment]
Hell yeah!
Looks perfect. A very good job :)

**Comment by ItielMaN** [comment]
2 other minor RTL issues I found:
1. In Preferences > Extractors > click Edit/New > align the input fields to right (as it is now), but the text itself should be LTR (I guess the same as the "recent files" issue).
2. Ditto as issue 1, for Catalog properties > plural custom expression field text.

**Comment by vslavik** [comment]
This should be all, I think.
