### ISSUE TITLE
Preferences being opened half way out of the screen

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#257]
Hi,

Using Windows 10 x86 Hebrew locale, an HP 15" screen. It happened also in Windows 7.
1. Open Poedit in hebrew/arabic locale
2. File > Preferences
3. The Window is half way out of the screen (image http://prntscr.com/aiqfet )
Of course I can drag the window into the screen.

Note: This does NOT happen if you open the preferences from File > Catalog manager > File > Preferences.

Thanks.

**Comment by vslavik** [comment]
> an HP 15" screen

That's unfortunately not very descriptive. What is your screen's *resolution* in pixels and its DPI setting in Windows? And is that a full-screened Poedit window or not?

**Comment by ItielMaN** [comment]
Sorry, you're right. Using HP L1510, screen resolution set to 1024x768, DPI set to normal 100%, though I'm not sure there's any connection to that.
Whether Poedit is full-screened or not doesn't matter here. I tried resizing and moving around Poedit window, and the Preferences window seems to always be opened a fixed positioning from the main Poedit window, regardless of it's position in the screen (unless most of the main app's window is located at the left "unseen" part of the screen. Image that explains what I mean is the second one in this post).
Technically, the same applies to LTR languages, but I'm guessing no one noticed that, since it looks okay there..
I think it's a bit hard to understand the issue from my above description, so I'll provide images:
![read](http://i.imgur.com/qTzzJbR.png)
The Preferences window will always open in that specific positioning (south east of the main Poedit window). So when Poedit is full-screened, this window will be "out of the screen"..
It seems that Poedit should let the Preferences window locate itself freely according to Windows rules.. Hope this makes sense lol.

![read](http://i.imgur.com/SlKjKYG.png)

If you need more info tell me.

Thanks.

**Comment by SafaAlfulaij** [comment]
I have the exact same problem, **and it's only when Arabic (Or Hebrew) is the app's language.**

**Comment by ItielMaN** [comment]
> I have the exact same problem, and it's only when Arabic (Or Hebrew) is the app's language.

Thank you for confirming :)

@vslavik What I said regarding:

> Note: This does NOT happen if you open the preferences from File > Catalog manager > File > Preferences.

No longer applies since the Catalog manager is being opened in the middle of the screen, thus when opening the Preferences window, it seems to be visible.

**Comment by ItielMaN** [comment]
I just noticed the same issue applies to Statistics and About dialogs.

**Comment by vslavik** [comment]
Yes, it is perfectly reproducible for *any* dialog windows under RTL locales, regardless of screen size: the child dialog is shown in a weird position to the right, and isn’t adjusted to fit onto screen.

**Comment by ItielMaN** [comment]
> Yes, it is perfectly reproducible for any dialog windows under RTL locales

Umm.. no, it isn't?
The Open, Verification and Search dialogs aren't affected by this issue. Same for Catalog's Properties and some more.
Unless.. you have something else in mind when referring to "_dialog_"?

**Comment by vslavik** [comment]
> The Open, Verification

… are *system*-provided windows...

>  Search

...is *not* a dialog, but a floating window...

**Comment by ItielMaN** [comment]
Right. Thank for clarifying.

**Comment by vslavik** [comment]
@ItielMaN SafaAlfulaij With the exception of incorrectly mirrored images (not just toolbar, there’s more), this build should have most issues fixed: https://jumpshare.com/v/CuhDhrLDAQvYLigNG2sz Could you give it a try? This can be used to test the updater as well: https://jumpshare.com/v/NIn4OA19RSQYMccWgbHP

**Comment by vslavik** [comment]
Should be fixed in this build: https://jumpshare.com/v/CuhDhrLDAQvYLigNG2sz — if you could check if it doesn’t introduce *other* window placement issues, I would be grateful.

**Comment by ItielMaN** [comment]
Opening Preferences window from the main screen is OK in this build, but not others:
Statistics window:
![a](https://cloud.githubusercontent.com/assets/18016656/14439262/f7be543a-0032-11e6-9ddd-28c55e2706c3.png)

Opening Preferences window from the catalog manager:
![b](https://cloud.githubusercontent.com/assets/18016656/14439351/809ddd34-0033-11e6-9d95-800c3971c431.png)

Can't see more than that.

**Comment by vslavik** [comment]
The latter is expected (i.e. consistent in how LTR would behave on the other side of the screen if you positioned the manager this close to its edge), the former is not :(

**Comment by ItielMaN** [comment]
> The latter is expected (i.e. consistent in how LTR would behave on the other side of the screen if you positioned the manager this close to its edge)

Well, no exactly. That would be expected if I was placing the catalog manager in the position you can see in the aforementioned image.
Thing is, I didn't. The images you see in my previous post were Print-Screened while Poedit is full-screened, without me changing positions of any of other Poedit's windows (i.e. clicking "catalog manager" from the file menu, then clicking file > preferences).
Shouldn't Poedit need to let Windows decide how and where to position the sub-windows?

> the former is not :(
I think I'm exercising you a bit too much in this past month :D

**Comment by vslavik** [comment]
> Shouldn't Poedit need to let Windows decide how and where to position the sub-windows?

Windows is incapable of position *this* kind of windows (dialogs) on its own. And manager’s placement is remembered, and a marginal part of Poedit as well, so I’m not going to worry about this — it would be enormous effort to get right and is simply not worth it, *for the manager*.

**Comment by ItielMaN** [comment]
Yeah, agreed.
Although that if I were you, I would remove the File menu from the catalog's manager. Seems.. irrelevant?

Anyway, the only left issue here is the Statistics window I guess. Can't see more than that.

**Comment by vslavik** [comment]
> Although that if I were you, I would remove the File menu from the catalog's manager. Seems.. irrelevant?

You’re right, thanks for pointing that out!
