### ISSUE TITLE
"Show references" dialog totally RTL'd

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#260]
Hi,

The "Show references" dialog is.. too much RTL'd.
I'll let the image speak for itself:
![show references](https://cloud.githubusercontent.com/assets/18016656/14061864/a15d5f8c-f394-11e5-8e1a-ee96948d9173.png)
Totally unreadble. Clicking left Ctrl+Shift does nothing.

Also, the "php:8.404" in the title- should it look that way?

Thanks.

**Comment by vslavik** [comment]
> Also, the "php:8.404" in the title- should it look that way?

I don’t know, you didn’t attach the file, so I can’t know what’s in in… I’m not seeing *that* myself, at least.

**Comment by ItielMaN** [comment]
Oh, Sorry.
The folder (WordPress theme I guess) is attached as a ZIP file here.
[rambo.1.4.4.zip](https://github.com/vslavik/poedit/files/192028/rambo.1.4.4.zip)

**Comment by vslavik** [comment]
I meant the PO file itself… Fortunately, there’s a POT in the archive and that includes a reference to `404.php:8` — so this seems to be the same kind of incorrectly handled English text as in #255.

I assume “404.php:8” is what you’d expect here to see as well? Or would you expect “8:404.php”  (“404.php” is filename, “8” is line number within the file)?

**Comment by ItielMaN** [comment]
> I meant the PO file itself

Sorry, a bit new to this stuff :)

I assume “404.php:8” is what you’d expect here to see as well? Or would you expect “8:404.php” (“404.php” is filename, “8” is line number within the file)?

I expect to see the same text as it would be in the english version (not RTL'd), so yes, it should be "404.php:8" as you said.
