### ISSUE TITLE
Different positioning of "Edit comment" windows

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#267]
Hello,

Not sure if this one is on purpose or not, but clicking "Edit comment" from the "Edit" menu, the window's position will be at the center of the screen, while clicking "Edit comment" from the bottom of Poedit UI will be opened at the same position of the "Edit comment" button (which makes sense).
Shouldn't both actions need to result in the window being opened at the bottom?

**Comment by vslavik** [comment]
> which makes sense

There’s your answer. This window *edits* — makes sense to have it place *where the user is at the moment*. When clicking a button, that’s around the button, but when using the menu, there’s no such locality and showing it in an usual location at the bottom would be surprising.

**Comment by ItielMaN** [comment]
Hmm. Thanks for elaborating.
