### ISSUE TITLE
Default to UTF-8 instead of ISO-8859-1 for files with unknown encoding?

### ISSUE THREAD

**Issue by Arthur2e5** [vslavik/poedit#270]
Sometimes I export BSD-licensed translations from launchpad for re-integration into upstream. Launchpad provides an "only strings that differ from imported versions" for exporting, which doesn't export the `""` msgid.

It would be great if poedit provides a mechanism for re-interpreting the file in a different encoding, or switch to a more common default (in the case of LP, that's UTF-8.)

**Comment by vslavik** [comment]
“Poedit” doesn’t define the PO file format, it’s older and used independently. The header msgid is mandatory. If you don’t use it, there’s no way to know what the charset of the file is. Here’s what `msgfmt`, a GNU gettext tool, has to say on the subject of such files:
```
$ msgfmt -v -c -o /dev/null x.po 
msgfmt: x.po: warning: PO file header missing or invalid
              warning: charset conversion will not work
msgfmt: found 1 fatal error
$
```
So, not a Poedit issue. Also, Poedit (gettext tools and format, really) *does* provide a mechanism for specifying the file’s charset — *it’s the header.*

You should instead complain to Launchpad developers that they output broken files.
