### ISSUE TITLE
"Open Poedit after installation" Hebrew string not translated in Inno Setup

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#274]
Hi Slavic,

As the title says, though I'm not sure if that's fixable from your end.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/18016656/15801595/d7bc92ce-2aa2-11e6-8d78-791dc01544ea.png)

Thanks.

BTW: Forgot to mention, the new version is looking good! :)

**Comment by vslavik** [comment]
> Hi Slavic

Please don't garble my *sur*name? :-)

It's translatable and present (& translated) in Crowdin, but I forgot to update it — it's a manual process for this one string, both in checking it and copying into the Inno Setup script. Will fix for 1.8.9.

**Comment by ItielMaN** [comment]
> Please don't garble my surname? :-)

Hmm? I thought it was your first name =\
And sorry, I just glimpsed at your name at Crowdin and misplaced c with k and i with í (I don't even have it on my keyboard!).

Thanks :)

**Comment by vslavik** [comment]
Hey, notice the smiley ;) It's a common enough thing

**Comment by ItielMaN** [comment]
Should I see the string's occurrence in Crowdin or to translate it here?

**Comment by vslavik** [comment]
As I said, the string *is* present in Crowdin and already translated (by you in fact ;), just click on All translations and search for it.

**Comment by ItielMaN** [comment]
> As I said, the string is present in Crowdin and already translated (by you in fact ;), just click on All translations and search for it.

Right.. silly me :D

**Comment by ItielMaN** [comment]
Ahm, you may have possibly forgot about this issue for 1.8.9.. =\

**Comment by vslavik** [comment]
Sorry :( Now in aebff891 finally.
