### ISSUE TITLE
Active window switched after saving when there are more one Poedit instances

### ISSUE THREAD

**Issue by atriwidada** [vslavik/poedit#281]
Environment: Windows 7 64-bits, Poedit version 1.8.8 (build 4339)
Steps to reproduce:
1. run first instance, open pofile-A
2. run second instance, open pofile-B
3. edit pofile-B until 100% translated, save
-> active window switched to pofile-A
Expected result:
-> active window stays at pofile-B

**Comment by atriwidada** [comment]
I have two files, both not 100%, which also trigger window switch on save. 
* both window must not in minimized state
* saving gnome-software.gnome-3-20.id.po with switch to polari.gnome-3-20.id.po
* saving polari.gnome-3-20.id.po will not switch window 
Files attached.
 
[save-switch-window.zip](https://github.com/vslavik/poedit/files/340215/save-switch-window.zip)

**Comment by vslavik** [comment]
This is completely ridiculous… and actually happening, I just confirmed with your files :( Thanks a lot for your report!
