### ISSUE TITLE
“Whole words only” setting not respected when highlighting search results

### ISSUE THREAD

**Issue by c72578** [vslavik/poedit#283]
The option "Whole words only" is not always working. An attached example shows, where a word is found as a part of a longer word.

Poedit find options:
![find_whole_word_options](https://cloud.githubusercontent.com/assets/371551/16990890/08b63612-4e9a-11e6-98e1-5b1087dbf22d.png)

This is how it looks, when the word "sie" is found inside the longer word "aktualisiert":

![find_whole_word_example](https://cloud.githubusercontent.com/assets/371551/16990902/0f1bf2a8-4e9a-11e6-8f6b-ce07b0ae2993.png)

How to reproduce:
- OS: Windows 7 64bit, de
- Poedit: 1.8.8
- Open the attached po file: gnome-help.master.de.po
- Search for the word "sie", using the options in the find dialogue as shown above
- Click next until you reach e.g. the original string "As the EDID cannot be updated, it has no expiry date."
- "sie" will be found inside the word "aktualisiert"
- there are further strings inside this po file, where it happens

Attachment (gnome-help.master.de.po):
[gnome-help.master.de.zip](https://github.com/vslavik/poedit/files/373963/gnome-help.master.de.zip)

**Comment by vslavik** [comment]
It’s true that it is incorrectly *highlighted* in the entry, however the actual search is performed correctly, as the item found *does* contain the string as a word:

    Da die EDID nicht aktualisiert werden kann, hat sie auch kein Ablaufdatum.
                                                    ^^^
