### ISSUE TITLE
configure: error: missing Lucene++ library

### ISSUE THREAD

**Issue by ac1dr3d** [vslavik/poedit#284]
but still luceneplusplus is installed from git repository

under centos 7

**Comment by vslavik** [comment]
You seem to be assuming I can read your mind and you don't need  [describe things](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html). I'm sorry to inform you that's not the case. I really don't — and more importantly, *can't* — know what you did wrong if you don't describe your steps in detail.

Generally speaking, lacking details you didn't provide, I can only say that you obviously failed at either installing Lucene++ from sources or pointing configure at it. That's not terribly useful, to put it mildly, but that's the best I can do w/o information. Check what you did and fix your omissions.

Honestly, compiling from sources (and particularly, as you do, from a *git checkout*!) requires certain level of competency with Linux, compiler toolchain and autotools. You should be able to read configure docs on your own, you should be able to run `configure --help` and investigate `config.log` in case of problems. If you're not up to a bit of learning, I recommend sticking to distro-provided packages.
