### ISSUE TITLE
"Show References" should be under "View" not "Edit"

### ISSUE THREAD

**Issue by gerdneuman** [vslavik/poedit#285]
Ok, searching for this feature 2 hours. Now I found it via https://github.com/vslavik/poedit/issues/282#issuecomment-230160010

>>     It’s in Edit → Show References. I suppose View or Window menu would be more appropriate…
> 
> Regarding that, yes, 

I agree, this is a View option (where I looked first) and definitely not something about Edit.

(BTW: I would prefer "Show program references" or "Show program code" as this would be less ambiguous)

**Comment by vslavik** [comment]
If you felt the need to make a separate duplicate issue for something you know I’m already aware of, perhaps you could go the remaining step and making it a PR? 

> (BTW: I would prefer "Show program references" or "Show program code" as this would be less ambiguous)

1. Not all references in PO files in the wild are “program” or “code”.
2. There’s nothing “ambiguous” here.
