### ISSUE TITLE
Cant open Source File with "open in editor"-Button

### ISSUE THREAD

**Issue by JanSuchandt** [vslavik/poedit#291]
Hi,

poedit is not able to open the source files with click on button "open in editor" out of the references popup-window after changing my default editor for .php-files to notepad++ (Windows 10 Home x64)

Is there any trick or workaround to make this button work again? Would be really nice and a huge timesaver.

Greeting from germany,
Jan

**Comment by vslavik** [comment]
If you’re filing bugs at GitHub, do take the time to check the current state of the project first: 596837dcfc4aea3e38ac49f8a093aa379ef280fa
