### ISSUE TITLE
Add the file name in the Find window titlebar

### ISSUE THREAD

**Issue by fbonzon** [vslavik/poedit#296]
### Actual

Each open Poedit document has its own Find window, with the fixed title "Find".

When you have several open documents, it is not easy to know in what Find window to type, unless you remembered where you placed the Find window for each document:

![poedit-screenshot-001](https://cloud.githubusercontent.com/assets/1116761/19533966/3c5d01c2-9642-11e6-9be2-bf05437981b1.png)
### Expected

The Find window includes the file name in the titlebar. E.g.: "Find — Views.es.po" instead of "Find"

**Comment by vslavik** [comment]
Put the find window in a sensible location, such as next to the document window. Problem solved. Why would you intentionally make a mess of it? Am I missing something?

As far as I can tell, having document name in the Find window’s title is *not* expected on macOS (or elsewhere). Pages, for example, uses a shared Find window for all documents — Poedit did that, but it can get confusing real fast. Having an inline search bar would be best, of course.

**Comment by fbonzon** [comment]
If the UI guidelines say not to modify the Find window title, then is better not to, I agree. Maybe you can add text inside the Find window, at the top, above the search field, to remind to what file this Find window corresponds?

Yes, with a big screen and a sensible way to place Find windows, it's easily manageable.

Sometimes I have many Poedit windows on top of each other, or I switch to other apps for some time, and I forget what Find window is for what document when I come back to Poedit. I'm just sharing my experience with Poedit. I got confused many times with Find windows. It's your call in the end, to decide how important is this issue :)

Yes, inline search bar is best solution.

**Comment by vslavik** [comment]
>  got confused many times with Find windows. 

…and you’re not the only one. You were right all along, will do as you suggested (as an interim fix until it’s done “properly” with inline search bar).
