### ISSUE TITLE
Broken encoding in Upgrade to Pro textbox

### ISSUE THREAD

**Issue by crayxt** [vslavik/poedit#297]
Hi,
Poedit 1.8.11, Win 7 64-bit.
When Poedit starts, it advertises upgrading to Pro, and then text changes to new offer with discount, and in this new message, the cyrillic text is shown with broken encoding, checked on Kazakh and Russian interface languages. See the screenshot.
![poedit](https://cloud.githubusercontent.com/assets/33132/19955504/d243e194-a1a3-11e6-8543-d5156549e6ac.png)

**Comment by vslavik** [comment]
Fixed, thanks!
