### ISSUE TITLE
Previous source text: messages are concatenated

### ISSUE THREAD

**Issue by crayxt** [vslavik/poedit#299]
Dear @vslavik 
Using Poedit 1.8.11 on Windows I noticed that in ```Previous source text:``` area, msgid and msgid_plural are concatenated, see the screenshot below
![poedit-prev-translation](https://cloud.githubusercontent.com/assets/33132/20255974/7b088e4e-aa62-11e6-8003-f2e4df6484ca.PNG)

**Comment by vslavik** [comment]
You forgot to attach an example file.

**Comment by crayxt** [comment]
Sorry, there you go, search for 'day ago'
[nautilus.zip](https://github.com/vslavik/poedit/files/588643/nautilus.zip)
