### ISSUE TITLE
Not Translating In wordpress

### ISSUE THREAD

**Issue by srinivasan1125** [vslavik/poedit#300]
I am trying to translate my wordpress site into Italian language. I have created a Italian language file using poedit and I moved the po and mo files into my site , but the contents were not translated. Kindly can you please help me to solve this issue

**Comment by vslavik** [comment]
This is a *bug tracker*, not a forum for idle questions. Please don’t add noise to it. The support page you came from explained this to you and mentioned that you should only use GitHub if you have experience with this stuff.

Also, it’s entirely inappropriate for you to email the support contact and *one minute later* create a duplicate issue for the same thing. Please don’t do this.
