### ISSUE TITLE
Warnings while creating PO file from bash POT

### ISSUE THREAD

**Issue by crayxt** [vslavik/poedit#301]
I just tried to create a PO file from bash POT (http://translationproject.org/POT-files/bash-4.4.pot)

It gave me the following error
```
25.11.2016 12:06:49: C:\Users\User1\AppData\Local\Temp\poeF0BF.tmp\0ref.pot:928: warning: internationalized messages should not contain the '\a' escape sequence
25.11.2016 12:06:49: C:\Users\User1\AppData\Local\Temp\poeF0BF.tmp\0ref.pot:1242: warning: internationalized messages should not contain the '\r' escape sequence
25.11.2016 12:06:49: C:\Users\User1\AppData\Local\Temp\poeF0BF.tmp\0ref.pot:1242: warning: internationalized messages should not contain the '\r' escape sequence
```
Who is breaking the rules here?

**Comment by vslavik** [comment]
Please don’t use the *bug* tracker for questions. 

If you read the errors, they spell quite clearly what gettext (not Poedit) thinks is wrong with your POT file. This is not a bug in Poedit.
