### ISSUE TITLE
 Poedit crashes with SIGSEGV in web::https:client::details::http_network_handler::http_network_handler()

### ISSUE THREAD

**Issue by numand** [vslavik/poedit#302]
Poedit crashes when I click Accounts tab in Preferences windows.

What I expected to happen:
I expected to open Accounts tab of Poedit.

What actually happened:
When I clicked Accounts tab, Poedit crashed.

Steps to produce bug:
    
1. Open Poedit applications. It does not matter whether you open it with a .po file or not.
2. Click Edit > Preferences > Accounts tab.

I reported this bug to the Launchpad. It contains valgrind, strace, apport-retrace and gdb logs with debugging symbols. Here is the link to the bug: https://bugs.launchpad.net/ubuntu/+source/poedit/+bug/1639470

    LC_ALL=C apt-cache policy poedit
    poedit:
    Installed: 1.8.9-1
    Candidate: 1.8.9-1
    Version table:
    *** 1.8.9-1 500
        500 http://archive.ubuntu.com/ubuntu yakkety/universe amd64 Packages
        100 /var/lib/dpkg/status

    LC_ALL=C lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description: Ubuntu 16.10
    Release: 16.10
    Codename: yakkety

**Comment by vslavik** [comment]
Please always check the *current* state of the project you’re reporting bugs against, not doing so wastes time for both you and the project.

Outdated by e5d68f3851341c59c712763e69839042e630555a.
