### ISSUE TITLE
[1.8.8] strings list frame is completely hidden by hints frame

### ISSUE THREAD

**Issue by Germano0** [vslavik/poedit#304]
screenshot: https://s13.postimg.org/w535oc9nr/poedit.jpg
OS: Fedora 24
poedit-1.8.8-1.fc24.x86_64

**Comment by c72578** [comment]
Hello,
this was caused by a recent Fedora bug in the wxGTK3 package. See:
https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=1396747

An updated package for Fedora 24 is currently in updates-testing:
https://bodhi.fedoraproject.org/updates/FEDORA-2016-74bef396a8
