### ISSUE TITLE
Missing strings for translation (from the status bar)

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#313]
Hi Václav,

All strings that can be seen in the status bar (or at least all of the ones I've noticed) aren't translatable, such as:
Show about dialog
Save current document
Quit this program

And so on.

Itiel.

**Comment by vslavik** [comment]
I doubt it’s “all strings” — more likely it’s just stock, standard menu items, translated in wxWidgets.

**Comment by ItielMaN** [comment]
Hmm. Thought about that but it didn't seem at first glance to relate to wxWidgets.
If that's the case, feel free to close this one.

**Comment by vslavik** [comment]
“Fixed" by 9e1106232a6c3bf1289a3ea2d50d0b6fbc9a8468.

**Comment by vslavik** [comment]
They were indeed all from wx, because Poedit itself didn’t use these help strings at all. Because this sort of UI is not used nowadays, I dealt with it, ehm, creatively — by not showing any help in the statusbar in the first place.

**Comment by ItielMaN** [comment]
(Replying for #312 as well as this one)
The Help strings are not the only ones affected. As I've mentioned in #312, you can also hover File > Exit (just an example) and you'll see "Quit this program".

**Comment by vslavik** [comment]
> The Help strings are not the only ones affected. As I've mentioned in #312, you can also hover File > Exit (just an example) and you'll see "Quit this program”.

Yes. That’s a help string.
