### ISSUE TITLE
TM lets crash Poedit (Beta 2.0)

### ISSUE THREAD

**Issue by rallek** [vslavik/poedit#315]
I accepted yesterday the new beta 2.0 version (I did not see it is a beta, I was in a hurry).
I used the pre translation. When I press ok after its pre-translation Poedit is closed.
![grafik](https://cloud.githubusercontent.com/assets/935250/21581800/d026bb2c-d040-11e6-8678-5bbd157fcbfb.png)

A chrash report is generated:
![grafik](https://cloud.githubusercontent.com/assets/935250/21581802/e7dd15fe-d040-11e6-9b98-5afd07314432.png)

**Comment by vslavik** [comment]
> (I did not see it is a beta, I was in a hurry).

You *also* explicitly enabled checking for beta versions first.

**Comment by vslavik** [comment]
Kindly make an effort to first of all check if the bug you’re reporting wasn’t already reported. It was: #308.

**Comment by rallek** [comment]
ups, overseen. Sorry
