### ISSUE TITLE
Selected list item is not ensured to be visible in 2.0 on Windows

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#320]
![poedit incomplete list entry](https://cloud.githubusercontent.com/assets/3233724/21786064/835c9194-d6c2-11e6-9fe5-228cfb62dd3b.png)

The selected list entry should always be completely visible. Ideally, to get some more context for the current translation, the 1 or 2 messages below it should also be visible, especially on large screens.

**Comment by vslavik** [comment]
(Please always provide basic information such as OS, its version and exact Poedit version. It can be guessed from the screenshot here [win10, 2.0beta1], but that’s not always the case.)
