### ISSUE TITLE
Word to translate with (different) more meanings 

### ISSUE THREAD

**Issue by vaso123** [vslavik/poedit#323]
I created a detailed post at [here](http://stackoverflow.com/questions/41698186/same-word-with-different-meanings)

The question is: Now how can I handle it with poedit, when processing catalog, to create two entries for the same word?

Let's look the google translator, and translate the word: case to your (any other) language. It could be a verb or noun, and it has a lot of meaning. 

If the word is in a sentence, there is no problem, but what if I want to use it stand alone?

Is it possible to do somehow?

**Comment by vslavik** [comment]
Please don’t create *bug* tracker issues for *questions* — respect the instructions at https://poedit.net/support

Your problem (i.e. contexts) is discussed in great detail in the GNU gettext manual, linked to from the Help menu.
