### ISSUE TITLE
PO file which is ISO-8859-1 coded is converted to UTF-8 at saving with 1.8.11

### ISSUE THREAD

**Issue by lordofbikes** [vslavik/poedit#325]
The attached PO file is iso-8859-1 coded and has some German umlauts in the msgid strings. The coding for content and source is set to iso-8859-1 in the header section. The file worked great with poedit 1.6.7.

With latest poedit 1.8.11 the file has following issue:
When I open the PO file and use File->Compile to MO... everything is fine. The compiled MO file is iso-8859-1 coded.

But when I use File->Save the PO file is converted to UTF-8 although it was not modified. And the automatically compiled MO file is UTF-8 then too. 

The PO file coding is shown correct as iso-8859-1 in the Catalogue properties.

Open the PO file again respects the unchanged header coding information as the umlauts are represented by 2 characters then (the 2-byte UTF-8 codes). The file is not interpreted as UTF-8.

[poiso.po.txt](https://github.com/vslavik/poedit/files/726313/poiso.po.txt)

**Comment by vslavik** [comment]
Thanks for the detailed report and a test case!

**Comment by lordofbikes** [comment]
Not at all! Thank you for your great support.
