### ISSUE TITLE
Poedit doesn’t show where TM DB is located

### ISSUE THREAD

**Issue by anasram** [vslavik/poedit#326]
I think the (Edit » Preferences » Translation Memory) tab should show two lists tell user explicitly:
* what are the input/source folders of the locale files used.
* where TM file(s) are located as an output/destinatution.

In #188, @kaio said  he found TM DB stored in `[User Home Dir]\AppData\Roaming\Poedit\TranslationMemory` (seems under Windows), so I expected to see `~/.poedit/TranslationMemory` file under Linux, but I didn’t find such a file.

I couldn’t so far figure out where TM DM located!

**Comment by anasram** [comment]
Why?! 😕

**Comment by c72578** [comment]
You may want to try:
locate TranslationMemory
which might lead you to e.g.:
~/.local/share/poedit/TranslationMemory

Or use the find command alternatively from your home directory:
find . -name TranslationMemory

**Comment by vslavik** [comment]
> Why?! 😕

Because it’s a duplicate that you intentionally (and thus rudely) created, despite being answered in full in the duplicated issue.
