### ISSUE TITLE
Plural forms for ie

### ISSUE THREAD

**Issue by Carmina16** [vslavik/poedit#327]
Please add the plural expression for Interlingue (ie):

`{ "ie" , "nplurals=2; plural=(n != 1);" },`

**Comment by vslavik** [comment]
Let's be realistic: if you want something as exotic/toy as this, you'll have to do the work yourself. Make a patch, *test it* and when everything works, submit a PR.

**Comment by vslavik** [comment]
Not going to happen, apparently → closing. Should anyone be interested in this picking this up, please submit a PR.
