### ISSUE TITLE
Double ampersand is displayed as triple ampersand in the list

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#328]
Poedit 2.0beta2 (4723)
Windows 10

When I load the attached [demo.po.txt](https://github.com/vslavik/poedit/files/769526/demo.po.txt), one instance of the double ampersand is displayed as `&&&`.

![poedit triple ampersand](https://cloud.githubusercontent.com/assets/3233724/22864945/d124cbe6-f15a-11e6-91fd-4f4400d15b83.png)

**Comment by vslavik** [comment]
Thanks so much for the report! You *really* seem to be hitting quite a few obscure bugs lately...
