### ISSUE TITLE
Add danish translation to desktop file:

### ISSUE THREAD

**Issue by LocutusOfBorg** [vslavik/poedit#335]
Hello,
from: scootergrisen <scootergrisen@gmail.com>
```
I woud like danish (da) translation to be added to the poedit desktop file:
GenericName[da]=Gettext-katalogredigering

Maybe it would be a good idea to also add "Comment=" to this file.
```
http://lists.alioth.debian.org/pipermail/debian-l10n-devel/2017-February/005269.html

opening a pr soon

**Comment by vslavik** [comment]
> opening a pr soon

Feel free to. But please don't create bogus non-issues like this one.

**Comment by LocutusOfBorg** [comment]
the reason for the pr is this sentence:
"Maybe it would be a good idea to also add "Comment=" to this file."

**Comment by vslavik** [comment]
> the reason for the pr is this sentence:

I'm not sure what was I supposed to do with that statement. It's not a question (and if it were, this is a *bug tracker*, not a questions forum).

**Comment by LocutusOfBorg** [comment]
I found this on the specification document:
``` Comment	Tooltip for the entry, for example "View sites on the Internet". The value should not be redundant with the values of Name and GenericName. 	localestring	NO	1-3 ```
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
