### ISSUE TITLE
Main menu behaves differently than in all other programs

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#341]
Poedit 2.0beta3
Windows 10

To reproduce:
1.  Click on the File menu
2.  Click again on the File menu

The file menu stays open. In all other applications (I tried Notepad, Thunderbird, eventvwr.exe) the menu is closed on the second click. The other applications differ in whether the File menu item has an active or inactive background, but they all close the menu and drop the keyboard focus.

Further:
1.  Click on the File menu
2.  Doubleclick on the File menu

Now the menu closes.

**Comment by vslavik** [comment]
Does the build from https://github.com/mity/mctrl/pull/52#issuecomment-284026456 help by any chance? 

(BTW, I'm not ignoring your other bug reports, I'll attend to them once the next 2.0 beta is feature-complete.)

**Comment by rillig** [comment]
No, it doesn't. The menu still behaves exactly as I described it above.
