### ISSUE TITLE
Translated text containing \0 is truncated in list view

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#344]
Poedit 2.0beta3
Windows 10

![poedit](https://cloud.githubusercontent.com/assets/3233724/23589591/08674dd8-01d0-11e7-8b1b-0a80db531f6e.png)

**Comment by vslavik** [comment]
FWIW, this for once I regard as perfectly reasonable. Poedit as well as [gettext tools](https://www.gnu.org/software/gettext/manual/html_node/MO-Files.html) and the rest of the civilized word use NULs to terminate strings, as the (C) God intended them to be used — it's the *normal* way of handling strings. 

That goes double if the *source string does not even use embedded NULs*, as in your screenshot. In that case, your translation is quite simply wrong and likely to break things in the software being translated, not just Poedit.

If you meant to write `\0` verbatim, then you need to escape the special-purpose character of `\` and write it as `\\0` (that's what the syntax highlighting is telling you, that the `\0` bit is special in some way). Your translation would still be unfaithful to the original then, and thus still wrong, but at least it would not break gcc.

**Comment by rillig** [comment]
Thanks for this good explanation. I filed a bug against gettext instead: https://savannah.gnu.org/bugs/index.php?50472

**Comment by vslavik** [comment]
I think there's no bug in gettext either. The document I linked to explicitly says it's keeping its options open...

**Comment by bhaible** [comment]
In the gettext bug tracker I commented:
"In fact, the original problem — accidental use of \0 instead of \\0 — is due to the backslashing of strings in PO files. I see it as a feature of a good PO editor to be clear about which backslashes are for the string and which backslashes are for the PO file syntax. In other words, it's a quality-of-implementation issue of the PO editor. (And yes, I know that the Emacs po-mode does not have good quality in this sense: it leaves backslashes from the PO file syntax visible to the translator.)"

**Comment by vslavik** [comment]
@bhaile Poedit doesn't expose "backslashes for PO file syntax" to the user and does the escaped-encoding into PO file's strings internally, invisibly to the user.

But it also happens to use the same C-like syntax for displaying and entering some unprintable characters such as tabs, bells etc., including NULL. These are visually highlighted to indicate their escape sequence nature to the user.

I have similar reservations to yours to flat out preventing entry of such strings. I could do that, or I could add warnings about use of such escapes if they're not present in the original, but to be frank, this is extremely rare occurence...

**Comment by bhaible** [comment]
> Poedit doesn't expose "backslashes for PO file syntax" to the user and does the escaped-encoding into PO file's strings internally, invisibly to the user.

Good to hear that!
