### ISSUE TITLE
After saving with errors, editing the current message does not work

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#350]
Poedit 2.0beta3
Windows 10

To reproduce:

1.  Open [cformat.po.txt](https://github.com/vslavik/poedit/files/836400/cformat.po.txt)
2.  Focus the Translation field
3.  Type `%s` and press Ctrl+Enter
4.  Press Ctrl+S, confirm the error dialog
5.  Type `de2` and press Ctrl+Enter

Expected:
* the current message is saved, and I can proceed translating message 3.
Actual:
* the cursor keeps blinking after the `de2` I entered.
* Pressing Ctrl+Enter has no effect, neither has Ctrl+Up or Ctrl+Down.
* Clicking in the list of messages restores the normal behavior.
* All entries in the Navigation menu are disabled.

It only happens when saving with errors. Saving without errors works fine.

**Comment by vslavik** [comment]
Sorry, I think I forgot to mark this as fixed… I can't reproduce in 2.0.4 anymore, can you?

**Comment by rillig** [comment]
I also cannot reproduce it with 2.0.4. Thanks for fixing it.

In step 4, when pressing Ctrl+S, the file is not checked for validity anymore, therefore I had to click on "Check" separately. Next time I'll include more details on "what did I see, what did I do, what happened then" in the description. :)

**Comment by vslavik** [comment]
Thanks for confirmation!

> In step 4, when pressing Ctrl+S, the file is not checked for validity anymore, 

It is… (i.e. should be, is here, and if you're seeing a situation when it isn't, it's a serious bug).

> Next time I'll include more details on "what did I see, what did I do, what happened then" in the description. :)

For the record, your bug reports are great (and appreciated!) and I really don't think there's much you could have added in terms of details. Thanks!
