### ISSUE TITLE
Programatic undoable text changes aren't undoable

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#353]
Poedit 2.0beta4
Windows 10

In the Translation text field, when I press Ctrl+B, the current text is replaced with the source text. For me as a user, this is a single operation, so I should be able to undo that by pressing Ctrl+Z. But when I do that, the Translation field gets empty. I have no chance of getting the original translated text back, not even by pressing Ctrl+Z several times in a row.

This already happened several times to me when I wanted to press Ctrl+V to insert some text.

**Comment by vslavik** [comment]
Confirmed present in 1.8.12 too.

**Comment by vslavik** [comment]
Seems to affect *Copy from singular* and applying suggestions as well.
