### ISSUE TITLE
Menu item for license on linux

### ISSUE THREAD

**Issue by missprogrammer** [vslavik/poedit#355]
Hi,

Where is the menu item for license?
I'm using Poedit on arch linux

**Comment by vslavik** [comment]
As explained at https://poedit.net/pro, Poedit Pro is for Mac and Windows.

Also please don’t misuse this *bug tracker* for *questions*. Appropriate support channels are prominently shown both in-app and at https://poedit.net/support

**Comment by missprogrammer** [comment]
Oh
Sorry
Thank you 👍

**Comment by vslavik** [comment]
Forgot to say: if you provide your email address, I’ll let you know if/when a Linux version is available.

**Comment by missprogrammer** [comment]
missprogrammer94@gmail.com

Thank you for your consideration.

**Comment by zdavatz** [comment]
Yes, I am asking myself the same question. I just compiled from Source on Gentoo, bought a yearly subscription but I can not enter the license key on Linux. Please help.

**Comment by vslavik** [comment]
The open source version with source code rather obviously cannot contain paid content.

Please do follow the instructions in your license key email and download Poedit from https://poedit.net/download
