### ISSUE TITLE
Opening a po file at a given segment number

### ISSUE THREAD

**Issue by pepc** [vslavik/poedit#356]
It would be great if poedit had a command-line argument that allowed to open a .po file (or reposition a currently opened .po file) to a given segment, something like `poedit.exe myfile.po -segment=10` to put the segment cursor on the the 10th segment in the file.

This would allow for example a third-party QA tool to launch poedit right at the segment, so that it can be edited in poedit.

**Comment by vslavik** [comment]
Are you jus theorizing or do *you*, personally, have actual, present need for this? Will anything actually use such function if it is implemented? If you do, please provide more specific details. 

By the way, “segment” is ill-suited terminology, it’s never used in gettext. And most lint-kind tools report line numbers with problems, so opening at an item corresponding to *a line in the file* would make more sense IMHO.

**Comment by pepc** [comment]
It was a request of one of our customers for a [QA tool](https://www.xbench.net).

In our QA tool, Xbench, we load and parse bilingual files but we do not edit them.  Instead, we call the home editor (Trados Studio, memoQ, Memsource, etc) and let the user edit the segment there.  This workflow avoids data integrity issues (some of these formats are proprietary so there are risks by editing files even if we parse them fine for browsing).  Around minute 2:20 in [this video](https://www.youtube.com/watch?v=TDEM1oXH8D4) you can see how it works with the Memsource Editor.  In our [YouTube Channel](https://www.youtube.com/user/xbenchdotnet) there are other similar integrations illustrated.

The instant gratification of seeing an issue in Xbench and instantly fix it in the home application with a keystroke is highly appreciated by users. 

Line number as input would be also fine, (i.e. something like `poedit.exe myfile.po -atline=123` because our parser can store line numbers in our internal data structures and then call poedit with the line number as argument.

The main audience for this feature would probably be professional translators who are very conscious of linguistic quality and use our tool (for example, they are translating with poedit and want to instantly spellcheck all .po files.

**Comment by vslavik** [comment]
I see. So since your interest in this is commercial, perhaps you’d like to make a PR? This shouldn’t be too difficult and I’m happy to lend a hand… but to be honest, I’m too busy finishing v2.0 at the moment to work on this myself (although I do agree it should be done).

**Comment by pepc** [comment]
Sure, we can give it a try.  In fact, yesterday we tried twice to clone from Github using Sourcetree but the clone failed at a couple of dependencies.  Will try to clone again, perhaps using the Github desktop client instead.

**Comment by vslavik** [comment]
Great, thanks! Just follow the README instructions, it’s two `git` commands, one to clone the repo, one to fetch all submodules (aka “dependencies”).
