### ISSUE TITLE
macOS: Ellipsized source text has tightened spacing with custom fonts

### ISSUE THREAD

**Issue by naokomc** [vslavik/poedit#361]
## Steps to reproduce:

1. Go to Preferences and check "Use custom list font".
2. Select a custom font (e.g. Helvetica size 11).

## Result:
The source text gets bunched up if it flows wider than the width of the left-side pane.

<img width="847" alt="export" src="https://cloud.githubusercontent.com/assets/34067/24460476/664c512e-146c-11e7-96e8-670f1f9760d9.png">

**Comment by vslavik** [comment]
I think that's just macOS being macOS… If it cannot fit the text in, it tries to squeeze letter spacing a bit if the font is amendable to it. I'm sceptical anything can be done about it in application code...

**Comment by naokomc** [comment]
I see. Used to work just fine but I can live without the custom font. Feel free to close it or make it low-priority.

**Comment by vslavik** [comment]
What needs emphasizing is that this affects *source text* only (I know you said, but I missed it as I didn't see it in the screenshot):

<img width="842" alt="screen shot 2017-04-03 at 11 20 28" src="https://cloud.githubusercontent.com/assets/145881/24603127/e1ecacc4-185f-11e7-88c4-38573414bfc5.png">

The difference between the columns is that the translation one use plain text (`NSString`) while the source column uses rich markup (`NSAttributedString`). That must be the cause of the difference and makes me hopeful than the control **can** be configured to disable this behavior.

**Comment by petergus** [comment]
Following. For me it is vital as the original text is to small.
