### ISSUE TITLE
Some localized strings not included in 2.0's MOs

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#362]
Hi Václav :)

I've been too dormant around here lately.
Using the stable 2.0 hebrew locale, the "Upgrade your Pro license to 2.0" string appears in english even though I've translated it a week ago.
There may be other untrasnslated strings, didn't notice any yet.

Thanks.

**Comment by vslavik** [comment]
Thanks! I must have screwed up translation import (although I don't see *how*), they're missing from MO files. Will be fixed in the next update.
