### ISSUE TITLE
Error popups upon opening Poedit

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#364]
After upgrading 2.0beta4 to 2.0 stable and opening Poedit, I received this error:
![default](https://cloud.githubusercontent.com/assets/18016656/24467637/fa9311f0-14bd-11e7-93dc-198c96973e4c.png)

Poedit seems to operate normally after confirming the error message.
Renaming "Vaclav Slavik" in HKLM\Software\Vaclav Slavik to "Vaclav Slavik1" and reopening the attached POT file fixed it (of course by recreating "Vaclav Slavik" with "fresh" settings).

Also, in the same session where I see this error, changing the Poedit's lang to hebrew and restarting it (by opening the attached POT file [opening Poedit from scratch doesn't trigger this error]) doesn't actually change it to hebrew (and after the same restart, no error message is apparent. After a second restart the error message appears again).

Attached HKLM\Software\Vaclav Slavik1 registry key (don't worry about the "1" at the end of the "Slavik", it was just to backup the old settings, license and stuff for Poedit to recreate "Vaclav Slavik").

I see other error messages such as these, when opening the attached POT file:
![default](https://cloud.githubusercontent.com/assets/18016656/24466872/1dcc61d8-14bb-11e7-86b8-ffc5b7fbf02d.png)
![default](https://cloud.githubusercontent.com/assets/18016656/24467485/5d2a72fa-14bd-11e7-9f8b-214fdf4049ac.png)

**Comment by ItielMaN** [comment]
Download link for both POT file and reg file containing the reg folder:
http://www9.zippyshare.com/v/HsG0dSZh/file.html

**Comment by mariobl** [comment]
I have the same problem under Linux. I'm maintaining the Fedora package for a while. Today I wanted to update to v2.0, and when opening a po file from the file manager, I get the same error message as described above. Here's the backtrace, as copied from the error window:

ASSERT INFO:
./src/gtk/dataview.cpp(211): assert "gtk_tree_selection_get_select_function(m_selection) == func" failed in CheckCurrentSelectionFunc(): selection function has changed unexpectedly, review this code!

BACKTRACE:
[1] wxDataViewCtrl::DoSetCurrentItem(wxDataViewItem const&)
[2] wxEvtHandler::TryHereOnly(wxEvent&)
[3] wxEvtHandler::ProcessEventLocally(wxEvent&)
[4] wxEvtHandler::ProcessEvent(wxEvent&)
[5] wxEvtHandler::ProcessPendingEvents()
[6] wxAppConsoleBase::ProcessPendingEvents()
[7] wxApp::DoIdle()
[8] g_main_context_dispatch
[9] g_main_loop_run
[10] gtk_main
[11] wxGUIEventLoop::DoRun()
[12] wxEventLoopBase::Run()
[13] wxAppConsoleBase::MainLoop()
[14] wxEntry(int&, wchar_t**)
[15] __libc_start_main

The system is Fedora 25 with wxGTK3-3.0.2. By the way, I can open Poedit from the application menu without problems. But after opening a po file, the same error will be issued.

**Comment by vslavik** [comment]
> I have the same problem under Linux

No, you don't, this has no relation *whatsoever*. As a *package maintainer*, you ought to understand that "a window is shown" being the only similarity doesn't make it the same issue.

Please file a separate issue. Please also provide more accurate information on how to reproduce — there's at least two ways to "open a PO file" and you didn't provide the file. As I'm sure you noticed, the backtrace is useless because you don't have debug symbols.

**Comment by vslavik** [comment]
Can you please attach the file directly here? That site you linked to is some malware-infested crap from which I wasn't even *able* to download the actual file. Just drag the ZIP to the comment area.

**Comment by vslavik** [comment]
Never mind, managed to download it with `wget` (!), here it is: 
[files.zip](https://github.com/vslavik/poedit/files/887466/files.zip)

FYI, attempts to download it from the site, using the only download link, which looks like this:
![screen shot 2017-04-01 at 10 19 23](https://cloud.githubusercontent.com/assets/145881/24576922/b63668fa-16c4-11e7-990f-4b4bcc71952f.png)
result in downloading apparent malware, `Your File Is Ready To Download.dmg`, on Mac, and opening adds in Edge on Windows. It's my understanding now that it used to be a legitimate place, but it is painfully obvious it no longer is.

**Comment by vslavik** [comment]
As a workaround until it is fixed:
1. Restore the settings from your reg file.
2. Delete everything under `license`.
3. Re-enter your key.
This is a multi-threading issue that only affects upgrade from betas to 2.0 final. I tried to upgrade beta's lic settings automagically so that I don't bother you with re-entering the key. That backfired a bit :(

**Comment by ItielMaN** [comment]
> That site you linked to is some malware-infested crap from which I wasn't even able to download the actual file.
Wow sorry about that, now that I try to download the file from there I receive many popups as well. Too bad :(

> Just drag the ZIP to the comment area.
Yeah, I tried that at first, but the text editor here claimed it can't accept the file for some reason ("We don’t support that file type"), even though it was a valid ZIP file.

> As a workaround until it is fixed:
> 
>     Restore the settings from your reg file.
>     Delete everything under license.
>     Re-enter your key.
Will I be able to verify this is fixed in the next version if I do this? (I have a license for 1.x, so I'm not sure if upgrading the key to 2.0 will make the issue reproducible then)

**Comment by vslavik** [comment]
> Will I be able to verify this is fixed in the next version if I do this?

No, but it doesn't really matter, this issue affected only low tens of people (and for those who upgraded, which because the beta is expiring soon, will be most of them, the damage is already done).

**Comment by bovirus** [comment]
I tried to remove license and add again with serial number.
Nothing changed.
Always popup error.
It seems that appear if I disable the side bar on the right.
Sometimes when I get the error message if I close and re-run Poedit with same .po file it works without error.

**Comment by ItielMaN** [comment]
I have some news after removing the registry folder (to start Poedit with "fresh" settings) & registering Poedit with v2 license:
1. The issue persists and it behaves exactly the same as my first comment here.
2. Quoting @bovirus:
> Sometimes when I get the error message if I close and re-run Poedit with same .po file it works without error.

Same here.
3. Quoting @bovirus again:
> It seems that appear if I disable the side bar on the right.

Hiding the side bar doesn't make the popups go away, but I've noticed that closing and reopening Poedit after hiding the sidebar doesn't _always_ preserve this setting (that hides the side bar). Same for other settings. I've disabled the "Automatically compile MO file when saving" and again- Poedit intermittently doesn't preserve this setting.
I think this is related to this issue and fixing the error messages would fix that, but @vslavik if you think it's not related tell me and I'll open another issue for that.

**Comment by vslavik** [comment]
This is a race condition issue; the apparent randomness is part of it.

**Comment by vslavik** [comment]
Can you give this build a bit of testing please: https://jumpshare.com/v/9KjthsXbHiJ7KMyiRsns ?

It seems to be fine here (doing the same steps as described here, which I was able to reproduce the bug with), but due to the uncertain nature of the bug, I'd appreciate your confirmation.

**Comment by ItielMaN** [comment]
Yep, seems to be fixed.
I've verified it by opening the previously mentioned PO file a few dozens of times with the "fresh" registry settings from my previous comment **and** with the "old" reg settings (the one I had when I've upgraded 2.0beta to 2.0 stable, with the 1.0 license)- in both cases no popup messages are shown.

Any more specific testing you'd like me to try?

**Comment by vslavik** [comment]
Nope, just the same fiddling with it that you and @bovirus did before -- I figured you have a better sense of the bug than I do. 

Thanks a lot for your help with this (and of course reporting it in the first place)!
