### ISSUE TITLE
Auto-size the "General" tab according to its text in RTL builds

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#368]
STR:
1. On Windows, set Poedit 2.0 to Hebrew/Arabic
2. Open Preferences
3. Observe the "General" tab text in relation to the tab's width

The tab's width should be shorter, and/or the text should be right in the middle of the tab.
Other tabs look okay in this regard.

Not sure if this is a regression since 1.8.

![default](https://cloud.githubusercontent.com/assets/18016656/24514298/775f1184-157c-11e7-9157-71e9d32b3c95.png)
The same can be observed if Poedit's lang is set to Arabic, thus I concluded that this is a RTL issue.

**Comment by vslavik** [comment]
My first reaction was dismissing this as the text is drawn by Windows. But Poedit does add some padding in HiDPI modes, so this *is* a Poedit bug: one present in HiDPI **and** RTL situation.

(BTW, I'm adding a RTL label, feel free to use it, your judgement is apparently often better than mine ;-)

**Comment by vslavik** [comment]
Actually, this appears to be standard Windows behavior: there's minimal width to the tabs and **כללי** is too short. Observe a similar situation in English:

![parallels picture](https://cloud.githubusercontent.com/assets/145881/24830480/53ae1840-1c87-11e7-9f4c-4fda09e0990f.png)

Closing as a Windows defect, then.
