### ISSUE TITLE
Assertion failure on GetGtkHotKey for some locales

### ISSUE THREAD

**Issue by rffontenelle** [vslavik/poedit#370]
While testing some (_not all_) of the poedit's locales for #369, I received "assertion failure" dialogs on GetGtkHotKey() for some languages. These are displayed a few times on startup, but can be dismissed and the GUI will be available as expected.

**Distro:** Arch Linux 64-bit
**Package versions:**
poedit 2.0
wxgtk 3.1.0 (built with GTK+2)

**Locales involved:** ca_ES es_ES hu_HU ja_JA kr_KR zh_CN zh_TW

**Steps to reproduce:**
1. Run `LC_ALL=<langcode> poedit' (Some dialogs will pop up)
2. Dismiss the dialogs by pressing "Continue" button and it's gone

**Log files:**
[assertion-error.txt](https://github.com/vslavik/poedit/files/886011/assertion-es_ES-error.txt) (same for all locales)
[gdb-accel.txt](https://github.com/vslavik/poedit/files/886012/gdb-accel.txt)

**Comment by vslavik** [comment]
This is a wx bug — it assumes a translation cannot be 1 character long for accels. I'm partially addressing it by deleting offending translations.

I'm *not* seeing it with Japanese or (either) Chinese, by the way, but do with the rest.

**Comment by vslavik** [comment]
Candidate proper fix: https://github.com/wxWidgets/wxWidgets/pull/451

**Comment by vslavik** [comment]
Closing as the combination of wx fixes and translation files workarounds deals with this for 2.0.1 (later this week).
