### ISSUE TITLE
"Needs work" switch doesn't make a msgid fuzzy in .po file source code if translation is empty

### ISSUE THREAD

**Issue by andoro** [vslavik/poedit#373]
What I've noticed, that if a msgid doesn't have translation at all (empty field in PoEdit) and I mark it as "Needs work", PoEdit doesn't make it fuzzy in the .po file code.

I can imagine that it works by design in this way, because a non-existing translation can't be fuzzy :)
Well for a translator it can be a helper function to mark somehow the msgid-s which are not clear howto translate, so it "Needs work"... It's different if I already spent some time with a msgid and don't know how to translate it or I didn't spent time with it at all.

**Comment by vslavik** [comment]
> I can imagine that it works by design in this way, because a non-existing translation can't be fuzzy :)

Exactly.

> Well for a translator it can be a helper function to mark somehow the msgid-s which are not clear howto translate, so it "Needs work"…

That's not what the flag is for. It is for marking *translations* as being *wrong*. An entry that is not translate *self-evidently* needs work.

In any case, nothing I can do about it even if I was so inclined (which, frankly, I'm not). This is how gettext tools, which Poedit uses, behave.
