### ISSUE TITLE
WordPress translation on server — provide path to WordPress installation

### ISSUE THREAD

**Issue by florianbrinkmann** [vslavik/poedit#376]
Hi!

I wanted to test the new Poedit 2 feature for translation directly on the server. My problem: The WordPress installation does not live in the root folder of the server, so Poedit cannot find the themes and plugins. Is it somehow possible to provide the server path of the WordPress installation to Poedit?

Thanks in advance!

**Comment by vslavik** [comment]
Can you please email help@poedit.net with details about your server setup? I'd like to understand the specifics of your setup so that I *don't* have to add yet another setting — this feature was targeted primarily at inexperienced users and supposed to automagically figure things out.

**Comment by FlorianBrinkmann** [comment]
Yes, will do that!

**Comment by vslavik** [comment]
Magic has its limits, apparently; there will be a field for this in ≥ 2.0.7.
