### ISSUE TITLE
2.0 on Windows doesn't parse PHP files

### ISSUE THREAD

**Issue by rarog** [vslavik/poedit#377]
On 2.0 with every refresh it claims to not having found any translations. I had to revert to 1.8.x to be able to get all the strings.

I have a suspicion, which mustn't be the correct one - I tried xgettext in console this morning and for some reason it told me, that it doesn't know PHP as value for --language parameter. While PHP is clearly listed in the help screen.

Those are the files that 2.0 doesn't parse but which work well with 1.8.x: https://github.com/rarog/TranslationManagerForAndroidApps/tree/master/module/Setup/language
If I can get some setting to enable logging of the program, I could try to give more information myself.

**Comment by vslavik** [comment]
Please make sure to check the repository's status before filing outdated bugs: https://github.com/vslavik/poedit/commit/52ac71741cb910d9798504b44a01215b8f57902c
