### ISSUE TITLE
Wish to see the "Reference" without having to right click

### ISSUE THREAD

**Issue by denis-bisson** [vslavik/poedit#378]
I was a proud registered user of poedit and now poedit 2.

For many elements something when working with outputted .po file of Lazarus there is no "msgctxt" tag. So when translating them, there is no text displayed for the "Source text" at the bottom. To have a little help regarding that, we may right click on the expression on top in poedit and then we see "References:" and this help to figure where it came from and it gives a kind of context also to help to where it is used and how to properly translate it. I know I am lazy but I wish we could see that hint without having to right click. As old-school programmer, I like to work faster with keyboard-shortcut and find annoying each time to have to right click on the item. If it could be displayed, I feel it would help in those circumstances.

I will attempt attach an example.

See for the text "Build". I wish we could see the "tfrmabout.lblbuild.caption" somwhere without having to right click on the expression on top.

I feel jalous that for the other element like the "About..." we see the "tfrmabout.caption" both on top in the expression and also in the hint at the bottom for the "Source text".  Instead of seeing the same thing TWO times, I wish at one place or the other to see "Reference". Could just above or next the the current "Source text" window label at the bottom.

Exemple of a file:

-----------------8<-----------------8<-----------------8<-----------------
msgid ""
msgstr ""
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"Project-Id-Version: MinimalSample\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Native-Language: Français\n"
"Language: fr\n"
"X-Generator: Poedit 1.8.7\n"
"X-Poedit-SourceCharset: UTF-8\n"

#: tfrmabout.caption
msgctxt "tfrmabout.caption"
msgid "About..."
msgstr "À propos..."

#: tfrmabout.lblbuild.caption
msgid "Build"
msgstr "Date de construction"
-----------------8<-----------------8<-----------------8<-----------------

![quickcapture](https://cloud.githubusercontent.com/assets/16710801/24833663/71527082-1c9e-11e7-82c7-3f64b51328c7.png)

**Comment by vslavik** [comment]
I'm not sure what to tell you… I have no plans to surface source code references, something rarely needed, into the main UI screen where space is already at a premium. This may change in the future if there's enough demand & rationale, but right now it seems it would be only for a benefit of a very rare (Lazarus) "creative" use of references.

You can, since 1.8, have references shown persistently: see *View → Show references*. This does show you the information you are after, even though it's not pretty (due to Lazarus' use of non-file references, which while strictly speaking in-spec are definitely not your typical use of them). Improving this view for both source files and non-file references is something I'd like to have in 2.1. But even in its current form, it is *functional* for you.

As for the rest:

- Duplicating the same information in *two* places (msgctxt and refs): Lazarus tools being weird. This is *not* Poedit showing it twice, but faithfully presenting you the PO files as they are. You should complain to Lazarus about this.
- Inconsistent use of msgctxt or not: Lazarus tools being weird.
- Use of non-file refs in the first place: Lazarus tools being weird.

These are all things that would be best addressed at the Lazarus end of it. And well, I *could* do something about it: I could have a dedicated view mode for Lazarus that shows information differently to accommodate the bizarre files. But at this moment, it's just not worth spending time on due to the relative unpopularity of Lazarus in the grand scheme of things. (A coronary of this is that if somebody else feels it's important enough and makes a PR to adapt the UI for Lazarus files only, by all means, I'm always happy to merge quality patches.)

--
P.S. If you could email me with some details about how Lazarus gettext extraction works, with what files, what tools, how's your extractor setup etc., I'd appreciate it — my end goal is to support all the common and even no-so-common stuff out of the box.

**Comment by denis-bisson** [comment]
Hello Sir!

I am not a specialist with .po file like I'm expected you should. I might not use the right term for what I meant. But I've spent enough time hoping you would do something. I've attached a sample .po file with what I was hoping to see. Instead, I did something else...

As far as I know, reading through pages like https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html or http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html , the "msgctxt" tag was not an obligation to be present into the .po file. Knowing that, I feel I can't qualify "weird" an application who did not include a "msgctxt" tag on each expression. In such circumstances, I though it would have been a not so much asked request to give a hint to user, to show the reference them where the expression was coming from without having to right click on each expression. 

**SO INSTEAD what I did is to make a small console application that I inserted at the end of my compile process. The application is given the output path of the .po files generated and will parse all the files and then add a "msgctxt" tag for each and every expression that FreePascal/Lazarus did not generate.** The "msgctxt" tag is holding the same text as what was in the reference line. This way, when I am opening them in your poedit, now I have a hint for each and every expression where it's coming from since you, you display in the main window the "msgctxt" tag.

I've committed this console tool on the web under this link for those rare-weirdo-person like me that it would help when working with original rare-weirdo .po file that don't have the "msgctxt" tag on each expression:
https://sourceforge.net/projects/msgctxt-adder/

When I am using your tool I am in a bus, or train, etc. with a laptop. It keeps moving and shaking. Using the mouse or pad is not as efficient as using the keyboard. That's why I was hoping to view that without having to right click.

It took me about an hour for that for that's fine. An hour on a Sunday morning is sometimes the same  value as a couple of minutes in rush project completion during week! :-)

I am including some screenshot for fun.

So thanks anyway.

Denis.
![dos_runningscreen](https://cloud.githubusercontent.com/assets/16710801/24837305/48d6a9a0-1cff-11e7-9e1a-7ce605f18f44.jpg)
![lookingatfiles](https://cloud.githubusercontent.com/assets/16710801/24837306/4ba075d0-1cff-11e7-8322-8fe1fe1f6bb0.jpg)
![endresult](https://cloud.githubusercontent.com/assets/16710801/24837308/4e44f25c-1cff-11e7-8c5a-b968ccc53f46.png)
![supportunicode](https://cloud.githubusercontent.com/assets/16710801/24837309/5119ced0-1cff-11e7-80d1-026f7fb2f00a.png)

**Comment by vslavik** [comment]
> Knowing that, I feel I can't qualify "weird" an application who did not include a "msgctxt" tag on each expression.

You twist my words. Doing it *inconsistently* is weird. Misusing context for essentially location information, which *is* done here also *is* weird — that's simply not what the context is for. 

> That's why I was hoping to view that without having to right click.

As I explained above, you *already can* do just that. Just show the references window, keep it open and continue working on the file.

**Comment by denis-bisson** [comment]
Hello Sir.

Ok. I feel you did not try the sample file I paste on the first post but that's fine. I think I figured what's wrong in this.

Like I wrote, I am not a specialist of these file and for me, the only .po file I've seen in the last five years are the ones generated with FreePascal/Lazarus. And you, you know everything and will repeat over and over that the files are not correct but not understanding me. But finally I think now I know what happens.

Me, I was asking to show the "reference" of the expression. I am under the impression that you, you are thinking I am asking you to show the part of text where the expression was coming from. But in fact, me, I was just asking for a few words, in fact, I was just hoping you would show like "tfrmabout.caption" from my above example...

After having spent a few minutes after your post to search again on the matter I realize something that maybe you "think" you've already told me but not as clearly as what I will write here: it's probably because you you assume that the reference will be under the form of a filename and a line number. But Lazarus is not providing that this way. It's providing it under the way "tfrmabout.caption". Which is a reference not so bad because it tells to the author directly where it is. It's the form called "tfrmabout" and it is the caption of the form. So this, your poedit can't interpret that. It can't show the location of that because he can't read the .lfm file to show me the line. It take a little bit more knowledge than just a line number to figure where is the "caption" of the object "tfrmabout" and hightlight the proper line.

So that's why what you suggest can't work but now at least I feel I understand a little why and I hope now you realized, from the example I gave right from the start, that it does not work.

But at least, with what I did, at least, just to have the reference shown like "tfrmabout.caption", it gives me a good hint. It's better than just the sentence out of no where. At least with what I did, without right-clicking I am able to have a hint, a reference, to from where it is.

Just in case you did not figure, implementing what I was hoping, what was for me my not-compatible-with-you-definition-of-the-reference would simply be "tfrmabout.caption" or maybe something like "..\source\fAbout.lfm:2233" if it would have been done originally in what poedit is expecting.

I've already fill in a question on that on the forum of Lazarus to see if there is a way to generate that type of file, if was could generate it in such way as a filename and line number. I doubt we will do something on that but anyway, we'll see.

By the way, when you wrote you did not have enoug room on screen to show the reference, I was like "What? No room for just one single line? Is he kidding me?". But now, I guess I understand. You did not understand that by "reference" I was just referring to the single line written as where to find the actual expression and not really many lines around it.

So again, thanks anyway. :-)

Denis.

![withreferencelikeitisnow](https://cloud.githubusercontent.com/assets/16710801/24838491/cd08543c-1d16-11e7-9e6d-83711768049b.png)
![withreferenceasfilenameandlinenumber](https://cloud.githubusercontent.com/assets/16710801/24838492/d13b340c-1d16-11e7-8821-014b37334046.png)

**Comment by vslavik** [comment]
> Ok. I feel you did not try the sample file I paste on the first post but that's fine.

I of course did. *Your own screenshot* shows that the reference text your after is shown at the top of the window!

> So that's why what you suggest can't work

It can and it does:

![cd08543c-1d16-11e7-9e6d-83711768049b](https://cloud.githubusercontent.com/assets/145881/24838551/49e10110-1d4a-11e7-9394-7e1998630df1.png)

> By the way, when you wrote you did not have enoug room on screen to show the reference, I was like "What? No room for just one single line? Is he kidding me?".

You once again put words in my mount that I never said. Yes, there's room. There's also something called good UI design and sanity and putting everything and kitchen sink on a single screen is neither. I said that the main window screen estate is premium and I won't "waste" it on references; that's a very different thing.

> You did not understand that by "reference"

This "single line" may actually contain many (10+ easily) files for common strings.

**Comment by denis-bisson** [comment]
> It can and it does:
  Ha! Ha! You're right. I feel I was naturally hoping to see "file reference" (I will call it this way now) in the main window that I did not realize that yes, you're right, what I was hoping to see is displayed in that window. Or maybe it was because I was gray on other gray... Or that it easily disappear under the main window and did not think to resize and replace it... Or did not have it restored from a session to another and I forgot about it... But you're right, it's easy to simply check the option and I'll have it.
At home I will use my little tool but outside, I'll you that trick now.

>This "single line" may actually contain many (10+ easily) files for common strings.
  Ha. I see. 
  It could have been "..this\path\this_file.ext:1258 (9 more...)" also but I won't insist. :-)

  Thanks and take it easy man!

Denis.
