### ISSUE TITLE
Export/Import/Sync Local translation memory

### ISSUE THREAD

**Issue by nilovelez** [vslavik/poedit#379]
Poedit's local translation memory works great but it could be awesome if you could export and import it. 

As far as I know, Poedit store it's TM in %APPDATA%\Poedit\TranslationMemory\
I guess I could copy those files to another computer, but that would replace the second computer's TM entirely. The idea is being able to import another computer's TM and merge it with the local one.

Possible scenarios:

- Translation communities could have a reference TM file that new members would download and import.
- If you have to work while traveling, you can copy your TM to a laptop, and update your local computer when you are back home.
- Keeping a backup of your TM

**Comment by vslavik** [comment]
I'm aware of the usefulness of sync — easier said than done, hence why it isn't there yet.

You know that the online suggestions largely give you the benefits you're after unless you disable contributing to it, right?

**Comment by nilovelez** [comment]
Yes, online suggestions cover most use cases, and I contribute almost all my work to it, but it doesn't provide offline access (obviously) and they can't be used for private texts.

Also, if you make lots of repetitive translations on a specific niche like WordPress themes, the TM often provides better translations than online suggestions.

**Comment by vslavik** [comment]
> but it doesn't provide offline access (obviously) and they can't be used for private texts.

Yes, of course.

> Also, if you make lots of repetitive translations on a specific niche like WordPress themes, the TM often provides better translations than online suggestions.

My point was that it *doesn't* — if you contribute to the online TM, you'll get the exact same quality of exact matches. For partial matches, that may be true (even though a bit surprising to me as the author of the code…).

Anyway: yes, this would be useful.

(Everybody else who sees this issue: feel free to thumbs-up if this would be useful to you.)

**Comment by vslavik** [comment]
Sorry for forgetting to close this: TMX import/export support was added 17110d3c0b1b8555fa89d2fa8e736bd42d128575 and released in [Poedit 2.1](https://poedit.net/news/poedit-2.1-improves-pretranslation/).

**Comment by babycaseny** [comment]
So this thread is closed? I am now using Poedit 2.2.3, and I think there is a little bit we can do for the TMX import/export: can we limit the scope to only a single language, or actually shall we build up a separate TranslationMemory folder when we are working on projects involving different languages, so the TranslationMemory do not get mixed up?
