### ISSUE TITLE
Ability to sort by reference

### ISSUE THREAD

**Issue by jeancroy** [vslavik/poedit#387]
Hi. First thanks you for such an useful tool.

Then I'd like to suggest an additional sort order: sort by reference.
Given that "view > show references" works well i'd guess Poedit has good support for reference annotation.

Additionally I'd like to have the reference visible somewhere on the GUI.

Underlying need is multiple short translations that i'd like to group to have some context.

The "file order" sorting in my case is the same as "source", that is alphabetical order of the msgid.

**Comment by vslavik** [comment]
Software design is in a large part saying "no" to things, so... No.

There's already perfectly suitable ordering by locality, the "by file order" one, which you're well aware of. Adding yet another, nearly identical but confusing not quite, sort order makes zero sense. (Also, do note the plural in reference**S** and ponder the difficulty of ordering by something that is not one, but multitude...) 

> The "file order" sorting in my case is the same as "source", that is alphabetical order of the msgid.

Don't generate or sort the file in such an unreasonable way, then. There, problem solved.

**Comment by jeancroy** [comment]
> Don't generate or sort the file in such an unreasonable way, then

Pot is generated by an asp.net i18n module. What is the standard file generation order ? How does the standard order deal with multiple references ?

In our case, not being able to group similar item together is way worse than the occasional duplicate references. However the pot generator is open source too so I might be able to adapt it.

Thank you for consideration.

**Comment by vslavik** [comment]
> by an asp.net i18n module.

Please don't be this vague when filling issues. It's not "a" module, it's some specific piece of software, so please name it.

> What is the standard file generation order ?

All standard/sane tools use source file order. This mysterious tool you use goes to extra lengths to sort things, loosing valuable locality information in the process. So yes, that's where you should be looking for a fix (not least because POs can be edited in a plain text editor too!).

> duplicate references.

Nobody said anything about any "duplicate" references… You seem to be entirely missing the point that you can't very well sort by references, because there often are multiple uses of the same string in different places, with no inherent ordering.

> However the pot generator is open source too so I might be able to adapt it.

Same applies to Poedit, you can make PRs instead of "suggestions" here too… But this really is something that would be best fixed at the source of the problem, i.e. the extraction tool responsible.

**Comment by jeancroy** [comment]
This project is the generator https://github.com/turquoiseowl/i18n
Specifically  i18n.PostBuild & i18n.POTGenerator

Ive traced the sort order to [this part](https://github.com/turquoiseowl/i18n/blob/ae1f88bae86a88f6c14cdb49e7ecd02f58f71a51/src/i18n.Domain/Concrete/POTranslationRepository.cs#L308-L313). Again references is a collection.

> You seem to be entirely missing the point that you can't very well sort by references.

You are right. The reason I ignore this point is that you suggest normal file order is sorted by scan order (aka reference). So any getText tool will just have to pick one order and continue. First file processed, last file processed or something like that. If I have to fix above sort example I'll probably take the first item of collection and sort by it.

> Same applies to Poedit, you can make PRs instead of "suggestions" here too…

Most projects I have participated, It is customary to talk issue in word before suggesting PR.
I did some search in both project source before deciding it would be easier for me to try a fix on the other one. 

>  But this really is something that would be best fixed at the source of the problem, i.e. the extraction tool responsible.

Very possible, especially if you tell me they diverge from GNU/getText standard file. OTOH flexibility in input file may be of interest to you or your users.

Have a very nice day.

**Comment by vslavik** [comment]
> This project is the generator https://github.com/turquoiseowl/i18n

Thanks!

> Most projects I have participated, It is customary to talk issue in word before suggesting PR.

…and to indicate such intention PR intention, yes.

> Very possible, especially if you tell me they diverge from GNU/getText standard file. 

Just to be perfectly clear: they diverge in the sense that they are unusual, but they still are *valid*.

> OTOH flexibility in input file may be of interest to you or your users.

Poedit works with the file, it doesn't refuse it. But it does, and always will, work *best* with files that are typical. As an another example, you can use non-English source language, but it's unusual and your experience will be degraded in Poedit in that case too (worse TM).

**Comment by safriks** [comment]
having the same issue - for us context an occurrence can be slightly different and being able to filter by which file it offers in would be a killer feature.

having to resort to adding to https://github.com/wichert/po-xls/ functionalty to do that

**Comment by vslavik** [comment]
> for us context an occurrence can be slightly different

Can you please elaborate in some level of detail?

> able to filter by which file it offers

Do you mean *filter* or *sort* (this issue is about the latter)? How do you propose to sort on reference when a string may occur in multiple files/references?
