### ISSUE TITLE
No batch mark fuzzy/needs work in 2.0.1

### ISSUE THREAD

**Issue by liftarn** [vslavik/poedit#388]
In the older versions I was able to mark several strings and mark them all as fuzzy (Needs work).
In the new version it don't seem to be possible any more.

**Comment by vslavik** [comment]
Of course it is possible, in the same way it always was, from the Edit menu.

You shouldn't do it, though, there's a reason why Poedit tells you to *review them individually*.

**Comment by vslavik** [comment]
Please also comment on other issues if you have nothing constructive to say. Please don't create issues unless you are 100% sure it's a bug.

If you are a Pro customer, please use help@poedit.net.
