### ISSUE TITLE
Menu Bar Disappears

### ISSUE THREAD

**Issue by scmyyc** [vslavik/poedit#392]
My environment:
Windows 10 build 1703 64bit
Poedit 2.0.1, Chinese locale
![20170509034507](https://cloud.githubusercontent.com/assets/5208277/25822046/f055a2d6-3469-11e7-9722-61f5a0590708.png)

**Comment by vslavik** [comment]
If you prefer to use the bug tracker instead of standard support channels, please use it as intended and check existing issues and post-release commits *before* filing issues, to prevent outdated or duplicate issues (or as is the case here, both).
