### ISSUE TITLE
Edit area font becomes smaller after displaying U+22EE

### ISSUE THREAD

**Issue by atriwidada** [vslavik/poedit#394]
Font became smaller after displaying a certain line.
Possibly a line containing \< superscript>foo< /superscript>

Attached is a sample file. Please check around ID 53.
[sf-bug.zip](https://github.com/vslavik/poedit/files/995674/sf-bug.zip)

--
Poedit 2.0.1 - OS X Version 10.12.4 (Build 16E195)~ -

**Comment by vslavik** [comment]
Sorry, this is extremely vague — what is "around"? What is "font became smaller"? What did you *do* to trigger it?

Please provide detailed, exact, step-by-step reproduction instructions (see [why](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)) and preferably *show* just what exactly you mean.

**Comment by atriwidada** [comment]
Step to reproduce
1. view translation file attached above, ID 54
initial font size is screen capture below
<img width="978" alt="screen shot 2017-05-12 at 16 55 10" src="https://cloud.githubusercontent.com/assets/1826702/25993611/b954e080-3734-11e7-98fe-357bb1b22ed9.png">
2. down arrow several times
3. up arrow several times, back to ID 54
font size now become smaller as captured below
<img width="978" alt="screen shot 2017-05-12 at 16 55 53" src="https://cloud.githubusercontent.com/assets/1826702/25993623/c304316c-3734-11e7-9382-e67048d08ab1.png">

**Comment by vslavik** [comment]
This has nothing to do with ID 54 and everything with the (unmentioned) fact that you show ID 52 in the process.

Apparently the tall **⋮** (U+22EE VERTICAL ELLIPSIS) character triggers *something* in `NSTextView` that makes it use a smaller font to be able to render the text. I don't think there's much that can be done to address it, unfortunately — it's internal to Cocoa.

Given the extremely rare circumstances (this is not a normal character to translate and this entry shouldn't have been present in the PO in the first place), it's also probably not worth spending any significant amount of time on fixing.

I would accept a PR for it, of course, but realistically speaking, this is about as low priority bug as it gets — unless it affects (much) more characters, that is, of course.
