### ISSUE TITLE
GtkTreeView quick search doesn't seem to work

### ISSUE THREAD

**Issue by ArthurHoaro** [vslavik/poedit#398]
*Disclaimer: I don't really know Poedit so it might be a user mistake.*

The quick search (when I start typing or use CTRL+F) doesn't seem to have any effect, aside from displaying the search field, and just disappear when I hit enter.
However, the search popup from *Edit > Search* works just fine (which should also be CTRL+F).

ArchLinux - Poedit 2.0.1

**Comment by vslavik** [comment]
Ctrl+F is *identical* to the menu item (as you can trivially see in the code). And search of course does work.

If you believe otherwise, show some reproducible evidence - see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by ArthurHoaro** [comment]
According to your link, obviously my initial issue wasn't clear, sorry about that. Here is [a screencast](https://s1.webmshare.com/6r9On.webm).

Steps:

  - Hit CTRL+F: the quick search appear
  - Type an existing key
  - Hit Enter

Actual result:

   - Nothing happens

Expected result (I guess):

   - The translation item corresponding to the search string is selected

> Ctrl+F is identical to the menu item (as you can trivially see in the code)

I didn't look at the code, but the menu item open a search popup while CTRL+F does not.

**Comment by vslavik** [comment]
> Hit CTRL+F: the quick search appear

*There's no such thing* as "quick search" in Poedit. You're seeing some built-in GTK+ behavior that presumably works automatically. I have no idea why it doesn't for you, except that it may depend on wxGTK and GTK+ versions. Please provide those.

**Comment by ArthurHoaro** [comment]
`wxgtk 3.0.3.1-1` and GTK+ `3.22.15`

I just noticed that CTRL+F works fine if I don't have the focus on the list, so it's a pretty minor issue.

**Comment by vslavik** [comment]
Notes to self:

This builtin search can be disabled easily enough with [by passing -1 to `gtk_tree_view_set_search_column()`](https://developer.gnome.org/gtk3/stable/GtkTreeView.html#gtk-tree-view-set-search-column). The question is whether it should, perhaps it would be preferable to set it to the source column *and* enable type-as-you search (see also #386).

But then resolving the ambiguity with existing <kbd>Ctrl</kbd> +<kbd>F</kbd> binding becomes an issue. It could be done by [manually unbinding Ctrl+F](https://stackoverflow.com/a/23388804/237188), which of course only works with the default bindings.
