### ISSUE TITLE
GetText entries in Twig files are not all scrapped if they're inside an IF statement and a var is set

### ISSUE THREAD

**Issue by fbnlsr** [vslavik/poedit#403]
Consider this Twig template:

```twig
{% if identification is defined %}
    {% set count = identification.replies|length %}
    {{ __('Posted by', 'csf-core') }}
    {{ __('Validator', 'csf-core') }}
    {{ __('Add a comment to this request', 'csf-core') }}
    {{ __('Make an identification suggestion to this request', 'csf-core') }}
{% endif %}
```

When this file is scrapped by poedit Pro, only the first entry ("Posted by") is seen by it.

- If you remove the "set" statement, all 4 translations are seen by poedit.
- If you remove the "if" statement, all 4 translations are seen by poedit.
- If you change the set statement to assign a string for `count`, all 4 translations are seen by poedit.
- If both statements are present, and the set statement is anything else than a string, only the first translation entry is seen by poedit.

It seems there's a bug in poedit's scrapping engine, or the regex its using, as it's unable to see all the translations in this case.

**Comment by fugudesign** [comment]
I have the same bug, please let us know about a fix or a workaround solution.

**Comment by vslavik** [comment]
@fugudesign The bug tracker is treated as a bug tracker, i.e. updated only when information is needed or material changes made. Please use email for Pro *support* (with corresponding expectations).

Will be fixed in 2.0.3. For workarounds, see the original post.

**Comment by vslavik** [comment]
Fixed for 2.0.3, to be released on beta updates channel soon-ish. If you need a fixed build urgently, please email me at support address and indicate your operating system.

**Comment by vslavik** [comment]
Sorry for the delay, this is now in the beta updates.

**Comment by fbnlsr** [comment]
@vslavik thanks again for addressing this issue. Do you have an ETA for when 2.0.3 will be out of beta by any chance?

**Comment by vslavik** [comment]
As I said in the comment above, this fix *already is available* - just enable beta updates in preferences.

**Comment by fbnlsr** [comment]
Alright, thanks a lot for your answer! 👍

**Comment by vslavik** [comment]
…And released.
