### ISSUE TITLE
"Update all" does not respect "Automatically compile MO" preference

### ISSUE THREAD

**Issue by wrygiel** [vslavik/poedit#405]
When I click *Update All* button in *Catalogs manager* window it correctly updates all my `*.po` files. However, it does not update any `*.mo` files, despite the fact that the option *Automatically compile MO file when saving* is checked in my preferences.

Is it a bug, or is it desirable? I'm not an expert on the structure of MO files, so I'm not sure if they need to be updated in this case. However, I guess that I'm not the only user who wonders.

**Comment by vslavik** [comment]
There's no bug. To understand, ask yourself: what do you expect to *gain* from updating the MO files at this point?

That's right, it doesn't make much sense. Not only does the option clearly says *Automatically compile MO file **when saving*** and *you* didn't save anything, but MOs contain translations and *you didn't change any translations* at this point. Recompiling MOs would be entirely pointless, as it would only recreate equivalent-in-use MOs.

> I'm not an expert on the structure of MO files,

You don't need to, you just need to understand what MO files are *for* and what they contain — which is explained well in the GNU gettext manual, linked from the Help menu. Please read it, understanding the basic concepts is important. 

> I guess that I'm not the only user who wonders.

You seem to be…

P.S. Please don't file issues if you're not sure it's a bug — there are more appropriate support channels for mere questions.

**Comment by wrygiel** [comment]
> Recompiling MOs would be entirely pointless, as it would only recreate equivalent-in-use MOs.

Following this reasoning - MO files get updated *only* when *translation strings* are updated, right? But this is not true. They are updated every time I hit Ctrl+S on the `*.po` file. As you have explained above, they don't need to be. So, there seems to be an inconsistency here...

**Comment by vslavik** [comment]
Please spend a second reading that checkbox's label again.

It does not say it will recompile MOs when *updating from sources*. It makes no sense to do it *when updating from sources*. Ergo, Poedit doesn't do it when *updating from sources*. Poedit does recompile when saving files because *that's what the checkbox says*. There's no "inconsistency" and this bug report *is* bogus.

**Comment by wrygiel** [comment]
> There's no "inconsistency"

Well, I disagree (from the "User Experience Design" perspective). But I can see I won't convince you alone, so let's leave it at that. :)
