### ISSUE TITLE
Add support for XLIFF

### ISSUE THREAD

**Issue by vslavik** [vslavik/poedit#408]
$SUBJECT says it: support editing XLIFF files.

(Please thumbs-up if this is of interest to you.)

**Comment by mahpah** [comment]
Are 10 votes enough?

**Comment by anymos** [comment]
Good morning,

Previous paid user, happy to buy the new version if there is XLIFF or other angular 2/4/5 format support

thank you in advance

**Comment by vslavik** [comment]
I'm now collecting sample "real life" XLIFF files for testing — if you have any, please send them to me at help@poedit.net. TIA!

**Comment by vslavik** [comment]
…and done in Poedit 2.2: https://poedit.net/news/xliff-and-dark-mode/
