### ISSUE TITLE
Extract language strings from HTML attribute

### ISSUE THREAD

**Issue by danielkoch** [vslavik/poedit#412]
Is it possible to extract language strings from HTML attributes?

**This works:**
`<label><?php __('Test', 'text-domain'); ?></label>`

**This not:**
`<input placeholder="<?php __('Test', 'text-domain'); ?>" />`

I know the flag `--extract-all`. But this does't work correctly for this use-case (first try).

Currently I use Poedit 1.8.8

**Comment by vslavik** [comment]
*(Please use help@poedit.net for questions; this bug tracker is for tracking bugs.)*

HTML is not a programming language and can therefore not have gettext support, so no, of course not. However your example shows *PHP* code with no apparent relation to "HTML attributes", and PHP is natively supported by gettext tools, so the above will be extracted.

Also, you mention `--extract-all`, which doesn't seem to be related, and is a `xgettext`, not Poedit flag — did you mean to file a *GNU gettext tools* bug report?

If you believe there's some extraction error in Poedit, please provide *full* reproducible example, including *full* source code and the PO file, not just a single line taken out of context. See also [some helpful tips](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) for bug reporting. Don't forget to include basics like your platform or Poedit version and, if you use a pre-2.0 version of Poedit or use custom extractors in 2.0, full definition of your PHP extractor.

**Comment by danielkoch** [comment]
Ok. I think the problem was not described well. I'll send you an email with more details.

**Comment by vslavik** [comment]
(In case somebody stumbles upon this issue: the actual problem was not with the code shown above (which will be fine), but with extracting from template files mis-parsed as Python.)
