### ISSUE TITLE
poedit: text right-aligned?

### ISSUE THREAD

**Issue by LocutusOfBorg** [vslavik/poedit#413]
Hello, this happens on Debian and Ubuntu, since version 2.0.1. (or maybe 2.x)
You can see this bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868042
and the dependencies are:
wx 3.0.2
boost 1.62
cpprest 2.9
libgtk2
libssl1.1

as usual, I can provide everything you need, this happens on my main laptop too, with an italian po file (or fr.po or whatever).
My Ubuntu is zesty with poedit 2.0.1 amd64

thanks!
screenshot here:
  https://ooo.0o0.ooo/2017/07/11/5964d97a73037.png

**Comment by vslavik** [comment]
Apparent duplicate of #369.

This is a wx, not Poedit, bug. wx 3.0.2 is ancient and the latest version, required by Poedit 2.0.2, is 3.0.3, which IIRC fixes this. Also IIRC you removed this version check in your packages against my recommendation.

Please verify in 2.0.2 with wx 3.0.3.

**Comment by LocutusOfBorg** [comment]
mmm I did try 2.0.2 with wx 3.0.2 + commit https://github.com/wxWidgets/wxWidgets/commit/ed8c3feab389493429c0a9bdde832b51a1c2186a
and I still can reproduce the issue with Ubuntu zesty amd64 bit.
I'll try wx 3.0.3 tomorrow probably :)

**Comment by LocutusOfBorg** [comment]
btw I cherry-picked that upstream wx commit a few days before ubuntu 17.04 release, so Debian and Ubuntu stable have both it

**Comment by vslavik** [comment]
There are *hundreds to a thousand* commits between the two wx versions, not just one.

**Comment by LocutusOfBorg** [comment]
yep, I confirm the fix, thanks!
