### ISSUE TITLE
Build fails due to undeclared 'http_client'

### ISSUE THREAD

**Issue by rffontenelle** [vslavik/poedit#414]
When building from master branch, I get the following error message ([See full build output](https://ptpb.pw/3scV)):
```
edapp.cpp: In member function ‘void PoeditApp::SetupLanguage()’:
edapp.cpp:596:5: error: ‘http_client’ has not been declared
     http_client::set_ui_language(uiLang.LanguageTag());
     ^~~~~~~~~~~
make[1]: *** [Makefile:691: edapp.o] Error 1
make[1]: Leaving directory '/home/rffontenelle/builds/poedit-git/src/poedit/src'
make: *** [Makefile:476: all-recursive] Error 1

```
It could be related to commits c1a9d762 and/or 9e4be366..

Environment: Arch Linux 64-bit

**Comment by vslavik** [comment]
Thanks for the report!

c1a9d76 is *fixing* such compilation problem. The actual culprit can be found in `config.log`:

```
Enabled features:

    * debug build:                    yes
    * language detection:             no
    * crowdin integration:            no          <---
```

I.e. you are building a limited version of Poedit in which this compilation error happens to exhibit itself. I generally recommend against doing that, but as long as that's supported/possible, it should of course compile.
