### ISSUE TITLE
Problems with special characters in the display of the source text-column

### ISSUE THREAD

**Issue by KATatHS** [vslavik/poedit#418]
* Version 1.8.11 (debian stretch)

I opened a list I used to work with version 1.6 (in debian jessie). The source text contains terms that end with various special characters. Now with the new version (1.8.11) there is a problem with a few of this special characters in the display of poedit. When I mark the entries and take a closer look everything seems ok with it. 
For example, if my term ends with ) the term in the display starts with ( and the ) at the end of the term is missing. The same problem is with . at the end and the sign for "Register trademark" and ™. If the term ends with % (or an "normal" letter or number) it is not a problem.
Now I am afraid that this might effect my po-list. And it is not very nice to work with, because I look for errors that are not there. (or maybe they are there and I can not see them yet). If I open the list with an editor (mousepad) everything seems ok.

It is my first reported bug, so I don't know if there is any more information necessary. 

![bildschirmfoto vom 2017-07-31 15-57-51](https://user-images.githubusercontent.com/30597798/28781429-4ddb6fda-760a-11e7-9c90-f54f79a7ebf8.png)

[en-GB-primary.po.zip](https://github.com/vslavik/poedit/files/1187803/en-GB-primary.po.zip)

**Comment by c72578** [comment]
Please use a recent version of Poedit.
The problem you describe does not appear any more in Poedit 1.8.13 or the current version 2.0.3.

**Comment by vslavik** [comment]
@c72578 Thanks for checking!

**Comment by KATatHS** [comment]
Is the issue reported to the Debian team? Can we help to improve the version of PoEdit which is distributed with Debian (currently 1.8.11) by submitting a patch?

**Comment by c72578** [comment]
Here you see, which versions of Poedit are available for Debian:
https://packages.debian.org/search?keywords=poedit
In Debian sid you will find e.g. Poedit 2.0.3-2
Maybe you want to file a bug at Debian or contact the Debian package maintainer. You will find the contact addresses from the above link.

**Comment by vslavik** [comment]
@KATatHS This is not the place to ask about unrelated projects' policies, please don't waste any more time on this invalid issue. Debian is competent and well aware of the existence of Poedit releases.
