### ISSUE TITLE
macOS "can't set default encoding to wxFONTENCODING_DEFAULT" assert

### ISSUE THREAD

**Issue by hamid914** [vslavik/poedit#420]
I got [Poedit-2.0.3](https://download.poedit.net/Poedit-2.0.3.zip) on macOS Sierra 10.12.6. and it crashes after running. This error is shown when I run the program from the Application folder:

![1](https://user-images.githubusercontent.com/1765587/28930844-6dbf015a-7889-11e7-9203-a057ca6fbe2d.jpg)

I run the program from the terminal and the result is:

    $ /Applications/Poedit.app/Contents/MacOS/Poedit
    /Users/vaclav/Development/poedit/deps/wx/src/common/fontcmn.cpp(144): assert "encoding != wxFONTENCODING_DEFAULT" failed in SetDefaultEncoding(): can't set default encoding to wxFONTENCODING_DEFAULT
    Collecting stack trace information, please wait...[1]    81684 segmentation fault  /Applications/Poedit.app/Contents/MacOS/Poedit

I tried to install Poedit from HomeBrew repository:

    $ brew cask install poedit
    ==> Satisfying dependencies
    ==> Downloading https://download.poedit.net/Poedit-2.0.2.zip
    Already downloaded: ~/Library/Caches/Homebrew/Cask/poedit--2.0.2.zip
    ==> Verifying checksum for Cask poedit
    ==> Uninstalling Cask poedit
    ==> Removing App '/Applications/Poedit.app'.
    ==> Installing Cask poedit
    ==> Moving App 'Poedit.app' to '/Applications/Poedit.app'.
    🍺  poedit was successfully installed!
but the result is the same.
There are two installed language on my macOS:

    $ defaults read .GlobalPreferences AppleLanguages
    (
        "fa-IR",
        "en-IR"
    )
In my `~/.zshrc` there are two lines about locale:

    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
I have installed wxwidgets with HomeBrew:

    $ brew install wxwidgets
    ==> Downloading https://homebrew.bintray.com/bottles/wxmac-3.0.3.1.sierra.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring wxmac-3.0.3.1.sierra.bottle.tar.gz
    ==> Using the sandbox
    🍺   /usr/local/Cellar/wxmac/3.0.3.1: 810 files, 24.3MB

But the results is the same yet.
I tried to run the program as root:

    $ sudo open -a Poedit
But no luck. Then with root user and program's executable file:

    $ sudo /Applications/Poedit.app/Contents/MacOS/Poedit

It "runs" now, but is it the only official way to run Poedit?!

**Comment by vslavik** [comment]
Please [read this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and follow the advice therein. Please also indicate where you got Poedit from.

If you have the latest official build and if this happens, then something very specific to your system is going on. It would help if you actually described your system to help identify what that something might be. E.g. your language, locale, font etc. settings are highly relevant.

**Comment by hamid914** [comment]
I've updated my question with more details. I got my locale in my shell and did not know how to get font or wxFONTENCODING_DEFAULT settings in my shell to update my question with them. Help me how to get them.

**Comment by vslavik** [comment]
Thanks. Unfortunately running with Persian as the primary language doesn't seem to be the cause — I tried.

As for the rest: Poedit is a macOS native GUI application, so your shell settings are entirely irrelevant, so is whatever you installed with Homebrew or your shell settings.

Of course root access is not required, that's a strange question (but then, so is running the application from shell at all). This merely demonstrates that *something* in your user settings is triggering this. Login into a Guest account and you'll probably see everything working.

Did you previously use Poedit? Did you configure any settings in it, such as custom fonts?

**Comment by hamid914** [comment]
Thanks for your reply.

1. ✅ I tried logging in Guest account and running the program. It worked with the default settings.
2. ✅ Then, I changed the language settings to what I had in my main account. It worked again.
3. ✅ I opened a Terminal and run `/Applications/Poedit.app/Contents/MacOS/Poedit` inside it with the Guest user. It worked.
4. ❌ Then, I changed the user with `su myUsername` and run it. The output was `assert "encoding != wxFONTENCODING_DEFAULT" failed...` again.
5. ❌ Finally, I installed my custom Persian fonts in the Guest account, then the problem occurred again.
6. ❌ After uninstalling all Persian fonts, the problem persisted until a logout and login.

In my main user account:

1. ✅ I tried `sudo atsutil databases -remove` and then changing my languages order in Language & Region (English first). The program worked in the English localization.
2. ✅ After that, I changed the language order (Persian first). The program worked in the Persian localization.
3. ❌ After a logout and login, the problem is reset to its initial state. I should change my languages order in Language & Region twice to make Poedit run.

- Is there any logging facility for Poedit to report my log for you?
- And is it a design mistake in Poedit because there are absolute paths in compiled distribution binary? (I mean `/Users/vaclav/Development/poedit/deps/wx/src/common/fontcmn.cpp(144):...` in my question)

**Comment by vslavik** [comment]
sudo, paths, language, logging off are irrelevant. No need for you waste time second-guessing the code or me.

What you established as relevant is the *fonts you have* — and it's no coincidence that the assert message talks about fonts. The fonts (or likely, a single font) is *clearly* what triggers it, per your report, and seems necessary to reproducing it. Can you please attach that font (or fonts, if you don't want to waste anymore time tracking the problematic one down)? That should be enough for me to reproduce… and thus fix.

Thanks!

**Comment by hamid914** [comment]
This is the content of my `~/Library/Fonts` folder:

    DejaVu Sans Mono for Powerline Nerd Font Complete Mono.ttf
    IRANSansWeb.ttf
    IranNastaliq.ttf
    ProFont IIx Nerd Font Complete Mono.ttf
    Roboto-Regular.ttf
    Samim-Bold.ttf
    Samim.ttf
    XB Niloofar.ttf
    XB NiloofarBd.ttf
    XB NiloofarBdIt.ttf
    XB NiloofarIt.ttf
    XB Titre It.ttf
    XB Titre Shadow It.ttf
    XB Titre Shadow.ttf
    XB Titre.ttf
    encodings.dir
    fontawesome-webfont.ttf
    fonts.dir
    fonts.list
    fonts.scale
And this is the compressed file of those fonts: [fonts.zip](https://github.com/vslavik/poedit/files/1202638/fonts.zip)

Thanks.

**Comment by hamid914** [comment]
@vslavik, In addition to my previous comment:
I removed all custom fonts from my `~/Library/Fonts` folder and was trying to translate a PO file inside Poedit in my main user account. In the top of the right sidebar, there was a message: `Lock obtain timed out (10)`
And it did not suggest any translations:

![lock](https://user-images.githubusercontent.com/1765587/29031259-2cfadf30-7b7d-11e7-8565-6255ad6c9209.jpg)

In addition to that, in the TM preferences, there is no translation memory database:

![myusername](https://user-images.githubusercontent.com/1765587/29031329-65ca9116-7b7d-11e7-8281-d41a80698dc5.jpg)

And there are several `UNIX error exception: 17` error messages in my Console. This is the log when I open Poedit and then access TM preferences: [poedit_myUsername.log](https://gist.github.com/hamid914/e226085ab07ddcbd9d40a0358cd66643)

In my Guest user, there is no such exception in the log while accessing TM preferences: [poedit_guest.log](https://gist.github.com/hamid914/7f1f205e48bacb39f788ab8235bd1840)
And also has translation memory database:
![guest](https://user-images.githubusercontent.com/1765587/29031843-0cfad42c-7b7f-11e7-8fdf-0f6b8546be39.jpg)

Thanks.

**Comment by vslavik** [comment]
@hamid914 I'm again asking you to read *and follow* the guidelines I asked you to read in my very first comment on this issue. In particular, please don't mix obviously unrelated things into a single issue: you're just making a giant unmanageable mess of it. I'm deleting your previous comment to restore some sanity to this issue. You probably corrupted permissions or files with your haphazard use of `sudo`: investigate, clean files, verify. If you are *certain* that's not it and is not transient (I'm pretty sure it is), file another issue.

**Comment by vslavik** [comment]
I can't reproduce this with neither 2.0.3 nor 2.0.4, with Persian locale, so either it's gone or there's something *else* required to trigger it.

Are you still seeing it in 2.0.4 (the library in which this font-handling code is was updated since then)?

**Comment by vslavik** [comment]
Assuming fixed, then.
