### ISSUE TITLE
Wikipedia says Poedit is shareware

### ISSUE THREAD

**Issue by rffontenelle** [vslavik/poedit#422]
[Poedit page on Wikipedia](https://en.wikipedia.org/w/index.php?title=Poedit) classifies this software as **shareware** since 2014 ([see diff](https://en.wikipedia.org/w/index.php?title=Poedit&diff=622759141&oldid=608344447)), however AFAIK a shareware doesn't share its source code, and a free software is not necessarily free as "free beer". So, should this be fixed in there?

**Comment by vslavik** [comment]
Poedit can be described as "freemium" or "open core", "shareware" is the wrong term. That said, this is not a Wikipedia bug tracker nor a free-form discussion forum, but a *Poedit bug tracker*. Please limit its use to reporting Poedit issues and use appropriate channels for anything else.

**Comment by fitojb** [comment]
@rffontenelle  Two things you should know about Wikipedia:

https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest (no editing about one’s own things)
and
https://en.wikipedia.org/wiki/Wikipedia:Be_bold (it’s a free encyclopedia. Instead of asking things to be changed, just do it yourself).

**Comment by rffontenelle** [comment]
@vslavik I will. Thanks for the info.

@fitojb Thanks, I knew about guidelines and I was planning to fix it. I just wasn't sure about the correct term.
