### ISSUE TITLE
Delete new added string

### ISSUE THREAD

**Issue by ankushkatiyar** [vslavik/poedit#427]
I have 2 po files ,first contain approx 1000 and 2nd contains approx 4000 strings and these 1000 commin in both,first po file is not translated ,2nd translated ,so I want to put translated content from 2nd file to 1st file but dont aant to add new string from 2nd to 1st,is there any way for do this ?

**Comment by vslavik** [comment]
Please don't carpet-bomb all support channels if you don't get a reply *within an hour*.

You already asked this at help@poedit.net. Besides, this is a *bug tracker*, not a forum for ill-described questions.
