### ISSUE TITLE
.svg of the new appicon?

### ISSUE THREAD

**Issue by maltris** [vslavik/poedit#428]
Hello,

do you still provide a .svg-File of the App-Icon (https://github.com/vslavik/poedit/blob/master/artwork/linux/appicon/48x48/apps/poedit.png) ? I would like to update it on Wikimedia (https://commons.wikimedia.org/wiki/File:Poedit_1.5_icon.svg).

Regards

**Comment by vslavik** [comment]
There is no SVG version.

There is no "app icon" (singular) either, but three platform-specific icons for platform-specific styles.

(Please don't misuse this *issue tracker* for questions and respect the instructions at https://poedit.net/support)
