### ISSUE TITLE
How can I add *.ctp to PHP extractor?

### ISSUE THREAD

**Issue by gonzela2006** [vslavik/poedit#429]
Hello,

How can I add *.ctp to PHP extractor? I can't edit the PHP extractor to add *.ctp extension like before

Thanks

**Comment by gonzela2006** [comment]
.ctp extension is for CakePHP template files

**Comment by vslavik** [comment]
This is a *bug tracker*, not a questions forum. Please respect the instructions at https://poedit.net/support

You can add extensions trivially in the extractors settings — did you even try? That won't, of course, make Poedit magically recognize a non-PHP template language.

**Comment by gonzela2006** [comment]
Ok, thank you
