### ISSUE TITLE
FIX Warning Poedit

### ISSUE THREAD

**Issue by marketfarsi** [vslavik/poedit#431]
Hi there I have problem with "?" mark when i Translate word with "?" end - need to translate and change for RTL lang to "؟" but at save have error. that told Translation end with "؟" but Source end with "?". I use last Version.Please if you can fix this in next update.

**example:**

**Source:**
"How long are license keys valid for?"

**Translate:**
"کلید مجوز چه مدت معتبر است؟"

**Comment by vslavik** [comment]
When you created this issue, you were asked to read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) first. Please do so. The text above is incomprehensible and vague and lacks many information that you were explicitly asked to provide.

**Comment by vslavik** [comment]
Also: please do not spam every available channel with the same thing when you don’t receive a reply within a few minutes. Such behavior is inconsiderate, rude and absolutely inappropriate when you got something for free.

**Comment by vslavik** [comment]
Closing as outdated.
