### ISSUE TITLE
Extracting from twig macro don't work properly 

### ISSUE THREAD

**Issue by Huvik** [vslavik/poedit#432]
When trying to extract from twig macros, only first string is extracted
`
{{ contact.box(__('String1', 'domain'), __('String2', 'domain')) }}
`
Only `String1` is extracted to po file, second is ignored. I am using Poedit 2.0.3 paid version and macOS 10.12.6. I tried New Wordpress translation or create catalogue and update from source.

**Comment by vslavik** [comment]
This is already fixed for inclusion in 2.0.4.

**Comment by Huvik** [comment]
And when will be 2.0.4 out? Thx for response

**Comment by vslavik** [comment]
> And when will be 2.0.4 out?

Now.
