### ISSUE TITLE
Un-flip some (or all) icons on the main window

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#435]
Current RTL icons:
![default](https://user-images.githubusercontent.com/18016656/30776985-85880c0c-a0b9-11e7-963d-9b4b333c545a.png)

vs. current LTR icons:
![default](https://user-images.githubusercontent.com/18016656/30776988-979c6b4a-a0b9-11e7-9238-55683da7f319.png)

1. The pencil: most RTL users are right handed (and correct me if I'm mistaken- also LTR users?).
See [this link](https://material.io/guidelines/usability/bidirectionality.html#bidirectionality-rtl-mirroring-guidelines) in "when not to mirror", 3rd paragraph.
2. The blank page and the green plus sign: I kinda like the current RTL implementation, but it should match the Update button on the toolbar. See #434. If you're going to flip the entire Update icon, this one should stay as-is for RTL, and the LTR version should get flipped.
3. 'W' for "WordPress": This is quite self explanatory.
4. The collaborate icon: I don't think it matters here if to RTL or not. I wouldn't mind in any case.

**Comment by vslavik** [comment]
Can you please spell out clearly what I should do in all (five, with #434) cases? 3. and 4. are clear, but I'm not entirely sure what you think is needed for 1+2... TIA!

(To explain: mirroring is automatic in Windows, it takes an extra step to prevent it. I simply failed to think about RTL considerations [again]...)

**Comment by ItielMaN** [comment]
Here's what I think should be done:

1. For RTL users: should look like current LTR implementation (as shown in the first comment).
For LTR users: if most LTR users are indeed right handed (as stated [here](https://material.io/guidelines/usability/bidirectionality.html#bidirectionality-rtl-mirroring-guidelines) in "when not to mirror", 3rd paragraph), the icon is okay as-is.
2. I don't think there's any direction in this icon, so I'd apply current RTL implementation for both RTL and LTR (that's for making your life less horrible for when you'd fix issue number 5 :) ). 
5. The Update icon: the white page icon in it should match whatever you'll decide on issue number 2 (for consistency), but in any case, the 'reload' part in the icon should always (RTL and LTR) be clockwise.
