### ISSUE TITLE
Translating between English "," and Japanese "、"

### ISSUE THREAD

**Issue by chason** [vslavik/poedit#436]
These characters represent the same function, but the Japanese one has a space after the comma built in. I am getting a warning in POEdit because my English source has a space at the end, but it does not see the Japanese character as including a space. Here is the source in question:

#: web/templates/web/settings.html:23
msgid "Before disconnecting from Facebook, "
msgstr "Facebookから切断の前に、"

**Comment by chason** [comment]
Ah, I should mention that the specific error I'm getting is:
> The translation should not end with "、".

**Comment by vslavik** [comment]
Closed in favor of #437.
