### ISSUE TITLE
False positive punctuation warnings for Persian

### ISSUE THREAD

**Issue by arashm** [vslavik/poedit#438]
The linter throws wrong warning regarding locale specific characters. For example in Persian/Arabic a question mark looks like this: `?`. The linter should be locale agnostic and do not make such false warning.

![question_mark](https://user-images.githubusercontent.com/849640/31046513-9bd7985e-a606-11e7-85e2-3cc182486393.png)

**Comment by vslavik** [comment]
When you created this issue, you were asked to read `SUPPORT.md` file and follow the instructions therein. Please don't ignore such instructions. Specifically, make sure you're actually using the latest version before filing a bug — that's just common sense, really.

This is already fixed in 2.0.4 via 536360ca3cbc4172b60714745a489cd5c565c9b1.

**Comment by arashm** [comment]
Thanks for the reply. Sorry for not following the guide lines and mentioning the Poedit version (I suggest adding the `issue_template.md` file too, [here's the docs](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)). I'm indeed using the latest `2.0.4` version provided in Archlinux repositories.

The commit you mentioned is specific to Arabic, while I mentioned Persian (which is my language). Maybe changing it to `else if (m_lang == "ar" || m_lang == "fa")` would help in this case.

Thank you.

**Comment by vslavik** [comment]
> (I suggest adding the issue_template.md file too, here's the docs)

You're being off-topic, but he sort that ignores instructions typically ignores templates as well. Let's not blame this project or GitHub UI for that.

> The commit you mentioned is specific to Arabic, while I mentioned Persian (which is my language). 

See what being vague (you claimed Arabic *is* affected in your version, which is untrue) and not providing reproduction steps or files (which would clarify that when you're talking about fa/ar, what you *actually* mean is fa only) does? 

> Maybe changing it to else if (m_lang == "ar" || m_lang == "fa") would help in this case.

Maybe submitting a PR to that effect would help even more… Failing that, at least real-life reproduction PO files as requested.

**Comment by arashm** [comment]
> Maybe submitting a PR to that effect would help even more…

I don't have any experience with C programming language, so I cannot test, or I would provide a PR for sure. [Here's real-life a sample PO file](https://l10n.gnome.org/POT/polari.master/polari.master.fa.po). Hope this works for you now.
