### ISSUE TITLE
Allow to edit (change/delete) local translation memory

### ISSUE THREAD

**Issue by ptrg** [vslavik/poedit#439]
Sometimes there are typos in msgid and/or msgstr strings. These false strings takes place in TM and may lead to select an incorrect translations again and again (mostly when using automatic translation). Also they are annoying...

So changing or deleting them should be a good option.

(If my memory is right a similar issue were reported in the past, but I can't find it.)

**Comment by vslavik** [comment]
> a similar issue were reported in the past

Sounds like a good reason not to file it again, no? There's a search box in the issues, take under a second to find #290.

**Comment by ptrg** [comment]
Thanks!
