### ISSUE TITLE
Enter is not handled in Find field on macOS

### ISSUE THREAD

**Issue by godzillante** [vslavik/poedit#440]
[RETURN] key should be enabled after typing terms in the search box.

**Comment by vslavik** [comment]
It of course is.

When you created this issue, you were asked to read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md). You seem to have though you are special and this doesn't apply to you, but you are not and it does. If you believe there's a bug, follow the instructions and provide a usable bug report. But this isn't one.

**Comment by godzillante** [comment]
It isn't on MacOS.

Also, please be less arrogant when someone reports a bug. This is a translation tool, not the Linux kernel, and you are not Linus Torvalds.

**Comment by vslavik** [comment]
@godzillante In a display of notable *arrogance* and self-centeredness, you don't bother with even the tiniest of courtesies of respecting the instructions, but then feel the need to preach to *other* people about arrogance. You're *way* out of line here.

This is indeed not Linux. What this *is* is 20 years of work that you got for free. I owe you nothing — I already gave you plenty. You might want to ponder that next time you feel like opening your mouth to attack an Open Source maintainer.
