### ISSUE TITLE
Failure merge between two file .po

### ISSUE THREAD

**Issue by alessandromacchi** [vslavik/poedit#441]
Hi!
I'm trying to do a merge between this two file. I open the first.po and then I try the merge with the second.po
I don't know why don't work, any ideas?
I attach the file in question
Thanks!

[file_po.tar.gz](https://github.com/vslavik/poedit/files/1379842/file_po.tar.gz)

**Comment by vslavik** [comment]
Please read and follow [this](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) as you were asked when you created this issue.

> I don't know why don't work, any ideas?

I can't read your mind and you literally provided no information, so that would be no.
