### ISSUE TITLE
View → Entries with Errors First doesn't refresh order if there are only warnings

### ISSUE THREAD

**Issue by c72578** [vslavik/poedit#443]
The View - "Entries with Errors First" is only working after saving a file.

How to reproduce:
- Open a .po file with some "errors" in Poedit 2.0.4 (e.g. the current App strings de_DE.po of Poedit from Crowdin)
- Click on View - "Entries with Errors First"
- No effect, even if disabled/enabled multiple times
- The entries with errors are not shown first
- Save the file or save it under a different name
- As soon as the file has been saved, the "Entries with Errors First" are shown first
- As long as this file is not closed, the View - "Entries with Errors First" is working. It can be enabled and disabled and does what it is supposed to do
- As soon as this file is closed an reopened, it is not working any more.

Poedit version: 2.0.4
Tested under OS: Windows 7 and Linux (Fedora 26)

**Comment by vslavik** [comment]
>  "Entries with Errors First" is only working after saving a file.

…or validating. That's when errors and warnings are detected, yes.

**Comment by c72578** [comment]
In case of validating the behavior is the following:

- Enable: View - "Entries with Errors First"
- Click on: Validate
- The entries with errors are not shown first yet
- Disable: View - "Entries with Errors First"
- Enable: View - "Entries with Errors First"
- Now the "Entries with Errors First" are shown first.

- Expected behavior:
Show entries with errors first, as soon as validate has been completed, when this is enabled under  View - "Entries with Errors First"

**Comment by vslavik** [comment]
Sorry, I still can't reproduce this.

Can you please provide more detailed reproduction instructions? I.e. provide a sample PO file, information about your View menu settings and detailed steps from the moment you launch Poedit (incl. how you launch it: normally, by opening a file, …).

**Comment by c72578** [comment]
Detailed steps:
- Start Poedit
- File - Open...
- Select de_DE.po
  This is the current German translation of Poedit, downloaded from Crowdin and attached here:
[de_DE.zip](https://github.com/vslavik/poedit/files/1517113/de_DE.zip)
- Click on Open
- Click on Validate

Screenshot of View menu settings:

![screenshot_view](https://user-images.githubusercontent.com/371551/33422481-1e11a498-d5b6-11e7-9c24-acff494ab444.png)

**Comment by vslavik** [comment]
Ah, I (think) I see — the crucial bit is that there are not errors, but there are warnings.

**Comment by c72578** [comment]
Yes, exactly.
