### ISSUE TITLE
The Translation should end with '%'.

### ISSUE THREAD

**Issue by andreaplanet** [vslavik/poedit#454]
Just a comment:

With the %d%% translated into %%%d I get the warning "The Translation should end with '%'." (PoEdit 2.0.5 on Windows). I understand it checks for special characters at the end of the translations like "Hello World!" miss the ! in "Hallo Welt".
![translationshouldendwithpercentage](https://user-images.githubusercontent.com/3232744/34872454-2c02ed58-f791-11e7-90bf-8104716c43ab.PNG)

**Comment by vslavik** [comment]
It's only a *warning* about a *potential* issue, not an error.

If you think it's important to get this right for Turkish, please submit a PR; I think it's not worth a hassle for something that is bound to affect only a minuscule number of strings.

P.S. The name's "Poedit" ;)
