### ISSUE TITLE
Unable to look at sources

### ISSUE THREAD

**Issue by christian-panel** [vslavik/poedit#455]
Linux - French Version  (Ubuntu 14.04 LTS):
-Unable to look at sources from poedit (a view with one blank line appear only)
-Two menus appears with the same command (it seems) : Fichier|Quitter and Fichier|Quit

Windows - French Version (Win10):
Found no way for the quotation marks to appear like in Unix version.

**Comment by vslavik** [comment]
Please read [this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and then file separate issues, *one per one issue*, that actually contain enough information to a) understand what you mean and b) reproduce. 

This lacks even the barest minimum of necessary information such as version numbers (only bugs confirmed in the latest version are of interest) or even approximate steps to reproduce. For example, I have absolutely no idea what could you possible mean by "Found no way for the quotation marks to appear like in Unix version."
