### ISSUE TITLE
Flaptak package

### ISSUE THREAD

**Issue by bil-elmoussaoui** [vslavik/poedit#456]
Hey,

I have been trying to create a [flatpak](https://flatpak.org/) package. Everything works as expected except that Boost version is not detected correctly. 

I would like to know if one the devs/contributors would love to help to get this done?
This will allow the users to install Poedit on any platform without having to worry about any dependencies problems.

Here's the link to my PR to add Poedit. https://github.com/flathub/flathub/pull/243

If you have any questions, let me know.

Thanks

**Comment by vslavik** [comment]
This is not an *issue*; you could have sent a FYI email instead…

I have my own packaging plans that conflict with this, sorry.
