### ISSUE TITLE
Update dialog doesn't react on keyboard

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#457]
Poedit 2.0.5
Windows 10.0.16299.192

When a new version of Poedit is released, I can say "Yes" to download it. After downloading, the dialog looks like this:

![image](https://user-images.githubusercontent.com/3233724/35541798-e003b728-055c-11e8-8599-9cd82e911806.png)

Pressing Enter does nothing.
Pressing Space downloads again.
Pressing Escape does nothing.
Pressing Tab does nothing.

After pressing Alt+Tab twice to switch applications, the border around the button has disappeared:

![image](https://user-images.githubusercontent.com/3233724/35541861-37f0b422-055d-11e8-9b2c-e5158a9f208f.png)

The keys mentioned above still do the same as before.

Funnily, trying to press random keys, I pressed Alt+Space and landed in the System menu. From there, I can resize and even maximize the window although no corresponding buttons are shown in its title bar. But still no way of reaching the button by keyboard alone since the button doesn't have a mnemonic.

When trying to reproduce the above paragraph, only resizing worked, but not maximizing. Strange …

Trying it again, the initial dialog is also not usable by keyboard. Pressing Space closes the dialog, and the other keys do nothing.

![image](https://user-images.githubusercontent.com/3233724/35542171-d7f353f2-055e-11e8-9191-10df9776247c.png)

Same picture here: Initially the `Update installieren` button has a border, after switching applications with Alt+Tab the border disappears.

Well, I think I'll have to use the mouse then for clicking the buttons. :)

**Comment by vslavik** [comment]
This is a WinSparkle rather than Poedit bug. Fixed over there, thanks for reporting!
