### ISSUE TITLE
Worming!  during install poedit 2.0.6 from git on linux mint 18.3

### ISSUE THREAD

**Issue by avma** [vslavik/poedit#458]
Hi,
 After ruing ./configure (Followed the instructions on README) I received the following worming message:

>  Configured poedit-2.0.6 for x86_64-pc-linux-gnu
Enabled features:
    * debug build:                         no
    * language detection:             no
    * crowdin integration:             yes

    !!! WARNING !!!

    Your are building a limited version of Poedit without some important
    features (see above). This makes Poedit harder to use and is strongly
    advised against.

    !!! WARNING !!!

What am I missing/doing wrong? how can I fix this?

Many thanks

Avi

**Comment by c72578** [comment]
You are building without language detection.
For this you need cld2 (Compact Language Detector 2).

**Comment by avma** [comment]
yup, true... 
I had **libcld2**-0 but not **libcld2-dev**
Thanks, it worked after adding it ;)
