### ISSUE TITLE
Don't save: Add accelerator

### ISSUE THREAD

**Issue by Fonata** [vslavik/poedit#459]
When exiting Poedit after changing things in the .po file, the question to save changes comes up.

I pressed "n" out of my habit of answering such windows with the keyboard. May programs offer this, e.g. this one:
![image](https://user-images.githubusercontent.com/6819464/37000092-866de20c-20c2-11e8-9552-9cbad0b6571b.png)

Maybe adding a `&` character in front of the "n" is enough to get it to work as an accelerator key.

**Comment by vslavik** [comment]
> Maybe adding a & character in front of the "n" is enough to get it to work as an accelerator key.

It indeed is. Pull request please?

**Comment by Fonata** [comment]
Alright, challenge accepted! I’m working on a pull request.
