### ISSUE TITLE
Messy error msg displayed when str check failed under zh_CN.UTF-8 env (wrong encoding?)

### ISSUE THREAD

**Issue by hosiet** [vslavik/poedit#461]
Downstream report (Debian): https://bugs.debian.org/892875

Using poedit 2.0.6 on Debian unstable.

The following procedures could reproduce the problem:

1. Enable zh_CN.UTF-8 locale
2. Install any CJK fonts on system (fonts-noto-cjk for example)
3. Open a random PO file with poedit under zh_CN.UTF-8 locale
4. (Wrongly) edit translation so that the check would fail
   For example, deliberately translate a %ld to %lu which would
   cause a mismatch.
5. Save the file.

In this way, messy error message would appear in poedit window.

A screenshot is provided. (Pay attention to the red parts)

![](https://i.loli.net/2018/03/14/5aa8823a50631.png)

**Comment by vslavik** [comment]
Please always the current state of `master` first: 51612c40fa814ef02b9aaad68737a76d463f46cd
