### ISSUE TITLE
Setup Travis CI for auto-build AppImage (portable binary packages for Linux)

### ISSUE THREAD

**Issue by Symbian9** [vslavik/poedit#466]
Propose setup `master` branch to produce auto-builds using Travis CI as `*.AppImage` package -- universal portable package format for most of Linux distributions.

* http://github.com/AppImage/AppImageKit
  * https://github.com/probonopd/linuxdeployqt
  * https://github.com/probonopd/uploadtool

Firstly, you need setup `.travis.yml` script in the root of `master` branch, for example:

* https://github.com/probonopd/linuxdeployqt/blob/master/.travis.yml
* https://github.com/leozide/leocad/blob/master/.travis.yml
* https://github.com/Symbian9/azpainter/blob/master/.travis.yml

@probonopd, please, help @vslavik to solve this task! ;-)

P.S.: Known apps that already provide AppImage's listed on *AppImageHub*

* https://appimage.github.io/apps

### NOTE

As *Poedit* is very important tool for translators and program development providing latest version of it as AppImage portable package could solve "slow repository updating" issue.

- https://repology.org/metapackage/poedit/versions

**Comment by probonopd** [comment]
> @probonopd, please, help @vslavik to solve this task! ;-)

Happy to help; please let me know if you are running into any issues given the description above.

**Comment by probonopd** [comment]
Basically 

https://github.com/vslavik/poedit/blob/0fe9e0d867fe532bd31e9a47b0dd179373574f91/.travis.yml#L48 

would need to be replaced by something along the lines from

https://github.com/probonopd/audacity/blob/AppImage/.travis.yml, like

```
  - time ./configure --prefix=/usr
  - time make -j$(nproc)
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - wget -c -q "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
```

Now, due to 

https://github.com/vslavik/poedit/blob/0fe9e0d867fe532bd31e9a47b0dd179373574f91/.travis.yml#L16

we need to do some extra shenanigans in order to make the AppImage compatible with somewhat more mature systems like Ubuntu 14.04.

```
  - # Workaround to increase compatibility with older systems; see https://github.com/darealshinji/AppImageKit-checkrt for details
  - mkdir -p appdir/usr/optional/ ; wget -c https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/exec-x86_64.so -O ./appdir/usr/optional/exec.so
  - mkdir -p appdir/usr/optional/libstdc++/ ; cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ./appdir/usr/optional/libstdc++/
  - ( cd appdir ; rm AppRun ; wget -c https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/AppRun-patched-x86_64 -O AppRun ; chmod a+x AppRun)
  - ./linuxdeployqt*.AppImage --appimage-extract
  - export PATH=$(readlink -f ./squashfs-root/usr/bin):$PATH
  - ./squashfs-root/usr/bin/appimagetool -g ./appdir/ $NAME-$VERSION-x86_64.AppImage
```

**Comment by vslavik** [comment]
I have plans for upstream packaging; I don't have plans for using AppImage and presently don't intend to do any work in that direction myself.

That said, if you feel strongly about it, you're welcome to submit a PR and I'll consider it. A well-written, reasonable (which includes not being dependent on Travis, but using some standard-ish method of building, such as using Docker to get a suitably ancient base OS image), *tested* PR would be hard to argue with.

**Comment by Symbian9** [comment]
> I don't have plans for using AppImage and presently don't intend to do any work in that direction myself.

If you don't intend to do any work in that direction yourself, we can help you do it (as pull requests to `.travis.yml`).

I very interested in `Poedit-2.*.AppImage` builds because like portable apps. Don't like apps that for install it from repository require messy dependency (that could fully broke my system) and need root access.

**Comment by Symbian9** [comment]
MX Linux team start working on backporting, firstly need backport wxWidgets 3.0.3, because it still not available for Debian 9 "Stretch"...

- https://forum.mxlinux.org/viewtopic.php?f=55&t=44733

And looking on this packaging/backporting progress (need not only backport Poedit 2.x, but all related dependency...), I can say -- AppImage is fully must-have option as alternative to this "repository packaging issue".

**Comment by vslavik** [comment]
> as pull requests to .travis.yml

As I said, I don't consider Travis-dependent way of building them useful. 

> I can say -- AppImage is fully must-have option

Let's agree to disagree on that.

**Comment by xmha97** [comment]
+1
