### ISSUE TITLE
% Complete is Unclear

### ISSUE THREAD

**Issue by raz0rknaif** [vslavik/poedit#467]
Currently, the % complete is calculated according to how many strings are translated and untranslated, but many of the strings in my project are one word, and some are quite long. I would just like a more realistic calculation.

**Comment by vslavik** [comment]
That you would prefer a different calculation doesn't make the percentage "unclear", nor would a different, e.g. character based, approach be "more realistic" — just different.

I consider the current implementation reasonable, but if you feel strongly about the need to improve it, please do so and submit a PR — I'm happy to merge it provided it is well-written (I can help you with that) and that it includes a reasonable justification for the change (i.e. in a little bit more detail/specifics/rationale that the single sentence above).

**Comment by raz0rknaif** [comment]
I'm a translator, so no PR from me, sorry. But maybe I can explain better...

**Comment by raz0rknaif** [comment]
I hope you understood what I was communicating, and there is no need to be
insulting.
