### ISSUE TITLE
xgettext extraction option '--no-location' doesn't works on Windows

### ISSUE THREAD

**Issue by vaites** [vslavik/poedit#473]
We use the `--no-location` option (to avoid conflicts in Git with line numbers) on macOS without problems but in Windows doesn't work.

**Comment by vslavik** [comment]
It of course does work.

If you believe otherwise, please do read the [document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) you were asked to read, instead of ignoring it. In particular, pay attention to point 3 and the linked article.

**Comment by vaites** [comment]
No, it doesn't work. 

Sorry, didn't readed the document, so here are de details:

1. We are using the latest version on both operating systems (2.0.7)
2. We use `--no-location` option as detailed in gettext manual ([5.1.7 Output details](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html#Output-details))
3. Adding `--no-location` option in advanced extraction options on the PO file works on macOS but doesn't works in Windows
4. I attach the example PO file (zipped)
5. I attach the example PHP file (zipped)

To reproduce the problem, just open the PO file with PoEdit for Windows, update from sources, save it and will see the comments (`#: test.php:1`)

Test files: [poedit.zip](https://github.com/vslavik/poedit/files/1987707/poedit.zip)

**Comment by vslavik** [comment]
> To reproduce the problem,

You didn't provide full reproduction information. OS versions, your environments description, your *Preferences → Extractors* settings (that are evidently relevant to an *extraction* issue) to name some. The point of that article from 3 is to reason about the issue and identify *all* differences in environments. Ask yourself: what is more reasonable assumption to make, that a thing unrelated to platform, in the same software, behaves radically differently for no apparent reason, or that you have some difference in environment explaining it? 

> Test files: poedit.zip

Verified that everything unsurprisingly works as it should on Windows. My guess would be that you have a custom extractor for PHP defined on one of the machines, but not the other (and undisclosed here) which is taking precedence and causing this.

**Comment by vaites** [comment]
You're right: there was custom extractors for PHP defined in the windows machine and none in macOS machine (I disabled it and works OK) but there are more (Java, Perl, Python...). I assume this custom extractors was added by PoEdit time ago, because we didn't added it.

Sorry for wasting your time.

**Comment by vslavik** [comment]
The only reason for custom extractors to be there is that you modified (i.e. customized) them in the past. If you don't want them, or don't know/remember why they are there, don't disable them, *delete them*.
