### ISSUE TITLE
The Monospace font text unable to be aligned

### ISSUE THREAD

**Issue by wsxy162** [vslavik/poedit#475]
Poedit: 2.0.7
OS: openSUSE Tumbleweed 20180511

![2018-05-14 04-14-54](https://user-images.githubusercontent.com/6559703/39971456-fbf45f1e-572d-11e8-9e29-af237b2e047c.png)
Testing text:
abcdefghijklmnopqrstovwxyzabcdefghijklmnopqrstovwxyzabcdefghijklmnopqrstovwxyzab
一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十

These two paragraphs of text are all 80 word-width. When setting a monospace font for the text box, I expect that the characters and letters are strictly aligned (In monospace, Chinese characters full-width and English letters are half-width). But the result isn't.

**Comment by vslavik** [comment]
> I expect that the characters and letters are strictly aligned

Your expectation [is not reality-based](https://denisbider.blogspot.cz/2015/09/when-monospace-fonts-arent-unicode.html) and you probably won't see it aligned in your browser either:

```
abcdefghijklmnopqrstovwxyzabcdefghijklmnopqrstovwxyzabcdefghijklmnopqrstovwxyzab
一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十
```

In any case, this has nothing to do with Poedit, which uses system-provided text control and does not do its own text rendering (that would be crazy). Feel free to complain to SUSE, GTK+ and/or Pango developers, or to the provider of whatever font it is that you're using.

**Comment by wsxy162** [comment]
I have gedit and gnome-terminal setting with a monospace font, that they work quite well. 
![2018-05-14 21-59-43](https://user-images.githubusercontent.com/6559703/40002156-7254436a-57c2-11e8-862b-27147dc01a49.png)
![2018-05-14 22-01-52](https://user-images.githubusercontent.com/6559703/40002164-76e45654-57c2-11e8-9fb0-de7943ba6ed4.png)
Don't know what kind of magic have they do.

**Comment by vslavik** [comment]
Again, Poedit uses a GTK+ control. It doesn't render text on its own, there's no way it could magically affect text rendering. You're probably seeing a difference in font chosen or GTK+ major version used.
