### ISSUE TITLE
Termplate name not translatable

### ISSUE THREAD

**Issue by alleknalle** [vslavik/poedit#478]
Hi Vslavik,

I posted the following comment yesterday on https://github.com/vslavik/poedit/issues/404
---------------------------------
how does this actually work? When I'm creating .POT file from my theme I don't see the template names in there?

I've got a template file which starts with:
```
<?php
/**
 * Template Name: Township overview
 */
```

but I don't see 'Township overview' in the .POT file.
----------------------------------

You responded that it's a PRO feature, but I have a PRO license and it still doesn't work.

**Comment by vslavik** [comment]
Please see https://poedit.net/support for Pro support — send email to help(at)poedit.net, preferably from in-app Help menu to include basic information about your version+license, include details of what you're doing, which remains unclear form this.

This is the open source bug tracker, not support forum.

**Comment by vslavik** [comment]
@alleknalle It would help if you wrote your emails form an address where you actually read your replies:

```
Dit emailadres wordt niet gelezen. Bel naar kantoor of stuur een mailtje naar het contactpersoon.
This email will not be read. Call to our office or send an email to your contact person.
```
