### ISSUE TITLE
"Needs work" toggle button should appear on the left side of the text

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#480]
Nothing much to exaplain I think, the toggle should be on the left and the "Needs work" on the right, on RTL locales.

![default](https://user-images.githubusercontent.com/18016656/40443817-1c31e4dc-5ed0-11e8-82b5-dd23c2b5f028.png)

**Comment by vslavik** [comment]
Thanks! I'm surprised it isn't, such things are supposed to get mirrored automatically…

P.S. There are Labels on the GitHub sidebar, you can use them to tag with RTL instead of prefixing the subject.

**Comment by ItielMaN** [comment]
Yeah I know, I thought about it, but as a newbie here I don't find how to do that :(
I found this article:
https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/
But this applies only to the repository owner (I think). And.. sorry about the off-topic. ^^

**Comment by vslavik** [comment]
> Yeah I know, I thought about it, but as a newbie here I don't find how to do that :(

Apparently you indeed can't and what you're doing is the only way to pre-tag issues. Sorry for the noise :(

**Comment by vslavik** [comment]
It looks like anything rendered with `wxGraphicsContext` is not mirrored when it should. 

The only other notable thing is the statistics window — can you confirm the bar should be mirrored too? It's semantically a progress bar (albeit with more colors), so I think it should fill up from the right too, right?

**Comment by ItielMaN** [comment]
> so I think it should fill up from the right too, correct?

That's right.

**Comment by ItielMaN** [comment]
> The only other notable thing is the statistics window — can you confirm the bar should be mirrored too? It's semantically a progress bar (albeit with more colors), so I think it should fill up from the right too, correct?

Should I open a new issue for that?
Not sure if you've already fixed it or not.

**Comment by vslavik** [comment]
> Should I open a new issue for that?

No need, I already fixed it as part of #485. It's the same class of bug as this one (GDI+ *not* magically mirroring as GDI does — win32 programming is fun).
