### ISSUE TITLE
Ellipsized RTL text in the list is not aligned to the right edge

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#481]
Using Windows 10, Poedit 2.0.7.

Forgive the **terrible**, non informative title, I just couldn't find a better way to summarize this. A different wording would be appreciated.

STR:
1. Not sure if this is a PO specific issue, so here is a file for example. [index.zip](https://github.com/vslavik/poedit/files/2032415/index.zip)
2. After loading the file, simply look at the translations that overflow the table. **Most** of them don't start at the same line as the others that don't overflow.

This is visible also when switching to RTL locale, but for the source text.

![default](https://user-images.githubusercontent.com/18016656/40444683-a44a42b8-5ed2-11e8-92a8-59efc5215358.png)

**Comment by vslavik** [comment]
Confirmed with Poedit's own `he.po` on long lines.

Doesn't happen on macOS.

Note to self: this is wxDVC rendering issue, it occurs even on strings that are too short to be trimmed in Poedit's own code.

**Comment by ItielMaN** [comment]
Did you fix this also for LTR text, on the Source Text column, when Poedit's locale is RTL?
![default](https://user-images.githubusercontent.com/18016656/40835189-636d0a30-659b-11e8-9277-af4b3c869031.png)

**Comment by vslavik** [comment]
> Did you fix this also for LTR text, on the Source Text column, when Poedit's locale is RTL?

I thought I did — it's the exact same situation mirrored at rendering level. *But* it actually isn't, because the source column has markup in it and so is rendered differently. That's a whole other can of RTL worms: #343
