### ISSUE TITLE
Moving cursor in Source text and Translation fields makes the cursor flicker from selection pointer to I-beam pointer, after right clicking

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#483]
Using Windows 10, Poedit 2.0.7.

STR:
1. Open any PO file
2. In the Source text or Translation field, move the cursor around -> normal behaviour
3. Right click in this field and move the cusor around -> the cursor flickers rapidly from the selection pointer to the I-beam pointer

![screencast](https://user-images.githubusercontent.com/18016656/40445801-dbfc04be-5ed5-11e8-86dc-84c780f4e955.gif)
(The flicker is actually much faster in real time)

**Comment by vslavik** [comment]
I think this and #484 will turn out to be one and the same.

> Windows 10

I can reproduce this myself too, but can you provide your exact Windows 10 version for reference (Settings → System → About)? Mine is 1803. I have a suspicion that this is new...

**Comment by ItielMaN** [comment]
> I think this and #484 will turn out to be one and the same.

Me too, but as you [like to keep different bugs in different issues](https://github.com/vslavik/poedit/issues/255#issuecomment-200266262).. :)

> I can reproduce this myself too, but can you provide your exact Windows 10 version for reference
> (Settings → System → About)? Mine is 1803. I have a suspicion that this is new...

Same here.

**Comment by vslavik** [comment]
This is a bug in wx… [created by me](https://github.com/wxWidgets/wxWidgets/commit/cad2b9cbfdc3804bd66d38957cab6cd4180f8d04) in 2014. https://github.com/wxWidgets/wxWidgets/commit/bd650ec3d9124939f7f514402b1ac243377a4e0e is loosely related, but not directly causing it.

This only manifests itself if you *dismiss* the popup menu — if you choose a menu item there, e.g. *Select all*, things behave normally afterwards.

I was also probably wrong about the relation to #484, see my comment over there.
