### ISSUE TITLE
The cursor that appears when hovering the right click menu of unrecognized words is not the right one

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#484]
Windows 10, Poedit 2.0.7.

STR:
1. Open any PO file
2. In the translation, start typing words that do not exist
3. Right click one of these words
4. Hover the context menu
5. The cursor is an I-beam one, and not a selection pointer (as opposed to, say, if you right click somewhere blank on the Translation field and hover on the resulting context menu)

![default](https://user-images.githubusercontent.com/18016656/40446120-dbbd234c-5ed6-11e8-8f07-58270d91ad19.png)

**Comment by vslavik** [comment]
Rather amazingly, this seems to be a bug in richedit control that wxWidgets [goes to great lengths to undo](https://github.com/wxWidgets/wxWidgets/blob/4fcc6e15b07b78f54d9783b6d940d12ec4640627/src/msw/textctrl.cpp#L2260):

> rich text controls seem to have a bug and don't change the cursor to the standard arrow one from the I-beam cursor usually used by them even when a popup menu is shown (this works fine for plain EDIT controls though), so explicitly work around this

For the same reasons explained in #482, I don't have direct control over the menu in spellchecking case and am unable to intercept it and correct the cursor.

**Comment by ItielMaN** [comment]
This is still an issue in 2.0.8. Same STR as before.

**Comment by vslavik** [comment]
I tagged & closed this one by mistake. As stated above, this is native behavior of the native control in a place where I have zero control over it. 

IOW, yes, it wasn't fixed in 2.0.8, but I'm keeping it closed. Nothing I can do about it — except the nuclear option as described in #482, so it's enough to keep that one open for it.
