### ISSUE TITLE
[RTL] Hardcode the percentage parts in Statistics to LTR

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#485]
![default](https://user-images.githubusercontent.com/18016656/40495464-edf3ab4a-5f7f-11e8-8ece-4a1c3def2f47.png)
The order of reading of a number and then the percentage sign is read from left to right, also on RTL languages.

**Comment by ItielMaN** [comment]
> Are you saying that the text should be e.g. "60 (98 %)" and not "(% 98) 60"

Yes.

> but otherwise the columns are OK?

Also yes.

**Comment by vslavik** [comment]
Fixed, thanks!
