### ISSUE TITLE
When directly opening an MO file, the string "MO files can’t be directly edited in Poedit." does not appear in its localized version

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#487]
Using Windows 10, Poedit 2.0.7.

![default](https://user-images.githubusercontent.com/18016656/40590180-41f3d87a-6203-11e8-814b-7976f0f57bd7.png)
This is what I get when I directly open an MO file.
Same for if I switch over to a different language (tested on Spanish, Arabic, Hebrew, German, Russian).
Also notice the corrupted "ג€™" text there.

I'm using the Hebrew localized version of Windows btw.

**Comment by vslavik** [comment]
This was already fixed in 76c77856534a5880ec9d48f6cc4c59acc7408ca2 post-2.0.7.
