### ISSUE TITLE
gettext build fails on macOS due to invoking aclocal

### ISSUE THREAD

**Issue by l2dy** [vslavik/poedit#488]
https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/61148

```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8/build/Deps.build/Release/_intermediate/gettext/build-aux/missing aclocal-1.15 -I m4 -I ../gettext-runtime/m4 -I ../m4 -I gnulib-m4 -I libgrep/gnulib-m4 -I libgettextpo/gnulib-m4
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8/build/Deps.build/Release/_intermediate/gettext/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[2]: *** [aclocal.m4] Error 127
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
ninja: build stopped: subcommand failed.
Command ./build_deps.sh failed with exit code 1
```

I'm not familiar with autconf, but I guess this is caused by touching `configure` too early at https://github.com/vslavik/poedit/blob/v2.0.8-oss/deps/build.ninja#L17-L20, making it older than some other files touched.

**Comment by l2dy** [comment]
- patch-deps-sdkroot.diff: set sdkroot only when provided
- patch-deps-tool-path.diff: set path of gsed and ninja
- patch-remove-sparkle.diff: disable sparkle

No patch is touching gettext files.

**Comment by l2dy** [comment]
My guess is that both `configure` and some of its input are touched in `build.ninja`, but `configure` is touched earlier, triggering a rebuild.

**Comment by vslavik** [comment]
> No patch is touching gettext files.

Well, I don't know what `org.macports.configure` does, but it's not unreasonable to expect that it might be doing something non-trivial — I'm yet to see a distro packaging toolset that *doesn't*. 

> My guess is that both configure and some of its input are touched in build.ninja, but configure is touched earlier, triggering a rebuild.

[As you can see](https://github.com/vslavik/poedit/blob/eaca3830a403222ac3303be484ef4e9d7a262002/deps/generate_build_ninja.py#L117), *output* files are touched to prevent exactly this. That "guess" is not supported by evidence.

*My* theory would be that your build environment exposes many more tools than mine does and some part of the build that doesn't run here runs for you. The answer would then be to touch more files in the above linked section. 

Unfortunately, it's unclear from [the log](https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/61148/steps/install-port/logs/stdio) just what triggers the rule. If you could run `make` with `V=1` and also `-d` (probably enough in `gettext-tools`) that would show enough information to understand what triggered the rebuild. Running make with `-j1` is best when debugging such things too for clarity.

**Comment by vslavik** [comment]
Is there some way to invoke Xcode build similarly to how you do myself (without installing macports)?

**Comment by l2dy** [comment]
> That "guess" is not supported by evidence.

True. I can't differentiate autoconf input and outout. I forgot to mention that the build fails by chance, also happened last time (v2.0.7), and *maybe* easier to reproduce on busy machines building many packages in parallel.

> Is there some way to invoke Xcode build similarly to how you do myself (without installing macports)?

Sure. By running the commands. Here's all commands called by grepping `DEBUG: system`:

```
DEBUG: system: /usr/bin/git clone --progress https://github.com/vslavik/poedit.git /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8 2>&1
DEBUG: system: GIT_DIR=/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8/.git GIT_WORK_TREE=/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8 /usr/bin/git checkout -q v2.0.8-oss 2>&1
DEBUG: system -W /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8: git submodule update --init
DEBUG: system:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8" && /usr/bin/patch -p0 < '/opt/bblocal/var/buildworker/ports/build/ports/editors/poedit/files/patch-deps-tool-path.diff'
DEBUG: system:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8" && /usr/bin/patch -p0 < '/opt/bblocal/var/buildworker/ports/build/ports/editors/poedit/files/patch-remove-sparkle.diff'
DEBUG: system:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8" && /usr/bin/patch -p0 < '/opt/bblocal/var/buildworker/ports/build/ports/editors/poedit/files/patch-deps-sdkroot.diff'
DEBUG: system: cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8" && /usr/bin/xcodebuild -workspace Poedit2.xcworkspace -derivedDataPath ./DerivedData  -scheme "Poedit" -configuration Release build INSTALL_PATH=/Applications/MacPorts OBJROOT=build/ SYMROOT=build/ MACOSX_DEPLOYMENT_TARGET=10.12 ARCHS=x86_64 SDKROOT="" GCC_VERSION=com.apple.compilers.llvm.clang.1_0 CLANG_CXX_LIBRARY="libc++" OBJROOT=/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8/build/ SYMROOT=/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_poedit/poedit/work/poedit-2.0.8/build/
```

I think you can skip the patches and replace the path with the absolute path of you checkout.

> Well, I don't know what org.macports.configure does.

Nothing, this phase is skipped. https://github.com/macports/macports-ports/blob/v2.5.0-archive/_resources/port1.0/group/xcode-1.0.tcl#L57

**Comment by vslavik** [comment]
Thanks! I'll try to reproduce with a clean checkout and `/usr/bin/git` — a difference in there could conceivably change checkout order and so timestamps.

**Comment by l2dy** [comment]
FYI, I started [a new build](https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/61151) when our Buildbot is [not busy](https://build.macports.org/waterfall), and it passed.
