### ISSUE TITLE
Show length of string being edited

### ISSUE THREAD

**Issue by LeOSW42** [vslavik/poedit#493]
Hello,

We are translating strings that are displayed in a 2 lines, 16 characters display.
A nice feature would be to display the string length (in characters) of the translation.

Léo

**Comment by vslavik** [comment]
The best way to get features that are rarely needed by most users, but that you care about, is to submit a PR, even imperfect one. Honestly, I'm unlikely to implement this myself, features useful to the other 99% users take precedence.
