### ISSUE TITLE
How to update files within multiple directories with command line?

### ISSUE THREAD

**Issue by baselbers** [vslavik/poedit#504]
Would like to add poedit as a composer dependency and update all files from multiple directories on composer update or git commit/push.

**Comment by vslavik** [comment]
@baselbers As you wish. This is a *bug tracker*. It's for handling *issues*, not for asking for support (you do have clear instructions for that on the site) or posting incoherent wishes.

The GNU gettext manual, which you didn't read and which is linked from the Help menu in Poedit, explains in detail how to use gettext tools. Read it.
