### ISSUE TITLE
Additional xgettext flags not working when updating catalog

### ISSUE THREAD

**Issue by jhogervorst** [vslavik/poedit#507]
Since a recent Poedit update, the additional `xgettext` flags seems to have no effect. I’m experiencing this issue in Poedit 2.1.1 (5418) on macOS 10.13.6 (17G65). Previously I used Poedit 2.0.8, in which it worked fine.

# Example

## test.php

```
<?php
_('Hello World');
_('Bye World');
```

## test.po

```
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2018-08-18 11:17+0200\n"
"PO-Revision-Date: 2018-08-18 11:17+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: en_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.1.1\n"
"X-Poedit-Basepath: .\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Poedit-Flags-xgettext: --add-location=file --sort-output\n"
"X-Poedit-SearchPath-0: test.php\n"
```

# Expected Output

When calling `xgettext` with the same two flags, I get the following output:

```
> xgettext -o - --add-location=file --sort-output test.php
...header...

#: test.php
msgid "Bye World"
msgstr ""

#: test.php
msgid "Hello World"
msgstr ""
```

Note that the entries are sorted by msgid (due to `--sort-output`), and no line numbers are shown in the comments (due to `--add-location=file`). I would expect the same output when updating the catalog in Poedit.

# Actual Output

When updating the catalog in Poedit, I get the following contents in the `.po` file:

```
...header...

#: test.php:2
msgid "Hello World"
msgstr ""

#: test.php:3
msgid "Bye World"
msgstr ""
```

Note that the entries are not sorted, and line numbers are shown.

**Comment by vslavik** [comment]
Closing as not reproducible & OP going incommunicado off-GitHub. Likely explanation: custom extractor overwriting the builtin one and messing things up.
