### ISSUE TITLE
Invalid links in about window (snap store build)

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [vslavik/poedit#515]
Reproduce steps:

1. `snap install poedit`
1. `snap run poedit`
1. Help > About
1. Click the "Acknowledgements" and "License Agreements" links

Current behavior:

Nothing happened, the following error message printed when clicking:

```
user-open error: no such file or directory
```

Also, note the tooltips of the two links:

![peek 2018-09-04 20-41](https://user-images.githubusercontent.com/13408130/45034796-007dfe80-b08b-11e8-93b8-baf1d4df78b5.gif)

The current content in `/snap/poedit/4/share/poedit`:

```
/snap/poedit/4/share/poedit
└── icons
    ├── actionbox-close-hover.png
    ├── actionbox-close.png

   <...stripped>

    ├── window-close.png
    ├── wxART_DELETE.png
    ├── wxART_EDIT.png
    ├── wxART_GO_DOWN.png
    ├── wxART_GO_UP.png
    └── wxART_NEW.png

1 directory, 58 files
```

**Comment by Lin-Buo-Ren** [comment]
The content in the OSS build of Poedit snap, for comparison:

```
/snap/poedit/current/share/poedit
└── icons
    ├── CrowdinLogo.png
    ├── document-new.png

   <...stripped>

    ├── SuggestionError.png
    ├── SuggestionPerfectMatch.png
    ├── SuggestionTM.png
    └── window-close.png

1 directory, 26 files
```

I noticed that Acknowledgments.html is available in `<src-tree>/docs`, but it doesn't seem to be installed to `$prefix/share/poedit` in the first place.

**Comment by vslavik** [comment]
Thanks, will be fixed in the next snap refresh.
