### ISSUE TITLE
Program quits during pre-translation process

### ISSUE THREAD

**Issue by swoidowski** [vslavik/poedit#517]
Hi,

PoEdit quits without any reason during pre-translation process. Sadly i can't reproduce the bug at any time because it ends without any message or something and not at the same location.

**Comment by vslavik** [comment]
Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html (as per the instructions for creating new issues) and provide some meaningful description, including — but not limited to! — such absolute basics as your platform, poedit version, your pre-pranslation settings, the file in question etc., as well as a description of what *exactly* you mean by "it quits".  

(P.S. The name's Poedit, no "PoEdit" or any other random spelling.)
