### ISSUE TITLE
wxColour::GetAsString() assert with wxGTK 3.0 due to use of alpha

### ISSUE THREAD

**Issue by cges30901** [vslavik/poedit#524]
Hello. After I updated Poedit to 2.2 from Manjaro repo, when I double click on a po file, Poedit window opens and crashes immediately. If I start Poedit (from menu), it starts fine but when I open a po file, a dialog is shown that says “An assertion failed!”. Every po file I try has the same result, so I think it is not related to po file.

This is the dialog screenshot:
![screenshot-poedit](https://user-images.githubusercontent.com/19516286/46953623-ef300500-d0c0-11e8-8983-dc4012b7a5b1.png)

Backtrace from dialog:
```
ASSERT INFO:
./src/common/colourcmn.cpp(228): assert "isOpaque" failed in GetAsString(): alpha is lost in HTML syntax

BACKTRACE:
[1] wxColourBase::GetAsString(long) const
[2] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[3] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[4] wxEvtHandler::TryHereOnly(wxEvent&)
[5] wxEvtHandler::ProcessEventLocally(wxEvent&)
[6] wxEvtHandler::ProcessEvent(wxEvent&)
[7] wxWindowBase::TryAfter(wxEvent&)
[8] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[9] wxToolBarBase::OnLeftClick(int, bool)
[10] g_closure_invoke
[11] g_signal_emit_valist
[12] g_signal_emit_by_name
[13] g_signal_emit_valist
[14] g_signal_emit
[15] g_closure_invoke
[16] g_signal_emit_valist
[17] g_signal_emit
[18] ffi_call_unix64
[19] ffi_call
[20] g_cclosure_marshal_generic_va
[21] g_signal_emit_valist
[22] g_signal_emit
[23] g_cclosure_marshal_VOID__BOXEDv
[24] g_signal_emit_valist
[25] g_signal_emit
[26] gtk_event_controller_handle_event
[27] g_signal_emit_valist
[28] g_signal_emit
[29] gtk_main_do_event
[30] g_main_context_dispatch
[31] g_main_loop_run
[32] gtk_main
[33] wxGUIEventLoop::DoRun()
[34] wxEventLoopBase::Run()
[35] wxAppConsoleBase::MainLoop()
[36] wxEntry(int&, wchar_t**)
[37] __libc_start_main
```

Output if I open a file with Poedit from command line:
```
[bill@bill-manjaro network-manager]$ poedit network-manager-applet.master.zh_TW.po
./src/common/colourcmn.cpp(228): assert "isOpaque" failed in GetAsString(): alpha is lost in HTML syntax

(poedit:3053): Gtk-WARNING **: 21:21:20.973: gtk_window_set_titlebar() called on a realized window
Trace/breakpoint trap (core dumped)
```

**Comment by vslavik** [comment]
>  Manjaro repo, when I double click on a po file, 

I don't know what "Manjaro repo" is…

Please provide information about your GTK+, wxGTK and Pango versions. Compilation flags would be good to know too.

> Poedit window opens and crashes immediately

The rest of what you wrote contradicts your claim that it "crashes" — that word has a specific meaning, it doesn't mean "something went wrong"...

**Comment by vslavik** [comment]
> I mean packages from Manjaro

No kidding. Point is, you can't seriously expect any upstream to have any knowledge of your favorite obscure distro.

> I thought core dump means crash?

Sure, but your original claim was that "Poedit window opens and crashes immediately". But in reality:
1. You launch Poedit
2. You click toolbar button (see item 8 in the stacktrace)
3. An *assert* window is shown
4. *You* intentionally press the Stop button to stop the application's execution
4. *Then* it stops (= crashes) just as you asked it to

That's a far cry from "crashes immediately"…

I thought this was Pango related, but it's actually about an old (but latest stable) wx version. Will fix.

Possible workarounds until then are to either a) don't use a dark theme (I *think* only dark colors are affected) or b) use the official Snap distribution of Poedit from https://poedit.net/download

**Comment by cges30901** [comment]
Sorry, I am not clear enough.
There are two ways of opening a po file: double click on a po file (or from command line "poedit FILE") and open Poedit, click File > Open and select the po file. The former one crashes immediately, and produce the output with "core dumped", and the latter one produces a dialog. I am not sure if they are different issues.

**Comment by cges30901** [comment]
Thank you! After I switched to a light theme, I no longer had this issue.

**Comment by Jerther** [comment]
I have Poedit 2.2 from Fedora 29 here. I do have the dark theme enabled. Same backtrace as OP when I open a file from the file menu.

gtk3 version: 3.24.1-1
wxGTK version: 2.8.12-31
Pango version: 1.42.4-1

I also have a crash when I open a file from the command line (or from an IDE):
```
[jerther@laptop-web i18n]$ poedit fr.po
../src/common/colourcmn.cpp(228): assert "isOpaque" failed in GetAsString(): alpha is lost in HTML syntax

(poedit:7476): Gtk-WARNING **: 11:06:03.828: gtk_window_set_titlebar() called on a realized window
Trace/breakpoint trap (core dumped)
```

Nothing new really from what's already been discussed here except for my version of wxGTK. Let me know if I could be of any help.

**Comment by somas95** [comment]
Same issue on archlinux when a dark theme is enabled
gtk3      3.24.1+8+g220f77d8c1-1
wxgtk3  3.0.4-2
pango   1.42.4-1

Poedit 2.2-2

**Comment by vslavik** [comment]
@somas95 Please refrain from "me too" comments, they add no value.

**Comment by Jerther** [comment]
I just got 2.2.1 from Fedora 29 and the problem is fixed, thank you.
