### ISSUE TITLE
Wayland incompatibility

### ISSUE THREAD

**Issue by bigon** [vslavik/poedit#538]
Hi,

Apparent the desktop file has already been renamed to `net.poedit.Poedit.desktop` but the executable has not.

With GTK3 under wayland this is causing the running poedit to not have an icon set in the application list.

It seems that the .desktop file and the executable MUST have the same name. An other solution is to set the program name using `g_set_prgname ("net.poedit.Poedit")` but I don't think this is feasable in wxwidgets

(For consistency the icons could also be renamed but that's not mandatory)

**Comment by vslavik** [comment]
> It seems that the .desktop file and the executable MUST have the same name.

That seems *highly* unlikely. Please provide evidence, i.e. links to documentation, supporting your claims. Please observe that e.g. GNOME Calendar has a binary called `gnome-calendar` and a `org.gnome.Calendar.desktop` file and does not call `g_set_prgname()`; this seems to prove your hypothesis incorrect.

For obvious reasons, naming the actual binary in such a ridiculous manner is absolutely out of the question; if anything, reverting the ID change would be better. But see above — I think something else is going on.

> g_set_prgname ("net.poedit.Poedit") but I don't think this is feasable in wxwidgets

Fortunately that opinion happens to be wrong.

> With GTK3 under wayland this is causing the running poedit to not have an icon set in the application list.

Please provide some docs/evidence for this too, as well as actual description that could be understood by people *not* using Wayland. No idea what "application list" is for one. Or how you launched Poedit and whether you actually launched the binary that matches the desktop file or not, i.e. what the precise steps to reproduce (that you *did*, not that you assume are sufficient) are.

> (For consistency the icons could also be renamed but that's not mandatory)

Source for the "should" bit?

**Comment by vslavik** [comment]
Providing the evidence I asked for myself:

Per https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased, what should be done is set application ID. But `GtkApplication` isn't used by wx and it isn't immediately obvious how this information propagates to Wayland.

The same link is a source for the "should rename icons".

[This patch](https://gitlab.gnome.org/GNOME/gtk/commit/e1fd877) strongly implies that calling `g_set_prgname()` is what should be done and [this GTK+4 documentation change](https://gitlab.gnome.org/GNOME/gtk/commit/f25f3b3c47db97686f7ad396f16ad7d4976f089f) says it outright (for GTK+3); so does [this post](https://honk.sigxcpu.org/con/GTK__and_the_application_id.html).

**Comment by LocutusOfBorg** [comment]
@vslavik so we have no patch / hack for this issue in Debian? this seems to be the only blocker for a gtk+3 switch...

**Comment by LocutusOfBorg** [comment]
oh, refreshing the page helped :)
