### ISSUE TITLE
Preserve formatting of existing files doesn't seem to work for me

### ISSUE THREAD

**Issue by kokoko3k** [vslavik/poedit#539]
I opened a .po file to modify it, every line in it has 80 columns (maximum).
I checked "Preserve formatting of existing files", edited it, saved it.
The resulting .po has long lines. poedit has unwrapped everything.

To keep my file with 80 columns, i have had to uncheck "Preserve formatting of existing files", and told poedit to wrap the lines to 80.

Is this intended?

**Comment by vslavik** [comment]
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), follow the instructions therein and provide the missing detailed information. Thanks!

**Comment by kokoko3k** [comment]
I've read it, why do you think i'm not?
Point 1: "Make sure you're using the latest version of Poedit; update it if not."
point 2: i'm not translating any code!
point 3: i've described my problem, there is no more to say (is there?)
Point 4: "Don't forget to mention your Poedit version, your operating system and its version."
(confused here, my version is obviously 2.2, see point 1!)
point 5: it is not specific to a particular PO file, so i've not attached anything
point 7: I'm not extracting any source code

**Comment by vslavik** [comment]
> I've read it, why do you think i'm not?

Because you provided absolutely no reproduction steps at all ("I edited it" is meaningless and can mean a gazillion things), provided no information whatsoever about your platform, Poedit version, and didn't attach the highly relevant PO file. Your assumption that the file is irrelevant is wrong and unfounded.

**Comment by kokoko3k** [comment]
The reprodution steps i provided are minimal because minimal is the edit i've to do to reproduce the problem.
```"I edited it" is meaningless```
No, it is not, it is you that are trying to make it meaningless.
"I Edited it" means that to reproduce the problem it is sufficient to change at least a char.
Should i rephrase? ok, read:
"i changed just a char". But what's the point in explaining the obvious?!

```provided no information whatsoever about your platform```
As stated in the previous post (and as the wiki document request) Operating system is Archlinux and version is meaningless, since it is a rolling release distro, do you want me to pos a list of all of the packages installed in my system with their versions, or do you need to know something about particular packages? i'm not a mind-reader, you know...

```Poedit version```
Poedit version is the latest! Man, you said: read the wiki, and the wiki says that the poedit version has to be updated before reporting any bug, so why are you, again, asking me to write obivous things?
Ok, i say it:, read:
"My poedit version is 2.2".

```didn't attach the highly relevant PO file```
Yes, because the document you think i did not read said:
"If the problem is specific to a particular PO file, attach it"

Now, since i can reproduce with more than one file, the assumption that the file is not relevand IS founded.
And if i did not attach any .po, you should realize that the problem IS NOT bound to a particular po file.
It is obvious, again, but still...
Do you want me to attach any file i can reproduce the problem with? Really?

That said, i'm closing this as it is going nowhere.

As a suggestion: read yourself [This document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) again, before supposing the other did not.
