### ISSUE TITLE
Poedit rearranges comments/paths

### ISSUE THREAD

**Issue by libreajans** [vslavik/poedit#545]
Before saving my file with Poedit comments/path were looking like this:

```
#: operations/common/gblur-1d.c:32 operations/common/median-blur.c:34
#: operations/common-gpl3+/fractal-explorer.c:96
```

After saving they have became like that:

```
#: operations/common/gblur-1d.c:32 operations/common/median-blur.c:34 operations/common-gpl3+/fractal-explorer.c:96
```

Is it a bug? And how can I keep my comment/paths the same order?

**Comment by vslavik** [comment]
If you think there is bug, please do read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), follow the instructions therein and provide the missing detailed information — in particular, you didn't provide even the most essential information like your platform, Poedit version, the file or your related preferences settings (advanced tab).

If you don't think it's a bug, this is a bug tracker, not a support forum.

**Comment by libreajans** [comment]
Sorry, Vslavik for my mistake.

Version: Poedit 2.0.6 / Poedit 2.2.1 via Snap
OS: Ubuntu 18.04

My Advanced settings are for both Poedit versions:
Line ending: Unix
Wrap at: 79
Preserve formatting of existing files: checked

I haven't shared the file (gegl-0.4.po) because it's huge. But I shared a sample from it via code tag.

Before saving with Poedit.

```#: bin/gegl.c:3851
#: bin/gegl.c:3852
#: bin/gegl.c:3853
#: bin/gegl.c:3854
#: bin/gegl.c:3855
#: bin/gegl.c:3856
#: bin/gegl.c:3857
#: bin/gegl.c:3858
#: bin/gegl.c:3859
#, c-format
msgid "Unknown"
msgstr "Bilinmeyen"
```

After saving with Poedit.

```
#: bin/gegl.c:3851 bin/gegl.c:3852 bin/gegl.c:3853 bin/gegl.c:3854
#: bin/gegl.c:3855 bin/gegl.c:3856 bin/gegl.c:3857 bin/gegl.c:3858
#: bin/gegl.c:3859
#, c-format
msgid "Unknown"
msgstr "Bilinmeyen"
```

I have no idea why Poedit rearranges these kinds of stuff. If it necessary, it might be good to have an option like "do not touch comments/paths order".

**Comment by vslavik** [comment]
> I have no idea why Poedit rearranges these kinds of stuff

A good practice is to search the bug tracker first...

> If it necessary, it might be good to have an option like "do not touch comments/paths order".

There's nothing I can do if you refuse to provide the information I asked for because "it's huge". 

As far as I can determine, this is expected behavior of using `msgcat` standard formatting. It would be impractical to address it, but if this matters to you, you are welcome to improve the code (without adding yet another user-configurable option, though).
