### ISSUE TITLE
Snap package crashes when closing window; infinite recursion

### ISSUE THREAD

**Issue by RavanH** [vslavik/poedit#546]
Trying to run poedit from command line in Ubuntu 18.10, I get:

> $ poedit
> Fontconfig warning: line 5: unknown element "its:rules"
> Fontconfig warning: line 6: unknown element "its:translateRule"
> Fontconfig error: line 6: invalid attribute 'translate'
> Fontconfig error: line 6: invalid attribute 'selector'
> Fontconfig error: line 7: invalid attribute 'xmlns:its'
> Fontconfig error: line 7: invalid attribute 'version'
> Fontconfig warning: line 9: unknown element "description"
> Fontconfig warning: "/snap/poedit/8/gnome-platform/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
> Fontconfig warning: "/snap/poedit/8/gnome-platform/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
> Fontconfig error: "/snap/poedit/8/gnome-platform/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
> Fontconfig error: "/snap/poedit/8/gnome-platform/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
> Fontconfig error: "/snap/poedit/8/gnome-platform/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
> Fontconfig error: "/snap/poedit/8/gnome-platform/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'

*(…and so on and so on…)*

> Fontconfig error: "/snap/poedit/8/gnome-platform/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
> Fontconfig error: Cannot load default config file
> Segmentatiefout (geheugendump gemaakt)

That last part is in Dutch, meaning: Segmentation error (core dump made).

**Comment by vslavik** [comment]
The errors are [apparently](
https://www.google.com/search?q=snap+Fontconfig+warning:+line+5:+unknown+element+%22its:rules%22) a fontconfig mismatch. Not sure why that happens with snap's bundled content, or what crashes. @Lin-Buo-Ren does it ring a bell by any chance?

**Comment by Lin-Buo-Ren** [comment]
The fontconfig errors are probably due to the incompatible fontconfig distributions shipped in the snap (from Ubuntu 16.04) and in the host (Ubuntu 18.10), as far as I know, these errors are non-fatal and shouldn't be the cause of the subsequent segmentation fault.

I can reproduce it on my end, the segmentation fault occurs after I close the main window, not sure what causes it yet, though.
[poedit.strace.log](https://github.com/vslavik/poedit/files/2803975/poedit.strace.log)

**Comment by vslavik** [comment]
@RavanH You never said: *when* do you get the crash, exactly?

**Comment by vslavik** [comment]
> The fontconfig errors are probably due to the incompatible fontconfig distributions shipped in the snap (from Ubuntu 16.04) and in the host (Ubuntu 18.10)

It's pretty crazy that Snap doesn't have that covered (not much of isolation from the distro runtime then, is it), and FWIW wasn't present before e2721f0118b935f7be95dcd1b026eb526b0d9c85 — I suspect gnome-platform (889ad8154e9b37380333b6d12849272d43bd8334) as the cause.

As for the more serious matter of the crash-on-close, that does seem like a mis-compilation. It is related to libcrypto (which is used from gnome-platform, apparently, so might be related to it too - that copy is different than the one in snap core) and boost. Something is fishy about the latter in the snap — *two* different versions of it are used: one as a shared library, dependency of libcpprest, the other our own newer statically built one. On one hand, that might be the cause, on the other, the crash didn't happen pre- e2721f0118b935f7be95dcd1b026eb526b0d9c85, but double boost *was* present back then.

**Comment by vslavik** [comment]
Is it possible the (entirely undocumented as far as I can tell) `no-system-libraries` flag is causing the libcrypto problem?

**Comment by RavanH** [comment]
Here's the funny part: even though it sais Segfault, poEdit starts up fine in an Xorg session, but on Wayland it does crash. With the same Fontconfig messages followed by:

> ...
> Fontconfig error: Cannot load default config file
> (net.poedit.Poedit:19829): Gdk-WARNING **: 22:37:47.937: /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gdk/wayland/gdkcursor-wayland.c:169: Unable to load hand2 from the cursor theme
> Segmentatiefout (geheugendump gemaakt)

Strange...

**Comment by Lin-Buo-Ren** [comment]
> net.poedit.Poedit:19829

Is it reproducible by running `snap run poedit` in a terminal?

**Comment by RavanH** [comment]
Yes, either `snap run poedit` or just `poedit` produces the same.

**Comment by vslavik** [comment]
This was indeed caused by duplicate boost libraries and is fixed in the above commit and the latest snap build (`sudo snap refresh` or rebooting will update to it).
