### ISSUE TITLE
PoEdit changing double quotes when saving/fetching (mac OS)

### ISSUE THREAD

**Issue by guillaumepotier** [vslavik/poedit#548]
Hi there,

I'm having hard times with my loyal poEdit these last days. Cannot say on which update it changed, but when I scrap/save my .po file from the app, it automatically changes my double quotes `"word"`(ASCII code `34`) to `“word”` (ASCII codes `8220` and `8221`).

This may not be problematic for regular sentences, but rare few cases when html is included in the translation, it totally mess things up. For example:

`my <a href="{{link}}">awesome translated link</a>` becomes `my <a href=“{{link}}”>awesome translated link</a>` and totally break things.

Please note this only happens to `msgstr` strings, not `msgid` ones.

Is it a "feature" or an "expected behaviour"? If so, why, and is it possible to de-activate it?

Thanks for your help on that matter.

Best

**Comment by vslavik** [comment]
Poedit is doing no such thing.

*Your operating system* is, because you have enabled this option in preferences. See Edit → Substitutions or System Preferences.

**Comment by guillaumepotier** [comment]
Thanks for the quick answers. Was looking into general preferences, did not thought about that one. Thanks @vslavik

**Comment by gflohr** [comment]
You can still enter regular, straight quotes with `CTRL`-" resp. `CTRL`-'. Depending on your keyboard layout, you also have to use the `Shift` key. Maybe that could be added as a hint to the dialogue in POEdit.
