### ISSUE TITLE
error with crowdin 

### ISSUE THREAD

**Issue by ykla** [vslavik/poedit#552]
Poedit can't upload the same translates as sources in English. Many strings no need to translate and just to copy sources strings. And Poedit only upload Chinese when you translate English to Chinese and doesn't upload any English.

**Comment by vslavik** [comment]
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), follow the instructions therein and provide the missing detailed information. Thanks!

**Comment by vslavik** [comment]
In gettext, identical "translations" make no sense and can be ignored.
