### ISSUE TITLE
Václav, do piče, práve mi to tretí krát spadlo uprostred prekladu

### ISSUE THREAD

**Issue by jasomdotnet** [vslavik/poedit#553]
Kurva. Práve mi Poedit 2.0.6 spadol tretí krát v priebehu 15 minút uprostred prekladu. Dorobte tam nejakú funkciu autosave a defaultne to nastavte na 30 sekúnd. V mene užívateľov ďakujem :-)

Používam Ubuntu 18.04

**Comment by vslavik** [comment]
Až za něco budete platit, tak si máte nárok stěžovat. 

Ani to by vám nedávalo právo chovat se jako hovado.
