### ISSUE TITLE
Exit confirmation

### ISSUE THREAD

**Issue by Seluj78** [vslavik/poedit#554]
Hi there 👋 

I love poedit and use it every day to help translate the Python documentation to french (see https://github.com/python/python-docs-fr).

I use the pro version of `poedit 2` and I had a feature request: Exit confirmation when multiple files are open but not saved :)

**Comment by vslavik** [comment]
I have a request too: please read *and follow* [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), including the linked documents. Your assumption that this is a "feature" to request is wrong, this *of course* is how Poedit behaves from day one. So if you think that's not the case, provide usable reproduction instructions, including such basics as your OS or Poedit version.

Thanks!

**Comment by Seluj78** [comment]
Alright then, i'll send an email with all that to help+pro@poedit.net ;) Cheers
