### ISSUE TITLE
Close References window if main window is closed

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#562]
My Poedit usage typically looks like this:

![image](https://user-images.githubusercontent.com/3233724/56060525-6dffb500-5d67-11e9-90d8-bc53f86d37f6.png)

In this situation, when I close the main window, the References window stays open. On its own, it doesn't provide much value. It feels more like a non-modal dependent window to me. Therefore, when I close the main window I expect the References window to close as well.

**Comment by vslavik** [comment]
Makes sense ... if *one* main window is present.
