### ISSUE TITLE
Shortcut for going back to previously translated message

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#563]
I'm translating a large file in which most translations have already been done. (It's still GCC 9.)

I have just finished translating a message and pressed Ctrl+Enter to go to the next message. But wait, I forgot to add a word. Now I want to go back to that message.

The shortcuts from the Navigate menu don't help me. In the Edit menu both Undo and Redo are disabled. (I wonder why, and how far back the undo history goes.)

From the JetBrains IDEs I'm used to press Shift to navigate into the other direction, therefore I tried Ctrl+Shift+Enter. Nothing happened.

Is there already a way to go back to the last message I edited?

**Comment by vslavik** [comment]
Closing in favor of newer #739.
