### ISSUE TITLE
Add support for Laravel's Blade templates

### ISSUE THREAD

**Issue by vaites** [vslavik/poedit#567]
The [Laravel's Blade templates](https://laravel.com/docs/5.8/blade) are quite similar to Twig. By now, we are using [this instructions](https://framework.themosis.com/docs/master/blade/#poedit) and works well with `trans` and `trans_choice` keywords (used by Laravel). 

The only addition must be the [translation directives](https://laravel.com/docs/5.8/localization#retrieving-translation-strings) (`@lang` and `@choice`) that are transformed to `trans` and `trans_choice` internally.

Can you add support for this files?.
Thanks!

**Comment by vslavik** [comment]
> By now, we are using this instructions and works well with trans and trans_choice keywords (used by Laravel).

Doesn't work so well when HTML attributes start being involved.

Yes, this is planned.

(Obligatory: Please thumbs-up this issue if this is of interest to you.)

**Comment by vaites** [comment]
Thanks Václav, we use Poedit in multiple Laravel projects, let me know if you need some testing...

**Comment by vslavik** [comment]
@vaites Thanks, I'm going to take you up on that offer when the time comes!

**Comment by displaynone** [comment]
It would be nice to have this feature.

Thanks :)

**Comment by JL2014** [comment]
+1

**Comment by erralb** [comment]
Hi @vslavik ,

I just bought Poedit Pro and noticed I cannot edit the extractors, as described [here](https://framework.themosis.com/docs/master/blade/#poedit) to manually add Blade template support.
Is this suppose to be like that?

Kind regards

**Comment by vslavik** [comment]
@erralb Please use help@poedit.net for support and include as much details as possible. Your comment doesn't seem to be related to the ticket at hand.

**Comment by erralb** [comment]
@vslavik are you sure? I am talking about Laravel's Blade templates support as mentioned here, but ok I will!
