### ISSUE TITLE
Allow to switch UI language to US English

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#568]
![image](https://user-images.githubusercontent.com/3233724/56983885-10e86980-6b85-11e9-8828-dadcc222d6b7.png)

There's no mention of en-US in this dialog. I'd like to change the language to en-US in order to report UI bugs and use the original terminology. (I guess en-US is the original language, but of course I may be wrong.)

As a workaround, I will use en-GB in the meantime.

**Comment by vslavik** [comment]
That's a very good point, thanks!
