### ISSUE TITLE
Generate POT file from PO

### ISSUE THREAD

**Issue by glixx** [vslavik/poedit#570]
Please add generation POT file from PO in poedit.

Noone tool works.

msgfilter:
The following msgid contains non-ASCII characters.
invalid multibyte sequence

**Comment by vslavik** [comment]
> Please add generation POT file from PO in poedit.

That doesn't make *any* sense. But if you insist: clear translations, rename to `.pot`. Evident after reading GNU gettext manual.

> Noone tool works.

No, they work just fine. Then even *tell you* what's wrong — your file. *Read* the error. Fix your invalid file — its header or encoding are wrong. The tool tells you exactly which part of your file is bad. How could you not investigate it and instead concluding that somehow the tool "doesn't work"?
