### ISSUE TITLE
Check for file changes made outside Poedit

### ISSUE THREAD

**Issue by vaites** [vslavik/poedit#574]
Take this scenario:

* An user works on a PO file inside a VCS repository
* With Poedit opened, the user pull some changes
* If PO file was modified, Poedit doesn't notice
* The user continue working on PO file and save its changes
* PO file loses the changes made in VCS

Yes, the problem can be solved closing Poedit before any pull, but is it reasonable for Poedit to check if there have been changes in the file?. This will avoid a possible data loss and Poedit can ask, like many code/text editors, to discard these changes or load the file from disk.

**Comment by vslavik** [comment]
> but is it reasonable for Poedit to check if there have been changes in the file?

It's certainly not *unreasonable*... and as you say, some text editors handle it.

**Comment by vslavik** [comment]
Sorry, forgot to close this: implemented in v3.0 in fd20186d7ce0fbe4caaee59c7d51d5cfd6004734

**Comment by vaites** [comment]
Thanks @vslavik!
