### ISSUE TITLE
Missing validation for %s placholders when using java-format?

### ISSUE THREAD

**Issue by Ahnfelt** [vslavik/poedit#577]
I have a .pot file with `#, java-format` tags, which Poedit correctly picks up (see screenshot). 

However, it validates even though there are **too many placeholders** in the translation. 

<img width="557" alt="billede" src="https://user-images.githubusercontent.com/78472/58261678-0fbbee00-7d79-11e9-96e4-f80876acd44d.png">

Shouldn't this cause a validation error?

**Comment by vslavik** [comment]
> Shouldn't this cause a validation error?

I can't possibly know, you didn't attach the file in question...

**Comment by Ahnfelt** [comment]
Here's a minimal example file to reproduce:
[en.po.txt](https://github.com/vslavik/poedit/files/3212930/en.po.txt)

It was created by selecting "New from POT/PO file ..." and entering "Welcome %s %s".
[xxx.pot.txt](https://github.com/vslavik/poedit/files/3212931/xxx.pot.txt)

(.txt since GitHub doesn't allow .po files)

**Comment by Ahnfelt** [comment]
The contents of en.po:

```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Poedit 2.2.3\n"
"Last-Translator: \n"
"Language: en\n"

#, java-format
msgid "Velkommen %s"
msgstr "Welcome %s %s"
```

**Comment by vslavik** [comment]
`java-format` is ([per docs](https://www.gnu.org/software/gettext/manual/html_node/java_002dformat.html)) for [`java.text.MessageFormat` syntax](https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html) rather than C-like, so this appears to work as intended. (It would also be a `msgfmt` rather than Poedit issue too.)

**Comment by Ahnfelt** [comment]
Ah, that explains it - I'm sorry about the misunderstanding. I can confirm that it works as advertised when replaced with c-format.
