### ISSUE TITLE
poedit v2.2.3 build fails on Arch

### ISSUE THREAD

**Issue by svetlemodry** [vslavik/poedit#579]
Hi all!
I am having trouble compiling poedit v2.2.3 for Arch Linux.
I am using the same [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/poedit) as for the previous versions, building within a [clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot) fails with the below output. Full log [here](https://paste.xinu.at/O4sk/) (for 10 days from now on).
Thanks for your help!

...
/usr/include/wx-3.0/wx/list.h:1111:5: note: in expansion of macro ‘WX_DECLARE_LIST_4’
     WX_DECLARE_LIST_4(T, Tbase, name, nodetype, classexp, WX_LIST_PTROP_NONE)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/list.h:1116:5: note: in expansion of macro ‘WX_DECLARE_LIST_3’
     WX_DECLARE_LIST_3(elementtype, elementtype, listname, nodename, classexp)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/list.h:1129:5: note: in expansion of macro ‘WX_DECLARE_LIST_2’
     WX_DECLARE_LIST_2(elementtype, listname, wx##listname##Node, decl)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/variant.h:101:1: note: in expansion of macro ‘WX_DECLARE_LIST_WITH_DECL’
 WX_DECLARE_LIST_WITH_DECL(wxVariant, wxVariantList, class WXDLLIMPEXP_BASE);
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/variant.h: In member function ‘wxVariant* const& wxVariantList::const_reverse_iterator::operator*() const’:
/usr/include/wx-3.0/wx/list.h:966:60: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
                 { return *(pointer_type)m_node->GetDataPtr(); }             \
                                                            ^
/usr/include/wx-3.0/wx/list.h:1111:5: note: in expansion of macro ‘WX_DECLARE_LIST_4’
     WX_DECLARE_LIST_4(T, Tbase, name, nodetype, classexp, WX_LIST_PTROP_NONE)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/list.h:1116:5: note: in expansion of macro ‘WX_DECLARE_LIST_3’
     WX_DECLARE_LIST_3(elementtype, elementtype, listname, nodename, classexp)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/list.h:1129:5: note: in expansion of macro ‘WX_DECLARE_LIST_2’
     WX_DECLARE_LIST_2(elementtype, listname, wx##listname##Node, decl)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/variant.h:101:1: note: in expansion of macro ‘WX_DECLARE_LIST_WITH_DECL’
 WX_DECLARE_LIST_WITH_DECL(wxVariant, wxVariantList, class WXDLLIMPEXP_BASE);
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/any.h: In member function ‘wxAny* const& wxAnyList::const_iterator::operator*() const’:
/usr/include/wx-3.0/wx/list.h:874:60: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
                 { return *(pointer_type)m_node->GetDataPtr(); }             \
                                                            ^
/usr/include/wx-3.0/wx/list.h:1111:5: note: in expansion of macro ‘WX_DECLARE_LIST_4’
     WX_DECLARE_LIST_4(T, Tbase, name, nodetype, classexp, WX_LIST_PTROP_NONE)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/list.h:1116:5: note: in expansion of macro ‘WX_DECLARE_LIST_3’
     WX_DECLARE_LIST_3(elementtype, elementtype, listname, nodename, classexp)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/list.h:1129:5: note: in expansion of macro ‘WX_DECLARE_LIST_2’
     WX_DECLARE_LIST_2(elementtype, listname, wx##listname##Node, decl)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/any.h:1113:1: note: in expansion of macro ‘WX_DECLARE_LIST_WITH_DECL’
 WX_DECLARE_LIST_WITH_DECL(wxAny, wxAnyList, class WXDLLIMPEXP_BASE);
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/any.h: In member function ‘wxAny* const& wxAnyList::const_reverse_iterator::operator*() const’:
/usr/include/wx-3.0/wx/list.h:966:60: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
                 { return *(pointer_type)m_node->GetDataPtr(); }             \
                                                            ^
/usr/include/wx-3.0/wx/list.h:1111:5: note: in expansion of macro ‘WX_DECLARE_LIST_4’
     WX_DECLARE_LIST_4(T, Tbase, name, nodetype, classexp, WX_LIST_PTROP_NONE)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/list.h:1116:5: note: in expansion of macro ‘WX_DECLARE_LIST_3’
     WX_DECLARE_LIST_3(elementtype, elementtype, listname, nodename, classexp)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/list.h:1129:5: note: in expansion of macro ‘WX_DECLARE_LIST_2’
     WX_DECLARE_LIST_2(elementtype, listname, wx##listname##Node, decl)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/any.h:1113:1: note: in expansion of macro ‘WX_DECLARE_LIST_WITH_DECL’
 WX_DECLARE_LIST_WITH_DECL(wxAny, wxAnyList, class WXDLLIMPEXP_BASE);
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/window.h: In member function ‘wxWindow* const& wxWindowList::const_iterator::operator*() const’:
/usr/include/wx-3.0/wx/list.h:874:60: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
                 { return *(pointer_type)m_node->GetDataPtr(); }             \
                                                            ^
/usr/include/wx-3.0/wx/list.h:1111:5: note: in expansion of macro ‘WX_DECLARE_LIST_4’
     WX_DECLARE_LIST_4(T, Tbase, name, nodetype, classexp, WX_LIST_PTROP_NONE)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/window.h:151:1: note: in expansion of macro ‘WX_DECLARE_LIST_3’
 WX_DECLARE_LIST_3(wxWindow, wxWindowBase, wxWindowList, wxWindowListNode, class WXDLLIMPEXP_CORE);
 ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/window.h: In member function ‘wxWindow* const& wxWindowList::const_reverse_iterator::operator*() const’:
/usr/include/wx-3.0/wx/list.h:966:60: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
                 { return *(pointer_type)m_node->GetDataPtr(); }             \
                                                            ^
/usr/include/wx-3.0/wx/list.h:1111:5: note: in expansion of macro ‘WX_DECLARE_LIST_4’
     WX_DECLARE_LIST_4(T, Tbase, name, nodetype, classexp, WX_LIST_PTROP_NONE)
     ^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/window.h:151:1: note: in expansion of macro ‘WX_DECLARE_LIST_3’
 WX_DECLARE_LIST_3(wxWindow, wxWindowBase, wxWindowList, wxWindowListNode, class WXDLLIMPEXP_CORE);
 ^~~~~~~~~~~~~~~~~
extractors/extractor_gettext.cpp: In member function ‘virtual wxString GettextExtractorBase::Extract(TempDirectory&, const SourceCodeSpec&, const std::vector<wxString>&) const’:
extractors/extractor_gettext.cpp:153:21: warning: catching polymorphic type ‘class std::out_of_range’ by value [-Wcatch-value=]
         catch (std::out_of_range) {}
                     ^~~~~~~~~~~~
make[1]: Leaving directory '/build/poedit/src/poedit-2.2.3/src'
make: *** [Makefile:475: all-recursive] Error 1

**Comment by vslavik** [comment]
Please do check existing issues and after-release commits before submitting and issue. Please also include *relevant* bits in the description — observe how the long description is entirely off-topic and doesn't show any information about the actual compilation *error* .

Fixed by 683788d49eb9cee391984659c39c3e2ac236b420.
