### ISSUE TITLE
MLSD give a time out when I want to connect to OVH Cloud Web 1 ftp server

### ISSUE THREAD

**Issue by olygoelements** [vslavik/poedit#580]
OVH use pureFtpd
when I connect on my FTP your software give me a error: FTP server is too old (missing MLSD support

the log :
par défaut	10:31:59.440967 +0200	Poedit	UNIX error exception: 17
par défaut	10:31:59.443983 +0200	Poedit	UNIX error exception: 17
par défaut	10:32:00.916386 +0200	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (Poedit[56318]/0#-1 LF=0)
par défaut	10:32:00.941585 +0200	Poedit	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
par défaut	10:32:00.943504 +0200	Poedit	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
par défaut	10:32:00.945776 +0200	Poedit	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
par défaut	10:32:00.948332 +0200	Poedit	possible duplicate, trying to delete invalid items
par défaut	10:32:00.948532 +0200	Poedit	no unique id, using 6 attributes from mDbAttributes
par défaut	10:32:00.951754 +0200	Poedit	duplicate item exception is real; throwing it on
par défaut	10:32:00.951818 +0200	Poedit	caught CssmError during add: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
par défaut	10:32:00.975634 +0200	Poedit	no previous integrity acl exists; making a new one
par défaut	10:32:00.992113 +0200	Poedit	0x600002a57e00 commited /Users/oly/Library/Keychains/login.keychain-db.sb-f061eb4e-YqwZNn to /Users/oly/Library/Keychains/login.keychain-db
par défaut	10:32:00.997884 +0200	Poedit	Task <AFAAFE8C-EB55-45E0-8F1F-256E4CA2F994>.<0> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
par défaut	10:32:00.998136 +0200	Poedit	TIC Enabling TLS [9:0x6000031a6640]
par défaut	10:32:00.998172 +0200	Poedit	TIC TCP Conn Start [9:0x6000031a6640]
par défaut	10:32:00.998263 +0200	Poedit	[C9 Hostname#70c283b1:443 tcp, url hash: f2c0ccc4, tls] start
par défaut	10:32:00.998527 +0200	Poedit	nw_connection_report_state_with_handler_locked [C9] reporting state preparing
par défaut	10:32:00.999475 +0200	Poedit	Task <AFAAFE8C-EB55-45E0-8F1F-256E4CA2F994>.<0> setting up Connection 9
par défaut	10:32:01.068608 +0200	Poedit	nw_socket_handle_socket_event [C9.1:3] Socket received CONNECTED event
par défaut	10:32:01.068699 +0200	Poedit	nw_endpoint_flow_protocol_connected [C9.1 IPv4#04b249f3:443 in_progress socket-flow (satisfied)] Transport protocol connected
par défaut	10:32:01.073521 +0200	Poedit	TIC TLS Event [9:0x6000031a6640]: 1, Pending(0)
par défaut	10:32:01.125753 +0200	Poedit	nw_endpoint_flow_protocol_connected [C9.1 IPv4#04b249f3:443 in_progress socket-flow (satisfied)] Output protocol connected
par défaut	10:32:01.126089 +0200	Poedit	nw_connection_report_state_with_handler_locked [C9] reporting state ready
par défaut	10:32:01.126645 +0200	Poedit	TIC TLS Event [9:0x6000031a6640]: 2, Pending(0)
par défaut	10:32:01.126682 +0200	Poedit	TIC TCP Conn Connected [9:0x6000031a6640]: Err(16)
par défaut	10:32:01.126935 +0200	Poedit	TIC TCP Conn Event [9:0x6000031a6640]: 1
par défaut	10:32:01.126953 +0200	Poedit	TIC TCP Conn Event [9:0x6000031a6640]: 8
par défaut	10:32:01.127050 +0200	Poedit	TIC TLS Handshake Complete [9:0x6000031a6640]
par défaut	10:32:01.127247 +0200	Poedit	Task <AFAAFE8C-EB55-45E0-8F1F-256E4CA2F994>.<0> now using Connection 9
par défaut	10:32:01.127463 +0200	Poedit	TIC TLS Event [9:0x6000031a6640]: 20, Pending(0)
par défaut	10:32:01.127701 +0200	Poedit	nw_endpoint_flow_protocol_connected [C9.1 IPv4#04b249f3:443 ready socket-flow (satisfied)] Output protocol connected
par défaut	10:32:01.127939 +0200	Poedit	Task <AFAAFE8C-EB55-45E0-8F1F-256E4CA2F994>.<0> sent request, body D
par défaut	10:32:01.190363 +0200	Poedit	Task <AFAAFE8C-EB55-45E0-8F1F-256E4CA2F994>.<0> received response, status 202 content K
par défaut	10:32:01.190561 +0200	Poedit	Task <AFAAFE8C-EB55-45E0-8F1F-256E4CA2F994>.<0> response ended
par défaut	10:32:01.190661 +0200	Poedit	Task <AFAAFE8C-EB55-45E0-8F1F-256E4CA2F994>.<0> done using Connection 9
par défaut	10:32:01.695178 +0200	Poedit	Task <0FA273E5-8292-40C6-A358-B9E7A65EF4FD>.<0> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
par défaut	10:32:01.695306 +0200	Poedit	Task <0FA273E5-8292-40C6-A358-B9E7A65EF4FD>.<0> now using Connection 9
par défaut	10:32:01.695523 +0200	Poedit	Task <0FA273E5-8292-40C6-A358-B9E7A65EF4FD>.<0> sent request, body N
par défaut	10:32:02.156521 +0200	Poedit	Task <0FA273E5-8292-40C6-A358-B9E7A65EF4FD>.<0> received response, status 200 content C
par défaut	10:32:02.156740 +0200	Poedit	Task <0FA273E5-8292-40C6-A358-B9E7A65EF4FD>.<0> response ended
par défaut	10:32:02.156845 +0200	Poedit	Task <0FA273E5-8292-40C6-A358-B9E7A65EF4FD>.<0> done using Connection 9
par défaut	10:32:02.657957 +0200	Poedit	Task <83CD6095-292C-4B8C-A5B4-F16297E233A0>.<0> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
par défaut	10:32:02.658043 +0200	Poedit	Task <83CD6095-292C-4B8C-A5B4-F16297E233A0>.<0> now using Connection 9
par défaut	10:32:02.658217 +0200	Poedit	Task <83CD6095-292C-4B8C-A5B4-F16297E233A0>.<0> sent request, body N
par défaut	10:32:02.755493 +0200	Poedit	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 7532, 513, <private>
par défaut	10:32:02.809087 +0200	Poedit	Task <83CD6095-292C-4B8C-A5B4-F16297E233A0>.<0> received response, status 200 content C
par défaut	10:32:02.809236 +0200	Poedit	Task <83CD6095-292C-4B8C-A5B4-F16297E233A0>.<0> response ended
par défaut	10:32:02.809288 +0200	Poedit	Task <83CD6095-292C-4B8C-A5B4-F16297E233A0>.<0> done using Connection 9
par défaut	10:32:03.310247 +0200	Poedit	Task <6119F4BF-F6CE-408C-9082-4CA680C877F0>.<0> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
par défaut	10:32:03.310339 +0200	Poedit	Task <6119F4BF-F6CE-408C-9082-4CA680C877F0>.<0> now using Connection 9
par défaut	10:32:03.310499 +0200	Poedit	Task <6119F4BF-F6CE-408C-9082-4CA680C877F0>.<0> sent request, body N
par défaut	10:32:03.848109 +0200	Poedit	Task <6119F4BF-F6CE-408C-9082-4CA680C877F0>.<0> received response, status 503 content K
par défaut	10:32:03.848224 +0200	Poedit	Task <6119F4BF-F6CE-408C-9082-4CA680C877F0>.<0> response ended
par défaut	10:32:03.848295 +0200	Poedit	Task <6119F4BF-F6CE-408C-9082-4CA680C877F0>.<0> done using Connection 9

**Comment by vslavik** [comment]
Please use help@poedit.net for Pro support. This is open source version's bug tracker.

The log is unrelated to the error, which is self-explanatory: your FTP server is too old/limited and doesn't support what Poedit requires (an FTP command standardized *more than ten years ago*). Use SFTP instead or upgrade to a more modern FTP server.
