### ISSUE TITLE
Support for xliff state="new"

### ISSUE THREAD

**Issue by DaSchTour** [vslavik/poedit#585]
I'm using poedit to translate xliff 1.2 file generated from an angular application. I have a workflow were new items are created with a `<target state="new">`. This items aren't handled by poedit but treated as translated. Either if state="new" poedit should treat this as untranslated or show that it needs translations. Currently I have to search through all translations to find the new owns which are not translated.

**Comment by vslavik** [comment]
> new items are created with a .

I don't know what you mean by that, something seems missing?

If you could elaborate and describe the workflow in more detail, including providing some example files (or even the angular project, if you can, privately to help@poedit.net), that would be greatly appreciated.

**Comment by DaSchTour** [comment]
Oh yes, sorry. Was a bit in a hurry. I can sand you a sample file. I use this https://github.com/martinroob/ngx-i18nsupport tool to generate and merge existing translations with new once.

**Comment by MarcusRiemer** [comment]
I am bitten by the same problem, an explanation how this happens with Angular can be found in [this issue](https://github.com/martinroob/ngx-i18nsupport/issues/149). An minimal example file could read as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="de" datatype="plaintext" original="ng2.template" target-language="en">
    <body>
      <trans-unit id="extractTest" datatype="html">
        <source>
          Dies ist ein deutscher Text
        </source>
        <target state="new">
          Dies ist ein deutscher Text
        </target>
        <context-group purpose="location">
          <context context-type="sourcefile">app/front/templates/about.html</context>
          <context context-type="linenumber">20</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

Note that the Angular translation tool has (imho unhelpfully) copied over the `source` text but it does set the state to `new` which marks it as untranslated. I guess this follows a reasoning along the lines of "better present the original text to the user than nothing", but it breaks the Poedit workflow. When opening the file above I get the following state of Poedit:

![Single untranslated unit](https://user-images.githubusercontent.com/2138773/66030531-ddc64f80-e501-11e9-80fc-1b789f9afffe.png)

The linked issue also contains the following screenshot, where the untranslated unit is **really** hard to find.

![Single untranslated unit among many translated units](https://camo.githubusercontent.com/28c47144be288cd534e94a1ff44f93921b1f9a80/68747470733a2f2f692e696d6775722e636f6d2f5044646b6936692e706e67)

In both cases Poedit happily tells me that the translation status is 100% and does not pull the missing translations to the top.

**Comment by vslavik** [comment]
See the status of the issue and the above commit link: it's been already fixed *and* released.
