### ISSUE TITLE
Option to hide XLIFF trans-units that don't need translation

### ISSUE THREAD

**Issue by rvanbekkum** [vslavik/poedit#586]
In .xlf files it is possible to have trans-unit nodes with the `translate` attribute set to `"no"`.
Here is an example:
```xml
<trans-unit id="SomeID" size-unit="char" translate="no" xml:space="preserve">
    <source>This is my fixed label</source>
    <note from="Developer" annotates="general" priority="2"/>
    <note from="Xliff Generator" annotates="general" priority="3">PageExtension CustomerListExt - Method OnOpenPage - NamedType MyLabel</note>
</trans-unit>
```
These trans-unit, however, still show up as needing a translation in poedit.
Would it be possible to add an option to hide the trans-unit nodes with `translate="no"` set? Or something similar to that so that we know the entry does not need a translation?

If there is already something in place to handle this that I was not able to find, just let me know.

**Comment by vslavik** [comment]
Thanks! If you could share a real-life sample file (via help@poedit.net), just to be sure I don't miss some subtlety in the context, that would be appreciated.

> Would it be possible to add an option to hide the trans-unit nodes with translate="no" set?

I'm inclined to say it shouldn't be an option, but just be hidden unconditionally, but maybe I'm missing something. Out of curiosity, would you know why anybody would choose to put non-translatable items into a translation file like this?

**Comment by rvanbekkum** [comment]
I have sent you an XLIFF files with some examples. The units with translate="no" mostly concern text constants that hold fixed names, labels, option- and property captions that should not be translated or do not need translation, but also should not be hardcoded in the source code of the application.

The reason I suggested it as an option is that I think it might also be desirable to sometimes be able to quickly (re)view the units that don't need a translation from poedit. I agree though that hiding them by default would probably be the best.

**Comment by vslavik** [comment]
I think it would be best to show them, but without edit UI and an explanation that the item is read-only and shown only for reference, but that would require deeper changes to Poedit.

For now, the above commit just hides them unconditionally; let's revisit it if it causes problems to translators in practice.
