### ISSUE TITLE
Separator line thicker

### ISSUE THREAD

**Issue by milotype** [vslavik/poedit#592]
Make separator line thicker (see attachment)
Currently it's anoying that one cannot always grab it with the mouse, bacuse it's so thin.

![GUI correction](https://user-images.githubusercontent.com/43657314/62146981-d2368c80-b2f6-11e9-8286-203aa8c5d706.png)

**Comment by vslavik** [comment]
I (obviously) disagree with your characterization, but by all means, make a patch and I'll consider. Preferably one that makes the sensitive area larger, not necessarily the visual one.

**Comment by milotype** [comment]
Hi Václav,
I'm sorry to say I'm not a programmer and don't know how/where to make such changes (same goes for issue #593 . :-(

**Comment by pereorga** [comment]
For me, that separator thickness is probably enough, though I guess making it thicker would make the UI more accessible (same goes for the vertical bar that separates the suggestions on the right)

**Comment by milotype** [comment]
Yes, horizontal and vertical could have larger sensitive area …

**Comment by vslavik** [comment]
Xcode has a good solution for this: the separator is thin, but the active draggable area where the cursor changes is the much wider (in Poedit's case, the entire *Source text:* row):

![2020-06-06 11 43 59](https://user-images.githubusercontent.com/145881/83941426-762c7680-a7eb-11ea-9972-1a7d5086e6f4.gif)
