### ISSUE TITLE
Feature request: Ability manually add translation

### ISSUE THREAD

**Issue by zapper** [vslavik/poedit#594]
Hello,

It would be nice if Poedit would have ability to add translations manually.

Parsing from source with keyword "self::l" does not work.

**Comment by vslavik** [comment]
This request comes from fundamentally misunderstand how gettext works — it doesn't make sense to add source strings manually, and Poedit is not going to have that capability for PO files. See the [GNU gettext manual](https://www.gnu.org/software/gettext/manual/gettext.html).

As for the rest, where you don't provide any details, `self::I` is not a valid function name in any language I know, so there's your problem.

P.S. Please don't mix multiple things in a single issue and provide more detailed explanations of what you mean — see [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue). Thanks!
