### ISSUE TITLE
comparison .pot and .po

### ISSUE THREAD

**Issue by Klaris69** [vslavik/poedit#597]
Hello,
I need advice on how to compare files .pot and .po

I have a translation from test_v1.pot > test_v1.po
and when a newer file exists test_v2.pot so I need to compare it with the translation test_v1.po. but how?

msgmerge.exe -o "C:\xxx\new.po" --no-wrap "C:\xxx\test_v1.po" "C:\xxx\test_v2.pot"
??

**Comment by vslavik** [comment]
This is a *bug tracker*, not help forum. It's also for Poedit, not GNU gettext command line tools. Please read up on the `diff` tool and see GNU gettext manual, it explains how to use the tools.

**Comment by Klaris69** [comment]
but these tools are part of your program..
but you are right, I will post my license key somewhere on the forum and ask for support for your program elsewhere..

**Comment by vslavik** [comment]
These tools are included as internal helpers.

If you're asking for *support*, then please use the contacts provided at https://poedit.net/support. 
If you're asking for paid support, then doing it anonymously, with no way to verify your license, on an open source bug tracker is a bit strange way of doing it.
