### ISSUE TITLE
Support machine translation using Apertium

### ISSUE THREAD

**Issue by pereorga** [vslavik/poedit#598]
Apertium is an open-source translation tool. It is coded in C++ and is licensed under the GPL. As you may be aware, the GPL is obviously incompatible with the MIT license and with proprietary software, so that could be a problem for both versions of your app.

Fortunately, the software also provides a REST API service, which can easily be hosted. As far as I can see, there is no public API service available.

**Comment by vslavik** [comment]
I don't see a practical benefit to doing it and currently have no plans to. 

If I were interested in self-hosting an MT engine (which *at the moment* I'm not, because there's nothing "easily" about it), then I'd go with [ModernMT](https://github.com/modernmt/modernmt) as a more promising alternative.

**Comment by pereorga** [comment]
With "self-hosting", I meant the user who uses Poedit (here and originally, in the LanguageTool issue) via a configurable screen that allows setting the endpoint (to http://localhost, or whatever). I fully understand why you wouldn't want to host a public service like this, and for free.

I wouldn't mind offering it myself in one of my VPS. But that's a bit of "wishful thinking", I don't have a clue about the traffic that Poedit could bring (nor the problems I would have to handle). But if you change your mind and want to do the difficult part (implementing the client), and decide to trust a random GitHub user, let me know.

By the way, thanks for pointing me to ModernMT.
