### ISSUE TITLE
Bug: Extraction from JSX in JS files fails some times

### ISSUE THREAD

**Issue by mi-roh** [vslavik/poedit#601]
In some JS-Files containing JSX the extraction fails with the Error `Warnung: RegExp-Literal wurde zu früh terminiert` (Should be in English: `warning: RegExp literal terminated too early`) witch seams to be triggerd by [deps/gettext/gettext-tools/src/x-javascript.c:955](https://github.com/vslavik/poedit/blob/76e879ee22e2f23e4dfc21eb64688251375ab566/deps/gettext/gettext-tools/src/x-javascript.c#L955). 

This seems to only happen on Files containg JSX. It dose not care if the File contains Translations. 

Translations in the file are found and placed in the pot until the error occurs.

# Example: 

The Example on github: [mi-roh/bugPoeditJSX](https://github.com/mi-roh/bugPoeditJSX).

## languages/example.pot

```pot
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Example\n"
"Report-Msgid-Bugs-To: https://wordpress.org/support/plugin/form-configurator-"
"guten\n"
"POT-Creation-Date: 2019-08-30 15:42+0200\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2019-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: \n"
"X-Generator: Poedit 2.2.3\n"
"X-Poedit-KeywordsList: __;_e;__ngettext:1,2;_n:1,2;__ngettext_noop:1,2;"
"_n_noop:1,2;_c,_nc:4c,1,2;_x:1,2c;_nx:4c,1,2;_nx_noop:4c,1,2;_ex:1,2c;"
"esc_attr__;esc_attr_e;esc_attr_x:1,2c;esc_html__;esc_html_e;esc_html_x:1,2c\n"
"X-Poedit-Basepath: ../js\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Poedit-SearchPath-0: .\n"

#: worksWithTranslation.js:4
msgid "Translate Me"
msgstr ""
```

*I tried this with and without X-Poedit-KeywordsList, Plural-Forms and other configurations. For Completnes, just in case there is a mistace by wrong configuration*

## js/breaks.js 

```js
function funcName () {
    return <div>
        <span className="someClassName">
            <span className="anotherClass" />
        </span>
    </div>;
}
```

## js/works.js

```js
function funcName() {
    return <div>
        <span className="someClassName" />
    </div>
}
```

## js/breaksWithTranslation.js

```js
function funcName () {
    return <div>
        <span className="someClassName">
            <span className="anotherClass">
                { __( 'Translate Me To', 'example' ) }
            </span>
        </span>
    </div>;
}

function funcName2() {
    return <div>
        <span className="someClassName">
            { __( 'Translate Me Not Found', 'example' ) }
        </span>
    </div>
}


```

## js/worksWithTranslation.js

```js
function funcName() {
    return <div>
        <span className="someClassName">
            { __( 'Translate Me', 'example' ) }
        </span>
    </div>
}

```

## Reproduce

Opening example.pot with poedit.app and runing `Katalog > Aktualisieren aus Quellcode` (Should be in English: `Catalog > Update from Code`) throughs a Error with the Detaild Log: 

```
breaks.js:8: Warnung: RegExp-Literal wurde zu früh terminiert
breaksWithTranslation.js:10: Warnung: RegExp-Literal wurde zu früh terminiert
```

(Should be in English: `... warning: RegExp literal terminated too early`). 

## Observation

- Switching from Lineending LF (\n) to CR (\c) 'solves' the Problem in 7 of 8 files in my Project – not in the Example shown above. I could not reproduce a short Example for this case.

# System

- OS: MacOs 10.14.6  
- Poedit: 2.2.3 (5738) (free Version)

Softwarecontext: 
- Wordpress plugin for new Gutenberg-Editor based on React and i18n in JS
- 200+ JS files
- 40+ from the JS files contaning React/JSX
- 8 of the files containg JSX fail with this Error. Expecialy all these files are semantically correct.

**Comment by vslavik** [comment]
The files are evidently not *JavaScript* files despite the misleading extension, so `xgettext`'s behavior is entirely unsurprising and follows the ages-old principle of [Garbage In, Garbage Out](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out). 

You need to use custom extractor for the [JSX language](https://reactjs.org/docs/introducing-jsx.html), such as https://github.com/zaach/jsxgettext I'll look into integrating it into Poedit, but can't make any specific promises yet. 

Using Commodore-era CR only for line termination is insane. Don't do that in 2019, even if it appears to help with something — it will cause many other problems elsewhere.

P.S. Wow, I appreciate the form and perfectness of the reproduction sample a *lot!*

**Comment by mi-roh** [comment]
Having poedit working with several files, and the pro-version of poedit naming Wordpress support, I thought its more a Bug than a feature request. Thanks for the clarification. 

Jsxgettext is worthy to have a look, but dose not suit my use case. 
For others reading this. As far as i can tell, Jsxgettext isn't configurable to match the complete wordpress-syntax. f.e.:
WP `_n`: jsxgettext requires n to be at the begining of a plural function name
WP `_x`: jsxgettext seems to have no context (pgettext) logic implemented

P.S. CR of course only temporary for debugging, never permanent. And I hate Bug-reports only saying "It's not working." :)

**Comment by vslavik** [comment]
Another alternative would be http://babel.pocoo.org/ — alternative extractor written in Python with support for both ES6 (which was a problem for xgettext too until 0.20) and JSX out of the box. Poedit already uses some bits written in Python, so it would be easy enough to bundle.

**Comment by vslavik** [comment]
I was wrong about this.

Apparently GNU gettext *is* supposed to handle JSX. This is evidenced by https://savannah.gnu.org/bugs/?56848 where another similar parsing problem was fixed and which shows that the parser has code for handling XML content already. Therefore this is a legitimate bug… in `xgettext` rather than Poedit, though.

In trying to formulate GNU gettext bugreport I realized I don't understand what the difference between "works" and "breaks" here is — do you? It is *not* the trailing `;` and isn't just any occurrence of `</` either, so what is the crucial difference here? I'm looking for something akin to the "self-closing tags" bit in #56848 above.

**Comment by mi-roh** [comment]
It shouldn't be the trailing `;` – My examples arent clean written in this point. 

It seems to be the depth of nesting. The Example below is the Code of breaks.js but without the nesting in JSX it self, and it works. 

```
function funcName () {
    const x = <span className="anotherClass" />;

    return <div>
        <span className="someClassName">
            { x }
        </span>
    </div>;
}
```

**Comment by mi-roh** [comment]
Now I'm getting confused. Placing the function from my last comment into a File that breaks – lets the File be handeld as it should... 

Finaly I added the following Function to all of the Files in my project breaking (shorter Version of the above one) – and it Fixing all Files.
 
```
function fixGetText () {
    const x = <span />;
    return <div><span>{ x }</span></div>;
}
```
As soon I remove one of the JSX-Elements or place it directly into the nesting it breaks again.

**Comment by mi-roh** [comment]
By testing the Files, I found a nother working/breaking Example without nesting and without touching the JSX-Parts: 

breaks: 
```
export function funcName( props ) {
    return <a { ...props } href={ 'y' }>{ 'x' }</a>;
}
```

works: 
```
export function funcName( props ) {
    const a =  <a { ...props } href={ 'y' }>{ 'x' }</a>;
    return a;
}
```

**Comment by vslavik** [comment]
I tried to figure the bug out on my own returning to it twice, but finally admitted defense and filed an upstream bugreport at https://savannah.gnu.org/bugs/index.php?57927

**Comment by vslavik** [comment]
This is now fixed in GNU gettext. I'd like to relay Bruno's (_the_ GNU gettext maintainer) thanks for your work on isolating this bug. 

(Leaving the bug open until bundled GNU gettext is updated or I backport the patch; as the patch is pretty big, I'd like to give it a bit of time for potential regressions to be spotted.)
