### ISSUE TITLE
Editor scrolls up unwantedly

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#602]
When I edit a large message at the bottom, the editor automatically scrolls up so that I cannot see the text I'm currently writing. An example is in https://translationproject.org/PO-files/de/bash-5.0.de.po, the entry starting with "Removes entries from the directory".

Poedit 2.2.3 (5738)
Windows 10.0.18362.356
Custom text fields font: Consolas 16pt

There are various similar effects related to this.
Sometimes, whenever I scroll to the bottom, the editor scrolls up automatically.
When I type text at the bottom, the text cursor goes invisible and the text field flickers for a moment since it scrolls up and then immediately down again.

**Comment by vslavik** [comment]
> the editor automatically scrolls up

When, i.e. after having done what?

**Comment by rillig** [comment]
> When, i.e. after having done what?

After typing some text. Anyway, it works perfectly today. As soon as I have more precise instructions to reproduce it, I will open it again.

**Comment by vslavik** [comment]
Thanks, please do — I was mystified by this because I couldn't trigger the described behavior with something as simple as just typing something even with larger texts...
