### ISSUE TITLE
translation suggestions problem

### ISSUE THREAD

**Issue by Xoristzatziki** [vslavik/poedit#607]
I have this "`_No`", as source text, which never shows any "translation suggestion" when creating an **el** translation, although I have translated it (as "`Ό_χι`") in many po files. Is it a bug or by design?

problem in both:
ubuntu 18.04, poedit 2.0.6
and
ubuntu 16.04, poedit 1.8.7.1

**Comment by vslavik** [comment]
Sorry, this makes no sense to me. Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue) and provide a more detailed explanation.
