### ISSUE TITLE
feature request: non flat names and paths of generated po files

### ISSUE THREAD

**Issue by Xoristzatziki** [vslavik/poedit#608]
Since gettext (at least in my ubuntu python) expects a language translation to be in:
```
Translations root folder
|   domain.id.pot
|__ LANG_CODE
|       |__ LC_MESSAGES
|              |   domain.id.mo
|              |   domain.id.po
```

users expect from poedit, when they open their domainid.pot to create a new translation, that this will be created based on the above structure and their po will be placed with an identical domain.id into the subfolder LC_MESSAGES of LANG_CODE folder.
Also their required paths (ex. X-Poedit-Basepath) to point at folders "converted" from the pot location to the new location.

**Comment by vslavik** [comment]
Sorry, I don't understand what you're trying to say, nor why you think it should be Poedit's job. Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue) and provide a more detailed explanation.

**Comment by vslavik** [comment]
@Xoristzatziki why did you waste everybody’s time filing these incomprehensible issues then, if you then just silently close them? Very rude. Sigh.
