### ISSUE TITLE
Group selection on items list

### ISSUE THREAD

**Issue by zio-pietro** [vslavik/poedit#609]
I tried to edit old .po file, found it too old. Contacted program author, obtained new version of .po file. After some hours of work I discovered some missing items, updating from source impossible due to absolute references (extract relative references with xgettext is easy, seems to me author didn't know the right procedure).
Finally I make fresh .po file, extracted from sources (this time with relative references) to redo whole translation. After pre-translation I've almost all translated well (thanks to Poedit cache and my precedent work with this translation). The last two things left to do are: correct a few badly translated entries and for all other ones change sign "Need verification".
Now I see whole screen with items translated well and I must do kbd/mouse gymnastic: Ctrl-down, click deselect "need verify", Ctrl-down, click, Ctrl-down, ... It's boring, frustrating and error prone.
It would be nice to have the possibility to select group of items (classic click first, Shift-click the last or Ctrl-click for non-continuous group) and change "need verify" for selected group with one click.
Opening .po with text editor and group delete _#, fuzzy_ comment isn't the solution, some voices really need verification.

**Comment by vslavik** [comment]
> Now I see whole screen with items translated well and I must do kbd/mouse gymnastic: Ctrl-down, click deselect "need verify", Ctrl-down, click, Ctrl-down, ... It's boring, frustrating and error prone.

Alternatively, you could have used the sane workflow for updating from a POT file, as explained in the GNU gettext manual. Or if you paid attention to the pre-translate window and *read* the options, you wouldn't have to unflag anything.

> It would be nice to have the possibility to select group of items (classic click first, Shift-click the last or Ctrl-click for non-continuous group) and change "need verify" for selected group with one click.

Perhaps you should look in the *Edit* menu. This is possible for ages.
