### ISSUE TITLE
Spellcheck not working on ArchLinux

### ISSUE THREAD

**Issue by TB1234** [vslavik/poedit#610]
OS: ArchLinux
Poedit installed via snap (2.2.4)
![poedit_spellcheck](https://user-images.githubusercontent.com/9974734/70554861-3bb88880-1b7e-11ea-8626-39f93c4f3031.png)

aspell and aspell-de is installed:

    $ sudo pacman -Ss aspell*
    extra/aspell 0.60.8-1 [Installiert]
        A spell checker designed to eventually replace Ispell
    extra/aspell-de 20161207-2 [Installiert]
        German dictionary for aspell
    extra/aspell-en 2018.04.16-1 [Installiert]
        English dictionary for aspell
    extra/aspell-es 1.11-7
        Spanish dictionary for aspell
    extra/aspell-fr 0.50.3-8

Also gtkspell3 is installed:

    $ sudo pacman -Ss gtkspell3 
    community/gtkspell3 3.0.10-2 [Installiert]
        Provides word-processor-style highlighting and replacement of misspelled
        words in a GtkTextView widget

If I start poedit from the command line, I found this errors:

    ** (net.poedit.Poedit:36321): CRITICAL **: 18:54:25.894: check_range: assertion 'spell->priv->speller != NULL' failed
    ** (net.poedit.Poedit:36321): CRITICAL **: 18:54:25.895: check_range: assertion 'spell->priv->speller != NULL' failed
    ** (net.poedit.Poedit:36321): CRITICAL **: 18:54:25.895: check_range: assertion 'spell->priv->speller != NULL' failed

Any ideas what is going wrong here?

**Comment by vslavik** [comment]
> aspell and aspell-de is installed:
…
> Also gtkspell3 is installed:

That is all but irrelevant to *snaps*. 

> Any ideas what is going wrong here?

No, sorry. Poedit's snap does come with spellchecker dictionaries installed.

**Comment by TB1234** [comment]
Hm, thank you for your fast reply. Is there another way to get a Pro/Pro+ version? The version I got via pacman is the source version without the option to enter a licence and get the Pro features.

Or do you know, if there's an opportunity for me to debug the snap package to find the problem?

**Comment by vslavik** [comment]
Fix pushed to snap.
