### ISSUE TITLE
Don't show warnings for fuzzy entries

### ISSUE THREAD

**Issue by lanurmi** [vslavik/poedit#611]
The warnings about inconsistent capitalization, missing full stops, etc. are mostly quite useful. However, warnings are also shown for *fuzzy* entries, and in that context the warnings are mostly noise, as automatically generated fuzzies can contain nearly anything, and incorrect capitalization is seldom the only nor the most crucial thing requiring work for such an entry.

If there was a distinction between automatically generated fuzzies and ones with the fuzzy flag set by the user, in that case obviously it would still make sense to show warnings for the latter.

My Poedit version: 2.2.4, on Windows 7.

**Comment by vslavik** [comment]
>  in that case obviously it would still make sense to show warnings for the latter.

Would it? I think your (great!) point applies to them equally well, doesn't it? If it's explicitly marked as *needs work*, i.e. known imperfect, doesn't it too make sense to stop bugging about it until the translator says "I think it's good now" by un-fuzzying the string?

**Comment by lanurmi** [comment]
> 
> 
> > in that case obviously it would still make sense to show warnings for the latter.
> 
> If a string is explicitly marked as _needs work_, i.e. known imperfect, by the translator, doesn't it too make sense to stop bugging about it until the translator says "I think it's good now" by un-fuzzying the string?

It does. However, with a manually fuzzied string the translator is likely to have consciously entered some kind of a translation whose meaning and punctuation resembles that of the original string... whereas with automatic fuzzies the "translation" may not have anything to do with the original.

Nevertheless, that statement was meant to be a mere speculative sidenote rather than the essence of this issue. I have expressed my opinion, and you have expressed yours. I am not going to argue about this.

**Comment by vslavik** [comment]
> Nevertheless, that statement was meant to be a mere speculative sidenote

Yes, of course, that's understood. 

> I have expressed my opinion, and you have expressed yours.

The point of my comment was that I don't *have* a well-formed opinion and wanted to reach, through discussion, not arguing, a better understanding of what should *ideally* happen (while it may be difficult with PO files due to the aforementioned ambiguity of the fuzzy flag, there's more flexibility with XLIFF).

Regarding where you see the warnings on fuzzies as mostly noise, it's in the list, correct? I think they should still be shown in the editing area when you're editing such entry, or do you think it's pointless there too?

**Comment by lanurmi** [comment]
> The point of my comment was that I don't _have_ a well-formed opinion and wanted to reach, through discussion, not arguing, a better understanding of what should _ideally_ happen

Good to hear that.

> Regarding where you see the warnings on fuzzies as mostly noise, it's in the list, correct? I think they should still be shown in the editing area when you're editing such entry, or do you think it's pointless there too?

Yes, that is correct. To formulate my opinion more clearly: The warning icon beside the fuzzy message in the list does not bother me per se – the noisiness is caused by the fact that such messages with warnings are sorted to the top of the list (because I have that preference enabled). And I like having warnings at the top of the list in general, but not warnings about fuzzies, because they are not higher-priority than any other fuzzies.

**Comment by vslavik** [comment]
> The warning icon beside the fuzzy message in the list does not bother me per se – the noisiness is caused by the fact that such messages with warnings are sorted to the top of the list

The above commit addresses it by not sorting fuzzy items with warnings to the top.

I decided to keep the list icon after all, because it was weird in the UI otherwise: un-fuzzying an item while editing would pop a new icon.
