### ISSUE TITLE
Opening files as relative through CLI breaks FileViewer

### ISSUE THREAD

**Issue by ederag** [vslavik/poedit#612]
After the [migration](https://wiki.gnome.org/MigratingFromIntltoolToGettext) of [hamster](https://github.com/projecthamster/hamster) from `intltools` to pure `gettext`,
`poedit` seems to play less nicely with relative paths (unless I'm missing something, of course).
Previous similar issues were either unclear or clearly different to me.

[Here](https://github.com/vslavik/poedit/files/4003336/hamster-poedit_19c26.tar.gz) is a minimal example, generated from the [update-i18n](https://github.com/ederag/hamster/tree/update-i18n) experimental branch by these commands:
```bash
cd ~/tmp
mkdir hamster-poedit
cd hamster-poedit
mkdir data
cp ~/share/prog/python/hamster/data/edit_activity.ui data/
mkdir po
echo "data/edit_activity.ui" > po/POTFILES.in
xgettext --files-from=po/POTFILES.in --default-domain=hamster --from-code=UTF-8 --keyword=_ --keyword=N_ --keyword=C_:1c,2 --keyword=NC_:1c,2 --keyword=g_dngettext:2,3 --add-comments --output=po/hamster.pot
msggrep --location=data/edit_activity.ui ~/share/prog/python/hamster/po/fr.po > po/fr.po
cd ..
tar cvfj hamster-poedit_19c26.tar.gz hamster-poedit/
```
Then
```bash
cd hamster-poedit/
poedit po/fr.po
# or cd po/ && poedit fr.po
```
Right click on the first line (`Add Earlier Activity`), then in the popup menu, 
navigate to the last item (`data/edit_activity.ui:15`) and release the mouse button.
![Screenshot_20191226_210216](https://user-images.githubusercontent.com/10962809/71488845-08832400-2823-11ea-8b90-8d65f6a7ddfe.png)
Which yields the following error window
![Screenshot_20191226_210348](https://user-images.githubusercontent.com/10962809/71488875-39635900-2823-11ea-842e-92c3a310c6da.png)
instead of showing the `data/edit_activity.ui` source file.

Workaround: 
Go to `Catalog>Properties>Source Paths>Add Folders` and select the root folder (`hamster-poedit`)
`.` appears in the path list.
But that has to be done each time a po is opened, and I'd rather spare the translators the trouble.

Of course it would be possible to add `../` in front of all `POTFILES.in` lines,
but that is not the way recommended in the [gettext documentation](https://www.gnu.org/software/gettext/manual/html_node/po_002fPOTFILES_002ein.html#po_002fPOTFILES_002ein):
> relative to the top level of your whole distribution, rather than the location of the `POTFILES.in` file itself

Checked with `poedit-2.2.1` on `openSUSE Leap-15.1`.
Sorry, I did try the latest `2.2.4-oss`, but the configure step failed with
```configure
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... no
configure: error: Could not link against boost_system !
```
That could be a problem on my side, and is not the subject of this issue at all.

The poedit changelog since 2.2.1 did not indicate any relevant change.
Nevertheless, I could try the snapcraft package (that's new to me), please let me know.

**Comment by vslavik** [comment]
> poedit po/fr.po
> or cd po/ && poedit fr.po

This wasn't a trivial realization to make, but it turns out that *this* above is the only relevant bit in the whole description — use of a *relative* filename as command line argument. The rest of this issue is irrelevant to the bug observed; the expected behavior for such not-quite-relative filenames is already fully implemented since 2013's fce4f65.

**Comment by ederag** [comment]
> this above is the only relevant bit in the whole description

This is offending, and I disagree. The screenshot and what follows shows the result and the issue.

Nevermind, but there is an inconsistency between your own recommendations 
(there used to be a link to https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) 
asking for detailed bug reports.

**Comment by vslavik** [comment]
> This is offending, and I disagree.

This is a note documenting progress on fixing a bug. That's what people *do* to organize their thoughts while working through something non-trivial. It is a strictly objective statement of fact, correctness of which will be made abundantly clear by an upcoming commit. You may "disagree" with it, but that's all you can do about the *fact* that this little side-note describes the actually relevant part; the rest is, *after analysis*, just coincidental noise, and further work on this issue can freely ignore it.

For crying out loud, I *prefixed* it by saying this wasn't trivial to realize (even with my knowledge of the codebase), just in case you were overly touchy and might read it as an attack on your ego. Chill out. You don't need to look that hard for something to get offended by.
