### ISSUE TITLE
Poedit after draft translation of lines shows a different number of lines

### ISSUE THREAD

**Issue by Dizer7** [vslavik/poedit#614]
The Poedit after draft translation of lines shows a different number of lines. I noticed this after the last update. I have the current version: 2.3 (PRO)
Screenshot: [http://prntscr.com/r0v1vn](http://prntscr.com/r0v1vn)

**Comment by vslavik** [comment]
Some strings were pre-translated twice (once from your local TM, once online with a better match). It's just a stupid display quirk.

Closing as it doesn't affect the OSS version this tracker is for.
