### ISSUE TITLE
Feature: suppress specific warnings on a translated message

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#615]
It's time for me to translate GCC again. One of the messages to translate is:

> ![image](https://user-images.githubusercontent.com/3233724/74372856-b189dc00-4ddb-11ea-9ba5-5b081f18d69d.png)

In this particular case, the warning is wrong. I am sure that I want to start the German message with a lowercase letter. Therefore I'd like to mark this warning as a false positive, and it should not be shown anymore.

My idea of solving this is to save a do-not-show marker either in the .po file itself (to share the marker with other translators) or in some local storage (to just hide it for me). The marker should only apply as long as `msgid`, `msgstr` and the text of the warning stay the same. As soon as any of them changes, the warning should appear again.

**Comment by vslavik** [comment]
> My idea of solving this is to save a do-not-show marker either in the .po file itself (to share the marker with other translators) or in some local storage (to just hide it for me). The marker should only apply as long as msgid, msgstr and the text of the warning stay the same.

That's pretty much how I want to do it, yes. Good point that the *warning* needs stay the same too.

While the PO format allows such flags easily, GNU gettext tools strip all unknown flags (e.g. `angular-format`) away, so practically speaking, the flag would have to go into a specially-formatted comment.

I'm not sure if it's good idea to pollute the file for non-Poedit translators when it concerns silencing Poedit's misbehavior in the first place, too; in that regard, local storage seems preferable. I was also thinking about (privately) crowd-sourcing this by having Poedit's server sync hashes of to-be-ignored warnings, but am unsure about the usefulness (certainly extremely limited for you specifically given the subject domain).

**Comment by jamielaw-jellyfish** [comment]
I've discovered another example of such a false positive. I am translating a list of devices, and one entry that causes trouble is

> pH Monitor

which in, say, Spanish is

> Monitor de pH

Poedit warns me that the translation should start with a lowercase character: in this case, it shouldn't. It's easily ignorable, but I felt it was worth documenting it here as another example.

**Comment by vslavik** [comment]
I forgot to close this; individual mis-warning suppression is implemented in Poedit 3.
