### ISSUE TITLE
Update from TWIG source code not working 100%

### ISSUE THREAD

**Issue by HJerem** [vslavik/poedit#620]
Hi I'm using [CakePHP](https://cakephp.org/) with [TwigView](https://github.com/cakephp/TwigView).
I use POEdit to translate to multiple languages, and I update **NOT** from `.pot` file but from source code (mostly `.php|.twig` files).
It's working almost perfectly, except for some strings placed in `{% element %}`, which is specific to [TwigView](https://github.com/cakephp/TwigView#elements). It's like include but for CakePHP.

Here is code where strings ` __(` are not extracted :
```twig
{% if not account.host.stripe_account %}
    {% element 'Components/Management/todo' {state: 'to finish', name: __('Set up payment info to receive earnings'), href: Url.build({action: 'createStripe'})} %}
{% elseif account.host.stripe_account_status != 'enabled' %}
    {% element 'Components/Management/todo' {state: 'to finish', name: __('Update payment info to receive earnings'), href: Url.build({action: 'updateStripe'})} %}
{% else %}
    {% element 'Components/Management/todo' {state: 'completed', name: __('Set up payment info to receive earnings'), href: '#'} %}
{% endif %}
```

I can't find `Set up payment info to receive earnings` or `Update payment info to receive earnings` on POEdit. I'm using PRO version with latest update.
I guess it's not working because it's specific to TwigView.

**Comment by vslavik** [comment]
Please email help@poedit.net directly; this is a tracker for the open source version, not Pro. Please also include the actual full files needed to reproduce (incl. both Twig and PO files). Don't forget to mention your exact Poedit version ("with latest update" is a bit vague) and platform.

Thanks!
