### ISSUE TITLE
build dependency for *.mo files missing

### ISSUE THREAD

**Issue by 0-wiz-0** [vslavik/poedit#622]
There is a missing dependency in `locales/Makefile.am`. When I do 'make && make install', the `*mo` files do not exist and installation fails. I have to manually run `make allmo` before `make install`.

**Comment by vslavik** [comment]
Working as intended. Read the `README` file, thus named for obvious reasons, which describes how to build from git checkouts, as you're doing (even though you don't bother to say so).

**Comment by 0-wiz-0** [comment]
Actually, I was just using the wrong tarball, it seems.
`https://github.com/vslavik/poedit/archive/v2.3-oss.tar.gz` instead of `https://github.com/vslavik/poedit/releases/download/v2.3-oss/poedit-2.3.tar.gz`

**Comment by vslavik** [comment]
So, *actually*, compiling from git checkout.
