### ISSUE TITLE
Add global source keywords

### ISSUE THREAD

**Issue by daveh** [vslavik/poedit#626]
Source keywords can be added to a specific catalogue that are used when extracting from the source code. However this has to be done per catalogue. It would be great if you could configure some global source keywords that are added to each catalogue by default.

**Comment by vslavik** [comment]
> However this has to be done per catalogue

And there's a *reason* for that: the keywords are linked to the source code you're extracting from, and so it doesn't make sense to customize globally *or* to put their configuration outside of VCS.

If you're putting configuration into many individual POs, don't: use a single POT instead.

FWIW, gettext already has "global" keywords: the default ones.

**Comment by daveh** [comment]
Ok, understood, thank you for the quick reply and clarification.
