### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by comradekingu** [vslavik/poedit#628]
From time to time I use Poeditor, and despair over not being able to improve the language in it.
It generally doesn't help seeing bad language when the task at hand is often trying to focus on doing the exact same, or in the very least remain attentive to the tall order of making sure ones own translations are as good as possible.

Crowdin is a lackluster tool in that regard, with tracking left right and center, being closed source to add insult and injury to the mix.

https://weblate.org/hosting/ offers gratis hosting to all libre software projects, regardless of whether they have a source of income or not. Like I imagine Poedit doesn't enjoy the pressure of. It is itself translated on Weblate, and it would help ensure consistency of the strings shared between the two if both were on Hosted Weblate https://weblate.org/hosting/

This would help with #551 and avoid #625.

**Comment by vslavik** [comment]
Please refrain from this kind of blatant spam. It's not welcome.
