### ISSUE TITLE
Dark mode switching while Poedit is running leaves artifacts

### ISSUE THREAD

**Issue by VulpesVulpes825** [vslavik/poedit#630]
In macOS 10.15.3, Poedit 2.3's sidebar will stay in light mode when the macOS has switch to dark mode. However, when the sidebar stays in light mode, the text in the sidebar has changed to white, which makes it impossible to see translation suggestions as well as the notes for translators.

**Comment by vslavik** [comment]
No, it is that way temporarily when you *switch* the theme. Restart Poedit. 

There are more such discrepancies. I'm aware of them. It's a rather minor issue.
