### ISSUE TITLE
Race condition on Crowdin upload, messes future syncing

### ISSUE THREAD

**Issue by vslavik** [vslavik/poedit#638]
As reported by @tetatetit: under following circumstances double-upload happens:

> 1. In the released v2.3 Poedit open any PO file from Crowdin (via Open from Crowdin or just > downloaded in browser via Crowdin UI)
> 2. Make any changes to any translation in that file in Poedit
> 3. Press Sync
> 4. Press Save in Do you want to save changes question dialog box
>
> Result: If you put breakpoint or log entry in CrowdinClient::UploadFile() - you will notice it's called twice on this step (i.e. after above Save pressed)

It's not quite that, in my testing:
1. couldn't be always reproduced, double upload happened sometimes, not always
2. required in-app open from Crowdin, didn't happen with files opened normally but having Crowdin metadata

Point 2 makes sense: sync on Save is done only when opening directly, and appears related.

Strangely, doing these steps repeatedly did *not* cause it again — and using Save second and more times didn't trigger syncing as it is supposed to.

This is arguably also an issue about confusing UI: there's a Sync button and Save, but under some circumstances, they do the same thing, or nearly the same thing.

**Comment by vslavik** [comment]
Part of #633 proposed fix like this (note that part of that patch is probably responsible for introducing the difference in behavior in point 2 above):

```diff
diff --git a/src/edframe.cpp b/src/edframe.cpp
index 0291d25817..240aaa9668 100644
--- a/src/edframe.cpp
+++ b/src/edframe.cpp
@@ -1039,7 +1039,7 @@ bool PoeditFrame::NeedsToAskIfCanDiscardCurrentDoc() const
 }
 
 template<typename TFunctor>
-void PoeditFrame::DoIfCanDiscardCurrentDoc(TFunctor completionHandler)
+void PoeditFrame::DoIfCanDiscardCurrentDoc(TFunctor completionHandler, bool bSkipUpload)
 {
     if ( !NeedsToAskIfCanDiscardCurrentDoc() )
     {
@@ -1049,7 +1049,7 @@ void PoeditFrame::DoIfCanDiscardCurrentDoc(TFunctor completionHandler)
 
     wxWindowPtr<wxMessageDialog> dlg = CreateAskAboutSavingDialog();
 
-    dlg->ShowWindowModalThenDo([this,dlg,completionHandler](int retval) {
+    dlg->ShowWindowModalThenDo([this,dlg,completionHandler,bSkipUpload](int retval) {
         // hide the dialog asap, WriteCatalog() may show another modal sheet
         dlg->Hide();
 #ifdef __WXOSX__
@@ -1058,7 +1058,7 @@ void PoeditFrame::DoIfCanDiscardCurrentDoc(TFunctor completionHandler)
         // from event loop (and not this functions' caller) at an unspecified
         // time anyway, we can just as well defer it into the next idle time
         // iteration.
-        CallAfter([this,retval,completionHandler]() {
+        CallAfter([this,retval,completionHandler,bSkipUpload]() {
 #endif
 
         if (retval == wxID_YES)
@@ -1067,7 +1067,7 @@ void PoeditFrame::DoIfCanDiscardCurrentDoc(TFunctor completionHandler)
                 WriteCatalog(fn, [=](bool saved){
                     if (saved)
                         completionHandler();
-                });
+                }, bSkipUpload);
             };
             if (!m_fileExistsOnDisk || GetFileName().empty())
                 GetSaveAsFilenameThenDo(m_catalog, doSaveFile);
@@ -1174,8 +1174,6 @@ void PoeditFrame::OnOpenFromCrowdin(wxCommandEvent&)
     DoIfCanDiscardCurrentDoc([=]{
         CrowdinOpenFile(this, [=](wxString name){
             DoOpenFile(name);
-            if (m_catalog)
-                m_catalog->AttachCloudSync(std::make_shared<CrowdinSyncDestination>());
         });
     });
 }
@@ -1846,8 +1844,11 @@ void PoeditFrame::OnUpdateFromCrowdin(wxCommandEvent&)
             EnsureAppropriateContentView();
             NotifyCatalogChanged(m_catalog);
             RefreshControls();
-        });
-    });
+        });  
+    }, true); // Set bSkipUpload to true to avoid twice upload of exactly same file with "Sync" button pressed once
+              // 1. DoIfCanDiscardCurrentDoc()=>WriteCatalog()=>CloudSyncProgressWindow::RunSync()=>CrowdinSyncDestination::Upload()=CrowdinClient::UploadFile()
+              // 2. <above lambda>=>CrowdinSyncFile()=>CrowdinClient::UploadFile()
+              // Otherwise reproducable with any file for which "Sync" (with Crowdin) button is active and pressed
 }
 
 void PoeditFrame::OnUpdateFromCrowdinUpdate(wxUpdateUIEvent& event)
@@ -2737,7 +2738,7 @@ void PoeditFrame::WriteCatalog(const wxString& catalog)
 }
 
 template<typename TFunctor>
-void PoeditFrame::WriteCatalog(const wxString& catalog, TFunctor completionHandler)
+void PoeditFrame::WriteCatalog(const wxString& catalog, TFunctor completionHandler, bool bSkipUpload)
 {
     wxBusyCursor bcur;
 
@@ -2796,10 +2797,11 @@ void PoeditFrame::WriteCatalog(const wxString& catalog, TFunctor completionHandl
     if (ManagerFrame::Get())
         ManagerFrame::Get()->NotifyFileChanged(GetFileName());
 
-    if (m_catalog->GetCloudSync())
-    {
+    if(!m_catalog->GetCloudSync() && m_catalog->IsFromCrowdin())
+        m_catalog->AttachCloudSync(std::make_shared<CrowdinSyncDestination>());
+    
+    if (!bSkipUpload && m_catalog->GetCloudSync())
         CloudSyncProgressWindow::RunSync(this, m_catalog->GetCloudSync(), m_catalog);
-    }
 
     if (tmUpdateThread.valid())
         tmUpdateThread.wait();
diff --git a/src/edframe.h b/src/edframe.h
index 244e100090..766f76faff 100644
--- a/src/edframe.h
+++ b/src/edframe.h
@@ -116,7 +116,7 @@ class PoeditFrame : public PoeditFrameBase
         void WriteCatalog(const wxString& catalog);
 
         template<typename TFunctor>
-        void WriteCatalog(const wxString& catalog, TFunctor completionHandler);
+        void WriteCatalog(const wxString& catalog, TFunctor completionHandler, bool bSkipUpload = false);
 
         void FixDuplicatesIfPresent();
         void WarnAboutLanguageIssues();
@@ -203,7 +203,7 @@ class PoeditFrame : public PoeditFrameBase
         // if there's modified catalog, ask user to save it; return true
         // if it's save to discard m_catalog and load new data
         template<typename TFunctor>
-        void DoIfCanDiscardCurrentDoc(TFunctor completionHandler);
+        void DoIfCanDiscardCurrentDoc(TFunctor completionHandler, bool bSkipUpload = false);
         bool NeedsToAskIfCanDiscardCurrentDoc() const;
         wxWindowPtr<wxMessageDialog> CreateAskAboutSavingDialog();
 
```

**Comment by tetatetit** [comment]
> couldn't be always reproduced, double upload happened sometimes, not always

Well reproducable __always__, but __only__ when yes, opened via `Open from Crowdin`, file modified and then `Sync` pressed.

**Comment by vslavik** [comment]
> Well reproducable always

I am one able to reproduce it always, I did observe some occurrences when the request was done once.

**Comment by tetatetit** [comment]
> > Well reproducable always
> 
> I am one able to reproduce it always, I did observe some occurrences when the request was done once.

I just wanted to point that's quite (unless most) frequent use case/flow in Poedit<=>Crowdin integration which might create essential inconvenience in case of big files in conjunction with weak internet connection (that's in turn why most users to chose Poedit to work with Crowdin, since in case of good connection - it's more effectively for them to use Crowdin web UI/app itself), as well might essentially increase load on Crowdin API server (due of this duplication of actually same operation)

**Comment by vslavik** [comment]
Your UX suggestion over in #641 led me to a moment of clarity regarding this as well. What this bug boils down to is this:

**Should the user even be asked if they want to save the file in the first place in this case?**

And I think the answer is no. I can't think of any situation when it would be desirable to sync your changes to Crowdin, but *not* save them locally. Can you? 

Put differently, I think the sync action is a *more serious* form of Save: you're not just saving things locally, you're pushing it out to the world. If you're not committed to your changes enough to have them saved in your file, they certainly shouldn't end up on Crowdin. It's like git: you can't push (sync to server) without committing (save) locally first.

So I think this mess can be avoided by simply a) always saving as part of sync and b) doing explicit sync only if there's no attached `CloudSyncDestination`.

**Comment by tetatetit** [comment]
> So I think this mess can be avoided by simply

> a) always saving as part of sync

Fully agree

and b) doing explicit sync only if there's no attached `CloudSyncDestination`.

Could you @vslavik please just better clarify:

1. what you mean under "explicit sync" here (then which is "implicit sync" or so?) 
2. in what exactly case there are "no attached `CloudSyncDestination`" when we are able still to sync "explicitly"?

Since that just might help me and other to better follow current Poedit concepts/semantics/logic here and to participate in contribution to Poedit or so. Thanks a lot

**Comment by vslavik** [comment]
explicit = when the user does something with the goal of doing it (click "sync" button to sync);
implicit = when it is done as a consequence of other action (saving something that is remote and so must be synced)
