### ISSUE TITLE
This project has no files that can be translated in Poedit

### ISSUE THREAD

**Issue by mHatsune** [vslavik/poedit#639]
Some popular projects have that problem
https://crowdin.com/project/x64dbg
https://crowdin.com/project/ublock
https://crowdin.com/project/obs-studio
https://crowdin.com/project/bitwarden-browser

**Comment by vslavik** [comment]
As of now, Poedit is for editing PO files.

If you look at open pull requests, you will see #633 that addresses it.

**Comment by mHatsune** [comment]
Thanks. kindly bear with me and i still have several questions about poedit (no documentation on site either)

1. Does that also address 'this file can only be edited in crowdin's web interface'?
https://crowdin.com/project/protonmail Eg: protonmail android 
2. About translator memory(personal dictionary). Is it possible to enhance that feature to,
     - view words history in separate window with option to edit, copy them manually 
     - custom option for only add necessary words to memory during translate. I mean similar popular office software
     - view which projects have used that translation and ability to sync for all projects if modify it
3. poedit terms 'Usage statistics of online suggestions and pre-translation are collected on license key basis for the purpose of license metering.'
can you clarify the reason or purpose of 'license metering'. is it for offer discount for next purchased or something?
4. Remind, several days ago i requested to enable 'sinhala' language translation for Poedit
