### ISSUE TITLE
Poedit treat literal '%' in string as error

### ISSUE THREAD

**Issue by zhaoweny** [vslavik/poedit#645]
#### Environment
* Poedit version: 2.3.1 (5904) free (non-oss)
* Windows 1909 (Build 18363.720)
* Python 3.7
* wxPython 4.0.6

#### Example usage
see this python script:
```py
import wx
print(wx.GetTranslation('Subcaps w/missiles 100% spool up'))
```

#### What's expected

Poedit parses string and think `100%` is literally 100%

#### What happened instead

Poedit thinks `%` is part of escape sequence, prompt it as error on saving the PO file, which is annoying.

**Comment by vslavik** [comment]
No, Poedit respects `python-format` flag in your PO file. 

It is your responsibility as a developer using GNU gettext to do it properly:

https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html
https://www.gnu.org/software/gettext/manual/html_node/c_002dformat-Flag.html
