### ISSUE TITLE
using \n inside msgstr to seperate lines of the same msgtxt

### ISSUE THREAD

**Issue by shacharoz** [vslavik/poedit#649]
hi,
i would like to compare an excel sheet i receive from a translator to a PO file I get from the software.
to make sure the translator did all the work in a proper way and detect differences per msgtxt (which would always stay as is).

i was thinking to make an automatic comparison of:
1. additional or removal of msgtxt items.
2. change in the msgstr per language per msgtxt (compared to a previous document version).

my big issue is that they are using a weird format.
inside msgstr, they add \n to separate lines. so standard PO interpreters just put all msgstr in one line, while they separate it into several lines (keeping the \n in the end of the line).

i would like to write that rule into my interpreter as well (i cant change their way of work) 

is it possible with your tool?

**Comment by vslavik** [comment]
You need to fix weird files at the source of weirdness, instead of asking standard tools to do bizarre things that nobody else will need. I would suggest a custom tools to fulfill your custom needs.

I am, as many others, open to consulting gigs, but this is not the appropriate place.
