### ISSUE TITLE
Snap package fonts are broken on Fedora

### ISSUE THREAD

**Issue by samtuke** [vslavik/poedit#657]
All font glyphs are presented as squares; no text is readable.

**Comment by vslavik** [comment]
You're complaining about an issue with Snapcraft and your distibution; this has nothing to do with with Poedit. See the first Google hit for "snap font fedora": https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484

**Comment by maltere** [comment]
For anyone still having this error. This worked for me:

    rm -rf ~/.cache/fontconfig && sudo fc-cache -r -v
