### ISSUE TITLE
Support for WordPress JSON translations

### ISSUE THREAD

**Issue by redoper1** [vslavik/poedit#661]
Hello,

do you plan to implement compilation to JSON translation files to support JavaScript I18n for WordPress in future?

Right now we must run WP-CLI script after each translation update to get new translations to work in JavaScript messages.

(This feature was mentioned in this [news](https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/))

**Comment by vslavik** [comment]
Please get it touch via help@poedit.net for non-open source portions of Poedit Pro.

The reality is that I'm yet to encounter this is real use outside of WordPress core itself, hence why it wasn't a high priority. So practical examples from you would be useful.

**Comment by redoper1** [comment]
Yeah sure, no problem. I will get to that as soon as possible.

**Comment by pedro-mendonca** [comment]
Hi, would be awesome to be able to generate the .json files on .po file save, as it saves the .mo binary.

**Comment by vslavik** [comment]
And Poedit 3 already does that (via FTP connection): https://poedit.net/news/poedit3/

**Comment by pedro-mendonca** [comment]
Thanks @vslavik :-)

**Comment by vslavik** [comment]
Sure, it is *possible* (what isn't), it's just a matter of technical hurdles. It's coming.

**Comment by pedro-mendonca** [comment]
Thanks 😃

**Comment by pfk84** [comment]
As [gettext.js](https://github.com/guillaumepotier/gettext.js/) also uses JSON, would also highly appreciate an "Export to JSON" feature.
