### ISSUE TITLE
"Needs work" flag ignored for empty translations

### ISSUE THREAD

**Issue by fangly** [vslavik/poedit#662]
**Steps to reproduce:**
1. Open any PO file that has some empty translations with poedit (version 2.2.3, sorry I cannot easily test the latest version).
2. Then mark those using the "Needs work" flag
3. Finally save.

**Expected result:**
The saved PO file should have a "#, fuzzy" line for the corresponding PO entries, i.e. the translations are marked in the PO file as needing work.

**Obtained result:**
The saved PO file does not have a "#, fuzzy" line for the PO entries.

**Comment by vslavik** [comment]
Empty translation doesn't have a translation. Therefore the translation can't possibly be inaccurate and needing work because there is no translation at all yet.

This is GNU gettext, not Poedit, behavior, and it makes sense.

**Comment by fangly** [comment]
Ok, thank you for the explanation @vslavik. I was not aware of that gettext behaviour.

PS/ In my opinion, this behaviour is not optimal, at least not for a translation front-end. As a translator, I need to see where there is translation work to do, regardless of whether it is the translation of a new entry, or the revision of an existing translation.

**Comment by vslavik** [comment]
> As a translator, I need to see where there is translation work to do

If a string is untranslated, *by definition* there is translation work to do on it. Fuzzy + untranslated = work to do.

Usually, and I'm speculating here, such feelings of something as fundamental as this in gettext being "not optimal" stem from using gettext in other than normal ways, e.g. by having strings that shouldn't be translated present in PO files (and thus needing to differentiate between the ones to ignore and the ones to work on). Such things are best addressed in other parts of the workflow (i.e. not putting such strings into the file in the first place).

**Comment by fangly** [comment]
> If a string is untranslated, _by definition_ there is translation work to do on it.
Exactly!
But in poedit, an untranslated message (that was not explicitly marked as fuzzy) is shown in black, i.e. like a message that does not need work...

**Comment by vslavik** [comment]
It is *also* shown as *having no translation in the Translation column*.

Are you seriously complaining that it is unclear whether items *with no translation* need translating or not? 😳

**Comment by fangly** [comment]
Absolutely! If I have a single untranslated message hidden amongst hundreds of translated messages, I am likely to miss it unless it ishighlighted visually. See in the example below how the untranslated message does not exactly jump to the eyes.

![image](https://user-images.githubusercontent.com/231905/97270128-eab19180-182e-11eb-9230-6f8414b7031a.png)

I suggest an untranslated message should be highlighted in some way:
1. It could be highlighted like a message that "needs work" (orange color). Note that the shortcuts to navigate the previous and next unfinished translation (which I just discovered) already consider an untranslated message as unfinished (just like "need work" messages).
1. Alternatively, an untranslated message could be highlighted like a translation with a problem (warning symbol in the left column). This has the advantage of keeping the "needs work" highlighting specifically for fuzzy messages.

**Comment by vslavik** [comment]
> Absolutely! If I have a single untranslated message hidden amongst hundreds of translated messages, I am likely to miss it unless it is highlighted visually.

That's why work to be done is shown at the top of the list. By default. You are complaining about something you *intentionally changed* to behave this way, in the *View* menu. It's also non issue for navigation (*Go  →  Done and Next*) or for overview of work left to do (*Catalog  →  Statistics*).

The question of how to indicate untranslated entries (I disagree with your opinion, but realize opinions on that may differ) is off-topic in this issue; it's not about the "needs work" flag or its preservation.

**Comment by fangly** [comment]
Please do not take my feedback as a complaint, @vslavik . I appreciate the work you put in poedit, 

Call me unsophisticated, but the first thing I do when I open a PO file is scroll through the messages, which means that neither messages with warnings nor untranslated messages are highlighted (yes, it is possible that I may have disabled the option to show untranslated messages on top a long time ago).

Anyway, messages with warnings are highlighted (after saving). Fuzzy messages are also highlighted. But untranslated messages are _not_ highlighted. If you are fine with this, I failed to convince you. But that's your project and your choices. So I'll leave it at that... Cheers.

**Comment by vslavik** [comment]
> Please do not take my feedback as a complaint

I don't, I take it as *criticism*. Nothing wrong with that, it is a perfectly legitimate and often useful thing.

> (after saving)

The validate button in the toolbar does it too (and I agree it should be realtime; it's on my roadmap).

> messages with warnings are highlighted (after saving). Fuzzy messages are also highlighted. But untranslated messages are not highlighted.

The difference is that the former two have *issues* (bad translation, either explicitly marked as such, or detected with QA checks) — there are translation and they are *bad*. "Not yet translated" is not inherently a bad state. And often, when you open a file, *all* items are untranslated. You wouldn't want to highlight *everything*, at that point it just adds noise.

Anyway, I think I now see where you're coming from. I'm not sure if I agree, but it's something for me to think about.

Thanks!
