### ISSUE TITLE
Unfinished string

### ISSUE THREAD

**Issue by pewixg3** [vslavik/poedit#664]
Hi

I have a problem with Poedit since I reset my PC, I cannot update from my code. I have this error message (sorry for the French) : 
![image](https://user-images.githubusercontent.com/45328945/98216874-f5180d80-1f49-11eb-8095-9726ac976373.png)

On the error message I am prompted for line 14946 but this line is in comment
![image](https://user-images.githubusercontent.com/45328945/98216499-6f945d80-1f49-11eb-92bc-a7be15ce21ae.png)

I specify that everything worked fine before formatting my PC

Thank you in advance

**Comment by vslavik** [comment]
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue, but you decided to ignore it). Follow the instructions therein and provide the missing detailed information. Thanks!

**Comment by vslavik** [comment]
Closing as irreproducible.
