### ISSUE TITLE
Gilaki Language is not Existed

### ISSUE THREAD

**Issue by LordArma** [vslavik/poedit#667]
Hello.

I want to translate .po files with your greate softtware. Unfortunately there is not Gilaki in "Catalog properties" window in the "Language" section.

You can learn about Gilaki here:
https://en.wikipedia.org/wiki/Gilaki_language

Please add Gilaki to Poedit.

Thank You

**Comment by vslavik** [comment]
You can enter any ISO 639 code (such as `glk` here) in the language field. The pre-populated list of human-readable names comes from a library dependency and it's not feasible to adjust it in Poedit; an update to the library will probably take care of it at some point.

**Comment by LordArma** [comment]
> You can enter any ISO 639 code (such as `glk` here) in the language field. The pre-populated list of human-readable names comes from a library dependency and it's not feasible to adjust it in Poedit; an update to the library will probably take care of it at some point.

Hello again. May I know the name of that library? I wanna send an issue to them. Thank you.
