### ISSUE TITLE
unterminated string literal

### ISSUE THREAD

**Issue by vomikan** [vslavik/poedit#668]
Hi,

1)  poedit 2.4.2 (6064)
2) --
3) 
The following piece of c++11 code generates the warning:

![image](https://user-images.githubusercontent.com/6836805/101986929-16cf8780-3ca2-11eb-9b9f-1587978f400c.png)

```
const char* bugreport_template = R"(
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title><TMPL_VAR REPORTNAME></title>
    <link href='memory:master.css' rel='stylesheet' />
    <style>
        canvas {min-height: 100px}
        body {font-size: <TMPL_VAR HTMLSCALE>%}
    </style>
</head>
<body>
<div class = "container">
<h3><TMPL_VAR HEADER></h3>
<div class = "col-xs-8">
<TMPL_VAR CONTENTS>
</div>
</body>
</html>
)";
```
4) windows 10  pro
5) it does not affects to translations
6) https://github.com/moneymanagerex/moneymanagerex/blob/master/src/reports/bugreport.h#L22-L43

**Comment by vslavik** [comment]
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md), as GitHub asked you to do when you created this issue. Follow the instructions therein and provide the missing detailed information. Thanks!

**Comment by vomikan** [comment]
I have a counter offer, please add the template as described in the documentation:

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository

PS the bug report first message has been updated

**Comment by vslavik** [comment]
> I have a counter offer,

You're asking for help. On an open source project you have at your free disposal. The least you can do in return is to be considerate and do a good job of at least following instructions, if not of describing things well. You're asking us to spend our free time on your needs: the polite thing to do is to minimize the time we'll need to spend on you.

Being obtuse and difficult, telling me what *else* to do to make things more convenient for *you*, ignoring the meaning of the word "attach" and forcing me to go spelunking into who-know-what codebase, is the opposite of that. Your time is not more valuable than mine, and it would be great if you stopped acting like it was.

> it does not affects to translations

Your problem clearly IS specific to specific files. If you could attach a small reproduction sample that contains everything needed to see the problem for myself, that would be appreciated.

**Comment by vomikan** [comment]
Dude, you use harsh words... Let's put it down to the translator's imperfection.
I'm also an open source programmer. Sorry for being brief, but in my opinion I provided enough information and provided a link to the code. Why do you need a file if there is a link?
I just wanted to show you that there is a minor bug in the program that can be fixed to make your program better. But I came across something rude.

**Comment by vslavik** [comment]
> Dude

This is inappropriate, rude and grossly offensive thing to say in any setting another than with your friends.

> Let's put it down to the translator's imperfection.

Let's not. You're behaving horribly and it's not an issue with your English.

>  in my opinion I provided enough information

In your arrogant opinion, you don't even consider a possibility of being wrong. 

>  Why do you need a file if there is a link?

Because it takes freaking TIME to go through and decipher the super-brief (non)description and get the files. I know you don't give a damn about how many time I spend on your issue, but I do. And it is inconsiderate, rude and incredibly entitled that you think your time is more valuable than mine. That you are a time-waster who closes the issues instead of spending one minute on actually providing non-crappy bug report, that's just a cherry on the top.
