### ISSUE TITLE
Multiline NSLocalizedString adds unnecessary newlines

### ISSUE THREAD

**Issue by thisIsTheFoxe** [vslavik/poedit#673]
Hi,
I haven't looked into it that much (might be a Xcode problem).
But I have the following code:
```swift
NSLocalizedString("""
This is a description.
This is a new line.
Ok.
""", comment: "teststring")
```

After exporting, translating and importing it gives me:
```swift
/* teststring */
"\nThis is a description.\nThis is a new line.\nOk.\n" = "......"
```

Which doesn't work. It works only when removing the leading and trailing `\n`. 

---

_And yes, I guess L10edString 'keys' are not meant to be multiline, but it's still unexpected behaviour, right? Would be great if you could look into that ^^_

**Comment by vslavik** [comment]
> I haven't looked into it that much

As a rule of thumb, *do* investigate before filing issues in open source projects.

While doing so, please do follow the advise in https://www.chiark.greenend.org.uk/~sgtatham/bugs.html as instructed when you created this issue — w.r.t. reproducibility and clarity in particular. tl;dr: it's unclear what you do, how, with what and on what, or why you think it is related to Poedit.

**Comment by vslavik** [comment]
@thisIsTheFoxe Please don't be the kind of inconsiderate person who treats other people as inferior and wastes their time. Closing an issue that you requested another person to spend time without a single word of explanation is extremely rude, inconsiderate and deeply insulting behavior.
