### ISSUE TITLE
[feature request] copy paste text

### ISSUE THREAD

**Issue by freddii** [vslavik/poedit#676]
It might be handy to be able to copy text to clipboard and to paste text from clipboard in poedit

![poedit-copy-paste2](https://user-images.githubusercontent.com/7213207/105513640-db799d00-5cd2-11eb-8a7f-3b2a0c9c6c30.png)

**Comment by freddii** [comment]
Yes but it might be handy to have a button to click to copy it.

**Comment by vslavik** [comment]
Sorry, but nope.
