### ISSUE TITLE
Poedit can't handle unsupported languages

### ISSUE THREAD

**Issue by tbodt** [vslavik/poedit#678]
I'm trying to edit [this po file](https://github.com/duckduckgo/duckduckgo-locales/blob/master/locales/tokipona_XX/LC_MESSAGES/duckduckgo.po) which is in Toki Pona, a language Poedit doesn't support. There are a lot of useless warnings, but more importantly, it removes the Language: line every time I save the file, and then displays an error about how the Language: line is missing (even though Poedit is the thing that deleted it).

**Comment by vslavik** [comment]
This has nothing to do with "unsupported languages" (which aren't a thing that would exist). 

This is about the file being invalid, specification-violating file with nonsense value in the `Language` field. Read the [docs](https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html).
