### ISSUE TITLE
Missing/empty translation should be highlighted as a problem

### ISSUE THREAD

**Issue by boxed** [vslavik/poedit#680]

**Comment by boxed** [comment]
Mind commenting? Or is this just a bot?

**Comment by vslavik** [comment]
You did rudely create an issue with no description whatsoever, despite being asked to follow issue-creating instructions. 

Missing translations is a *normal state* during translation.  It is *common*. It is not a problem.

**Comment by boxed** [comment]
> You did rudely create an issue with no description whatsoever, despite being asked to follow issue-creating instructions.

When was I asked this? And the description is pretty clear isn't it? Super simple thing.

> Missing translations is a normal state during translation. It is common. It is not a problem.

Normal state for unfinished translations yes. But that's why you'd want to use this tool no? To find problems? A totally missing translation seems like the most obvious problem.

**Comment by vslavik** [comment]
> When was I asked this?

When you create this very issue. It's the instructions you didn't bother to read.

> And the description is pretty clear isn't it? Super simple thing.

With no rationale and detailed explanation of the *why*, it's a super absurd thing on its face. Which shows that explaining your thinking *matters*.  

> A totally missing translation seems like the most obvious problem.

It is indeed most obvious and obviously visible in plain sight in Poedit — *there is no translation shown*. It does not need any further highlighting, it is painfully obvious already.

This was closed on purpose and I am not going to implement marking of the normal state as "problem".

**Comment by boxed** [comment]
> It is indeed most obvious and obviously visible in plain sight in Poedit — there is no translation shown. It does not need any further highlighting, it is painfully obvious already.

I don't have hundreds of strings and it's already quite hard to see it at a glance. So I disagree.

Anyway, your weird hostile attitude and the lack of this crucial feature that is the most important for me have made me delete the app anyway. I hope your day improves, you seem to be on edge today.

**Comment by vslavik** [comment]
> I don't have hundreds of strings and it's already quite hard to see it at a glance. So I disagree.

You might want to look in the View and Go menus. I'm sorry, but this is a textbook PEBKAC situation.

> Anyway, your weird hostile attitude and the lack of this crucial feature

I am unaware of you having paid for any support, or having done anything for me, to warrant your expectations. Put bluntly, I owe you absolutely nothing, it's you who's weirdly and inappropriately entitled, and  extremely inconsiderate to other people who you evidently consider lesser than you: it's OK for me to waste my time hand-holding you, but *you* can't be bothered to even look in the menu first, or read the instructions? And that seems *sensible* to you?

> I hope your day improves, you seem to be on edge today.

Jeez, I wonder what it might be. Possibly certain entitled jerk's behavior?
