### ISSUE TITLE
Watch for file changes

### ISSUE THREAD

**Issue by boxed** [vslavik/poedit#681]
It would be great if poedit would watch for file changes. Now I have to close and open the file to get the new translations that are added to the file by django when collecting translation strings.

**Comment by vslavik** [comment]
Please do check the content of the repository before creating issues: https://github.com/vslavik/poedit/tree/devel/watch-file-modifications

**Comment by boxed** [comment]
Sorry. I searched among issues (including closed) before posting. Good to see that it's worked on!
