### ISSUE TITLE
Broken symlink Permission denied.

### ISSUE THREAD

**Issue by tsamu** [vslavik/poedit#682]
Try to update catalogue from source code, and get "You don’t have permission to read source code files from the location specified in the catalogue’s Properties.
If you previously denied access to your files, you can allow it in System Preferences > Security & Privacy > Privacy > Files & Folders." error.

Under Files and Folders there is no Poedit. Manually add Poedit to Full disk access section, but get the same error message. 

Any idea?

**Comment by vslavik** [comment]
> Any idea?

Sure: you probably misread that sentence starting with *if* and the precondition isn't meant. IOW, your permissions problem is a different one from the one the sentence is referring to. Unfortunately you provide zero details about the specifics of what and *where* you do, whether you checked the permissions (and how and with what result etc.), or even such basics of your Poedit version, so it's impossible to tell you more.

Please also read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) as GitHub asked you to do when you created this issue.

**Comment by tsamu** [comment]
So let me more specific and forget "any idea" :).

Using version 2.4.2

Meanwhile found the problem: I have a broken symlink under source path. The symlink is broken because of local development, on server env it's ok. This broken symlink throws the error message. I removed it and also removed all permissions from System Preferences > Security & Privacy > Privacy > Full disk access / Files & Folders. Catalogue successfully updated.

It would be great if the catalogue update process just shows a warning if some file does not exist.

**Comment by vslavik** [comment]
It would be great if you could *follow the instructions* and provide reproducible test case. You're asking me to fix or improve behavior in a weird edge case of yours without giving me enough to see the situation for myself (i.e. a copy of the source tree + instructions). I can't reproduce the behavior based on just a vague description and can't fix what I can't reproduce.

**Comment by inikoo** [comment]
He already gave the info, in macOS if is a broken symlink you have a misleading error message, to reproduce:
1) Buy / Borrow a mac computer
2) Create a project , with a broken symlink 
3) Try to extract from sources
