### ISSUE TITLE
Reference Language instead of `msgId`

### ISSUE THREAD

**Issue by colindjk** [vslavik/poedit#688]
So I've been reviewing some of the features of PoEdit, and I noticed that if I use a tool like [lingui](https://github.com/lingui/js-lingui) for example, the `msgId` will be used as the "original text". There are a few other libraries that do this. 

Forgive me if this is already supported, but could there be a feature add to simply have a reference language (so effectively have two `*.po` files side-by-side). 

Theoretically you could just have two tabs open, but then validation wouldn't work well. 

Thanks for any feedback!

**Comment by vslavik** [comment]
> Thanks for any feedback!

As a rule of thumb, gettext tools work much better when you use gettext as it is intended to be used and somewhat worse when you abuse gettext in ways it is not designed for. Non-English symbolic msgids are exactly that kind of abuse.

**Comment by vslavik** [comment]
See also #449.

**Comment by colindjk** [comment]
@vslavik Given that there are a few libraries that use the `msgid` as a symbol based key (as opposed to a phrase), would you be open to having a PR that could add the option of using a reference language instead of the msgid?
