### ISSUE TITLE
Ordinal numbers in Turkish give warning "The translation should not end with a '.' "

### ISSUE THREAD

**Issue by charlesdeb** [vslavik/poedit#689]
When translating ordinal numbers in English like `1st` or `2nd`, the correct Turkish translation would be `1.` or `2.`. The period indicates an ordinal number in Turkish. I could get around this by using the Turkish words for `first` or `second` but the original software author probably chose the shortened versions for a reason.

However, when I do this. then Poedit gives me the warning in the issue heading about the translation not ending with a period. I understand that since it's only a warning I can probably just ignore this, right?

I am not a C++ developer so am not able to submit a PR. I also don't know anything about `gettext` - and so appreciate the work that people like you put into this free tool.

**Comment by vslavik** [comment]
> I understand that since it's only a warning I can probably just ignore this, right?

Right. Or disable them in the *View* menu.

**Comment by lanurmi** [comment]
I foresaw exactly this problem 4 years in advance, in #395.

**Comment by charlesdeb** [comment]
I am curious to know what I am actually being warned about. As I am a developer (just not a C++ one), I kind of had fears that putting a period at the end of a translation string might be a little little like adding "`; DELETE FROM users;`" in user input. That is a "WARNING - SHARKS AHEAD" type warning as opposed to "Warning - eating cheese before you sleep might give you crazy dreams". One is clearly more important than the other...

From the context of #395, I am now guessing that this warning probably relates to the fact that there was no full stop at the end of the English sentence, and so putting one at the end of the Turkish one might be a problem? It would be too much to expect Poedit to know the a period after a number in Turkish means "ordinal number" - but a slightly more expanded explanation of why a translation should not end with a "." might be good. Assuming, this warning _is_ about inconsistent punctuation, could I suggest a rewording like:

`Warning: The original text did not end with the punctuation of "%s". Are you sure the translated text should?`

Or something like that... That would suit this use case - but there are likely dozens of different ones so my specific suggestion maybe totally inappropriate. Only the developer or a much more experienced Poedit user would know.

My point is simply that giving some reason as why Poedit is flagging a warning will enable to translator to know whether it is a warning that can be ignored (e.g. because Poedit doesn't understand language x), or one that should actually be taken seriously.

Thanks again for this tool.
