### ISSUE TITLE
Request new features

### ISSUE THREAD

**Issue by vnwildman** [vslavik/poedit#691]
Hi,
Poedit should add features:

- File filter (include, exclude file) that only show one or some file for translating. It also sould support wildcard in it. Useful when translate framework, or big project.
- Warning bout repeating space (double space etc.), word (ex. `me me`)
- Check accelerate (& and _) key (must be ASCII or a string specified by user)

**Comment by vslavik** [comment]
I'm closing this one as unactionable - it mixes multiple unrelated things (one issue per one thing is an important rule to make it possible to manage things) and the one-sentence descriptions are not easy to understand. If you think these are still relevant, please create individual issues, one per one thing, and provide much more details, including e.g. examples. I think I understand the 2nd one, but the rest is not at all clear to me.

Thanks!
