### ISSUE TITLE
"Source code not available error" for Html5 files.

### ISSUE THREAD

**Issue by Diae-Louali** [vslavik/poedit#695]
I get a "Source code not available error"  whenever i try to extract from source code within an Html5 file. Changing its extention to .php does work, but is not a viable solution unfortunately. 

![Capture](https://user-images.githubusercontent.com/68733422/118731862-32325600-b831-11eb-891d-5b0adaad1e4a.PNG)

![Capture](https://user-images.githubusercontent.com/68733422/118731226-d1a31900-b830-11eb-9a22-303d5774fe12.PNG)

**Comment by vslavik** [comment]
".html5" is not a file extension of PHP files.
