### ISSUE TITLE
Close "Edit comment" window with key combo

### ISSUE THREAD

**Issue by daPhipz** [vslavik/poedit#702]
I would love to be able to write a comment using the "Edit comment" button on the bottom right of the main window and then close the comment window with `Ctrl+Enter`. This is how most text forms, chat apps etc. handle it nowadays (including GitHub :wink:)
This would make keyboard-oriented translation workflows even more efficient.
Is there something like this planned?
I am using Poedit 2.4.2 on Ubuntu 21.04.

Thanks for consideration!

**Comment by vslavik** [comment]
It actually does have that, since 2015 (ea1fd0e). And it does work in GTK+ version too.

If it doesn't work for you, investigate and submit a PR with a fix.

**Comment by vslavik** [comment]
Or perhaps the issue wasn't with Enter but with Numpad Enter? If yes, then 0e2fc20243cb33f38d7d15dfa8a62af42acb4f88 fixes it; if not, then I honestly don't know and you need to investigate or provide reproduction steps.

**Comment by daPhipz** [comment]
Yes, it is the numpad Enter key! Thank you very much for implementing it ;)
