### ISSUE TITLE
Poedit crash when opening code occurrence

### ISSUE THREAD

**Issue by isti03** [vslavik/poedit#709]
# Issue description

Poedit crashes when opening some code occurrences multiple times, probably due to a highlighter error. 

# Steps to reproduce

```
git clone https://gitlab.com/arcmenu/ArcMenu.git
cd ArcMenu
git checkout dd41002595d7cd59b12e95728cf8b35c0a641a7f
poedit po/hu.po
```

Then find a string that has `prefs.js` in the Code occurences section of the context menu. Choose that option. The window will probably show up, but the syntax highlighting will fail. Now repeat that multiple times, maybe with another string and Poedit will eventually crash. 

# My environment

- Arch Linux
- the latest version of Poedit from the arch community repository
  - for details see <https://archlinux.org/packages/community/x86_64/poedit/>
- GNOME shell v40.3.0 on Wayland

**Comment by vslavik** [comment]
> Then find a string that has prefs.js in the Code occurences section of the context menu. 

Please provide a pointer to a specific string.

> The window will probably show up, but the syntax highlighting will fail.

Please explain why you say it will "probably" show up. Either it shows or not, no?

> Now repeat that multiple times, maybe with another string and Poedit will eventually crash.

Please provide precise steps that can be followed. This is a bit hand-wavy and I can't be certain I followed the instructions correctly if nothing of interest happens.

> the latest version of Poedit from the arch community repository

Please provide exact version *number* (which, unlike "the latest version", doesn't change in time nor is subject to a human error e.g. in believing the version is the latest while it is not).

Thanks!

**Comment by isti03** [comment]
> Please provide exact version number
v3.0, built against webkit2gtk v2.32.3

Ok, first of all one thing I forgot, is make sure that you have updated from the POT file, so we are on the same page. 

Also, I mentioned a problem which is probably irrelevant to the current discussion. Turns out that linting  does not fail on the `prefs.js` file, it just takes nearly one minute to complete on an Intel Core i5-4300U (1.90 GHz, 2 cores / 4 threads). This and my other experiences outlined below makes me suspect that the issue is with webkit2gtk, therefore I included its version number above. 

> Please explain why you say it will "probably" show up. Either it shows or not, no?

If I randomly pick a string then randomly pick an occurrence of that and repeat this process over and over again, it might fail on the second open, or it might fail at the fifth open. It is really hard to find any pattern defining when Poedit will crash. It might depend on the speed, i.e. in how rapid succession do I open and close the windows and how long the syntax highlighting process might take. Therefore, I can't provide one single example. 

What I surely know is that if there is a Code Occurrences window open, and I choose a different occurrence of the current string in the dropdown menu at the top of the Code Occurrences window, no issues occur. 

One thing I think might be relevant is that even after closing the Code Occurrences window, there still remain running `WebKitNetworkProcess` processes. I don't know if this is intentional or not, I just thought it might be relevant. 

I am not really experienced with error reporting, but if I could get a stack trace form a coredump or something like that, would that be helpful?

Thanks

**Comment by vslavik** [comment]
> Ok, first of all one thing I forgot, is make sure that you have updated from the POT file, so we are on the same page.

Again: please describe the exact, precise *steps* needed to take. "Update from the POT file" is vague (what POT file? how? etc.) and assumes my understanding will be 100% same as yours. That's unlikely to be the case.

> It is really hard to find any pattern defining when Poedit will crash. […] Therefore, I can't provide one single example.

Your previous version sounded like you *do* have steps to reproduce. And it certainly *is* possible to describe better: instead of "go find some string from prefs.js" as you did, you can say "go to string with source text XYZ".  

> I am not really experienced with error reporting

Please do read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html (GitHub pointed you that way too). It helps a lot.

What is needed is accuracy, preciseness and explicitness. Describe steps to reproduce that a person-that-is-not-you and that never used Poedit can follow.

**Comment by isti03** [comment]
# Environment

- [Intel Core i5-4300U](https://www.intel.com/content/www/us/en/products/sku/76308/intel-core-i54300u-processor-3m-cache-up-to-2-90-ghz/specifications.html) (1.90 GHz, 2 cores / 4 threads)
- [Arch Linux](https://wiki.archlinux.org/title/Arch_Linux)
- [GNOME Shell](https://archlinux.org/packages/extra/x86_64/gnome-shell/) 40.3.0 on [Wayland](https://archlinux.org/packages/extra/x86_64/wayland/) 1.19.0
- [Poedit](https://archlinux.org/packages/community/x86_64/poedit/) 3.0
- [`gtk3`](https://archlinux.org/packages/extra/x86_64/gtk3/) 3.24.30
- [`webkit2gtk`](https://archlinux.org/packages/extra/x86_64/webkit2gtk/) 2.32.3
- [`wxgtk3`](https://archlinux.org/packages/extra/x86_64/wxgtk3/) 3.0.5.1
- [`lucene++`](https://archlinux.org/packages/community/x86_64/lucene++/) 3.0.8
- [`gtkspell3`](https://archlinux.org/packages/community/x86_64/gtkspell3/) 3.0.10

# Steps to reproduce

Install Arch Linux if you feel really adventurous. Otherwise, just install the aforementioned versions of programs. Install `git` if not installed already. 

Fire up the terminal / command prompt, and run the following programs to launch Poedit at the state that I experienced the crash. 

```
git clone https://gitlab.com/arcmenu/ArcMenu.git
cd ArcMenu
git checkout dd41002595d7cd59b12e95728cf8b35c0a641a7f
LC_ALL=C poedit po/hu.po
```

Now you have poedit opened at the Hungarian translation of the ArcMenu project. The Hungarian po file is a bit outdated, so first let's update it by choosing `Update from POT file...` from the `Translation` menu, and choose your single option you could choose, which is `arcmenu.pot` file in the file picker dialog popup. 

Choose the string wit "All Programs" as its Source text. Then right click and choose `constants.js:79` in the Code Occurrences section of the context menu. A Code Occurrences window will pop up. Close that window, right click on "All Programs" and open `constants.js:79` from the context menu again. If it opens fine, try doing it in a more rapid succession, because how quickly you open and close the window affects the outcome. The crash might also be dependent on your hardware's performance. You now hopefully reproduced the bug and Poedit will crash dumping a core.

**Comment by cloudfish** [comment]
I encountered the same issue and reported this as [Debian bug #1001790](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001790). The segfault is triggered by accessing node->is_instantiatable in g_type_check_instance_is_a in glib ([code](https://salsa.debian.org/gnome-team/glib/-/blob/debian/2.70.2-1/gobject/gtype.c#L4081)). See the bugreport for a backtrace.

**Comment by vslavik** [comment]
Thanks. The relevant bit of it:
```
Thread 1 (Thread 0x7ff241da5b40 (LWP 59473)):
#0  0x00007ff24cbbde2c in g_type_check_instance_is_a (type_instance=type_instance@entry=0x55bf44e0d390, iface_type=<optimized out>) at ../../../gobject/gtype.c:4081
        node = 0x41ce894d56415740
        iface = 0x55bf44de3a10
        check = <optimized out>
#1  0x00007ff24b6407e6 in g_dbus_server_get_client_address (server=0x55bf44e0d390) at ../../../gio/gdbusserver.c:557
        __inst = 0x55bf44e0d390
        __t = 94279982529040
        __r = <optimized out>
        _g_boolean_var_ = <optimized out>
        __func__ = "g_dbus_server_get_client_address"
#2  0x00007ff24e760032 in wxgtk_initialize_web_extensions (context=0x55bf44de8160, dbusServer=<optimized out>) at ../src/gtk/webview_webkit2.cpp:367
        address = <optimized out>
        user_data = <optimized out>
#3  0x00007ff24cb9d6df in g_closure_invoke (closure=0x55bf44e61000, return_value=return_value@entry=0x0, n_param_values=1, param_values=param_values@entry=0x7ffe4fcc5840, invocation_hint=invocation_hint@entry=0x7ffe4fcc57c0) at ../../../gobject/gclosure.c:830
        marshal = 0x7ff24cb9f710 <g_cclosure_marshal_VOID__VOID>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x55bf44e60fe0
        __func__ = "g_closure_invoke"
#4  0x00007ff24cbafb36 in signal_emit_unlocked_R (node=node@entry=0x55bf44dd4020, detail=detail@entry=0, instance=instance@entry=0x55bf44de8160, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffe4fcc5840) at ../../../gobject/gsignal.c:3742
        tmp = <optimized out>
        handler = 0x55bf44dda400
        accumulator = 0x0
        emission = {next = 0x7ffe4fcc6890, instance = 0x55bf44de8160, ihint = {signal_id = 363, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = 4}
        class_closure = 0x55bf44dd3fd0
        hlist = <optimized out>
        handler_list = 0x55bf44de6c40
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 363
        max_sequential_handler_number = 22260
        return_value_altered = 1
        EMIT_RESTART = <optimized out>
#5  0x00007ff24cbb5f51 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe4fcc59c0) at ../../../gobject/gsignal.c:3497
        instance_and_params = 0x7ffe4fcc5840
        signal_return_type = <optimized out>
        param_values = 0x7ffe4fcc5858
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#6  0x00007ff24cbb64ff in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3553
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffe4fcc5aa0, reg_save_area = 0x7ffe4fcc59e0}}
#7  0x00007ff24889ee33 in webkitWebContextInitializeWebExtensions () at ./Source/WebKit/UIProcess/API/glib/WebKitWebContext.cpp:1875
No locals.
#8  0x00007ff248881fc8 in WebKitInjectedBundleClient::getInjectedBundleInitializationUserData () at ./Source/WebKit/UIProcess/API/glib/WebKitInjectedBundleClient.cpp:172
No locals.
#9  0x00007ff2488232ba in WebKit::WebProcessPool::initializeNewWebProcess () at ./Source/WebKit/UIProcess/WebProcessPool.cpp:825
No locals.
#10 0x00007ff248823e84 in WebKit::WebProcessPool::createNewWebProcess () at ./Source/WebKit/UIProcess/WebProcessPool.cpp:608
No locals.
#11 0x00007ff2488242cc in WebKit::WebProcessPool::processForRegistrableDomain () at ./Source/WebKit/UIProcess/WebProcessPool.cpp:1013
No locals.
#12 0x00007ff2487e8319 in WebKit::WebPageProxy::launchProcess () at ./Source/WebKit/UIProcess/WebPageProxy.cpp:852
No locals.
#13 0x00007ff2487e89e0 in WebKit::WebPageProxy::loadRequest () at ./Source/WebKit/UIProcess/WebPageProxy.cpp:1369
No locals.
#14 0x00007ff2488a9122 in webkit_web_view_load_uri () at ./Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp:3077
No locals.
#15 0x00007ff24e761d64 in wxWebViewWebKit::Create (this=this@entry=0x55bf44e0ca10, parent=parent@entry=0x55bf44ef0c00, id=id@entry=-1, url=..., pos=..., size=..., style=-1073741824, name=...) at ../include/wx/buffer.h:171
        __FUNCTION__ = "Create"
        findctrl = <optimized out>
#16 0x00007ff24e76859e in wxWebViewWebKit::wxWebViewWebKit (name=..., style=0, size=..., pos=..., url=..., id=-1, parent=0x55bf44ef0c00, this=<optimized out>) at ../include/wx/gtk/webview_webkit.h:42
No locals.
#17 wxWebViewFactoryWebKit::Create (name=..., style=0, size=..., pos=..., url=..., id=-1, parent=0x55bf44ef0c00, this=<optimized out>) at ../include/wx/gtk/webview_webkit.h:196
No locals.
#18 wxWebView::New (parent=0x55bf44ef0c00, id=-1, url=..., pos=..., size=..., backend=..., style=0, name=...) at ../src/common/webview.cpp:77
        iter = {<wxStringWebViewFactoryMap_wxImplementation_HashTable::Iterator> = {m_node = <optimized out>, m_ht = <optimized out>}, <No data fields>}
#19 0x000055bf41dada69 in FileViewer::FileViewer (this=0x55bf44f09310) at ./src/fileviewer.cpp:141
        panel = 0x55bf44ef0c00
        sizer = 0x55bf44e07c00
        topsizer = 0x7c
        panel = <optimized out>
        sizer = <optimized out>
        topsizer = <optimized out>
#20 0x000055bf41dad15f in FileViewer::GetAndActivate () at ./src/fileviewer.cpp:91
No locals.
#21 0x000055bf41d32b45 in PoeditFrame::ShowReference (this=0x55bf43c3d980, num=0) at ./src/edframe.cpp:2035
        entry = {<std::__shared_ptr<CatalogItem, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<CatalogItem, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x55bf43e61160, _M_refcount = {_M_pi = 0x55bf43e61150}}, <No data fields>}
#22 0x000055bf41d32af0 in PoeditFrame::OnReference (this=0x55bf43c3d980, event=...) at ./src/edframe.cpp:2025
No locals.
```

The crash happens inside wxGTK code outside Poedit. Chances are the latest wx version (3.1.x) fixes it. 

Can you reproduce the same crash in Poedit's snap-packaged version: https://snapcraft.io/poedit ? That one uses more current wx build… E.g. this fix might be relevant: https://github.com/wxWidgets/wxWidgets/commit/44b30c1a602c3eab75b49d3f94c55fb4d21e24e7#diff-685547fad736f48f2b97065887d3e5fa06452d2b057369a911a4fb1eb137385b

**Comment by gusnan** [comment]
I have tested the snap build, and there I don't get the crash, while I do get it in the non-snap version. Thanks!

**Comment by cloudfish** [comment]
I don't experience any crash on the snap version either. Thanks!

Another question, I prefer using the ordinary .deb package, so I built a poedit package against wx 3.1.5, but I'm getting the following assertion failure when opening a .po file:
```
Gtk-Message: 21:46:00.463: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 21:46:00.463: Failed to load module "colorreload-gtk-module"

** (net.poedit.Poedit:5454): CRITICAL **: 21:46:08.830: check_range: assertion 'spell->priv->speller != NULL' failed

** (net.poedit.Poedit:5454): CRITICAL **: 21:46:08.830: check_range: assertion 'spell->priv->speller != NULL' failed
../src/common/bmpbase.cpp(33): assert "variant.GetType() == "wxBitmap"" failed in operator<<().
Debug: window wxTextCtrl(0x555f5da4b800) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x555f5da4b800) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x555f5da4b800) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x555f5da4b800) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x555f5da4b800) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x555f5da4b800) lost focus even though it didn't have it
Debug: window wxTextCtrl(0x555f5da4b800) lost focus even though it didn't have it
Trace/breakpoint trap
```
Do you have any idea on this? Do I need to use an older version than 3.1.5?

**Comment by vslavik** [comment]
@cloudfish Let's please keep this issue on-topic; this isn't. If you compile from sources and against development=unstable series of libraries, you need to be prepared to dig into such issues or try VCS snapshots.

**Comment by vslavik** [comment]
Now that wx-3.2, which doesn't have the problem, is shipping in distros, it's safe to close this issue. Poedit will make wx-3.2 a hard requirement shortly.
