### ISSUE TITLE
Add support for JSON Files

### ISSUE THREAD

**Issue by mattexpa** [vslavik/poedit#710]
Hey there, 

premium member here and wanted to edit JSON localization a few days ago.
Maybe for future implications.
Keep up the great work - nice app!

**Comment by mattexpa** [comment]
Okay, get it.
https://github.com/nielsfaber/alarmo/pull/257/files is a example of the json translation i wanted to do. 
Used BabelEdit in the end and because it recognized the json format perfectly fine i thought json localizations are always formatted the same.

**Comment by vslavik** [comment]
What should be handled by "JSON support":

- The linked document appears to use [Shopify format](https://shopify.dev/themes/architecture/locales).
- There's also Jed, [which WordPress uses](https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/) and which is a literal transcription of PO file format.
- React [is different too](https://www.i18next.com/misc/json-format); in its original simple key-value form it is also used by Laravel.

Guess we'll just start with the simple forms and keep adding features incrementally as needed.
