### ISSUE TITLE
Display \v visibly

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#712]
I am currently translating cryptsetup, which [in one message](https://github.com/mbroz/cryptsetup/blob/72384b43bd83de836c5e7bc5248d47d676440449/tokens/ssh/cryptsetup-ssh.c#L126) uses the string escape `\v`.

* In the source text, Poedit displays this as an otherwise invisible line break.
* In the translated text, `\v` is not highlighted as an escape sequence but rather as plain text.
* In the translated text, when I type `\v`, it is saved as `\\v`.

**Comment by vslavik** [comment]
I'm not sure if it's worth having special support for vertical tabs, given their extreme rarity, but at the very least, the source vs translation inconsistency and especially the input corruption from your 3rd point are very bad indeed.

**Comment by rillig** [comment]
Thank you for fixing this. When I looked at the code changes, I was not sure whether `\007` is always handled correctly and not interpreted as `\0` followed by the digits `07`. It's only a suspicion though, you know the code best. I tried GNU gettext, and it did not generate `\0` at all in the message IDs.

**Comment by vslavik** [comment]
Yes, there were inconsistencies.
