### ISSUE TITLE
XLIFF files translated to RTL languages have wrong script direction

### ISSUE THREAD

**Issue by eshagh79** [vslavik/poedit#724]
Hi.
When opening a translation xliff file in right-to-left languages (in my example Persian), the texts in the display list are displayed in the wrong direction. That is, instead of right-to-left, they are arranged or adjusted to the right-to-left.
This problem does not exist in po files

![نماگرفت از 2021-11-03 09-25-47](https://user-images.githubusercontent.com/52137191/140027002-89a50ea3-98f7-41e5-9ec2-1f4a8ebcfe91.png)
![نماگرفت از 2021-11-03 11-39-29](https://user-images.githubusercontent.com/52137191/140027006-85ef4afe-2637-4ee7-a5ca-6438b9002278.png)
.

**Comment by vslavik** [comment]
Please attach the file in question (always a good idea when encountering file-specific issues). TIA!

**Comment by eshagh79** [comment]
[file.zip](https://github.com/vslavik/poedit/files/7467118/file.zip)

**Comment by vslavik** [comment]
Thanks for the test file!
