### ISSUE TITLE
ARB files support

### ISSUE THREAD

**Issue by juanluispaz** [vslavik/poedit#727]
Hi,

Do you have plans to add support to ARB files format (commonly used in Flutter)?

**Comment by vslavik** [comment]
Not currently. But patches or thumbs-uping this issue welcome.

Spec: https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification

**Comment by mbalmer** [comment]
I'd second that request, as the obvious workaround (using arb-convert, see https://github.com/trufi-association/arb-convert) seems not working well:

The following ARB fragment

 "stpNumChildren": "Numero di bambini",
  "@stpNumChildren": {
    "description": "STP number of children",
    "type": "text",
    "placeholders": {}
  },

will be converted to

#. STP number of children
msgctxt "stpNumChildren"
msgid "Numero di bambini"
msgstr ""

That is it puts the english text into msgctxt, the translated text in msgid and leaves msgstr blank, whereas the english text should be in msgid and the translated italian text in msgstr.

**Comment by vslavik** [comment]
Support for Flutter's ARB files was added in version 3.3 (commit 75b6fefa7e544496df6724fc53ba1711504b5d95):
https://poedit.net/news/poedit-3.3-json/
