### ISSUE TITLE
Wrong colorization position of non breakable spaces when the string contains an emoji

### ISSUE THREAD

**Issue by Pierre-Lannoy** [vslavik/poedit#731]
Hello!
On 3.0.1 (and 3.0.0, I've just tested) on Monterey 12.1, colorization of non breakable spaces is at the wrong place when the string contains an emoji.
![image](https://user-images.githubusercontent.com/15095492/151149611-94c26403-6833-4a04-96d6-ee0dda392d9b.png)

**Comment by vslavik** [comment]
Please attach an actual file that can be used to reproduce, as per instructions when creating the bug.

**Comment by Pierre-Lannoy** [comment]
Hello @vslavik
Sorry for this late answer, my notifications are gone dead…
Here it is.
[wp-plugins-decalog-stable-readme-fr.po.zip](https://github.com/vslavik/poedit/files/7960568/wp-plugins-decalog-stable-readme-fr.po.zip)

**Comment by vslavik** [comment]
Thanks!

**Comment by Pierre-Lannoy** [comment]
Thank you so much ❤️
