### ISSUE TITLE
Request for the addition of Santali language (sat) plural form with addition of new language lem

### ISSUE THREAD

**Issue by Prasanta-Hembram** [vslavik/poedit#735]
Hi, i was translating document from English to Santali language and found some missing things, instead of making changes in code and creating pull req i thought to discuss, what can be done for this issue.

There is missing plural form for Santali language where, It's plural form should be:

> Plural-Forms: nplurals=3; plural=n==1 ? 0 : n==2 ? 1 : 2  

This plural form is also used in Launchpad (https://translations.launchpad.net/+languages/sat) and Ponoon (Mozilla - https://pontoon.mozilla.org/sat/)

I have been translating Santali language using Ol Chiki script (Olck), but always having problem creating a new translated file from pot files as always i have to edit po file using Notepad and change langauge tag to sat-Olck-IN (where sat is the code of langauge, Olck is the script, and IN is for India).

Is it possible to give an option for these language form below for Santali language while creating a translated po file from pot, it will save mine and others time for just doing same repetative task in Notepad by changing name tags. These are mostly used language tags while translating in Santali language.

sat for Santali language.
sat-Olck for Santali language with Ol Chiki script.
sat-Olck-IN for Santali language with Ol Chiki script in India.
sat-Deva for Santali language with Devanagari script.
sat-Deva-IN for Santali language with Devanagari script in India.

Ref of Santali language written in 5 script but with primary as Ol Chiki (Olck) - https://unicode-org.github.io/cldr-staging/charts/37/supplemental/languages_and_scripts.html

**Comment by vslavik** [comment]
"sat-Olck-IN" is not a valid locale identifier. 

I don't know why you say you have to edit the file manually, you can enter any language code as well as any plural forms expression.

Plural forms expressions are regularly updated from CLDR data. I'm not going to maintain a separate database of plural form expressions - been there, done that, didn't work well.

Finally, this issue seems to be mixing at least 3 unrelated things (one of which is in subject only, with no discussion), so I'm not ever sure what action it asks for.

**Comment by Prasanta-Hembram** [comment]
sorry for replying late, actually I was a new to Poedit and was doing Voodoo programming when I first opened the issue. Now I have read the documentation and clear that how to enter any language code as well as any plural forms expression and how to deal with it. I think we should close this issue for without any reason and unclear.
