### ISSUE TITLE
How to install Poedit 3.1 on Ubuntu?

### ISSUE THREAD

**Issue by alucardu** [vslavik/poedit#738]
Devs that are using Mac have Poedit 3.1 installed, but the latest snap on Ubuntu seem to be version 3.0. Any chance on updating Poedit on Ubuntu?

**Comment by vslavik** [comment]
This is a bug tracker; please don't use it as a support forum.

Poedit 3.1 doesn't exist yet, you can't install it. If you're talking about 3.0.1, that one is available via snap.
