### ISSUE TITLE
Feature: navigate to previously modified message

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#739]
Every now and then, after having translated a message, I press Ctrl+Enter to navigate to the next untranslated message. One second later I notice that I need to fix the previous message, but I don't remember which one it was.
* There is no visual indicator in the list of messages for the last few translated messages.
* The Navigate menu doesn't have an item "Most recently modified".
* The Edit menu has its items Undo and Redo grayed out.

Is there an easy way to navigate to the most recently translated message? Something like `browser.back()` in JavaScript.

**Comment by vslavik** [comment]
This is something that file-scoped undo/redo would address (that's what I do in code editors in this situation: Ctrl+Z followed by Ctrl+Shift+Z. 

But it does make sense to have either *Most recently modified* or a deeper-level *Go back* action.

> There is no visual indicator in the list of messages for the last few translated messages.

…and regardless of that, this too.

**Comment by vslavik** [comment]
Shortcut suggested in #563: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd>

More naming options: "Previously modified" or "Previously edited"
