### ISSUE TITLE
Wrong warning "translation should start as sentence"

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#740]
~~~po
msgid "MSP430 built-in"
msgstr "eingebaute MSP430"
~~~

In the German version of Poedit, this generates the warning "Die Übersetzung sollte als Satz beginnen.", which should not be shown here. The original message may or may not be a sentence, that is not clear from the text alone. The warning should only be shown if the original message starts with an uppercase letter followed by a lowercase letter.

**Comment by vslavik** [comment]
> The warning should only be shown if the original message starts with an uppercase letter followed by a lowercase letter.

I like this phrasing. It may not be bulletproof (e.g. proper nouns, uppercase-emphasized text), but false negatives are better than false positives. Thanks!
