### ISSUE TITLE
PHP "sprintf" specifiers not correctly handled

### ISSUE THREAD

**Issue by kjo-sdds** [vslavik/poedit#754]
Hi, 
The program seems to have problems handling some PHP specifiers ( https://www.php.net/manual/fr/function.sprintf.php ).
If I have :
```php
sprintf(_("Some text with insert %s ... and a second one here %s"), $name1, $name2);
```
It works fine! However, when having :
```php
sprintf(_("Some text with insert %1$s ... and a second one here %2$s"), $name1, $name2);
```
The string `"Some text with insert %1$s ... and a second one here %2$s"` is not recognised as a _"string to translate"._

This is important because in some languages, the postion of `$name1` and `$name2` might be reversed ... so using the first version will give inaccurate results.

The second version lets the translator give a translation like : _"Some other language text with second insert %2$s ... and the first one here %1$s"_ ... and still be correct.

**Comment by kjo-sdds** [comment]
My bad ... I just noticed it was (for some reason...??) double quoted string ... 
So behavior is correct :
in `"Some text with insert %1$s ..."` the `$s` is supposedly matching a PHP variable ... 
but in `"Some text with insert %1\$s ..."` it is corectly recognised ... as well as in `'Some text with insert %1$s ...'`

Sorry for the inconvenience ... and thanks for the great work !

**Comment by vslavik** [comment]
… and if you followed https://github.com/vslavik/poedit/blob/master/SUPPORT.md, you'd figure it out before creating the issue, by process of providing reproduction details.
