### ISSUE TITLE
Translation broken - unsure why

### ISSUE THREAD

**Issue by MortenMacFly** [vslavik/poedit#756]
I did an update of wxWidgets from v3.1.5 to v3.1.6 and in parallel an update of Poedit from v2.xx to v3.01.
Since then, the translation in a project of mine is completely broken: There are only very few words shown translated in the UI but most remain in the original language (which is English). I am unable to find out, why that is. I did not change the translation code, but what I did is updating the translation wrt new items with Poedit 3.xx.
So I am wondering: Since you develop Poedit with wxWidgets, too: Did you experience such a thing, too lately? Is it me, wx3.1.6 or Poedit 3.xx? :-)

**Comment by MortenMacFly** [comment]
One step further: I've seen that 1.) the "internat" sample project of wxWidgets works but also that 2.) the translation API has changed in wxWidgets and the "internat" sample is updated. So it seems it is wxWidgets related and the new API breaks the old one. I would guess you should have to deal with the same issue in Poedit, do you?

Now I wonder: Is that a bug in wxWidgets - so they did not manage to keep compatibilty with old versions? If so, I should report to the wx guys. But in case the change and compatibility break is intended, how should I handle this with platforms like Linux, where this lib is far from being available? (Most distros are still at wx 3.0.x.)

I am aware this is likely not a Poedit problem, but I guess you are a good expert to ask anyways. I would really welcome a hint - but feel free to close the ticket, if you like.

**Comment by vslavik** [comment]
This really isn't the place. This is a bug tracker, for tracking bugs in Poedit, not support forum for things at best tangentially related to Poedit's domain.

I'm happy to provide tangenial advice to paying customers (which you don't seem to be) over proper channels, but even that requires some meaningful description and investigation by them.

See http://www.chiark.greenend.org.uk/~sgtatham/bugs.html - follow that and you're likely to figure out what your code is doing wrong all on your own.
