### ISSUE TITLE
Code occurrences returns a blank page (Windows 10)

### ISSUE THREAD

**Issue by bic-ed** [vslavik/poedit#761]
After installing v3.1, I get a blank page when I try to see code occurrences.
I've rolled back to v3.0.1 at the moment and it works fine for me.
I'm running poedit on a Windows10 x64 machine.

**Comment by vslavik** [comment]
Please check the changes before the latest release before filing issues: https://github.com/vslavik/poedit/commit/602e8f3603c2ca75c743204393fb6ff89af32c20

**Comment by bic-ed** [comment]
The release with the above fix was not yet available when I opened this issue though.
Thanks for your work and for the feedback.

**Comment by vslavik** [comment]
> The release with the above fix was not yet available when I opened this issue though.

Which is why I suggested to check the commits *since* the release, i.e. unreleased ones.
