### ISSUE TITLE
Confusing to use on open source repos that do not gain any money.

### ISSUE THREAD

**Issue by AraHaan** [vslavik/poedit#765]
The free version is confusing to use for me when I use it on my open source repos that do not gain any money so I can set up having hard coded strings translated. With Resx resource manager (optional extension to Visual Studio for .NET projects) it translates with google translate for free while it's paywalled with Poedit. As much as I would love to use it, I think it needs a few changes.
I think poedit should be modified to where if the repository:
- is on github and in git
- and if the repository when you extract the url from git does not return 404 on request by the program (without any authorization headers or logged in state on github so you can actually know if it's open source as a public repository (closed source on github will return 404 because it's private))
- does not activate the sponsorship feature of github (or activated but does not have any sponsors) I think should be able to use at least the google translate for free but only if they provide *their own* api keys for it (same can be said for Microsoft too since they can create some for free I think unless they changed it).

Also I would absolutely love it if the project tried activing the github sponsorships feature too, so those who actually love poedit can sponsor (even if it's 1$) to help it's development or even if they work incredibly hard on it's development by opening pull requests.

And finally I would love if the project could allow using pro features of Poedit by participating in the github studend program where while a student one can use the pro features of poedit free (but after that it reverts back to the free version). It might be a bit of a work but it would be totally worth it. Filing issue here is more easier than email because emails can get lost.

And last but not least, keep up the good work and improving poedit.

**Comment by vslavik** [comment]
This is a bug tracker. GitHub explained this to you when you created this issue and asked you to follow some rules, *all* of which you summarily ignored.

Please refrain from posting incoherent rants to the bug tracker.
