### ISSUE TITLE
Unable to set up watch for "path to WSL"

### ISSUE THREAD

**Issue by joshkreud** [vslavik/poedit#767]
Hi, 

Whenever I open a `pot` or `po` file located inside the windows WSL (`\\wsl.localhost\Ubuntu.....` or `\\wsl$\ubuntu\...`) I get an error popup: 

![image](https://user-images.githubusercontent.com/10895412/181501527-f60193fe-4797-4a6d-ae77-335a59f6558c.png)

The Error1 Translates from German: forbidden function. 

Can we either get an option to disable file watch or get this fixed in the WSL? 

PoEdit Version: 3.1.1 (6476) (but also observed in earlier versions from the last 6 months)
Operating System: Win 11 21H2 22000.318 (but also reproducible in Win 10)

**Comment by vslavik** [comment]
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), follow the instructions therein and provide the missing detailed information. Thanks!

**Comment by joshkreud** [comment]
I added my operating system Information. (Did I miss something else?)

I've seen the error every time when working with files in the WSL filesystem. 

I guess the error happens because the WSL filesystem runs via a some sort of network protocol which doesn' t support informing applications about file changes. 

This can also be observed in Windows Explorer when looking at a Folder in WSL.
File changes through the Commandline do not appear in the Explorer until it gets manually refreshed.
In normal Filesystem folders changes are immediately updated, even when the change doesnt originate in the explorer.

**Comment by vslavik** [comment]
> This can also be observed in Windows Explorer when looking at a Folder in WSL.

That's kind of important and in that case, it has nothing to do with Poedit and there's nothing we can do about it. I am therefore closing this issue; if you disagree with the "nothing we can do about it" part, please submit a PR.

**Comment by chdenat** [comment]
Please consider to reopen this issue, as WSL is now the main developer system on window.
A lot of developer use WSL to create but are using some windows tools like POEdit to work with WSL like several tools.
It has to do with POEdit as POEdit does not work fine with WSL, which is part of Windows...
Thanxs
