### ISSUE TITLE
Poedit can not save(saving error)

### ISSUE THREAD

**Issue by takuphuquoc** [vslavik/poedit#769]
I'm trying to use Poedit (Ver3.1.1) but can not save a new project. When I save the project, indicate error message. please let me know what the incorrect is.
![Saving Error](https://user-images.githubusercontent.com/110758824/183278779-775a8f47-a51d-49e7-889c-b582f46daea8.jpg)

**Comment by vslavik** [comment]
You probably refused to allow Poedit to access the files, which are stored on the Desktop, which is protected by the operating system (which you don't even mention) in some versions (which you don't specify).

Censoring information as you did above and [ignoring explicit instructions](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) makes it hard to be more specific; the above is just a guess. Please do read the instructions and the linked article and fix this bug report. TIA!
