### ISSUE TITLE
Wrong suggestion language in translation memory

### ISSUE THREAD

**Issue by eson57** [vslavik/poedit#773]
I translate into Swedish only, but I always get a lot of Norwegian suggestions from translation memory.
It's very annoying and takes to much of my time to clean the memory from Norwegian translations.
Is there anything I can do to fix this ones and for all?

**Comment by vslavik** [comment]
You made a mistake and polluted your personal TM with bad data. See Preferences → TM → Manage → Reset. Or http://www.chiark.greenend.org.uk/~sgtatham/bugs.html too.

**Comment by eson57** [comment]
Thanks! That will eventually fix the problem, but I still don't understand how that happened. Could it be enough that I ones maybe opened a Norwegian translation file to check something? Because I know for sure that I have never imported one.

**Comment by vslavik** [comment]
> Could it be enough that I ones maybe opened a Norwegian translation file to check something?

No. You must have *saved* an edited translation file which had the language (incorrectly) set to Swedish.

**Comment by eson57** [comment]
Aha... during hundreds of translations that might actually have happened. Thanks again!
