### ISSUE TITLE
Error messages at startup (Leap-15.4, Poedit-3.01)

### ISSUE THREAD

**Issue by LETARTARE** [vslavik/poedit#776]
OpenSuse-Leap15.4::Poedit3.01
Hello,
a simple launch from a console by 'poedit' gives the error messages shown on the picture.

![Poedit_Error_Launch](https://user-images.githubusercontent.com/5158475/202770253-1eee6500-90a5-4042-8144-19b9631fa213.png)

Of course the mentioned address does not exist!

Thanks in advance

**Comment by vslavik** [comment]
File a bug with your distro.
