### ISSUE TITLE
Poedit identifies normal words as something else

### ISSUE THREAD

**Issue by Felipefpl** [vslavik/poedit#778]
This is a translation file for dolphin emulator https://www.transifex.com/delroth/dolphin-emu/languages/ - there are 2 problems:

"Show % Speed" is treated like a string with C format

"Shows the % speed of emulation compared to full speed" the s in speed is treated like if it was part of the percentage symbol related to the code. I attached the file for testing.

[dolphin-emu_emulator_pt_BR.zip](https://github.com/vslavik/poedit/files/10098398/dolphin-emu_emulator_pt_BR.zip)

**Comment by vslavik** [comment]
Please read [this article](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and provide a detailed explanation. In particular, please do clearly state expected vs observed result. It is unclear what you mean by "treated", it is unclear why you think that the string shouldn't be a C format one, and it not at all clear what does "part of the percentage symbol related to the code" mean.

**Comment by vslavik** [comment]
@Felipefpl You asked us to spend time reading, responding to and looking into your issue. It is *incredibly* rude, inappropriate and inconsiderate to then close the issue without as much as a single word of explanation.
