### ISSUE TITLE
Possibly wrong exception on PunctuationMismatch

### ISSUE THREAD

**Issue by atriwidada** [vslavik/poedit#779]
Current exception in file qa_checks.cpp: 
if (m_lang == "th" || m_lang == "lo" || m_lang == "km" || m_lang == "my")
            // For Thai, Lao, Khmer and Burmese

last two test are using wrong country codes:
Country code km is for Comoros
Country code my is for Malaysia

should be changed into:
Country code for Khmer is kh
Country code for Burmese is bu or mm

**Comment by vslavik** [comment]
> last two test are using wrong country codes:

These are ISO 639 *language* codes, not country codes.

If you have a specific reproducible issue, please report it as such. Or is it just speculation ("possibly")?

**Comment by atriwidada** [comment]
Ah sorry, I was incorrectly use ISO 3166
