### ISSUE TITLE
Message: 'gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar'

### ISSUE THREAD

**Issue by Ricky-Tigg** [vslavik/poedit#780]
**OS:** Fedora. Are installed:
```
$ dnf -q rq --installed --qf '%{name} %{version}' gtk? poedit | column
gtk2 2.24.33	gtk3 3.24.36	gtk4 4.8.2	poedit 3.2.2
```
Hello. Run the application either in Wayland or X11 window system `GDK_BACKEND=<parameter> poedit` respectively with _wayland_ and _x11_ as `<parameter>`. Identical error message produced in both cases.

- Steps to reproduce | method 1:
1. Execute `poedit`
2. Once the GUI opens, click option _Browse files_ then select a file.

Resulting output in terminal triggered by the selection of the file:
```
(net.poedit.Poedit:39603): Gtk-CRITICAL **: 18:46:30.252: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```
The application opens successfully. though i am unable to determine what functions might be affected by the issue depicted in that very message.

- Steps to reproduce | method 2:

1. 
```
$ echo $DEBUGINFOD_URLS
https://debuginfod.fedoraproject.org/
$ G_DEBUG=fatal-criticals gdb /usr/bin/poedit
(...)
Enable debuginfod for this session? (y or [n]) y
(...)
(gdb) run
(...)
```
2. Once the GUI opens, click option _Browse files_ then select a file.

Resulting output in terminal triggered by the selection of a file:
```
Downloading 0.33 MB separate debug info for /usr/lib64/gio/modules/libgioremote-volume-monitor.so
(...)
(net.poedit.Poedit:36347): Gtk-CRITICAL **: 17:52:37.680: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

Thread 1 "poedit" received signal SIGTRAP, Trace/breakpoint trap.
g_log_writer_default (log_level=<optimized out>, fields=0x7fffffffa320, n_fields=6, user_data=0x0) at ../glib/gmessages.c:563
Downloading 0.03 MB source file /usr/src/debug/glib2-2.74.1-2.fc37.x86_64/redhat-linux-build/../glib/gmessages.c
563	    G_BREAKPOINT ();
(gdb) 
```

**Comment by vslavik** [comment]
> The application opens successfully. though i am unable to determine what functions might be affected by the issue depicted in that very message.

In other words, no *actual* issue...

> Steps to reproduce

These require your specific distro, in its specific (but unknown!) version installed. I don't have that installed, but you do, so it seems you're in a much better position to debug it and provide a patch than I am. Can you please do it?

> (gdb) 

At the very least, you're in a position to provide an actual backtrace by typing `bt`.

**Comment by vslavik** [comment]
> In other words, the cause of the message is not yet investigated. "no actual issue..."; that i wouldn't myself state without investigation.

You didn't describe any issue. Ergo, there is not any (filed) issue *by definition*.

I may be old-school, but the sensible course of action is to identify a problem, *then* file a bug for it; not to file a bug and figure out what it's about later — or worse, ask others to figure it out for you.

Seeing your recently filed issues elsewhere, this seems to be a common pattern. I am thus closing this as non-issue (and the backtrace makes it evident it would be an issue with wxGTK or GTK+, not Poedit anyway). If you disagree, please submit a PR with a working patch.

**Comment by Ricky-Tigg** [comment]
"_Seeing your recently filed issues elsewhere, this seems to be a common pattern._" I am sorry for you then. Not our fault if either you are not made for the job you picked up or the job did not like you at start. Looks like to me atrange place to exhibit your frustration. No reason to doubt that it could not to be seen as well in others reports you had dealt with and shall deal with. You managed to make me feel that this platform is a quite sad place when i read you. Sorry if none of us could help you here nor elsewhere. Keep on going though. Maybe you do better next time.

**Comment by Ricky-Tigg** [comment]
"_Seeing your recently filed issues elsewhere, this seems to be a common pattern._" I am sorry for you then. Not our fault if either you were not made for the job you picked up or the job did not like you at start. Looks like to me strange place to exhibit your frustration. No reason to doubt that it could not to be seen as well in others reports you had dealt with and shall deal with. You managed to make me feel that this platform is a quite sad place when i read you. Sorry if none of us could help you here nor elsewhere. Keep on going though. Maybe you do better next time.

**Comment by Ricky-Tigg** [comment]
"_Seeing your recently filed issues elsewhere, this seems to be a common pattern._" I am sorry for you then. Not our fault if either you were not made for the job you picked up or the job did not like you at start. Looks like to me a strange place to exhibit your frustration. No reason to doubt that it could not to be seen as well in others reports you had dealt with and shall deal with. You managed to make me feel that this platform is a quite sad place when i read you. Sorry if none of us could help you here nor elsewhere. Keep on going though. Maybe you do better next time.

**Comment by vslavik** [comment]
@Ricky-Tigg And now outright harassment. Wow. We're done here.
