### ISSUE TITLE
Preferences tabs are mirrored and unreadable in RTL locales

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#784]
![תמונה](https://user-images.githubusercontent.com/18016656/221382569-275b24bb-25e3-4dd8-97a9-5b8561620d98.png)

**Comment by ItielMaN** [comment]
(as an example, the General tab being selected in the screenshot above should look like כללי)

**Comment by vslavik** [comment]
This is one of those WTF moments - it's a system control... Is it just the tab labels (כללי and friends) or the content of the tabs and the buttons too?

**Comment by ItielMaN** [comment]
Apparently just the tab labels.
(tbh I haven't looked around the UI too much, these are the only mirrored text I've noticed. Haven't used Poedit in a while. Let me know if you want me to do some more testing, and if you know which area may be prone to this issue elsewhere, let me know also,,,)

**Comment by vslavik** [comment]
This is fixed on the `devel/upgrade-to-wx-3.2` branch (to be merged for Poedit 3.4); I was finally able to identify a hotfix for wx-3.0 used by Poedit 3.3.
