### ISSUE TITLE
[suggest] Add instructions to install Poedit with PkgMgrs on Windows.

### ISSUE THREAD

**Issue by hwhsu1231** [vslavik/poedit#786]
### Suggestion

Currently, we can use some package managers to install Poedit on Windows.

For example, we can use [winget-cli](https://github.com/microsoft/winget-cli) to install Poedit with the following command:

```cmd
C:\Users\hwhsu1231>winget search poedit
名稱   識別碼              版本  來源
----------------------------------------
Poedit VaclavSlavik.Poedit 3.1.1 winget

C:\Users\hwhsu1231>winget install VaclavSlavik.Poedit
找到 Poedit [VaclavSlavik.Poedit] 版本 3.1.1
此應用程式已由其擁有者授權給您。
Microsoft 不負任何責任，也不會授與協力廠商封裝的任何授權。
正在下載 https://download.poedit.net/Poedit-3.1.1-setup.exe
  ██████████████████████████████  17.5 MB / 17.5 MB
已成功驗證安裝程式雜湊
正在啟動套件安裝...
已成功安裝
```

Therefore, I suggest that it add instructions to install Poedit with PkgMgrs on Windows in `README.md`.

**Comment by vslavik** [comment]
> Therefore, I suggest that it add instructions to install Poedit with PkgMgrs on Windows in README.md.

I suggest that you use the official installer and not rely on some apparently unmaintained 3rd party source that has very outdated versions.

**Comment by hwhsu1231** [comment]
>I suggest that you use the official installer and not rely on some apparently unmaintained 3rd party source that has very outdated versions.

@vslavik 

WinGet is using the official installer provided by [Poedit](https://poedit.net/download).

WinGet is kept maintaining by Microsoft. And if the current version of the package is out-of-date, then all we need to do is to post an update request in [winget-pkgs](https://github.com/microsoft/winget-pkgs). For example, the latest version of `VaclavSlavik.Poedit` in WinGet is currently `3.1.1`, which is indeed out-of-date. Therefore, I posted the following two update requests in winget-pkgs just now:

* https://github.com/microsoft/winget-pkgs/issues/97983
* https://github.com/microsoft/winget-pkgs/issues/97984

**Comment by vslavik** [comment]
> WinGet is kept maintaining by Microsoft.

I mean, *self-evidently* not. You contradict this claim in the very next sentence yourself:

> all we need to do is to post 

(i.e. some unspecified "we", not the supposedly maintaining Microsoft)

I am not going to a non-official download source and would appreciate it if you stopped arguing about it.

**Comment by hwhsu1231** [comment]
> I am not going to a non-official download source and would appreciate it if you stopped arguing about it.

I understand and I'll respect your decision. Sorry for the inconvenience caused. However, there is one more thing I would like to ask: What do you mean _"non-official download source"_?
