### ISSUE TITLE
Source text and translation window next to each other

### ISSUE THREAD

**Issue by Amereyeu** [vslavik/poedit#790]
Could we have an option to show  windows next to each other as shown below?

![split](https://user-images.githubusercontent.com/59344168/227617274-a21e2f0b-a0cd-41c5-a92a-c168c3f60286.png)

**Comment by vslavik** [comment]
Please provide rationale. You label this "improvement", but don't say a single word about why you think so...

**Comment by vslavik** [comment]
> [Amereyeu](https://github.com/Amereyeu) closed this as [completed](https://github.com/vslavik/poedit/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [2 days ago](https://github.com/vslavik/poedit/issues/790#event-12704663088)

If you create an issue, asking us to pay attention to your needs, it's *extremely* rude of you to a) ignore questions and b) then just randomly close the issue. You're just wasting everybody's time with such behavior.
