### ISSUE TITLE
Crowdin - Poedit integration - unable to synchronize translations

### ISSUE THREAD

**Issue by VadymSobchuk** [vslavik/poedit#792]
Hi!

I'm from the Crowdin team.
We noticed that our Crowdin - Poedit integration stopped working properly and users can't sync translations.

We assume that the integration transmits the wrong language codes.
Here is the list of our default codes
https://developer.crowdin.com/language-codes/

As an example of the error users receive, please see below (Chinese Traditional language used)
![image](https://user-images.githubusercontent.com/85502742/232775207-b9e89203-1772-49b2-81d5-f11bd926d284.png)

Text error message 
Language 'zh-Hant' not found or does not exist.

Please take a look and let us know if it can be fixed. Thank you!

**Comment by vslavik** [comment]
This was already fixed for PO files yesterday in 970703feccc24a9d8fc25851d3e10c60971586b3 — Poedit was accidentally fixing legacy `zh-TW`, used by Crowdin, into `zh-Hant` internally.

There are other issues with Crowdin intwgration that I'm currently looking into — if you could reach out by email, assuming you're handling these things, I'd appreciate it. The above issue remains for XLIFF files where the file's language code is sometimes inconsistent with API's, and the `Language` header is incorrect in the downloaded PO (just `zh` here; this is a new-ish regression).
