### ISSUE TITLE
New syntax for msgstr-strings inherited from msgid

### ISSUE THREAD

**Issue by StanleyKid-22** [vslavik/poedit#793]
I don't know if this was asked, so I'm writing.
According to Poedit's idea, using this syntax, e. g.
```
#: ui.cpp:1
msgid "Sample text"
msgstr ""
```
means that **msgstr** inherited **msgid**. However, the msgstr continues to be considered untranslated, so the percentages of the total translation in various resources (Poedit, Transifex, etc.) aren't calculated quite correctly, and this partially misleads application manufacturers.
Is it possible to add special syntax so that msgstr is considered translated when referring to the original msgid? And we'll know which msgstr-strings need to be translated **_msgstr ""_**, and which simply inherit msgid-strings. Then duplicating the text from msgid to msgstr won't be necessary, which will make the size of the translation smaller.
One of the examples:
```
#: ui.cpp:1
msgid_str "Sample text"
```

**Comment by vslavik** [comment]
This is a *bug tracker*, not questions forum.

> aren't calculated quite correctly, and this partially misleads application manufacturers.

This makes no sense at all. It seems you're confused about something, but it's not clear what. Reading the GNU gettext manual would probably help to clear that confusion.

> Is it possible to add special syntax

No. This is a standard format, not Poedit's own. 

> And we'll know which msgstr-strings need to be translated msgstr "", and which simply inherit msgid-strings

This makes no sense. If something doesn't need to be translated, *don't make it translatable and don't put it in a translation file*. Duh.
