### ISSUE TITLE
Poedit won't start on M2 Mac with Ventura 13.5.1

### ISSUE THREAD

**Issue by heyman** [vslavik/poedit#805]
Hi!

When I try to start Poedit I get the following message:

```
“Poedit” is damaged and can’t be opened. You should move it to the Bin.
```

It has worked previously on MacOS Monterey, but I've upgraded to Ventura since then. I've tried with both the old version that I had installed (which I believe was `3.1.1`) as well as with version `3.3.2`. The machine is an M2 Macbook Air.

Here's a screenshot of the error dialog:

<img width="372" alt="image" src="https://github.com/vslavik/poedit/assets/54217/958c812e-b04a-4a52-9116-be9600b8eee9">

Not sure if this is caused by an issue in Poedit or in my environment, but any pointers on how this can be fixed would be greatly appreciated.

**Comment by vslavik** [comment]
You do, in fact, have a damaged copy exactly as macOS is telling you. Probably because you use some non-default and broken app to unzip the archive.

**Comment by heyman** [comment]
Ah, should have checked that 🤦. 

Thanks for the help!
