### ISSUE TITLE
Clarify Whether Commercial Use Is Allowed In Free

### ISSUE THREAD

**Issue by SylvKT** [vslavik/poedit#806]
Hello. I'd like to know whether commercial use of Poedit is allowed under the Free version. The website does not mention this except here:
![Heading: Which plan should I choose? Description: The Pro and Pro+ plans are personal licenses for individuals and can be used for both commercial and non-commercial purposes. The license is valid for one person and can be used on up to 3 computers (whether running Windows, macOS, or Linux). These personal licenses cannot be transferred to or shared with other persons.](https://github.com/vslavik/poedit/assets/18603248/d7f74e6e-ab4f-4d00-ba02-5dde35c50178)

**Comment by vslavik** [comment]
@SylvKT This is open source version's bug tracker. It is not a place for idle questions.

If you need assistance with reading the license agreement, then you need the paid version, which includes support with such things.

And anyway, freeloading commercially would be a very immoral thing to do, so surely you wouldn't do it anyway and this entire question is moot, no?
