### ISSUE TITLE
OS X version auto-corrupts translations

### ISSUE THREAD

**Issue by lanurmi** [vslavik/poedit#81]
Translations get auto-corrected and modified without the user's request or consent, nor attention. Version 1.6.5.

Take for example this minimal .po file (the mandatory `msgid ""` header can be copied from de.po):

```
msgid "Please log in, ok?"
msgstr "Bitte einloggen, ok?"

msgid "About..."
msgstr "Über..."
```

Just opening this in Poedit modifies the first message. The word `einloggen` gets replaced with `einlochen` -- a completely different word. When moving to the second message using the arrow keys, the three dots get replaced by the Unicode ellipsis.

If autocorrect is disabled in settings, the first message doesn't get modified, but the ellipsis still does.

With this minimal sample the behavior is quite deterministic and reproducable, but in a big real-life PO file modifications appear to happen at random.

IMHO this is pretty bad, as random words in translations may get replaced with some unrelated words, and the only indication of this happening is the little star icon appearing on the row.

**Comment by oxeron** [comment]
I'm having the issue with version 3.5.1 on OSX 15.0.1 (Apple MacBook Pro M3)
