### ISSUE TITLE
Run "Validate translations" Automatically after Update from POT File

### ISSUE THREAD

**Issue by ravage84** [vslavik/poedit#811]
Context:
We are working with managable-sized translation files for our web application projects based on [CakePHP](https://cakephp.org).
The POT files are generated through semi-automated means.
Afterwards, the PO files of the usually 1-4 languages/locales will get updated manually by using "Update from POT file..." in Poedit  and then translate the new or changed strings.
To verify the translations are still valid, we often press "Validate translations".

Feature proposal:
I think the manual translation verification could be (optionally) improved by running the validation automatcially after updating the PO file from a POT file.

Rationale:
Automating it could help reduce errors and improve the UX for detecting issues with the translations.
This might not work for everybody or ever project. Thus, it would be sensible to have a configuration option just like showing the statistics after updating from POT file.

![grafik](https://github.com/vslavik/poedit/assets/625761/3038545c-b5ce-4188-a738-c5f4b23cfab9)

**Comment by vslavik** [comment]
Updating from POT either doesn't change strings or introduces "needs work" strings only. These are already marked as needing attention and won't be used in compiled files until you un-mark them. 

It thus makes no sense to explicitly validate after updating from POT.

**Comment by ravage84** [comment]
We had situations where the state of the file was broken after the upate form the POT file and it was detected by executing the validation function. 
I guess it would have also been detected when one would have tried to save the file after the update but that could be  after updating several translation strings in the mean time.
