### ISSUE TITLE
Run "Validate translations" Automatically after Loading a PO File

### ISSUE THREAD

**Issue by ravage84** [vslavik/poedit#812]
Context:
We are working with managable-sized translation files for our web application projects based on [CakePHP](https://cakephp.org/).
The POT files are generated through semi-automated means.
Sometimes, the PO files will get updated by search/replace in our IDE instead of though Poedit.
To verify the translations are still valid, we often then open the PO file and press "Validate translations".

Feature proposal:
I think the manual translation verification could be (optionally) improved by running the validation automatcially after loading the PO file.

Rationale:
Automating it could help reduce errors and improve the UX for detecting issues with the translations.
This might not work for everybody or ever project. Thus, it would be sensible to have a configuration option just like showing the statistics after updating from POT file.

![grafik](https://github.com/vslavik/poedit/assets/625761/3038545c-b5ce-4188-a738-c5f4b23cfab9)

**Comment by vslavik** [comment]
Poedit does, in fact, perform validation after opening a file.

**Comment by ravage84** [comment]
It might but the results aren't shown (as a window or see https://github.com/vslavik/poedit/issues/815) and depending on how one has setup the entry sort order potential errors aren't shown in the visible part of the list of translation strings.

![grafik](https://github.com/vslavik/poedit/assets/625761/2b34149b-ff7f-4200-8092-f077c67664e3)

![grafik](https://github.com/vslavik/poedit/assets/625761/e6c14db6-ef47-4e5e-bac8-a437b2746e73)

![grafik](https://github.com/vslavik/poedit/assets/625761/6bcc5832-afa7-496f-b796-67178e4cd116)

![grafik](https://github.com/vslavik/poedit/assets/625761/11dc7412-dbb5-42b6-863f-6caab3007267)

**Comment by ravage84** [comment]
The warning could be shown after load only if there are (severe) issues like duplicated entries.
