### ISSUE TITLE
Complete List of Keyboard Shortcuts

### ISSUE THREAD

**Issue by ravage84** [vslavik/poedit#816]
Context:
It seems there is no documented list of all the keybaord shortcuts for Poedit.

Feature Request:
Making the full list available under the "Help" menu.

![grafik](https://github.com/vslavik/poedit/assets/625761/fc226daf-2231-458e-a26f-928d402f7d6c)

As a window, HTML file or a sa PDF file.

For example, JetBrains IDEs provide a list of most common default keyboard shortcuts.

[ReferenceCard.pdf](https://github.com/vslavik/poedit/files/13043458/ReferenceCard.pdf)

Reationale:
Easily learning about all the available keyboard shortcuts of Poedit could lead to improved usage thereof.
This would also help implement new keyboard shortcuts like in https://github.com/vslavik/poedit/issues/814 and https://github.com/vslavik/poedit/issues/813.

**Comment by vslavik** [comment]
All keyboard shortcuts are listed in the standard place used by ~everybody else: the menus itself. 

If you'd like to have a single list of them, I'm happy to accept a PR, provided that it is done in a way that doesn't require extra maintenance — i.e. extracts its data in some automated way or is real easy to edit. (You previously excused your lack of contributions as not being a C programmer; this probably doesn't require that and as you keep referring to yourself as "we" and appear to be in a commercial setting, I hope you do have some resources to give back a bit.)
