### ISSUE TITLE
Displaying Directory Path and/or Language of Translation in Window Title Bar

### ISSUE THREAD

**Issue by ravage84** [vslavik/poedit#819]
Context:
We often have to translate into more than one language.
The POT & PO files are named after their translation context. E.g. "Admin" in ``Admin.po`` for the translation strings belonging to the admin part of an application.
This is a [convention given by the CakePHP farmework](https://book.cakephp.org/4/en/core-libraries/internationalization-and-localization.html#language-files)

Unfortunatley, that means when opening the PO files the window always just shows "Admin.po" in the title bar.

![grafik](https://github.com/vslavik/poedit/assets/625761/e8ff027f-fbc7-4881-95bf-56a97746c363)

![grafik](https://github.com/vslavik/poedit/assets/625761/793dc880-8201-4758-a15f-2f05779601f7)

Feature Request
It would be nice Poedit would display the directory path along with the file name of and/or the language set in the PO file.

![grafik](https://github.com/vslavik/poedit/assets/625761/1f16e7b1-2893-469f-b09e-f1ee81e32534)

For example in this case, it could display one of the following in the title bar:

1. ``Admin.po * PROJECT VERSION - C:\path/to/application/resources/locales/de_CH/- PoEdit``
2. ``Admin.po * PROJECT VERSION - German (Switzerland) - PoEdit``
3. ``Admin.po * PROJECT VERSION - German (Switzerland) - C:\path/to/application/resources/locales/de_CH/ - PoEdit``

Rationale:
Currently, it's quite confusing when working with more than one translation file.
Displaying the directory path would also make it unnecessary to display ``PROJECT VERSION``, which we (and likely others) never set.

**Comment by vslavik** [comment]
Full path is impractical for size reasons. One way would be to at least have a tooltip (which is [non-trivial](https://stackoverflow.com/questions/65853810/is-it-possible-to-add-a-tooltip-to-the-form-titlebar)).

Showing the language there, either as full text or code, is definitely a good idea — thanks!

Showing verbatim `PROJECT VERSION` is definitely bad. 

Showing the project *when set* is solving the inverse problem: when the language is obvious from the filename, but the project ("Admin" in your example) is not.
