### ISSUE TITLE
Highlighting for C++20 std::format, Boost Format

### ISSUE THREAD

**Issue by Ulysses1337** [vslavik/poedit#821]
I use Boost Format extensively, particularly empty pipe syntax. I intend to migrate to std::format, so if time is too limited for both, please do std. Thank you.

**Comment by vslavik** [comment]
Your tone here is completely inappropriate - you really are not entitled to have your needs prioritized by others. You're welcome to contribute a PR with changes you need.


Also, https://github.com/vslavik/poedit/commit/28aac5734e66d0cb190dbc29c400b4e64d15e912

**Comment by Ulysses1337** [comment]
Wow.

**Comment by vslavik** [comment]
Ah, sorry, I didn't realize you're a paying customer. Use the appropriate support channel, then, please.
