### ISSUE TITLE
Poedit does not preserve comments above msgid ""

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#827]
https://translationproject.org/PO-files/de/e2fsprogs-1.46.6-rc1.de.po has a big block of comments above the initial msgid, explaining how to translate this particular domain:
~~~text
#. 	%S		backup superblock
#. 	%X	<num>	hexadecimal format
#.
msgid ""
msgstr ""
~~~

When I open that file with Poedit 3.4.1 and save it, this comment gets lost.

**Comment by vslavik** [comment]
(Specifically, it's only the `#.` portion - i.e. the *extracted-comments* - that is lost, the *translator-comments* above with with copyright and authorship information are preserved.)

**Comment by vslavik** [comment]
Handling of this file is still not perfect after the above commits, some trailing whitespace is still stripped and some lines reformatted. But that's a more involved fix.
