### ISSUE TITLE
False positive Broken markup in translation string warning with HTML

### ISSUE THREAD

**Issue by moritz89** [vslavik/poedit#832]
The following translation results in the "Broken markup in translation string" warning. Looking at POedit sources, it seems to parse this as XML? Would it be sensible to handle the case where HTML is used in the translation?

    Additional details can be found on the <a href="https://github.com/..." target="_blank" rel="noopener"> GitHub page.</a>

**Comment by vslavik** [comment]
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md), follow the instructions therein and provide the missing detailed information, including any files necessary to reproduce and detailed, specific steps to reproduce. Thanks!

> POedit

BTW, why do you use this bizarre mis-spelling of Poedit's name?

**Comment by moritz89** [comment]
It turned out to be a problem in the PO files themselves. They were generated by Angular and included source tags such as

    <source> Install and start the Snap package. For the self-contained binary, older versions and other platforms see the <x id="START_LINK" ctype="x-a" equiv-text="&lt;a                   href=&quot;https://github.com/InamataCo/Flasher/releases/latest&quot;                   target=&quot;_blank&quot;                   rel=&quot;noopener&quot;                 >"/> GitHub releases page. <x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a>"/></source>

This understandably confused Poedit and resulted in weird behavior. Will fix it in the source text to not include HTML tags. I assumed the name from seeing POEditor.
