### ISSUE TITLE
Do not display singular panel for plural-only messages

### ISSUE THREAD

**Issue by zdm** [vslavik/poedit#835]
Some messages in po file can reperesents plural forms only.

It this case `msgid` is equal tp the `msgid_plural`.

```
msgid "${n} roless selected"
msgid_plural "${n} roless selected"
```

It would be nice to hide singular form panel for such messages to not confuse translators.

![image](https://github.com/vslavik/poedit/assets/1025608/f91fd454-606a-48d0-b297-c5d53696d524)

**Comment by zdm** [comment]
Not required, sorry.

**Comment by vslavik** [comment]
> Not required, sorry.

Next time please do the step of readings the docs and learning how gettext works *before* you create an issue.
