### ISSUE TITLE
XLIFF: superfluous &quot; within text is replaced with " on save

### ISSUE THREAD

**Issue by sbaeumlisberger** [vslavik/poedit#836]
xliff Translation files generated with Angular are using `&quot;` to escape double-quotes `"`. Poedit should keep them escaped when saving the file.

Here an example git diff after saving the file in Poedit:

```
- <source>The file path must end with &quot;.p12&quot; or &quot;.pfx&quot;</source>  
- <target>Der Dateipfad muss mit &quot;.p12&quot; oder &quot;.pfx&quot; enden.</target>  
+ <source>The file path must end with ".p12" or ".pfx"</source>  
+ <target>Der Dateipfad muss mit ".p12" oder ".pfx" enden.</target> 
```

**Comment by sbaeumlisberger** [comment]
Thank's for the fast response. I understand that it would complicate the implementation. The problem is that when the file is update by angular the process get's inverted which results in big diffs whenever we are adding a translation. But I think the behavior of PoEdit is right as the escaping is indeed completely unnecessary. I will open an issue in the angular repository. Thank's for your time and great tool!

**Comment by berkbltc** [comment]
@sbaeumlisberger were you able to find a workaround? I am having the same issue.

**Comment by sbaeumlisberger** [comment]
@berkbltc  unfortunately no solution yet, see: https://github.com/angular/angular/issues/54565
