### ISSUE TITLE
Poedit requires unofficial wx libs

### ISSUE THREAD

**Issue by brccabral** [vslavik/poedit#837]
Hi,
I tried to install Poedit from apt
```sh
sudo apt install poedit
```
The installation finished, but when running `poedit` it was complaining about some `libwx` libs having the wrong version.
I tried to compile from source but got same error as #700 `error: incomplete type ‘wxWebView’`.
I removed anything related to wx on my system and ran the `make distcheck` and now it finished fine. I noticed it was using the wx from submodule.
But for some reason I could not run `make install`, it could not find `<wx/deps.h>`, I could not find reason why.
Anyway, I noticed this project has `.github/workflow`, I decided to take a look at the builds commands, and it adds a repo from `codelite.org` and it installs unofficial `libwxgtk3` libs.
I decided to add that repo and install the same libs from the workflow and install Poedit again from apt and now it works.

So, is it correct to say that Poedit requires the unofficial libwxgtk3? Any chance to make it work with the official ones?

Best regards,
Bruno

**Comment by vslavik** [comment]
> The installation finished, but when running poedit it was complaining about some libwx libs having the wrong version.

And if you googled it, you would found an explanation and realized that you messed up your runtime environment and mixed unrelated builds of wx shared libraries. That didn't happen on its own, and it didn't come from your distribution packages either.

> I noticed it was using the wx from submodule.

It wasn't.

> I could not find reason why.

Frankly, you shouldn't be compiling from sources if you're incapable of inspecting the compiler command and figuring out where it looks for headers.

> So, is it correct to say that Poedit requires the unofficial libwxgtk3?

No, that's preposterous. 

The linked issue contains advise and pointers that you apparently didn't bother to read. You should, they apply to you too, including the advise on debugging and the advise that you shouldn't compile from sources if you're not equipped to interpret and diagnose compiler issues.

Use packages, either from your distro or the snap ones.
