### ISSUE TITLE
.po.txt files not supported

### ISSUE THREAD

**Issue by Arkarit** [vslavik/poedit#839]
Hi,

for use in Unity 3D I need to rename .po files to .po.txt, because otherwise they are not accessible as text files properly within Unity 3D.
Unfortunately poedit detects these syntactically valid .po files wrongly as invalid, just because of the extension.
This hasn't been the case in earlier versions, so it seems to be a disimprovement...

Apart from that, also "All files" should imo be supported in the file selector for opening files.
The validity of the files should be determined by its content, not by the extension.

3.4.2, German, Windows 10

Thank you

**Comment by vslavik** [comment]
> Unfortunately poedit detects these syntactically valid .po files wrongly as invalid, just because of the extension.

No, Poedit doesn't recognize a file that has an extension and MIME type of a plain text file as a PO - i.e. not plain text - file. As it should.

> The validity of the files should be determined by its content, not by the extension.

You're welcome to contribute patches.
