### ISSUE TITLE
How to invoke poedit as a Visual Studio custom tooling

### ISSUE THREAD

**Issue by mwpowellhtx** [vslavik/poedit#842]
Is there a way in which to invoke `poedit` as a Visual Studio custom tooling option? i.e.

![image](https://github.com/vslavik/poedit/assets/1824187/11169034-8bc6-4344-9097-e2ab7dd8bafd)

Given the `.po` _"source file"_, which would yield the `.mo` result.

Cheers, and thank you...

**Comment by vslavik** [comment]
This is an issue tracker for *issues*. It is not a questions forum or support channel or even Visual Studio support channel.
