### ISSUE TITLE
Adding Export to Yii translation files

### ISSUE THREAD

**Issue by mtangoo** [vslavik/poedit#847]
Hi Vaclav,
hope you do well. I would like to import markdown into PoEdit, each paragraph as an entry. Then after translation, PoEdit should export to Markdown again. Is PoEdit capable of doing that? If not how hard is it to add it?

I have a good experience with C++/wxWidgets and I will be willing to invest some time if not difficult. If PoEdit supports Plugins, will you point me to the API?

Sorry for initial description. I conflated two related but different things.

**Comment by vslavik** [comment]
@mtangoo If you ask somebody to look into an issue you create, don't then immediately close it yourself - it's extremely rude and disrespectful behavior.
