### ISSUE TITLE
Poedit does not recognize Geez Script punctuation.

### ISSUE THREAD

**Issue by weldu0** [vslavik/poedit#851]
Poedit does not recognize Geez Script punctuation.
![Screenshot from 2024-07-24 12-59-15](https://github.com/user-attachments/assets/c12a36f1-a34a-4d90-bab1-69a56ae644ec)

Here is their differences.
| Punctuation Name| Punctuation (*en*) | Geez Script(*ti*, *am*) |
| ------ | ------ |  ------ | 
| section mark |  | ፠ |
| full stop | . | ። |
| comma| , | ፣ |
| semicolon | ; | ፤ |
| colon | : | ፥ |
| preface colon |  | ፦|
| question mark | ? | ፧ |
| paragraph separator |  | ፨ |

https://en.wikipedia.org/wiki/Ge%CA%BDez_script#Punctuation
https://lexilogos.com/keyboard/tigrinya.htm

**Comment by vslavik** [comment]
Can you please provide sample PO file?

**Comment by weldu0** [comment]
it seem GitHub does not support po file to be upload here.
here is a copy of the file you can look at.
```PO
msgid ""
msgstr ""
"Project-Id-Version: sample po\n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: ti_ER\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Generator: Poedit 3.0.1\n"

msgid "Hello."
msgstr "ሰላም።"

msgid "How are you?"
msgstr "ከመይ ኣለኻ፧"

msgid "Thank you."
msgstr "የቐንየለይ።"
```

**Comment by vslavik** [comment]
Thanks!
