### ISSUE TITLE
ARB (JSON) Handicapped without 'replacing source text'

### ISSUE THREAD

**Issue by isaksky** [vslavik/poedit#852]
I checked out the new ARB / JSON when I saw [your announcement](https://poedit.net/news/poedit-3.3-json/) about this feature. The format and the support in POEdit looks great, except I see that this format doesn't ship with the source text to translate. I guess that is why you also added 'Replacing source text with reference translations' at the same time.

That feature is just in the Pro version though, which effectively means the free version doesn't support ARB at all. I say that because how could one translate an ARB file if one couldn't see the source texts, just the symbols? This problem isn't there with the other formats, like XLIFF, .po files, etc.

What do you think about opening up the 'Replacing source text with reference translations' feature in the free version just for formats like .ARB, where the source text is not included in the file? This way ARB files are at least editable.

The reason I ask is not to avoid sending you $3.33, but because I have to decide on a format for translation files to be opened and used by others, and with this limitation, it seems like the .arb format is essentially unusable.

**Comment by vslavik** [comment]
> POEdit 

(Why this particular misspelling of the name?)

> which effectively means the free version doesn't support ARB at all [...]  it seems like the .arb format is essentially unusable.

I could do without the inflammatory rhetorics, if I'm being honest. The OSS version on which you filed the issue, does open English files. Plus you have other options, e.g. starting from English text or opening multiple windows...

I think it's reasonable to ask for payment for a few conveniences to fund the development. Expecting everything on a silver plate; less so.

Having that said, this is under consideration, but a topic for this OSS tracker, so closing.

> I have to decide on a format for translation files 

You have many options, including JSON-based variants that store source text, e.g. [WebExtension's](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization) or XLIFF.

**Comment by isaksky** [comment]
Sorry, I didn't expect that to be controversial. After all, you support showing the source text for every other format (at least that I have tested). I figured it was just an oversight.

**Comment by vslavik** [comment]
> After all, you support showing the source text for every other format

Poedit shows the source *as present in the file*. ARB chooses to use a cryptic ID for the source text and to not include full information in its source-form files. It's absolutely not the case that Poedit is "not showing the source text" - the cryptic ID *is* the source text.

> I figured it was just an oversight.

Revisionist much? Re-read this issue's description.
