### ISSUE TITLE
Poedit 3.5 stopped respecting "Prefer tabs when opening documents" system setting

### ISSUE THREAD

**Issue by scruwi** [vslavik/poedit#856]
## Problem Description
In version 3.5 of the application on MacOS (Sonoma), opening multiple *.po files simultaneously results in each file being opened in a separate window.

## Expected Behavior (As in Previous Version 3.4.4)
In version 3.4.4, when multiple *.po files were opened simultaneously, they were all opened in the same window, but in different tabs. This was more convenient for managing multiple files at once.

## Actual Behavior in Version 3.5
With the update to version 3.5, the behavior has changed so that each *.po file opens in its own separate window, which can be less efficient and harder to manage.

## Steps to Reproduce
On MacOS, open the application version 3.5.
Attempt to open multiple *.po files simultaneously.
Observe that each file is opened in a separate window instead of in tabs within the same window.

## Environment
Application Version: 3.5
Previous Version: 3.4.4
Operating System: MacOS Sonoma

**Comment by vslavik** [comment]
Probably related to the wx-3.2 upgrade.
