### ISSUE TITLE
Croatian poedit.mo file not included in 3.5

### ISSUE THREAD

**Issue by milotype** [vslavik/poedit#857]
After updating Poedit from Version 3.4.4 to Version 3.5 the language of the UI shows in German. In Version 3.4.4 I had the UI in Croatian language.

How can I set Croatian back again?

MacBook Pro, Sonoma 14.6.1

**Comment by vslavik** [comment]
https://github.com/vslavik/poedit/blob/master/SUPPORT.md please. As you can probably guess, your OS settings (particularly language related) are going to be highly relevant...

**Comment by milotype** [comment]
@vslavik Ah, sorry for sending my problem here.
I've just sent the problem to help@poedit.net

**Comment by milotype** [comment]
@vslavik Thank you very much for updating Poedit to version 3.5.1. I now have the Croatian UI back again!
