### ISSUE TITLE
With update from 3.4.4 to 3.5 lost bookmarks menu

### ISSUE THREAD

**Issue by ITDarkUFO** [vslavik/poedit#862]
On 3.4.4 in Go menu was submenu Bookmarks, now it is gone. Keyboard shortcuts not working too.
![image](https://github.com/user-attachments/assets/5c5132c2-7d8d-4d2e-90aa-147724d7f212)

**Comment by vslavik** [comment]
https://github.com/vslavik/poedit/commit/d700851058037ee563511bae467c4db0a37e80d5
