### ISSUE TITLE
Pasing translation string after bitwise left shift operator

### ISSUE THREAD

**Issue by outcomer** [vslavik/poedit#864]
Conclusion in advance: every entry of `__` after templates literals, used inside an object that is followed by bitwise left shift operator will not be ever reach by POEDIT parser.
----------
It might be I have found something very specific, rare combination.

Here is Javascript file content (simplified).
_pasing this file with POEDIT will NOT find "Categories terms" string._
```javascript
const tabsHtml = [];
var mask = 2 << 1;
 
tabsHtml.push({
  name: `segment-${segment.value}-slug`,
});

const title = __('Categories terms', 'messia');
```

------------------

removing bitwise left shift operator (double left arrows <<) will do the job
_pasing this file with POEDIT WILL find "Categories terms" string._
```javascript
const tabsHtml = [];
var mask = 2 + 1;
 
tabsHtml.push({
  name: `segment-${segment.value}-slug`,
});

const title = __('Categories terms', 'messia');
```

-----------
!!! But in fact problem is not in bitwise left shift operator (double left arrows <<) itself, but in combination of bitwise left shift operator and template literals, used inside objects (<< and `segment-${segment.value}-slug` inside {}).

Inside this code POEDIT will not find transatable string, cause template literals are inside {} and follow by << and __('Categories terms', 'messia'); goes later

```javascript
const tabsHtml = [];
var mask = 2 << 1;
 
{ name: `segment-${segment.value}-slug` };

const title = __('Categories terms', 'messia');
```

in case we move translation before templates literal - it will work
```javascript
const tabsHtml = [];
var mask = 2 << 1;

const title = __('Categories terms', 'messia');

{ name: `segment-${segment.value}-slug` };
```

or we can left it in place but avoid using {}, lets say like this (it will works too):
```javascript
const tabsHtml = [];
var mask = 2 << 1;
 
[name: `segment-${segment.value}-slug`];

const title = __('Categories terms', 'messia');
```

**Comment by vslavik** [comment]
Poedit uses `xgettext` from GNU gettext tools for extraction. If you think there's a bug in its handling of some source code, you should submit a bug report to GNU gettext, not Poedit. You'll probably want to provide actual reproducible example with files, too.

**Comment by outcomer** [comment]
@vslavik from now you are aware that Poedit has this problem, even if you are not kin to resolve it. More important that it is known.

**Comment by vslavik** [comment]
@outcomer Sigh. This is not a Poedit issue. This is (if it is real) an xgettext issue. Filing an issue on an unrelated project won't magically fix it. Neither will making random people "aware" magically fix it. 

As a user of open source software, you have a responsibility (i.e. it's the least you can do) to report issues to the correct place — not expect random people on the Internet to do it for you.

Once again, "Poedit" doesn't "have this problem". It's possibly an issue in something that Poedit merely *uses*. This really shouldn't be a complicated thought to understand.
