### ISSUE TITLE
Installing poedit on Mint22, not finding lucene++

### ISSUE THREAD

**Issue by brianread108** [vslavik/poedit#869]
./configure, gives me this:
`
configure: error: missing Lucene++ library

brianr@brian-Mint21:~/Downloads/poedit-3.5.1$ sudo apt install liblucene++0t64

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
liblucene++0t64 is already the newest version (3.0.9-3.1build1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

brianr@brian-Mint21:~/Downloads/poedit-3.5.1$ 
`

**Comment by gusnan** [comment]
Do you have `liblucene++-dev` installed?

**Comment by brianread108** [comment]
ok, that got me to the end of the ./configure - thanks.

**Comment by vslavik** [comment]
Closing as RTFM.
