### ISSUE TITLE
pre-translate is fully inaccurate and stupid

### ISSUE THREAD

**Issue by estatistics** [vslavik/poedit#871]
I think Pre-translation is very stupid 
(lines remain in english in order to present differences)

1) Even the "arguments" cannot replace them as exact.
eg. Syntax error expecting %s or %s. --> Syntax error expecting %s, %s, %s, %s, or %s.

2) Also, single words like "Examine" are translated with a full phrase with more than 10 words. 

I thought that pre-translate:
a) Could infer that when "Syntax error" is translated as "abc_Syntax error" in 90% of times in phrases will be "replaced" as "abc_Syntax" and not with something else. 
b) replace only words and not arguments. 
c) it says that pre-translated 650 lines but actually only 20 lines were pretranslated and almost all with wrong arguments, words. 

If you like, i will provide you with the pspp.po file that i try to translate to greek. 

It will best if poedit can create a dictionary of words and phrases that can be edited from the user. Using that, people can speed translation very much by exchanging / merging dictionaries eg. on statistics. I wonder why this has not implemented yet. 

Can "Argos translate" be supported as an external translator? how?

**Comment by vslavik** [comment]
This is the open source version bug tracker. If you complain about machine translation in pre-translation, that is Pro feature and this is not the appropriate forum for support.

Poedit *does* correctly handle placeholders *if your file correctly identifies them*. 

Please see http://www.chiark.greenend.org.uk/~sgtatham/bugs.html on how to describe issues in a way that other people can reproduce and understand. I'm afraid I can't make much sense of anything in this.
