### ISSUE TITLE
src/gtk/bitmap.cpp(1020): assert "'m_refData"" failed in SetScaleFactor): invalid bitmap

### ISSUE THREAD

**Issue by tojestzart** [vslavik/poedit#872]
as above
![poedit](https://github.com/user-attachments/assets/d0a96395-c743-437e-ab64-63c05f4e641c)
Tried to open https://launchpad.net/ubuntu/+source/ubuntu-release-upgrader/1:25.04.1 in /po/pl.po

```
lsd@Crawler-E25:~$ apt list poedit
poedit/oracular,now 3.5-1 amd64 [zainstalowany]
lsd@Crawler-E25:~$ 
```

Operating System: Kubuntu 24.10
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.6.2
Kernel Version: 6.11.0-9-generic (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600H with Radeon Graphics
Memory: 22.8 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: MEDION
Product Name: Crawler E25

**Comment by vslavik** [comment]
After re-reviewing the code, I found *one* pathway that could theoretically still trigger this *if your GTK theme is broken* and that the other issues linked didn't catch. I added extra defensive checks in https://github.com/vslavik/poedit/commit/d1728143657d9f15d12746ed6a4ab7ec09dd9cd1, so closing this now, please reopen if you encounter this in a version *newer than 3.5.2*. Note that even with this, you won't see some icons, so some breakage will still be there.
