### ISSUE TITLE
Feature Request: A button to automatically cop the untranslated phrase at translated box

### ISSUE THREAD

**Issue by estatistics** [vslavik/poedit#873]
Feature Request: A button to automatically cop the untranslated phrase at translated box

User Case: Having 50 phrases starting as "expecting error at....... 
 - By pressing a copy button to transfer the phrase below, i can quickly highlight it and paste the translated phrase. 
 - Ideally, poedit must allow a type of dictionary that you must define that some phrases be substituted automatically. Like copy/paste in writer.

- So by copy/paste, "expecting error..." can be susbstituted very quickly. 
- This will speed up the translation very much!

**Comment by vslavik** [comment]
> Feature Request: A button to automatically cop the untranslated phrase at translated box

See the Edit menu.

If you mean something else (you're not exactly comprehensible and should read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html), submit a PR.
