### ISSUE TITLE
Respect original word wrap (and no wrap), or make it configurable

### ISSUE THREAD

**Issue by den4b** [vslavik/poedit#94]
Re-saving *.po files with Poedit, forces all long lines in `msgid` and `msgstr` entries to be wrapped.

This creates two problems:
1. Unnecessary diff in version control.
2. Tools that automatically generate and update *.po files can accumulate such wrapped changes as fuzzy entries.

Specific example: Localization tools of [Lazarus IDE](http://www.lazarus.freepascal.org/) (Free Pascal) automatically generate and update *.po files for a project. Produced *.po files contain long lines. Editing such *.po files with Poedit wraps long lines, creating issues for future automatic updates by the IDE and diff noise in version control.

Please, either respect the original word wrapping (or no wrapping in this case), or at least make it configurable from within Poedit whether it should or shouldn't wrap long lines.

Because of this issue, we are forced to use [Virtaal](http://virtaal.translatehouse.org/), instead of preferable Poedit.

P.S. This may be related to an old [Ticket 25 - please preserve wordwrap](http://poedit.net/trac/ticket/25).

**Comment by dezlov** [comment]
Just wanted to leave feedback to say that this feature has been working perfectly in recent versions!

Now I am a very happy Pro user. Thank you!

**Comment by vslavik** [comment]
> Just wanted to leave feedback to say that this feature has been working perfectly in recent versions!

Much appreciated — that must be a first ;) For *years*, there were problems with wrapping, over and over again, and I'm still not happy with Poedit's *code* for wrapping, but I'm cautiously optimistic myself about the *behavior* finally being good enough...
